provider: gitlab
team: team-1
webhook_source: gitlab-platform
management: nopsai
triggers:
  - on: push
    branches:
      - main
    scope: dev
    pipelines:
      - platform/prod/platform-maintenance

  - on: pull_request
    scope: dev
    pipelines:
      - platform/prod/platform-maintenance
