triggers:
  - on: push
    branches:
      - main
    skip_repos:      # List repositories to ignore
      - legacy-app
      - internal-*
    pipelines:
      - main-pipeline.yaml
      - general/include-pipeline
    scope: prod

  - on: push
    skip_branches:
      - 'main'
      - 'master'
    skip_repos:      # List repositories to ignore
      - legacy-app
      - internal-*
    pipelines: 
      - branch-pipeline.yaml

  - on: pull_request
    skip_repos:      # List repositories to ignore
      - legacy-app
      - internal-*
    pipelines: 
      - main-pipeline.yaml
      - general/include-pipeline
      - branch-pipeline
