ARG BASE_IMAGE=hoseindocker/nopsai-base:latest
FROM ${BASE_IMAGE} AS base
FROM alpine:latest

WORKDIR /app
COPY --from=base /nopsai-git-bot /usr/local/bin/nopsai-git-bot
COPY --from=base /app/config.yml .

ENTRYPOINT ["nopsai-git-bot"]
