ARG BASE_IMAGE=hoseindocker/nopsai-base:latest
FROM ${BASE_IMAGE} AS base
FROM alpine:latest

ARG VERSION=dev
ARG COMMIT=unknown
ARG BUILD_DATE=unknown

LABEL org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${COMMIT}" \
  org.opencontainers.image.created="${BUILD_DATE}"

WORKDIR /app
COPY --from=base /nopsai-k8s-runner /usr/local/bin/nopsai-k8s-runner
COPY --from=base /app/config.yml .

ENTRYPOINT ["nopsai-k8s-runner"]
