FROM hoseindocker/nopsai-base:latest AS base
FROM alpine:latest

RUN apk --no-cache add git bash docker-cli yq jq 
COPY --from=base /nopsai-agent /usr/local/bin/nopsai-agent

ENTRYPOINT ["nopsai-agent"]
