ARG BASE_IMAGE=hoseindocker/nopsai-base:latest
FROM ${BASE_IMAGE} AS base
FROM alpine:latest

WORKDIR /app
COPY --from=base /nopsai-dispatcher /usr/local/bin/nopsai-dispatcher
COPY --from=base /app/config.yml .

ENTRYPOINT ["nopsai-dispatcher"]
