import type { WikiApiRoute } from '../../types.js';

const LLM_PROFILE =
  '{\n  "name": "reasoning-large",\n  "provider": "anthropic",\n  "model": "claude-sonnet-4-5",\n  "credential_ref": "platform/anthropic",\n  "enabled": true,\n  "is_default": true,\n  "allowed_scopes": ["platform/production"]\n}';

const AGENT_PROFILE =
  '{\n  "id": "senior-release-engineer",\n  "name": "Senior release engineer",\n  "enabled": true,\n  "is_default": false,\n  "instructions": "Review changes for release risk before recommending a promotion."\n}';

const MCP_SERVER =
  '{\n  "name": "jira",\n  "display_name": "Jira",\n  "enabled": true,\n  "transport": "http",\n  "url": "https://mcp.example.com/jira",\n  "auth_type": "credential",\n  "credential_ref": "platform/jira-mcp"\n}';

const MCP_PROFILE =
  '{\n  "name": "jira-readonly",\n  "enabled": true,\n  "allowed_scopes": ["platform/production"],\n  "servers": [{ "server": "jira", "tools": ["search", "get_issue"] }]\n}';

/**
 * AI configuration.
 *
 * Three separate registries: model profiles decide which provider and model a
 * run may use, agent roles decide how it behaves, and MCP servers and profiles
 * decide which tools it can reach. A pipeline names them; it cannot define them.
 */
export const ai_configurationRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/system/models',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Lists platform model profiles.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List model profiles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/models" | jq \'.[] | {name, provider, enabled, is_default}\'',
      expectedOutput: 'Every profile with its provider and whether it is the platform default. Credential values are never included.',
    },
    responses: [{ status: 200, description: 'Model profiles.', contentType: 'application/json', sample: '[' + LLM_PROFILE + ']' }],
    errors: [{ status: 503, cause: 'Authorization is unavailable, so the list cannot be filtered.', action: 'Check AAA.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/llm_config_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
    notes: 'A profile names a provider, a model, and a credential reference. `model:` in a pipeline names the profile, never the provider model id directly.',
  },
  {
    method: 'PUT',
    path: '/v1/system/models',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Replaces the platform model profile set.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Replace the profile set',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/models" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @models.json | jq',
      expectedOutput: 'The stored set. Profiles omitted from the body are removed.',
      placeholders: ['`models.json` is the complete profile list.'],
    },
    responses: [{ status: 200, description: 'Profiles stored.', contentType: 'application/json', sample: '[' + LLM_PROFILE + ']' }],
    errors: [
      { status: 400, cause: 'An unknown provider, a missing model, or a credential reference that does not resolve.', action: 'The message names the profile and field.' },
      { status: 500, cause: 'The profiles could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Removing a profile makes every pipeline naming it fail authorization on its next run.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/llm_config_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
    notes: 'This replaces the whole set. To change one profile use the single-profile PUT, which leaves the others alone.',
  },
  {
    method: 'PUT',
    path: '/v1/system/models/default',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Sets the platform default model profile.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Set the platform default model',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/models/default" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"reasoning-large"}\' | jq',
      expectedOutput: 'The default a run falls back to when neither the task, step, pipeline, nor team names a model.',
    },
    responses: [{ status: 200, description: 'Default set.', contentType: 'application/json', sample: '{ "name": "reasoning-large", "is_default": true }' }],
    errors: [
      { status: 400, cause: 'The profile does not exist or is disabled.', action: 'List profiles first.' },
      { status: 500, cause: 'The default could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes the last step of model resolution for every team without its own default.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/llm_config_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
    notes: 'Resolution order is task, step, pipeline, team, then this. Changing it moves the floor, not the ceiling.',
  },
  {
    method: 'PUT',
    path: '/v1/system/models/{profileName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Creates or replaces one model profile.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'reasoning-large' }],
    requestSample: {
      title: 'Upsert a model profile',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/models/reasoning-large" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"provider":"anthropic","model":"claude-sonnet-4-5","credential_ref":"platform/anthropic","enabled":true}\' | jq',
      expectedOutput: 'The stored profile, leaving every other profile untouched.',
    },
    responses: [{ status: 200, description: 'Profile stored.', contentType: 'application/json', sample: LLM_PROFILE }],
    errors: [
      { status: 400, cause: 'An unknown provider, missing model, or unresolvable credential.', action: 'The message names the field.' },
      { status: 500, cause: 'The profile could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Takes effect for the next run that resolves this profile.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/llm_config_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/system/models/{profileName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Deletes a model profile.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to delete.', example: 'reasoning-large' }],
    requestSample: {
      title: 'Delete a model profile',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/models/reasoning-large" -w "%{http_code}\\n"',
      expectedOutput: '204, unless something still depends on it.',
    },
    responses: [{ status: 204, description: 'Profile deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The name is missing.', action: 'Name the profile.' },
      { status: 404, cause: 'No profile with that name.', action: 'It may already be deleted.' },
      { status: 409, cause: 'The profile is still in use — as a default, or by a pipeline.', action: 'Reassign the dependants first. The platform refuses rather than breaking them.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/llm_config_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
    notes: 'The 409 is a feature: deleting a model out from under a pipeline is refused rather than discovered at the next run.',
  },
  {
    method: 'POST',
    path: '/v1/system/models/{profileName}/test',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Tests a model profile against its provider.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to test.', example: 'reasoning-large' }],
    requestSample: {
      title: 'Test a model profile',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/models/reasoning-large/test" | jq',
      expectedOutput: 'A real provider round trip: this is the difference between "configured" and "working".',
    },
    responses: [{ status: 200, description: 'The provider answered.', contentType: 'application/json', sample: '{ "ok": true, "provider": "anthropic", "model": "claude-sonnet-4-5" }' }],
    errors: [
      { status: 400, cause: 'The profile is incomplete or disabled.', action: 'Finish configuring it first.' },
      { status: 404, cause: 'No profile with that name.', action: 'Confirm the name.' },
      { status: 502, cause: 'The provider rejected the call or could not be reached.', action: 'The message carries the provider’s response — usually a bad key, a wrong model id, or egress being blocked.' },
    ],
    sideEffects: ['Makes one real call to the provider, which may be billable.'],
    coveringTests: ['services/nopsai/llm_profile_provider_clients_test.go'],
    evidence: ['services/nopsai/llm_profiles.go'],
    notes: 'Run this after every credential rotation. A rotated key that was never tested fails at the least convenient moment.',
  },
  {
    method: 'GET',
    path: '/v1/system/agent-roles',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Lists platform agent roles.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List agent roles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/agent-roles" | jq \'.[] | {id, name, enabled, is_default}\'',
      expectedOutput: 'Every persona a pipeline or step may name.',
    },
    responses: [{ status: 200, description: 'Agent roles.', contentType: 'application/json', sample: '[' + AGENT_PROFILE + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go', 'pkg/models/agent_profile.go'],
    notes: 'An agent role is behaviour, not capability: it shapes the prompt and does not grant tools or models.',
  },
  {
    method: 'POST',
    path: '/v1/system/agent-roles',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Creates an agent role.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create an agent role',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/agent-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"id":"senior-release-engineer","name":"Senior release engineer","instructions":"Review changes for release risk."}\' | jq',
      expectedOutput: 'The created role, nameable from `agent_role` on a pipeline or step.',
    },
    responses: [{ status: 201, description: 'Agent role created.', contentType: 'application/json', sample: AGENT_PROFILE }],
    errors: [
      { status: 400, cause: 'A missing id, name, or instructions.', action: 'Validate first with the validate route.' },
      { status: 409, cause: 'A role with that id already exists.', action: 'Update it instead.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The role could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/agent-roles/{profileID}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Reads one agent role.',
    depth: 'full',
    parameters: [{ name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role id.', example: 'senior-release-engineer' }],
    requestSample: {
      title: 'Read an agent role',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/agent-roles/senior-release-engineer" | jq',
      expectedOutput: 'The role and the instructions that become part of the prompt.',
    },
    responses: [{ status: 200, description: 'The agent role.', contentType: 'application/json', sample: AGENT_PROFILE }],
    errors: [
      { status: 404, cause: 'No role with that id.', action: 'Confirm the id from the list.' },
      { status: 500, cause: 'The role could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
  },
  {
    method: 'PUT',
    path: '/v1/system/agent-roles/{profileID}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Replaces an agent role.',
    depth: 'full',
    parameters: [{ name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role id.', example: 'senior-release-engineer' }],
    requestSample: {
      title: 'Update an agent role',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/agent-roles/senior-release-engineer" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @role.json | jq',
      expectedOutput: 'The stored role. Runs already executing keep the instructions they started with.',
    },
    responses: [{ status: 200, description: 'Role stored.', contentType: 'application/json', sample: AGENT_PROFILE }],
    errors: [
      { status: 400, cause: 'Invalid instructions.', action: 'Validate first.' },
      { status: 404, cause: 'No role with that id.', action: 'Create it instead.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes the prompt for every future step naming this role.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
    notes: 'Editing a widely used role changes behaviour across many pipelines at once. Check its usage first.',
  },
  {
    method: 'PUT',
    path: '/v1/system/agent-roles/default',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Sets the platform default agent role.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Set the default agent role',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/agent-roles/default" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"id":"senior-release-engineer"}\' | jq',
      expectedOutput: 'The role used when nothing else names one.',
    },
    responses: [{ status: 200, description: 'Default set.', contentType: 'application/json', sample: '{ "id": "senior-release-engineer", "is_default": true }' }],
    errors: [
      { status: 400, cause: 'The role does not exist or is disabled.', action: 'List roles first.' },
      { status: 500, cause: 'The default could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes behaviour for every LLM step that names no role.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
    notes: '`default` is a literal path segment, so no agent role may use it as an id.',
  },
  {
    method: 'DELETE',
    path: '/v1/system/agent-roles/{profileID}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Deletes an agent role.',
    depth: 'full',
    parameters: [{ name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role to delete.', example: 'senior-release-engineer' }],
    requestSample: {
      title: 'Delete an agent role',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/agent-roles/senior-release-engineer" -w "%{http_code}\\n"',
      expectedOutput: '204, unless something still names it.',
    },
    responses: [{ status: 204, description: 'Role deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is missing.', action: 'Name the role.' },
      { status: 403, cause: 'The caller may not delete this role.', action: 'Team-owned roles are deleted through the team routes.' },
      { status: 404, cause: 'No role with that id.', action: 'It may already be deleted.' },
      { status: 409, cause: 'The role is still in use, or is a default.', action: 'Check its usage and reassign first.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/agent-roles/{profileID}/usage',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Reports what currently uses an agent role.',
    depth: 'full',
    parameters: [{ name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role id.', example: 'senior-release-engineer' }],
    requestSample: {
      title: 'Check usage before editing or deleting',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/agent-roles/senior-release-engineer/usage" | jq',
      expectedOutput: 'The pipelines and teams that depend on the role — the answer to "what will I break?".',
    },
    responses: [{ status: 200, description: 'Usage across pipelines and teams.', contentType: 'application/json', sample: '{\n  "pipelines": ["platform/release-service"],\n  "teams": ["platform"],\n  "is_default": false\n}' }],
    errors: [
      { status: 400, cause: 'The id is missing.', action: 'Name the role.' },
      { status: 500, cause: 'The usage query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
    notes: 'Call this before editing a role, not just before deleting one: an edit changes behaviour everywhere without any error.',
  },
  {
    method: 'POST',
    path: '/v1/system/agent-roles/validate',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Validates an agent role definition without storing it.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Validate an agent role',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/agent-roles/validate" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @role.json | jq',
      expectedOutput: 'The `valid`, `errors`, `warnings` shape used by every validation route.',
    },
    responses: [{ status: 200, description: 'Validation ran. Read `valid` rather than the status code.', contentType: 'application/json', sample: '{\n  "valid": true,\n  "errors": [],\n  "warnings": []\n}' }],
    errors: [{ status: 400, cause: 'The payload could not be read.', action: 'Send a JSON role document.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/agent_profiles_test.go'],
    evidence: ['services/nopsai/agent_profiles.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/mcp/servers',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Lists configured MCP servers.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List MCP servers',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/servers" | jq \'.[] | {name, transport, enabled}\'',
      expectedOutput: 'Every server the platform may connect to. Credentials are references, never values.',
    },
    responses: [{ status: 200, description: 'MCP servers.', contentType: 'application/json', sample: '[' + MCP_SERVER + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
    notes: 'A server is a connection; a profile is permission to use some of its tools. Pipelines name profiles, never servers.',
  },
  {
    method: 'POST',
    path: '/v1/system/mcp/servers',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Registers an MCP server.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Register a server',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/mcp/servers" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"jira","transport":"http","url":"https://mcp.example.com/jira","auth_type":"credential","credential_ref":"platform/jira-mcp"}\' | jq',
      expectedOutput: 'The registered server. Nothing can use it until a profile names it.',
    },
    responses: [{ status: 200, description: 'Server registered.', contentType: 'application/json', sample: MCP_SERVER }],
    errors: [
      { status: 400, cause: 'An unknown transport, a missing URL, or an unresolvable credential.', action: 'The message names the field.' },
      { status: 500, cause: 'The server could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Registers a connection target. Registration alone grants nothing.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_registry_persistence_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/mcp/servers/{serverName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Reads one MCP server.',
    depth: 'full',
    parameters: [{ name: 'serverName', in: 'path', type: 'string', required: true, description: 'Server name.', example: 'jira' }],
    requestSample: {
      title: 'Read a server',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/servers/jira" | jq',
      expectedOutput: 'Transport, URL, and auth type. The credential is a reference.',
    },
    responses: [{ status: 200, description: 'The server.', contentType: 'application/json', sample: MCP_SERVER }],
    errors: [{ status: 404, cause: 'No server with that name.', action: 'Confirm the name from the list.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'PUT',
    path: '/v1/system/mcp/servers/{serverName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Creates or replaces an MCP server.',
    depth: 'full',
    parameters: [{ name: 'serverName', in: 'path', type: 'string', required: true, description: 'Server name.', example: 'jira' }],
    requestSample: {
      title: 'Upsert a server',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/mcp/servers/jira" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @server.json | jq',
      expectedOutput: 'The stored server. Test it before relying on it.',
    },
    responses: [{ status: 200, description: 'Server stored.', contentType: 'application/json', sample: MCP_SERVER }],
    errors: [
      { status: 400, cause: 'An invalid transport, URL, or credential reference.', action: 'The message names the field.' },
      { status: 500, cause: 'The server could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Every profile naming this server picks up the change.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_registry_persistence_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/system/mcp/servers/{serverName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Removes an MCP server.',
    depth: 'full',
    parameters: [{ name: 'serverName', in: 'path', type: 'string', required: true, description: 'Server to remove.', example: 'jira' }],
    requestSample: {
      title: 'Remove a server',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/servers/jira" -w "%{http_code}\\n"',
      expectedOutput: '204, unless a profile still names it.',
    },
    responses: [{ status: 204, description: 'Server removed.', sample: '' }],
    errors: [
      { status: 400, cause: 'The name is missing.', action: 'Name the server.' },
      { status: 404, cause: 'No server with that name.', action: 'It may already be removed.' },
      { status: 409, cause: 'A profile still references the server.', action: 'Remove it from the profiles first.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_registry_persistence_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/mcp/servers/{serverName}/test',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Tests connectivity and authentication to an MCP server.',
    depth: 'full',
    parameters: [{ name: 'serverName', in: 'path', type: 'string', required: true, description: 'Server to test.', example: 'jira' }],
    requestSample: {
      title: 'Test a server',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/servers/jira/test" | jq',
      expectedOutput: 'A real connection attempt, which is how you separate "configured" from "reachable".',
    },
    responses: [{ status: 200, description: 'The server answered.', contentType: 'application/json', sample: '{ "ok": true, "server": "jira" }' }],
    errors: [
      { status: 400, cause: 'The server is incomplete or disabled.', action: 'Finish configuring it.' },
      { status: 404, cause: 'No server with that name.', action: 'Confirm the name.' },
      { status: 502, cause: 'The server could not be reached or rejected the credentials.', action: 'The message carries the failure — usually egress or an expired credential.' },
    ],
    sideEffects: ['Makes one real connection to the server.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/mcp/servers/{serverName}/discover-tools',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Asks a server which tools it offers.',
    depth: 'full',
    parameters: [{ name: 'serverName', in: 'path', type: 'string', required: true, description: 'Server to query.', example: 'jira' }],
    requestSample: {
      title: 'Discover a server’s tools',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/servers/jira/discover-tools" | jq',
      expectedOutput: 'The tool list, which is what a profile then narrows.',
    },
    responses: [{ status: 200, description: 'Tools the server offers.', contentType: 'application/json', sample: '{\n  "server": "jira",\n  "tools": ["search", "get_issue", "create_issue"]\n}' }],
    errors: [
      { status: 400, cause: 'The server is incomplete or disabled.', action: 'Finish configuring it.' },
      { status: 404, cause: 'No server with that name.', action: 'Confirm the name.' },
      { status: 502, cause: 'The server could not be reached.', action: 'Test the server first.' },
      { status: 500, cause: 'The discovery response could not be read.', action: 'The server answered something unexpected.' },
    ],
    sideEffects: ['Makes one real call to the server.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
    notes: 'Discovery is what makes a profile reviewable: you grant named tools rather than "whatever this server exposes".',
  },
  {
    method: 'GET',
    path: '/v1/system/mcp/profiles',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Lists platform MCP profiles.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List MCP profiles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/profiles" | jq',
      expectedOutput: 'Each profile with the servers and tools it permits.',
    },
    responses: [{ status: 200, description: 'MCP profiles.', contentType: 'application/json', sample: '[' + MCP_PROFILE + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/mcp/profiles',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Creates an MCP profile.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a profile from discovered tools',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/mcp/profiles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"jira-readonly","servers":[{"server":"jira","tools":["search","get_issue"]}],"allowed_scopes":["platform/production"]}\' | jq',
      expectedOutput: 'The profile a pipeline may then name in `mcp_profiles`.',
    },
    responses: [{ status: 200, description: 'Profile created.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [
      { status: 400, cause: 'An unknown server, an empty tool list, or an unusable scope.', action: 'Discover the server’s tools first.' },
      { status: 500, cause: 'The profile could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a grantable tool set.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
    notes: '`allowed_scopes` bounds where the profile may be used, which is how a production-only tool set stays out of development runs.',
  },
  {
    method: 'GET',
    path: '/v1/system/mcp/profiles/{profileName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Reads one MCP profile.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'jira-readonly' }],
    requestSample: {
      title: 'Read a profile',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/profiles/jira-readonly" | jq',
      expectedOutput: 'The exact tools this profile permits, per server.',
    },
    responses: [{ status: 200, description: 'The profile.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [{ status: 404, cause: 'No profile with that name.', action: 'Confirm the name.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'PUT',
    path: '/v1/system/mcp/profiles/{profileName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Creates or replaces an MCP profile.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'jira-readonly' }],
    requestSample: {
      title: 'Narrow a profile’s tools',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/mcp/profiles/jira-readonly" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"servers":[{"server":"jira","tools":["search"]}]}\' | jq',
      expectedOutput: 'The stored profile. Every pipeline naming it is narrowed at once.',
    },
    responses: [{ status: 200, description: 'Profile stored.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [
      { status: 400, cause: 'An unknown server or tool.', action: 'Rediscover the server’s tools; the offer may have changed.' },
      { status: 500, cause: 'The profile could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what every pipeline naming the profile can reach.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
    notes: 'This is the only place tool access narrows. Pipeline, step, and task profiles are additive at run time.',
  },
  {
    method: 'DELETE',
    path: '/v1/system/mcp/profiles/{profileName}',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Deletes an MCP profile.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to delete.', example: 'jira-readonly' }],
    requestSample: {
      title: 'Delete a profile',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/profiles/jira-readonly" -w "%{http_code}\\n"',
      expectedOutput: '204, unless a pipeline still names it.',
    },
    responses: [{ status: 204, description: 'Profile deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The name is missing.', action: 'Name the profile.' },
      { status: 404, cause: 'No profile with that name.', action: 'It may already be deleted.' },
      { status: 409, cause: 'A pipeline still names the profile.', action: 'Remove the reference first.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/mcp/profiles/{profileName}/test',
    area: 'AI configuration',
    access: 'authorized',
    purpose: 'Tests every server a profile names.',
    depth: 'full',
    parameters: [{ name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to test.', example: 'jira-readonly' }],
    requestSample: {
      title: 'Test a profile end to end',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/mcp/profiles/jira-readonly/test" | jq',
      expectedOutput: 'One result per server the profile names, so a partially broken profile is visible before a run needs it.',
    },
    responses: [{ status: 200, description: 'Per-server results.', contentType: 'application/json', sample: '{\n  "profile": "jira-readonly",\n  "servers": [{ "server": "jira", "ok": true }]\n}' }],
    errors: [
      { status: 400, cause: 'The profile is empty or disabled.', action: 'Add at least one server.' },
      { status: 404, cause: 'No profile with that name.', action: 'Confirm the name.' },
      { status: 502, cause: 'A server could not be reached.', action: 'Test that server directly to isolate it.' },
      { status: 500, cause: 'The test could not run.', action: 'Platform fault.' },
    ],
    sideEffects: ['Makes one real call per server in the profile.'],
    coveringTests: ['services/nopsai/mcp_config_test.go'],
    evidence: ['services/nopsai/mcp_registry.go'],
  },
];
