import type { WikiApiRoute } from '../../types.js';

const CONVERSATION =
  '{\n  "id": "d7a1b3c4-9e21-4f88-b0c2-5a7f1e3d9b60",\n  "title": "Why did release-service fail?",\n  "created_at": "2026-08-19T12:02:11Z",\n  "updated_at": "2026-08-19T12:06:44Z"\n}';

/**
 * Assistant and AI surfaces.
 *
 * The assistant, the analysis evaluator, and the hosted MCP endpoint all run as
 * the calling subject: configuration decides which capability families exist at
 * all, and AAA still decides which resources within them the caller may reach.
 */
export const assistant_and_ai_surfacesRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/assistant/config',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Reads the assistant capability configuration for this install.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read assistant configuration',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/config" | jq',
      expectedOutput: 'Which capability families are enabled. Runtime and admin execution tools are hidden unless action execution is on.',
    },
    responses: [
      { status: 200, description: 'Assistant feature flags.', contentType: 'application/json', sample: '{\n  "enabled": true,\n  "features": {\n    "action_execution": false,\n    "page_context": true\n  }\n}' },
    ],
    errors: [],
    notes: 'Feature flags come from `setting/system/assistant.yaml`, so they are GitOps-owned rather than set through this API.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go', 'doc/assistant-capabilities.md'],
  },
  {
    method: 'GET',
    path: '/v1/assistant/models',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Lists the model profiles the caller may drive the assistant with.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List assistant models',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/models" | jq',
      expectedOutput: 'Profiles this caller is allowed to use — not every profile the platform has.',
    },
    responses: [
      { status: 200, description: 'Model profiles available to the caller.', contentType: 'application/json', sample: '[\n  { "name": "reasoning-large", "provider": "anthropic", "is_default": true }\n]' },
    ],
    errors: [],
    notes: 'The list is per caller, so two people can legitimately see different models.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/assistant_llm_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
  },
  {
    method: 'GET',
    path: '/v1/assistant/conversations',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Lists the caller’s conversations.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List your conversations',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/conversations" | jq',
      expectedOutput: 'Only the caller’s own conversations. There is no route that lists another subject’s.',
    },
    responses: [{ status: 200, description: 'The caller’s conversations.', contentType: 'application/json', sample: '[' + CONVERSATION + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
  },
  {
    method: 'POST',
    path: '/v1/assistant/conversations',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Starts a conversation.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Start a conversation',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/assistant/conversations" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"title":"Why did release-service fail?"}\' | jq -r .id',
      expectedOutput: 'The conversation id to post messages into.',
    },
    responses: [{ status: 201, description: 'Conversation created.', contentType: 'application/json', sample: CONVERSATION }],
    errors: [
      { status: 400, cause: 'The body is malformed.', action: 'Send valid JSON; the title is optional.' },
      { status: 500, cause: 'The conversation could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a conversation owned by the caller.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
  },
  {
    method: 'GET',
    path: '/v1/assistant/conversations/{id}',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Reads one conversation with its messages.',
    depth: 'full',
    parameters: [{ name: 'id', in: 'path', type: 'uuid', required: true, description: 'Conversation id.', example: 'd7a1b3c4-9e21-4f88-b0c2-5a7f1e3d9b60' }],
    requestSample: {
      title: 'Read a conversation',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/conversations/$CONVERSATION_ID" | jq',
      expectedOutput: 'The conversation and its message history.',
    },
    responses: [{ status: 200, description: 'The conversation.', contentType: 'application/json', sample: CONVERSATION }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use an id from the list.' },
      { status: 404, cause: 'No conversation with that id for this caller.', action: 'A conversation belonging to someone else is a 404, not a 403.' },
      { status: 500, cause: 'The conversation could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
    notes: 'Another subject’s conversation answers 404 rather than 403, so the API does not confirm it exists.',
  },
  {
    method: 'POST',
    path: '/v1/assistant/conversations/{id}/messages',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Sends a message and gets the assistant’s reply.',
    depth: 'full',
    parameters: [{ name: 'id', in: 'path', type: 'uuid', required: true, description: 'Conversation id.', example: 'd7a1b3c4-9e21-4f88-b0c2-5a7f1e3d9b60' }],
    requestSample: {
      title: 'Ask a question',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/assistant/conversations/$CONVERSATION_ID/messages" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"message":"Why did the last release-service run fail?"}\' | jq',
      expectedOutput: 'The assistant’s reply, produced by reading only what this caller is allowed to see.',
    },
    responses: [{ status: 201, description: 'The reply.', contentType: 'application/json', sample: '{\n  "role": "assistant",\n  "content": "The last run failed at the licences task...",\n  "created_at": "2026-08-19T12:06:44Z"\n}' }],
    errors: [
      { status: 400, cause: 'An empty message or malformed body.', action: 'Send `message`.' },
      { status: 401, cause: 'The caller identity could not be resolved.', action: 'The assistant runs as the caller and refuses to run as nobody.' },
      { status: 404, cause: 'No conversation with that id for this caller.', action: 'Confirm the id.' },
      { status: 500, cause: 'The assistant call failed.', action: 'Retry; check the model profile is working.' },
    ],
    sideEffects: [
      'Stores the message and the reply on the conversation.',
      'Reads product data as the caller, so the answer is bounded by the caller’s own access.',
      'Records AI usage for the call.',
    ],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go', 'services/nopsai/assistant_page_context_test.go'],
    evidence: ['services/nopsai/assistant_routes.go', 'doc/assistant-capabilities.md'],
    notes: 'The assistant is not a privileged reader. It sees exactly what the caller could fetch through the API, which is why two people get different answers to the same question.',
  },
  {
    method: 'POST',
    path: '/v1/assistant/conversations/{id}/summarize-memory',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Compacts a long conversation into a summary the assistant keeps using.',
    depth: 'full',
    parameters: [{ name: 'id', in: 'path', type: 'uuid', required: true, description: 'Conversation id.', example: 'd7a1b3c4-9e21-4f88-b0c2-5a7f1e3d9b60' }],
    requestSample: {
      title: 'Summarise a long conversation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/conversations/$CONVERSATION_ID/summarize-memory" | jq',
      expectedOutput: 'A stored summary that replaces older turns in the prompt, keeping the conversation usable.',
    },
    responses: [{ status: 200, description: 'The stored summary.', contentType: 'application/json', sample: '{\n  "summary": "Investigating repeated licence-check failures on release-service."\n}' }],
    errors: [
      { status: 400, cause: 'The id is malformed or the conversation is empty.', action: 'There has to be something to summarise.' },
      { status: 404, cause: 'No conversation with that id for this caller.', action: 'Confirm the id.' },
      { status: 500, cause: 'Summarisation failed.', action: 'Retry; it makes a model call.' },
    ],
    sideEffects: ['Makes a model call and records AI usage.', 'Replaces older turns in the prompt with the summary.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/assistant/conversations/{id}',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Deletes a conversation.',
    depth: 'full',
    parameters: [{ name: 'id', in: 'path', type: 'uuid', required: true, description: 'Conversation to delete.', example: 'd7a1b3c4-9e21-4f88-b0c2-5a7f1e3d9b60' }],
    requestSample: {
      title: 'Delete a conversation',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/conversations/$CONVERSATION_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. The conversation and its messages go; recorded AI usage stays.',
    },
    responses: [{ status: 204, description: 'Conversation deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use an id from the list.' },
      { status: 404, cause: 'No conversation with that id for this caller.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the conversation and its messages. AI usage records remain for accounting.'],
    coveringTests: ['services/nopsai/assistant_orchestration_test.go'],
    evidence: ['services/nopsai/assistant_routes.go'],
  },
  {
    method: 'POST',
    path: '/v1/analysis/evaluate',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'Runs an AI evaluation over a pipeline analysis.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Evaluate a pipeline analysis',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/analysis/evaluate" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @evaluation.json | jq',
      expectedOutput: 'A structured evaluation the pipeline Health tab renders alongside the analysis.',
      placeholders: ['`evaluation.json` is the analysis payload the Health tab submits.'],
    },
    responses: [{ status: 200, description: 'The evaluation.', contentType: 'application/json', sample: '{\n  "summary": "Two steps have no failure handling.",\n  "findings": [{ "severity": "medium", "message": "announce has no timeout" }]\n}' }],
    errors: [
      { status: 400, cause: 'The payload is malformed, or AI evaluation is disabled for this install.', action: 'The route refuses when the feature is off rather than silently returning nothing.' },
      { status: 502, cause: 'The model call failed.', action: 'Test the model profile.' },
    ],
    sideEffects: ['Makes a model call and records AI usage. It does not run the pipeline or consume runner capacity.'],
    coveringTests: ['services/nopsai/analysis_evaluation_handlers_test.go'],
    evidence: ['services/nopsai/analysis_evaluation_handlers.go'],
    notes: 'An evaluation is advice. Enforcement comes from governance level, guardrail knowledge, and approvals, which are separate mechanisms.',
  },
  {
    method: 'POST',
    path: '/v1/mcp',
    area: 'Assistant and AI surfaces',
    access: 'authenticated',
    purpose: 'The hosted MCP endpoint: JSON-RPC access to NopsAI as a set of tools.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List the tools this subject may call',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/mcp" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"jsonrpc":"2.0","id":2,"method":"tools/list"}\' | jq',
      expectedOutput: 'The tool list, scoped to the caller. An empty body defaults to `tools/list` rather than a parse error.',
    },
    responses: [
      { status: 200, description: 'A JSON-RPC result.', contentType: 'application/json', sample: '{\n  "jsonrpc": "2.0",\n  "id": 2,\n  "result": { "tools": [{ "name": "list_runs" }] }\n}' },
      { status: 202, description: 'Accepted for a notification-style request that expects no result.' },
    ],
    errors: [
      { status: 401, cause: 'No usable bearer token.', action: 'The hosted endpoint runs as the caller and refuses anonymous access.' },
    ],
    sideEffects: [
      'Tool calls perform real product operations as the caller, with the same AAA and audit as the REST routes they wrap.',
      'Mutating tools stay hidden unless assistant action execution is enabled, and confirmed mutations still pass every existing check.',
    ],
    coveringTests: ['services/nopsai/hosted_mcp_tools_test.go'],
    evidence: ['services/nopsai/hosted_mcp_api_bridge.go', 'doc/mcp-feature-coverage.md'],
    notes: 'An empty body is treated as `tools/list`, which makes it easy to check the endpoint by hand. Errors inside a JSON-RPC result are a 200 with an `error` member, not an HTTP error.',
  },
];
