import type { WikiApiRoute } from '../../types.js';

const LOGIN_RESPONSE =
  '{\n  "access_token": "eyJhbGciOi...",\n  "refresh_token": "rt_9f2c...",\n  "expires_at": "2026-08-19T11:04:11Z",\n  "roles": ["nopsai-admin"],\n  "provider": "local",\n  "email": "admin@example.com",\n  "sub": "admin",\n  "must_change_password": false,\n  "capabilities": {\n    "pipelines": { "write": true, "delete": true },\n    "system": { "config_read": true, "config_write": true, "access": true }\n  }\n}';

const TOKEN_RESPONSE =
  '{\n  "id": "5f0f5c0c-4a1e-4a6f-9f3a-6b1f7d2c9a11",\n  "name": "integration",\n  "token": "nopat_2f9c...only-returned-once",\n  "token_suffix": "9a11",\n  "created_at": "2026-08-19T10:41:02Z",\n  "expires_at": "2027-08-19T10:41:02Z"\n}';

/**
 * Authentication.
 *
 * Identity is provider ID, issuer, and subject. Email is metadata with a
 * verification status, and only an explicitly verified email may be used by
 * opt-in email-linking policy. Everything here except the caller-scoped routes
 * answers without a token, because a login flow cannot require one.
 */
export const authenticationRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/auth/providers',
    area: 'Authentication',
    access: 'public',
    purpose: 'Login methods offered by this installation.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List login methods',
      language: 'bash',
      code: 'curl -s "$NOPSAI_URL/v1/auth/providers" | jq',
      expectedOutput: 'Whether local login is enabled, whether OIDC is enabled, and the providers the login screen should offer.',
    },
    responses: [
      {
        status: 200,
        description: 'Public provider list. Client credentials and issuer configuration are deliberately not included.',
        contentType: 'application/json',
        sample:
          '{\n  "local_enabled": true,\n  "oidc_enabled": true,\n  "providers": [\n    {\n      "id": "keycloak",\n      "type": "oidc",\n      "display_name": "Corporate SSO",\n      "scopes": ["openid", "email", "profile"],\n      "allowed_email_domains": ["example.com"],\n      "auth_url_kind": "oidc"\n    }\n  ]\n}',
      },
    ],
    errors: [
      { status: 500, cause: 'Auth settings or the provider list could not be loaded from the database.', action: 'Check `/healthz` — this failure almost always means the database is unreachable.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go', 'services/nopsai/auth_oidc_models.go'],
    notes: '`local_enabled: false` is accepted only when external auth is enabled and at least one identity provider remains enabled, so an install cannot lock itself out.',
  },
  {
    method: 'POST',
    path: '/v1/auth/discover',
    area: 'Authentication',
    access: 'public',
    purpose: 'Resolves which provider should handle a given login identifier.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Discover the provider for an email',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/discover" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email":"person@example.com"}\' | jq',
      expectedOutput: '`found: true` with the provider to redirect to, or `found: false` when the domain maps to local login.',
      placeholders: ['The body takes `email` — not `identifier`, which is what the login route takes.'],
    },
    responses: [
      { status: 200, description: 'Whether a provider claims this email domain.', contentType: 'application/json', sample: '{\n  "found": true,\n  "provider": {\n    "id": "keycloak",\n    "type": "oidc",\n    "display_name": "Corporate SSO",\n    "auth_url_kind": "oidc"\n  }\n}' },
    ],
    errors: [
      { status: 400, cause: 'The body is malformed or the email cannot be normalised.', action: 'Send a syntactically valid email address in the `email` field.' },
      { status: 405, cause: 'A method other than POST.', action: 'Use POST.' },
      { status: 500, cause: 'Provider lookup failed.', action: 'Treat as a platform fault, not a client error.' },
    ],
    sideEffects: ['None. Discovery does not create a session or a login attempt record.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: 'This is how a login screen decides between showing a password field and redirecting to SSO.',
  },
  {
    method: 'POST',
    path: '/v1/auth/login',
    area: 'Authentication',
    access: 'public',
    purpose: 'Local username and password login.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Log in with a local account',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/login" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"identifier":"admin@example.com","password":"<password>"}\' | jq',
      expectedOutput: 'An access token, a refresh token, the resolved roles, and the capability map the UI renders from.',
      placeholders: ['The field is `identifier`, which accepts the subject or the email.'],
    },
    responses: [{ status: 200, description: 'Session established.', contentType: 'application/json', sample: LOGIN_RESPONSE }],
    errors: [
      { status: 400, cause: 'The body is not valid JSON.', action: 'Send `identifier` and `password` as JSON.' },
      { status: 401, cause: 'Unknown identifier, wrong password, a disabled account, or local login turned off.', action: 'The message is deliberately identical for each: it does not reveal whether the account exists.' },
      { status: 500, cause: 'Auth settings could not be loaded.', action: 'Platform fault. Check database reachability.' },
    ],
    sideEffects: [
      'Records a login attempt, which feeds rate limiting and lockout.',
      'Issues a refresh token that is stored server side and can be revoked by logout.',
      'Writes an audit record for the authentication decision.',
    ],
    coveringTests: ['services/nopsai/auth_middleware_test.go', 'services/nopsai/auth_bootstrap_test.go'],
    evidence: ['services/nopsai/auth_handlers.go', 'services/nopsai/auth_models.go'],
    notes: '`must_change_password: true` means the forced rotation is pending: change it before expecting other routes to answer.',
  },
  {
    method: 'POST',
    path: '/v1/auth/refresh',
    area: 'Authentication',
    access: 'public',
    purpose: 'Issues a new access token from a refresh token.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Refresh an access token',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/refresh" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"refresh_token\\":\\"$REFRESH\\"}" | jq -r .access_token',
      expectedOutput: 'A new access token with a fresh expiry.',
      placeholders: ['`$REFRESH` is the `refresh_token` from login or from the session exchange.'],
    },
    responses: [{ status: 200, description: 'A new session, in the same shape login returns.', contentType: 'application/json', sample: LOGIN_RESPONSE }],
    errors: [
      { status: 400, cause: 'The body is malformed or carries no refresh token.', action: 'Send `refresh_token`.' },
      { status: 401, cause: 'The refresh token is unknown, expired, or already revoked by a logout.', action: 'Start a new login. A revoked refresh token never becomes valid again.' },
    ],
    sideEffects: ['Rotates the stored refresh token state for the session.'],
    coveringTests: ['services/nopsai/auth_middleware_test.go'],
    evidence: ['services/nopsai/auth_handlers.go'],
    notes: 'This route is public because a caller with an expired access token has nothing else to authenticate with.',
  },
  {
    method: 'POST',
    path: '/v1/auth/logout',
    area: 'Authentication',
    access: 'public',
    purpose: 'Ends the current session and invalidates its refresh token.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Log out and follow the provider logout',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/logout" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"refresh_token\\":\\"$REFRESH\\",\\"return_to\\":\\"https://nopsai.example.com/login\\"}" | jq',
      expectedOutput: 'A `logout_url` when the provider supports single logout, otherwise an empty body with 204.',
      placeholders: ['`return_to` must be a URL the provider accepts as a post-logout redirect.'],
    },
    responses: [
      { status: 200, description: 'Session ended and the provider offers a logout URL to redirect to.', contentType: 'application/json', sample: '{"logout_url":"https://sso.example.com/logout?post_logout_redirect_uri=..."}' },
      { status: 204, description: 'Session ended and there is nothing further to redirect to.' },
    ],
    errors: [
      { status: 400, cause: 'The body is malformed.', action: 'Send valid JSON, or no body at all.' },
      { status: 500, cause: 'The refresh token could not be revoked.', action: 'Retry. Until it succeeds the refresh token remains usable.' },
    ],
    sideEffects: ['Revokes the refresh token server side.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_logout_test.go'],
    evidence: ['services/nopsai/auth_handlers.go', 'services/nopsai/http_middleware.go'],
    notes: 'Public at the middleware, like login and refresh: what it acts on is the refresh token in the body, so a caller whose access token already expired can still end its session.',
  },
  {
    method: 'GET',
    path: '/v1/auth/me',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Current identity, roles, and effective capabilities.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read the current identity',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/auth/me" | jq',
      expectedOutput: 'The subject, provider, roles, and the capability map. A 401 here means the token is wrong; a 403 elsewhere means the token is right and the access is not.',
    },
    responses: [
      {
        status: 200,
        description: 'Identity and capabilities for the caller behind this token.',
        contentType: 'application/json',
        sample:
          '{\n  "sub": "admin",\n  "email": "admin@example.com",\n  "provider": "local",\n  "roles": [{ "role": "nopsai-admin" }],\n  "external_managed": false,\n  "authentication_source": "local"\n}',
      },
    ],
    errors: [
      { status: 401, cause: 'Missing, malformed, or expired bearer token.', action: 'Refresh the access token or log in again.' },
      { status: 403, cause: 'The token is valid but the subject may not read its own record, which happens for a disabled account.', action: 'Check the account status in identity administration.' },
      { status: 404, cause: 'The token authenticates a subject that no longer exists.', action: 'Revoke the token: it outlived its account.' },
      { status: 500, cause: 'Capability resolution failed.', action: 'Platform fault; check AAA reachability.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/auth_middleware_test.go'],
    evidence: ['services/nopsai/auth_handlers.go', 'services/nopsai/auth_models.go'],
    notes: 'The capability map is what the UI renders navigation from. It is a convenience, not the authorization boundary — AAA still decides every request.',
  },
  {
    method: 'POST',
    path: '/v1/auth/password',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Changes the caller password, including the forced first-login rotation.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Rotate the caller password',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/password" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"current_password":"<old>","new_password":"<new>"}\' | jq',
      expectedOutput: '204 with no body. The old password stops working immediately.',
      placeholders: ['Both fields are required, including during the forced first-login rotation.'],
    },
    responses: [{ status: 204, description: 'Password changed.', sample: '' }],
    errors: [
      { status: 400, cause: 'The body is malformed or the new password fails policy.', action: 'The message names the rule that rejected it.' },
      { status: 401, cause: 'The current password is wrong, or the bearer token is invalid.', action: 'Confirm both before retrying.' },
      { status: 403, cause: 'The account is externally managed, so its password is not the platform’s to change.', action: 'Change it at the identity provider.' },
      { status: 404, cause: 'The subject no longer exists.', action: 'Revoke the token.' },
      { status: 500, cause: 'The change could not be persisted.', action: 'Retry; the old password remains valid until it succeeds.' },
    ],
    sideEffects: ['Clears the forced-rotation flag when one was pending.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_bootstrap_test.go'],
    evidence: ['services/nopsai/auth_profile_handlers.go', 'services/nopsai/auth_models.go'],
  },
  {
    method: 'POST',
    path: '/v1/auth/email',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Updates the caller email. Email is metadata, not identity.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Update the caller email',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/email" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email":"person@example.com"}\' | jq',
      expectedOutput: 'The updated user record. The subject and provider are unchanged, because those are the identity.',
    },
    responses: [
      { status: 200, description: 'The updated user summary.', contentType: 'application/json', sample: '{\n  "sub": "admin",\n  "email": "person@example.com",\n  "provider": "local",\n  "status": "active",\n  "external_managed": false\n}' },
    ],
    errors: [
      { status: 400, cause: 'The address is missing or not a valid email.', action: 'Send a syntactically valid address.' },
      { status: 401, cause: 'Invalid bearer token.', action: 'Refresh or log in again.' },
      { status: 403, cause: 'The account is externally managed, so its email comes from the provider.', action: 'Change it at the identity provider; the platform will not override provider metadata.' },
      { status: 404, cause: 'The subject no longer exists.', action: 'Revoke the token.' },
      { status: 409, cause: 'Another account already uses that address.', action: 'Pick a different address, or resolve the duplicate account first.' },
      { status: 500, cause: 'The update could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.', 'Does not change the subject, so nothing about authorization changes.'],
    coveringTests: ['services/nopsai/auth_middleware_test.go'],
    evidence: ['services/nopsai/auth_profile_handlers.go'],
    notes: 'Changing an email never changes who the caller is. Identity is provider ID, issuer, and subject.',
  },
  {
    method: 'GET',
    path: '/v1/auth/personal-tokens',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Lists the caller personal access tokens.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List your tokens',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/auth/personal-tokens" | jq',
      expectedOutput: 'Metadata only: id, name, suffix, creation, expiry, and last use. The value is never listed.',
    },
    responses: [
      {
        status: 200,
        description: 'The caller own tokens. Never another subject’s.',
        contentType: 'application/json',
        sample: '[\n  {\n    "id": "5f0f5c0c-4a1e-4a6f-9f3a-6b1f7d2c9a11",\n    "name": "laptop-cli",\n    "token_suffix": "9a11",\n    "created_at": "2026-08-19T10:41:02Z",\n    "last_used_at": "2026-08-19T12:03:55Z"\n  }\n]',
      },
    ],
    errors: [
      { status: 405, cause: 'A method other than GET.', action: 'Use GET.' },
      { status: 500, cause: 'The token list could not be read.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/personal_tokens.go', 'services/nopsai/auth_models.go'],
    notes: '`last_used_at` is the fastest way to find a token nothing uses any more before revoking it.',
  },
  {
    method: 'POST',
    path: '/v1/auth/personal-tokens',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Creates a personal access token. The value is returned once.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a personal access token',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/personal-tokens" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"integration","expires_in_days":365}\' | jq',
      expectedOutput: 'The token record including `token`, which appears in this response and nowhere else, ever.',
      placeholders: ['Choose exactly one expiry: `expires_in_days`, an explicit `expires_at`, or `never_expires: true`.'],
    },
    responses: [{ status: 201, description: 'Token created. Store the value now.', contentType: 'application/json', sample: TOKEN_RESPONSE }],
    errors: [
      { status: 400, cause: 'The name is missing, or the expiry fields conflict or are unparseable.', action: 'Send a name and exactly one expiry form.' },
      { status: 405, cause: 'A method other than POST.', action: 'Use POST.' },
      { status: 500, cause: 'The token could not be stored.', action: 'Retry; no token was issued.' },
    ],
    sideEffects: ['Creates a credential that carries the caller own permissions.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/personal_tokens.go', 'services/nopsai/auth_models.go'],
    notes: 'A personal token acts as the person who created it. A system that needs its own access should get a service account instead.',
  },
  {
    method: 'DELETE',
    path: '/v1/auth/personal-tokens/{tokenID}',
    area: 'Authentication',
    access: 'authenticated',
    purpose: 'Revokes a personal access token.',
    depth: 'full',
    parameters: [
      { name: 'tokenID', in: 'path', type: 'uuid', required: true, description: 'The token id from the list route — not the token value.', example: '5f0f5c0c-4a1e-4a6f-9f3a-6b1f7d2c9a11' },
    ],
    requestSample: {
      title: 'Revoke a token',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/auth/personal-tokens/$TOKEN_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. The token stops working immediately, including for requests already in flight elsewhere.',
    },
    responses: [{ status: 204, description: 'Token revoked.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is missing or malformed.', action: 'Use the `id` from the list route.' },
      { status: 404, cause: 'No such token for this caller.', action: 'A caller can only revoke their own tokens; an administrator revokes others through identity administration.' },
      { status: 500, cause: 'The revocation could not be persisted.', action: 'Retry: the token remains valid until it succeeds.' },
    ],
    sideEffects: ['Invalidates the token immediately.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/personal_tokens.go'],
  },
  {
    method: 'POST',
    path: '/v1/auth/session/exchange',
    area: 'Authentication',
    access: 'public',
    purpose: 'Exchanges a browser session artifact for API tokens.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Exchange a one-time code for tokens',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/auth/session/exchange" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"code\\":\\"$CODE\\"}" | jq',
      expectedOutput: 'The same session shape login returns.',
      placeholders: ['`$CODE` is the one-time code the provider callback handed to the browser.'],
    },
    responses: [{ status: 200, description: 'Session established from the exchanged code.', contentType: 'application/json', sample: LOGIN_RESPONSE }],
    errors: [
      { status: 400, cause: 'The body is malformed or carries no code.', action: 'Send `code`.' },
      { status: 401, cause: 'The code is unknown, expired, or already used.', action: 'Restart the login flow. A code works exactly once.' },
      { status: 405, cause: 'A method other than POST.', action: 'Use POST.' },
    ],
    sideEffects: ['Consumes the one-time code.', 'Issues access and refresh tokens.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_profile_handlers.go', 'services/nopsai/auth_oidc_models.go'],
    notes: 'This is what keeps provider tokens out of the browser URL: the callback hands over a code, and the code is exchanged server side.',
  },
  {
    method: 'GET',
    path: '/v1/auth/oidc/{provider}/start',
    area: 'Authentication',
    access: 'public',
    purpose: 'Begins an OIDC authorization code flow.',
    depth: 'full',
    parameters: [
      { name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider id from `/v1/auth/providers`.', example: 'keycloak' },
    ],
    requestSample: {
      title: 'Start an OIDC login',
      language: 'bash',
      code: 'curl -si "$NOPSAI_URL/v1/auth/oidc/keycloak/start" | head -3',
      expectedOutput: 'A 302 to the provider authorization endpoint with state and PKCE parameters.',
    },
    responses: [{ status: 302, description: 'Redirect to the identity provider.', sample: 'Location: https://sso.example.com/realms/nopsai/protocol/openid-connect/auth?client_id=...&state=...' }],
    errors: [
      { status: 400, cause: 'Unknown provider id, or the provider is disabled.', action: 'Use an id from `/v1/auth/providers`.' },
    ],
    sideEffects: ['Creates the pending login state the callback will validate.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: 'A browser route: it is meant to be navigated to, not called from an API client.',
  },
  {
    method: 'GET',
    path: '/v1/auth/oidc/{provider}/callback',
    area: 'Authentication',
    access: 'public',
    purpose: 'Completes the OIDC flow and establishes identity from provider ID, issuer, and subject.',
    depth: 'full',
    parameters: [
      { name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider id the flow was started for.', example: 'keycloak' },
      { name: 'code', in: 'query', type: 'string', required: true, description: 'Authorization code issued by the provider.' },
      { name: 'state', in: 'query', type: 'string', required: true, description: 'Opaque state that must match the pending login the start route created.' },
    ],
    requestSample: {
      title: 'What the provider calls',
      language: 'text',
      code: 'GET /v1/auth/oidc/keycloak/callback?code=<code>&state=<state>',
      expectedOutput: 'A redirect back to the UI carrying a one-time code, which the browser exchanges at /v1/auth/session/exchange.',
    },
    responses: [{ status: 302, description: 'Redirect to the UI with a one-time exchange code.', sample: 'Location: https://nopsai.example.com/login#code=...' }],
    errors: [
      { status: 400, cause: 'State does not match, the code is missing, or the ID token fails validation.', action: 'Restart the flow. A mismatched state is treated as a failed login, not a retryable error.' },
    ],
    sideEffects: [
      'Establishes or reconciles the local user record from provider ID, issuer, and subject.',
      'Records the email verification status the provider asserted.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go', 'services/nopsai/auth_oidc_integration_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: 'Email is optional metadata with verified, unverified, unknown, or not-provided status. Only an explicitly verified email may be used by opt-in email-linking policy.',
  },
  {
    method: 'GET',
    path: '/v1/auth/oauth2/{provider}/start',
    area: 'Authentication',
    access: 'public',
    purpose: 'Begins an OAuth2 flow for providers without full OIDC discovery.',
    depth: 'full',
    parameters: [
      { name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider id from `/v1/auth/providers` whose `auth_url_kind` is oauth2.', example: 'github' },
    ],
    requestSample: {
      title: 'Start an OAuth2 login',
      language: 'bash',
      code: 'curl -si "$NOPSAI_URL/v1/auth/oauth2/github/start" | head -3',
      expectedOutput: 'A 302 to the provider authorization endpoint.',
    },
    responses: [{ status: 302, description: 'Redirect to the provider.', sample: 'Location: https://github.com/login/oauth/authorize?client_id=...&state=...' }],
    errors: [{ status: 400, cause: 'Unknown or disabled provider.', action: 'Use an id from `/v1/auth/providers`.' }],
    sideEffects: ['Creates the pending login state the callback will validate.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: 'GitHub uses this pair rather than the OIDC one because it does not issue an ID token.',
  },
  {
    method: 'GET',
    path: '/v1/auth/oauth2/{provider}/callback',
    area: 'Authentication',
    access: 'public',
    purpose: 'Completes the OAuth2 flow.',
    depth: 'full',
    parameters: [
      { name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider id the flow was started for.', example: 'github' },
      { name: 'code', in: 'query', type: 'string', required: true, description: 'Authorization code issued by the provider.' },
      { name: 'state', in: 'query', type: 'string', required: true, description: 'Opaque state that must match the pending login.' },
    ],
    requestSample: {
      title: 'What the provider calls',
      language: 'text',
      code: 'GET /v1/auth/oauth2/github/callback?code=<code>&state=<state>',
      expectedOutput: 'A redirect back to the UI carrying a one-time exchange code.',
    },
    responses: [{ status: 302, description: 'Redirect to the UI with a one-time exchange code.', sample: 'Location: https://nopsai.example.com/login#code=...' }],
    errors: [{ status: 400, cause: 'State mismatch, missing code, or the provider profile call failed.', action: 'Restart the flow.' }],
    sideEffects: ['Establishes or reconciles the local user record.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_oidc_flow_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
  },
];
