import type { WikiApiRoute } from '../../types.js';

const DASHBOARD =
  '{\n  "id": "platform/service-health",\n  "name": "service-health",\n  "team_path": "platform",\n  "title": "Service health",\n  "sections": [{ "section_key": "releases", "title": "Releases", "display_order": 1 }]\n}';

const SOURCE =
  '{\n  "id": "7f10c3a2-55d8-4a19-8f61-2c4b9e0d7a34",\n  "section_key": "releases",\n  "pipeline_id": "platform/release-service",\n  "output_name": "Release health",\n  "entry_key": "payments",\n  "enabled": true,\n  "required_for_refresh": true\n}';

const REFRESH =
  '{\n  "id": "c92a1f70-4d6b-4a02-9f18-7b3c5e9d2a41",\n  "state": "running",\n  "started_at": "2026-08-19T13:02:11Z",\n  "sources_total": 3,\n  "sources_completed": 1,\n  "sources_failed": 0\n}';

const SCHEDULE =
  '{\n  "id": "e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52",\n  "cron_expression": "0 6 * * *",\n  "timezone": "Europe/Berlin",\n  "enabled": true,\n  "strict": true\n}';

const DASH_ID = {
  name: 'dashboardID',
  in: 'path' as const,
  type: 'string',
  required: true,
  description: 'Dashboard identifier.',
  example: 'platform/service-health',
};

/**
 * Dashboards.
 *
 * A dashboard is a container of sections; pipelines publish entries into it
 * through final outputs of `type: dashboard`. A refresh re-runs the bound source
 * pipelines rather than re-querying stored data, which is why it is
 * asynchronous, capacity-bound, and refused while one is already in flight.
 */
export const dashboardsRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/dashboards',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists dashboards the caller can see.',
    depth: 'full',
    parameters: [
      { name: 'team_path', in: 'query', type: 'string', required: false, description: 'Restrict to one team path.', example: 'team_path=platform' },
    ],
    requestSample: {
      title: 'List dashboards',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards" | jq \'.[] | {id, team_path}\'',
      expectedOutput: 'Dashboards the caller may see, filtered per caller by AAA.',
    },
    responses: [{ status: 200, description: 'Visible dashboards.', contentType: 'application/json', sample: '[' + DASHBOARD + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_auth_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'A dashboard is owned by a team path, so two callers legitimately see different lists.',
  },
  {
    method: 'POST',
    path: '/v1/dashboards',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Creates a dashboard.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a dashboard with one section',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/dashboards" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"service-health","team_path":"platform","sections":[{"section_key":"releases","title":"Releases"}]}\' | jq -r .id',
      expectedOutput: 'The dashboard id, which a pipeline then publishes into through `dashboard.ref`.',
    },
    responses: [{ status: 201, description: 'Dashboard created.', contentType: 'application/json', sample: DASHBOARD }],
    errors: [
      { status: 400, cause: 'A missing name or an unusable team path.', action: 'The message names the field.' },
      { status: 409, cause: 'A dashboard with that name already exists in the team.', action: 'Pick another name.' },
      { status: 500, cause: 'The dashboard could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a publication target. Nothing appears until a run publishes into it.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'The dashboard is the container; the data arrives from pipeline final outputs of `type: dashboard`.',
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Reads a dashboard definition.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Read a dashboard definition',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID" | jq',
      expectedOutput: 'Sections, sources, and settings — the definition rather than the rendered data.',
    },
    responses: [{ status: 200, description: 'The dashboard definition.', contentType: 'application/json', sample: DASHBOARD }],
    errors: [],
    notes: 'Definition and rendered view are separate routes: this one never composes published data.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_auth_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/view',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Reads the composed dashboard with its current entries.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Read the rendered dashboard',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/view" | jq',
      expectedOutput: 'Sections with their published entries, which is what the UI renders.',
    },
    responses: [
      { status: 200, description: 'The composed view.', contentType: 'application/json', sample: '{\n  "id": "platform/service-health",\n  "sections": [\n    {\n      "section_key": "releases",\n      "entries": [{ "entry_key": "payments", "published_at": "2026-08-19T12:44:02Z" }]\n    }\n  ]\n}' },
    ],
    errors: [{ status: 500, cause: 'The view could not be composed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'An empty section means nothing has published yet, not that the dashboard is broken. The publication history tells the two apart.',
  },
  {
    method: 'PUT',
    path: '/v1/dashboards/{dashboardID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Replaces a dashboard definition.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Replace a dashboard',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @dashboard.json | jq',
      expectedOutput: 'The stored definition. Sections omitted from the body are removed with their entries.',
      placeholders: ['A PUT replaces the whole definition; use PATCH to change one field.'],
    },
    responses: [{ status: 200, description: 'Dashboard replaced.', contentType: 'application/json', sample: DASHBOARD }],
    errors: [
      { status: 400, cause: 'An invalid section or layout.', action: 'The message names the field.' },
      { status: 409, cause: 'The new name collides with another dashboard in the team.', action: 'Pick another name.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removing a section removes the entries published into it.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/dashboards/{dashboardID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Partially updates a dashboard.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Retitle a dashboard',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"title":"Payments service health"}\' | jq',
      expectedOutput: 'Only the supplied fields change; sections and entries are untouched.',
    },
    responses: [{ status: 200, description: 'Dashboard updated.', contentType: 'application/json', sample: DASHBOARD }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'Prefer PATCH for edits: a PUT that forgets a section deletes it and everything published into it.',
  },
  {
    method: 'DELETE',
    path: '/v1/dashboards/{dashboardID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Deletes a dashboard.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Delete a dashboard',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Pipelines publishing into it start failing that output item.',
    },
    responses: [{ status: 204, description: 'Dashboard deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: [
      'Every published entry goes with it.',
      'Pipelines with a `dashboard.ref` to it fail that output item on their next run.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'Check which pipelines publish into it first: the failure surfaces at their next run, not here.',
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/sections',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists a dashboard’s sections.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'List sections',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sections" | jq',
      expectedOutput: 'Sections with their keys and display order. A pipeline publishes into a section by key.',
    },
    responses: [
      { status: 200, description: 'Sections.', contentType: 'application/json', sample: '[\n  { "section_key": "releases", "title": "Releases", "display_order": 1 }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: '`section_key` is what a pipeline’s `dashboard.section` must match. A typo there publishes nowhere without erroring.',
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/sections',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Adds a section.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Add a section',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sections" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"section_key":"incidents","title":"Incidents","display_order":2}\' | jq',
      expectedOutput: 'The section, ready to be published into by key.',
    },
    responses: [{ status: 201, description: 'Section created.', contentType: 'application/json', sample: '{ "section_key": "incidents", "title": "Incidents", "display_order": 2 }' }],
    errors: [
      { status: 400, cause: 'A missing key or title.', action: 'Both are required.' },
      { status: 409, cause: 'That section key already exists on the dashboard.', action: 'Keys are unique per dashboard.' },
      { status: 500, cause: 'The section could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'PUT',
    path: '/v1/dashboards/{dashboardID}/sections/{sectionID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Replaces a section.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sectionID', in: 'path', type: 'string', required: true, description: 'Section identifier or key.', example: 'releases' }],
    requestSample: {
      title: 'Replace a section',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sections/releases" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"title":"Releases","display_order":1}\' | jq',
      expectedOutput: 'The stored section. Its published entries are unaffected.',
    },
    responses: [{ status: 200, description: 'Section replaced.', contentType: 'application/json', sample: '{ "section_key": "releases", "title": "Releases", "display_order": 1 }' }],
    errors: [
      { status: 400, cause: 'An invalid layout or order.', action: 'The message names the field.' },
      { status: 404, cause: 'No section with that key.', action: 'List the sections.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'Renaming the title is safe; changing the key is not, because pipelines publish by key.',
  },
  {
    method: 'PATCH',
    path: '/v1/dashboards/{dashboardID}/sections/{sectionID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Partially updates a section.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sectionID', in: 'path', type: 'string', required: true, description: 'Section identifier or key.', example: 'releases' }],
    requestSample: {
      title: 'Reorder a section',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sections/releases" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"display_order":3}\' | jq',
      expectedOutput: 'Only the supplied fields change.',
    },
    responses: [{ status: 200, description: 'Section updated.', contentType: 'application/json', sample: '{ "section_key": "releases", "title": "Releases", "display_order": 3 }' }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 404, cause: 'No section with that key.', action: 'List the sections.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/dashboards/{dashboardID}/sections/{sectionID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Deletes a section and its entries.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sectionID', in: 'path', type: 'string', required: true, description: 'Section to delete.', example: 'incidents' }],
    requestSample: {
      title: 'Delete a section',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sections/incidents" -w "%{http_code}\\n"',
      expectedOutput: '204, with every entry published into it.',
    },
    responses: [{ status: 204, description: 'Section deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No section with that key.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the entries published into the section.', 'Pipelines publishing into it silently stop appearing.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'A pipeline publishing into a missing section does not error — it publishes nowhere. That is the failure mode to watch for after deleting one.',
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/sources',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists the source bindings a refresh will run.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'List source bindings',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sources" | jq',
      expectedOutput: 'Which pipeline and output feeds each section, and whether it is required for a strict refresh.',
    },
    responses: [{ status: 200, description: 'Source bindings.', contentType: 'application/json', sample: '[' + SOURCE + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'A source binding is what makes a refresh possible: without one, the dashboard only updates when a pipeline happens to run.',
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/sources',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Binds a pipeline output to a section.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Bind a pipeline output to a section',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sources" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"section_key":"releases","pipeline_id":"platform/release-service","output_name":"Release health","entry_key":"payments","required_for_refresh":true}\' | jq',
      expectedOutput: 'The binding. A refresh now runs this pipeline to repopulate the section.',
    },
    responses: [{ status: 201, description: 'Source bound.', contentType: 'application/json', sample: SOURCE }],
    errors: [
      { status: 400, cause: 'An unknown pipeline, output name, or section key.', action: 'The output name must match the pipeline final output item.' },
      { status: 500, cause: 'The binding could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['A refresh will run this pipeline, which consumes runner capacity.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: '`required_for_refresh` decides whether a strict refresh fails when this source fails, or carries on with the rest.',
  },
  {
    method: 'PUT',
    path: '/v1/dashboards/{dashboardID}/sources/{sourceID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Replaces a source binding.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source binding identifier.', example: '7f10c3a2-55d8-4a19-8f61-2c4b9e0d7a34' }],
    requestSample: {
      title: 'Replace a source binding',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sources/$SOURCE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @source.json | jq',
      expectedOutput: 'The stored binding.',
    },
    responses: [{ status: 200, description: 'Binding replaced.', contentType: 'application/json', sample: SOURCE }],
    errors: [
      { status: 400, cause: 'An unknown pipeline or output name.', action: 'The message names the field.' },
      { status: 404, cause: 'No binding with that id.', action: 'List the sources.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what the next refresh runs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/dashboards/{dashboardID}/sources/{sourceID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Partially updates a source binding.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source binding identifier.', example: '7f10c3a2-55d8-4a19-8f61-2c4b9e0d7a34' }],
    requestSample: {
      title: 'Make a source optional for refresh',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sources/$SOURCE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"required_for_refresh":false}\' | jq \'{id, required_for_refresh}\'',
      expectedOutput: 'A strict refresh now continues when this source fails instead of failing the whole run.',
    },
    responses: [{ status: 200, description: 'Binding updated.', contentType: 'application/json', sample: SOURCE }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 404, cause: 'No binding with that id.', action: 'List the sources.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes how a strict refresh treats a failure from this source.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'This is the setting to reach for when one flaky source keeps failing an otherwise healthy refresh.',
  },
  {
    method: 'DELETE',
    path: '/v1/dashboards/{dashboardID}/sources/{sourceID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Removes a source binding.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Binding to remove.', example: '7f10c3a2-55d8-4a19-8f61-2c4b9e0d7a34' }],
    requestSample: {
      title: 'Remove a source binding',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/sources/$SOURCE_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Entries already published stay; refreshes stop running that pipeline.',
    },
    responses: [{ status: 204, description: 'Binding removed.', sample: '' }],
    errors: [
      { status: 404, cause: 'No binding with that id.', action: 'It may already be removed.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Refreshes stop running that pipeline. Published entries remain until overwritten or expired.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/history',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists publication history.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'limit', in: 'query', type: 'integer', required: false, description: 'How many publications to return.', example: 'limit=50' }],
    requestSample: {
      title: 'Read publication history',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/history" | jq',
      expectedOutput: 'What was published, when, and by which run.',
    },
    responses: [
      { status: 200, description: 'Publication history.', contentType: 'application/json', sample: '[\n  {\n    "publication_id": "a30f5c81-2b47-4d90-9e12-6f3a7c0b5d24",\n    "section_key": "releases",\n    "entry_key": "payments",\n    "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n    "published_at": "2026-08-19T12:44:02Z"\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'This is where a missing tile is diagnosed: it separates "never published" from "published and later removed".',
  },
  {
    method: 'DELETE',
    path: '/v1/dashboards/{dashboardID}/publications/{publicationID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Removes one published entry.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'publicationID', in: 'path', type: 'string', required: true, description: 'Publication identifier from the history.', example: 'a30f5c81-2b47-4d90-9e12-6f3a7c0b5d24' }],
    requestSample: {
      title: 'Remove a published entry',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/publications/$PUBLICATION_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. The card disappears from the view; the run that produced it is untouched.',
    },
    responses: [{ status: 204, description: 'Publication removed.', sample: '' }],
    errors: [
      { status: 404, cause: 'No publication with that id.', action: 'Take the id from the history.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes one entry from the view. The producing run and its outputs are unaffected.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_publication_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'Removing a bad entry is a display fix, not a data fix. The next publication from that source brings it back.',
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refresh',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Starts a refresh, re-running the bound source pipelines.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'strict', in: 'query', type: 'boolean', required: false, defaultValue: 'false', description: 'Fail the refresh when a source marked `required_for_refresh` fails.', example: 'strict=true' }],
    requestSample: {
      title: 'Start a strict refresh',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh?strict=true" | jq -r .id',
      expectedOutput: '202 with a refresh id. This starts real pipeline runs, so it consumes runner capacity.',
    },
    responses: [{ status: 202, description: 'Refresh started.', contentType: 'application/json', sample: REFRESH }],
    errors: [
      { status: 400, cause: 'The dashboard has no source bindings to refresh.', action: 'Bind at least one pipeline output first.' },
      { status: 401, cause: 'The caller identity could not be resolved.', action: 'A refresh runs pipelines as the caller and refuses to run as nobody.' },
      { status: 409, cause: 'A refresh is already running for this dashboard.', action: 'Poll the refresh, or cancel it before starting another.' },
    ],
    sideEffects: [
      'Starts a pipeline run per bound source, consuming runner capacity.',
      'Each run publishes into the dashboard on completion.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go', 'doc/dashboards.md'],
    notes: 'A refresh is not a query. It re-runs the source pipelines, which is why it is asynchronous, capacity-bound, and refused when one is already in flight.',
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/refreshes',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists refresh runs.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'limit', in: 'query', type: 'integer', required: false, description: 'How many refreshes to return.', example: 'limit=20' }],
    requestSample: {
      title: 'List refreshes',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refreshes" | jq \'.[] | {id, state, sources_failed}\'',
      expectedOutput: 'Recent refreshes with how many sources completed and failed.',
    },
    responses: [{ status: 200, description: 'Refresh runs.', contentType: 'application/json', sample: '[' + REFRESH + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Reads one refresh and its per-source progress.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'refreshID', in: 'path', type: 'string', required: true, description: 'Refresh identifier.', example: 'c92a1f70-4d6b-4a02-9f18-7b3c5e9d2a41' }],
    requestSample: {
      title: 'Track a refresh',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refreshes/$REFRESH_ID" | jq',
      expectedOutput: 'State plus per-source progress, so a stuck refresh points at the source holding it up.',
    },
    responses: [{ status: 200, description: 'The refresh.', contentType: 'application/json', sample: REFRESH }],
    errors: [
      { status: 404, cause: 'No refresh with that id.', action: 'List the refreshes.' },
      { status: 500, cause: 'The refresh could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}/cancel',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Cancels a running refresh.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'refreshID', in: 'path', type: 'string', required: true, description: 'Refresh to cancel.', example: 'c92a1f70-4d6b-4a02-9f18-7b3c5e9d2a41' }],
    requestSample: {
      title: 'Cancel a refresh',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refreshes/$REFRESH_ID/cancel" | jq',
      expectedOutput: 'Remaining source runs are cancelled; sources that already published keep their entries.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{ "id": "c92a1f70-4d6b-4a02-9f18-7b3c5e9d2a41", "state": "cancelled" }' }],
    errors: [],
    notes: 'Cancelling leaves a partially refreshed dashboard: sources that finished keep their new entries.',
    sideEffects: ['Cancels the outstanding source runs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}/retry-failed',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Retries only the sources that failed in a refresh.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'refreshID', in: 'path', type: 'string', required: true, description: 'Refresh to retry.', example: 'c92a1f70-4d6b-4a02-9f18-7b3c5e9d2a41' }],
    requestSample: {
      title: 'Retry the failed sources',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refreshes/$REFRESH_ID/retry-failed" | jq',
      expectedOutput: '202. Only the failed sources run again, which is much cheaper than a full refresh.',
    },
    responses: [{ status: 202, description: 'Retry started for the failed sources.', contentType: 'application/json', sample: REFRESH }],
    errors: [
      { status: 401, cause: 'The caller identity could not be resolved.', action: 'A retry runs pipelines as the caller.' },
    ],
    sideEffects: ['Starts a run for each previously failed source.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'Reach for this rather than a fresh refresh after a transient failure: successful sources are not re-run.',
  },
  {
    method: 'GET',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Lists scheduled refreshes.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'List refresh schedules',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules" | jq',
      expectedOutput: 'Each schedule with its cron expression, timezone, and whether it is strict.',
    },
    responses: [{ status: 200, description: 'Refresh schedules.', contentType: 'application/json', sample: '[' + SCHEDULE + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Creates a scheduled refresh.',
    depth: 'full',
    parameters: [DASH_ID],
    requestSample: {
      title: 'Refresh every morning',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"cron_expression":"0 6 * * *","timezone":"Europe/Berlin","strict":true}\' | jq -r .id',
      expectedOutput: 'The schedule id. Each firing starts the same work a manual refresh does.',
      placeholders: ['`timezone` is an IANA name; without one a cron expression drifts twice a year.'],
    },
    responses: [{ status: 201, description: 'Schedule created.', contentType: 'application/json', sample: SCHEDULE }],
    errors: [
      { status: 400, cause: 'An invalid cron expression or timezone.', action: 'The message names the field.' },
      { status: 409, cause: 'An equivalent schedule already exists.', action: 'Update the existing one.' },
      { status: 500, cause: 'The schedule could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Every firing starts source pipeline runs and consumes runner capacity.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'A daily refresh of a five-source dashboard is five pipeline runs a day. Size the cadence against capacity, not against how fresh the data could theoretically be.',
  },
  {
    method: 'PUT',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Replaces a refresh schedule.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule identifier.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Change the refresh time',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"cron_expression":"0 7 * * *","timezone":"Europe/Berlin","strict":true}\' | jq',
      expectedOutput: 'The stored schedule with a recalculated next firing.',
    },
    responses: [{ status: 200, description: 'Schedule replaced.', contentType: 'application/json', sample: SCHEDULE }],
    errors: [
      { status: 400, cause: 'An invalid cron expression or timezone.', action: 'The message names the field.' },
      { status: 404, cause: 'No schedule with that id.', action: 'List the schedules.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Recalculates the next firing.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Partially updates a refresh schedule.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule identifier.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Make a scheduled refresh non-strict',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"strict":false}\' | jq \'{id, strict}\'',
      expectedOutput: 'Failing sources no longer fail the whole scheduled refresh.',
    },
    responses: [{ status: 200, description: 'Schedule updated.', contentType: 'application/json', sample: SCHEDULE }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 404, cause: 'No schedule with that id.', action: 'List the schedules.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/enable',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Enables a refresh schedule.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule to enable.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Enable a refresh schedule',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID/enable" | jq \'{id, enabled}\'',
      expectedOutput: 'Firing resumes from now; missed occurrences are not replayed.',
    },
    responses: [{ status: 200, description: 'Schedule enabled.', contentType: 'application/json', sample: SCHEDULE }],
    errors: [
      { status: 404, cause: 'No schedule with that id.', action: 'List the schedules.' },
      { status: 500, cause: 'The change failed.', action: 'Retry.' },
    ],
    sideEffects: ['Schedules the next firing from now.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/disable',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Disables a refresh schedule.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule to disable.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Pause a refresh schedule',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID/disable" | jq \'{id, enabled}\'',
      expectedOutput: 'Firing stops. A refresh already running is not cancelled.',
    },
    responses: [{ status: 200, description: 'Schedule disabled.', contentType: 'application/json', sample: SCHEDULE }],
    errors: [
      { status: 404, cause: 'No schedule with that id.', action: 'List the schedules.' },
      { status: 500, cause: 'The change failed.', action: 'Retry.' },
    ],
    sideEffects: ['Stops future firings. An in-flight refresh continues.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'The fastest way to stop a dashboard consuming capacity while its sources are being fixed.',
  },
  {
    method: 'POST',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/run',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Runs a scheduled refresh now.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule to run.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Fire a scheduled refresh immediately',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID/run" | jq',
      expectedOutput: '202, using the schedule own strictness. The next scheduled firing is unchanged.',
    },
    responses: [{ status: 202, description: 'Refresh started from the schedule.', contentType: 'application/json', sample: REFRESH }],
    errors: [
      { status: 404, cause: 'No schedule with that id.', action: 'List the schedules.' },
      { status: 500, cause: 'The refresh could not be started.', action: 'Retry.' },
    ],
    sideEffects: ['Starts the source runs. Does not move the next scheduled firing.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
    notes: 'The cheapest way to test a schedule strictness setting without waiting for 6am.',
  },
  {
    method: 'DELETE',
    path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}',
    area: 'Dashboards',
    access: 'authorized',
    purpose: 'Deletes a refresh schedule.',
    depth: 'full',
    parameters: [DASH_ID, { name: 'scheduleID', in: 'path', type: 'string', required: true, description: 'Schedule to delete.', example: 'e17b8c05-2a49-4d31-b6f0-9c1e4a7d3b52' }],
    requestSample: {
      title: 'Delete a refresh schedule',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/dashboards/$DASHBOARD_ID/refresh-schedules/$SCHEDULE_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Past refreshes and their published entries stay.',
    },
    responses: [{ status: 204, description: 'Schedule deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No schedule with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Stops future firings. Refresh history remains.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/dashboard_refresh_test.go'],
    evidence: ['services/nopsai/dashboards.go'],
  },
];
