import type { WikiApiRoute } from '../../types.js';

const INSTALL_ID = { name: 'installationID', in: 'path' as const, type: 'string', required: true, description: 'GitHub App installation id.', example: '48210077' };

const SOURCE_RECORD =
  '{\n  "id": "c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33",\n  "name": "gitlab-platform",\n  "provider": "gitlab",\n  "enabled": true,\n  "team_path": "platform",\n  "visibility": "team",\n  "auth_mode": "signature",\n  "credential_ref": "platform/gitlab-webhook-secret",\n  "repository_allowlist": ["acme/payments"],\n  "rate_limit": { "per_minute": 60 },\n  "connected_trigger_count": 2\n}';

/**
 * Git integration.
 *
 * Two ingress routes accept provider deliveries, a managed source owns the
 * signing secret and repository allowlist for non-GitHub providers, and trigger
 * overrides pin which pipeline a repository runs. The ingress routes are the
 * only part of the platform that must be reachable from the internet.
 */
export const git_integrationRoutes: WikiApiRoute[] = [
  {
    method: 'POST',
    path: '/v1/git/webhooks/{sourceID}',
    area: 'Git integration',
    access: 'public',
    purpose: 'Receives a provider delivery for one managed webhook source.',
    depth: 'full',
    parameters: [
      { name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'The source the provider was configured against.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' },
      { name: 'X-Hub-Signature-256', in: 'header', type: 'string', required: false, description: 'Provider signature. The header name depends on the provider; every delivery is verified against the source secret before it is accepted.' },
    ],
    requestSample: {
      title: 'Replay a delivery by hand',
      language: 'bash',
      code:
        'BODY=$(cat push-event.json)\nSIG=$(printf \'%s\' "$BODY" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | sed \'s/^.* //\')\ncurl -sX POST "$NOPSAI_URL/v1/git/webhooks/$SOURCE_ID" \\\n  -H "Content-Type: application/json" \\\n  -H "X-Hub-Signature-256: sha256=$SIG" \\\n  --data "$BODY" -w "\\n%{http_code}\\n"',
      expectedOutput: '202 when the delivery is accepted and normalised into an event.',
      placeholders: ['`push-event.json` is a provider payload; `$WEBHOOK_SECRET` is the source signing secret.'],
    },
    responses: [
      { status: 202, description: 'Delivery accepted and normalised. Matching triggers start runs asynchronously.', contentType: 'application/json', sample: '{"status":"accepted"}' },
      { status: 200, description: 'Accepted but produced no run, which is normal for an event no trigger matches.', contentType: 'application/json', sample: '{"status":"ignored"}' },
    ],
    errors: [
      { status: 400, cause: 'The payload is not parseable as a provider event.', action: 'Check the provider content type; form-encoded deliveries must be configured as JSON.' },
      { status: 401, cause: 'The signature is missing or does not match the source secret.', action: 'Re-copy the secret into the provider. This is the common cause of "the webhook shows a red delivery".' },
      { status: 403, cause: 'The repository is not in the source allowlist.', action: 'Add the `owner/repository` pattern to the source.' },
      { status: 404, cause: 'No source with that id, or the source is disabled.', action: 'Check `enabled` on the source.' },
      { status: 413, cause: 'The payload exceeds the platform body limit.', action: 'Nothing to do at the provider; very large events are rejected by design.' },
      { status: 422, cause: 'The event is understood but carries nothing runnable.', action: 'Usually a provider ping or an event type the platform does not map.' },
      { status: 429, cause: 'The source rate limit was exceeded.', action: 'Providers retry; a sustained 429 means the limit is too low for the repository traffic.' },
      { status: 503, cause: 'Authorization is unavailable, so the delivery cannot be evaluated.', action: 'Deliveries fail closed rather than starting unauthorized runs.' },
    ],
    sideEffects: [
      'Records a delivery, accepted or rejected, with its verification result.',
      'Normalises the payload into the shared event model, so trigger manifests stay provider-neutral.',
      'Starts runs for every matching trigger.',
    ],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_model.go', 'doc/git-webhook-sources.md'],
    notes: 'Public by necessity — the provider calls it — but never unauthenticated in effect: every delivery is signature-verified against the source secret.',
  },
  {
    method: 'POST',
    path: '/v1/git/events',
    area: 'Git integration',
    access: 'authenticated',
    purpose: 'Receives a normalised Git event, used by git-bot for GitHub App deliveries.',
    depth: 'full',
    parameters: [
      { name: 'X-Nopsai-Signature', in: 'header', type: 'string', required: false, description: 'Signature over the event body, verified before the event is accepted.' },
    ],
    requestSample: {
      title: 'What git-bot forwards',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/git/events" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @doc/sample-git-event.json -w "\\n%{http_code}\\n"',
      expectedOutput: '202 when the event is accepted. The repository ships a sample event at `doc/sample-git-event.json`.',
      placeholders: ['In normal operation git-bot calls this route; calling it by hand is a testing aid.'],
    },
    responses: [
      { status: 202, description: 'Event accepted and dispatched to matching triggers.', contentType: 'application/json', sample: '{"status":"accepted"}' },
      { status: 201, description: 'Event accepted and a run was created directly from it.', contentType: 'application/json', sample: '{"run_id":"9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11"}' },
      { status: 200, description: 'Accepted with nothing to run.', contentType: 'application/json', sample: '{"status":"ignored"}' },
    ],
    errors: [
      { status: 400, cause: 'The event body is malformed or missing required repository context.', action: 'Compare against `doc/sample-git-event.json`.' },
      { status: 401, cause: 'No bearer token. Unlike the webhook ingress, this route is not public.', action: 'Send a token; git-bot uses its service token.' },
      { status: 403, cause: 'The event is not permitted to start the pipeline it matched.', action: 'Check the trigger owner and the scope it runs in.' },
      { status: 500, cause: 'The event could not be recorded.', action: 'Retry; providers redeliver.' },
    ],
    sideEffects: ['Creates a trigger event record.', 'Starts runs for matching triggers.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/routes.go', 'doc/triggering.md'],
    notes: 'git-bot is the intended caller and uses a service token, but the gate is authentication rather than a service token specifically: any authenticated caller may post an event. The public, signature-verified ingress is `/v1/git/webhooks/{sourceID}`.',
  },
  {
    method: 'GET',
    path: '/v1/git-webhook-sources',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists managed Git webhook sources.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List webhook sources',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-webhook-sources" | jq \'.[] | {id, provider, enabled, connected_trigger_count}\'',
      expectedOutput: 'One entry per source, with how many triggers currently depend on it.',
    },
    responses: [{ status: 200, description: 'Sources visible to the caller.', contentType: 'application/json', sample: '[' + SOURCE_RECORD + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_model.go'],
    notes: '`connected_trigger_count` is what makes a source safe to delete or not: zero means nothing depends on it.',
  },
  {
    method: 'POST',
    path: '/v1/git-webhook-sources',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Creates a managed webhook source.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a GitLab source',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/git-webhook-sources" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"gitlab-platform","provider":"gitlab","team_path":"platform","auth_mode":"signature","credential_ref":"platform/gitlab-webhook-secret","repository_allowlist":["acme/payments"]}\' | jq -r .id',
      expectedOutput: 'The source id, which becomes part of the delivery URL the provider is configured with.',
      placeholders: ['`credential_ref` names a stored credential holding the signing secret.'],
    },
    responses: [{ status: 201, description: 'Source created.', contentType: 'application/json', sample: SOURCE_RECORD }],
    errors: [
      { status: 400, cause: 'An unknown provider, a missing allowlist, or an unusable credential reference.', action: 'Every source needs at least one `owner/repository` allowlist pattern.' },
      { status: 401, cause: 'The caller identity could not be resolved for the created-by record.', action: 'Use a user or service account token.' },
      { status: 409, cause: 'A source with that name already exists.', action: 'Pick another name.' },
      { status: 500, cause: 'The source could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a public delivery endpoint at `/v1/git/webhooks/{sourceID}`.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go', 'services/nopsai/git_webhook_sources_schema_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_schema.go'],
  },
  {
    method: 'GET',
    path: '/v1/git-webhook-sources/{sourceID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Reads one webhook source.',
    depth: 'full',
    parameters: [{ name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source identifier.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' }],
    requestSample: {
      title: 'Read a source',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID" | jq',
      expectedOutput: 'The source with its allowlist, auth mode, and connected triggers. The signing secret itself is a credential reference, not a value.',
    },
    responses: [{ status: 200, description: 'The source.', contentType: 'application/json', sample: SOURCE_RECORD }],
    errors: [
      { status: 404, cause: 'No source with that id.', action: 'Confirm the id from the list route.' },
      { status: 500, cause: 'The source could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_model.go'],
  },
  {
    method: 'PUT',
    path: '/v1/git-webhook-sources/{sourceID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Replaces a webhook source definition.',
    depth: 'full',
    parameters: [{ name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source to replace.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' }],
    requestSample: {
      title: 'Replace a source',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @source.json | jq',
      expectedOutput: 'The stored source after replacement.',
      placeholders: ['A PUT replaces the whole document, including the allowlist.'],
    },
    responses: [{ status: 200, description: 'Source replaced.', contentType: 'application/json', sample: SOURCE_RECORD }],
    errors: [
      { status: 400, cause: 'The document is invalid.', action: 'The message names the field.' },
      { status: 401, cause: 'The caller identity could not be resolved.', action: 'Use a user or service account token.' },
      { status: 404, cause: 'No source with that id.', action: 'Create it instead.' },
      { status: 500, cause: 'The update could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Changes which repositories may deliver through this source.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_schema.go'],
    notes: 'Narrowing the allowlist takes effect on the next delivery. Runs already started are unaffected.',
  },
  {
    method: 'PATCH',
    path: '/v1/git-webhook-sources/{sourceID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Partially updates a webhook source.',
    depth: 'full',
    parameters: [{ name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source to update.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' }],
    requestSample: {
      title: 'Disable a source',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"enabled":false}\' | jq \'{id, enabled}\'',
      expectedOutput: 'Deliveries to this source start answering 404 while it is disabled.',
    },
    responses: [{ status: 200, description: 'Source updated.', contentType: 'application/json', sample: SOURCE_RECORD }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 404, cause: 'No source with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_schema.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/git-webhook-sources/{sourceID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Deletes a webhook source.',
    depth: 'full',
    parameters: [{ name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source to delete.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' }],
    requestSample: {
      title: 'Delete a source',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Its delivery endpoint stops existing, and triggers bound to it stop firing.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No source with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Triggers that referenced the source stop receiving events.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_model.go'],
    notes: 'Check `connected_trigger_count` first. Deleting a source with connected triggers silently stops them.',
  },
  {
    method: 'GET',
    path: '/v1/git-webhook-sources/{sourceID}/deliveries',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists recent deliveries for diagnosis.',
    depth: 'full',
    parameters: [
      { name: 'sourceID', in: 'path', type: 'uuid', required: true, description: 'Source identifier.', example: 'c81f2b40-5e37-4a94-9b1e-1d2f6a0c7e33' },
      { name: 'limit', in: 'query', type: 'integer', required: false, description: 'How many deliveries to return.', example: 'limit=50' },
    ],
    requestSample: {
      title: 'Read recent deliveries',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID/deliveries" | jq \'.[] | {received_at, event_type, result}\'',
      expectedOutput: 'Accepted and rejected deliveries alike, with the verification result.',
    },
    responses: [
      {
        status: 200,
        description: 'Recent deliveries, newest first.',
        contentType: 'application/json',
        sample: '[\n  {\n    "id": "7d21...",\n    "received_at": "2026-08-19T11:02:44Z",\n    "event_type": "push",\n    "repository": "acme/payments",\n    "result": "accepted",\n    "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11"\n  }\n]',
      },
    ],
    errors: [{ status: 500, cause: 'The delivery query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_webhook_sources_test.go'],
    evidence: ['services/nopsai/git_webhook_sources_model.go', 'doc/git-webhook-sources.md'],
    notes: 'First stop when a push produced no run: this separates "never arrived" from "arrived and was rejected".',
  },
  {
    method: 'GET',
    path: '/v1/overrides',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists repository trigger overrides.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List overrides',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/overrides" | jq',
      expectedOutput: 'Every repository whose trigger resolution is pinned rather than taken from the repository.',
    },
    responses: [
      { status: 200, description: 'Overrides visible to the caller.', contentType: 'application/json', sample: '[\n  {\n    "repo_owner": "acme",\n    "repo_name": "payments",\n    "pipeline": "platform/release-service",\n    "updated_at": "2026-08-18T14:20:00Z"\n  }\n]' },
    ],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/routes.go'],
  },
  {
    method: 'GET',
    path: '/v1/overrides/{repoOwner}/{repoName}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Reads the override for one repository.',
    depth: 'full',
    parameters: [
      { name: 'repoOwner', in: 'path', type: 'string', required: true, description: 'Repository owner.', example: 'acme' },
      { name: 'repoName', in: 'path', type: 'string', required: true, description: 'Repository name.', example: 'payments' },
    ],
    requestSample: {
      title: 'Read one override',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/overrides/acme/payments" | jq',
      expectedOutput: 'The override, or an empty document when the repository has none.',
    },
    responses: [{ status: 200, description: 'The override for that repository.', contentType: 'application/json', sample: '{\n  "repo_owner": "acme",\n  "repo_name": "payments",\n  "pipeline": "platform/release-service"\n}' }],
    errors: [],
    notes: 'A repository with no override answers 200 with an empty document rather than 404, so a client can read unconditionally.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/routes.go'],
  },
  {
    method: 'PUT',
    path: '/v1/overrides/{repoOwner}/{repoName}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Sets a trigger override for a repository.',
    depth: 'full',
    parameters: [
      { name: 'repoOwner', in: 'path', type: 'string', required: true, description: 'Repository owner.', example: 'acme' },
      { name: 'repoName', in: 'path', type: 'string', required: true, description: 'Repository name.', example: 'payments' },
    ],
    requestSample: {
      title: 'Pin a repository to a pipeline',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/overrides/acme/payments" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"pipeline":"platform/release-service"}\' | jq',
      expectedOutput: '201. Events for that repository resolve to this pipeline regardless of what the repository declares.',
    },
    responses: [{ status: 201, description: 'Override stored.', contentType: 'application/json', sample: '{\n  "repo_owner": "acme",\n  "repo_name": "payments",\n  "pipeline": "platform/release-service"\n}' }],
    errors: [
      { status: 400, cause: 'The document is invalid or names an unknown pipeline.', action: 'Validate with `POST /v1/overrides/validate` first.' },
      { status: 409, cause: 'The override conflicts with an existing one.', action: 'Read the current override before replacing it.' },
      { status: 500, cause: 'The override could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes which pipeline the repository’s events resolve to.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/routes.go', 'doc/triggering.md'],
    notes: 'An override outranks the repository’s own trigger manifest, which makes it powerful and easy to forget. List overrides when a repository runs something unexpected.',
  },
  {
    method: 'DELETE',
    path: '/v1/overrides/{repoOwner}/{repoName}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Removes a trigger override.',
    depth: 'full',
    parameters: [
      { name: 'repoOwner', in: 'path', type: 'string', required: true, description: 'Repository owner.', example: 'acme' },
      { name: 'repoName', in: 'path', type: 'string', required: true, description: 'Repository name.', example: 'payments' },
    ],
    requestSample: {
      title: 'Remove an override',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/overrides/acme/payments" -w "%{http_code}\\n"',
      expectedOutput: '204. Trigger resolution returns to what the repository declares.',
    },
    responses: [{ status: 204, description: 'Override removed.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete could not be persisted.', action: 'Retry.' }],
    sideEffects: ['Repository events resolve from the repository again.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/routes.go'],
  },
  {
    method: 'POST',
    path: '/v1/overrides/validate',
    area: 'Git integration',
    access: 'authenticated',
    purpose: 'Validates an override document without storing it.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Validate an override',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/overrides/validate" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/yaml" \\\n  --data-binary @override.yaml | jq',
      expectedOutput: 'The same `valid`, `errors`, `warnings` shape the pipeline validator returns.',
    },
    responses: [{ status: 200, description: 'Validation ran. Read `valid` rather than the status code.', contentType: 'application/json', sample: '{\n  "valid": true,\n  "errors": [],\n  "warnings": []\n}' }],
    errors: [],
    notes: 'Like every validation route, it answers 200 even when the document is rejected: the failure is in the body.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/validation_contract.go'],
  },
  {
    method: 'GET',
    path: '/v1/repositories/{repoOwner}/{repoName}/branches',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists branches for a connected repository, used when choosing a revision.',
    depth: 'full',
    parameters: [
      { name: 'repoOwner', in: 'path' as const, type: 'string', required: true, description: 'Repository owner.', example: 'acme' },
      { name: 'repoName', in: 'path' as const, type: 'string', required: true, description: 'Repository name.', example: 'payments' },
    ],
    requestSample: {
      title: 'List branches',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/branches" | jq',
      expectedOutput: 'Branches the connected installation can see, which is what a revision picker renders from.',
    },
    responses: [
      { status: 200, description: 'Branches.', contentType: 'application/json', sample: '[\n  { "name": "main", "commit_sha": "4f2a91c" }\n]' },
    ],
    errors: [
      { status: 404, cause: 'The repository is not connected, or the installation cannot see it.', action: 'Refresh the installation; repository access granted at GitHub is not pushed to NopsAI.' },
      { status: 502, cause: 'The provider could not be reached.', action: 'Verify the installation.' },
    ],
    sideEffects: ['Calls the provider.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Reads GitHub App settings.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read GitHub App settings',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github" | jq',
      expectedOutput: 'App id, slug, and whether a private key is configured. The key itself is never returned.',
    },
    responses: [
      { status: 200, description: 'GitHub App settings, or an empty document when none is registered.', contentType: 'application/json', sample: '{\n  "app_id": "1284410",\n  "slug": "nopsai-platform",\n  "has_private_key": true,\n  "webhook_configured": true\n}' },
    ],
    errors: [],
    notes: 'Reachable while first-install setup is still locked, because the wizard connects GitHub before setup completes.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go', 'doc/git-apps.md'],
  },
  {
    method: 'PUT',
    path: '/v1/git-apps/github',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Updates GitHub App settings.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Configure an existing GitHub App by hand',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/git-apps/github" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @github-app.json | jq \'{app_id, has_private_key}\'',
      expectedOutput: 'The stored settings. Use this when the App already exists; use the registration flow to create one.',
      placeholders: ['`github-app.json` carries the app id, slug, private key, and webhook secret.'],
    },
    responses: [
      { status: 200, description: 'Settings stored.', contentType: 'application/json', sample: '{\n  "app_id": "1284410",\n  "slug": "nopsai-platform",\n  "has_private_key": true\n}' },
    ],
    errors: [
      { status: 400, cause: 'A malformed private key or a missing app id.', action: 'The key is a PEM block; paste it whole, newlines included.' },
      { status: 500, cause: 'Settings could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['git-bot picks up the new credentials for subsequent deliveries.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/git-apps/github/register/start',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Begins GitHub App registration.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Start registering a GitHub App',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/git-apps/github/register/start" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @registration.json | jq',
      expectedOutput: 'A URL and manifest for the operator browser to post to GitHub. The flow is completed by the callback.',
      placeholders: ['`registration.json` names the organisation and the public URL GitHub will call back on.'],
    },
    responses: [
      { status: 200, description: 'The registration handoff for the browser.', contentType: 'application/json', sample: '{\n  "url": "https://github.com/organizations/acme/settings/apps/new",\n  "state": "9f2c...",\n  "manifest": { "name": "nopsai-platform" }\n}' },
    ],
    errors: [
      { status: 400, cause: 'A missing organisation or an unusable callback URL.', action: 'The callback must be reachable from GitHub.' },
      { status: 412, cause: 'A GitHub App is already registered.', action: 'Remove or replace the existing settings first.' },
      { status: 500, cause: 'The registration could not be started.', action: 'Retry.' },
    ],
    sideEffects: ['Creates the pending registration state the callback validates.'],
    coveringTests: ['services/nopsai/git_apps_registration_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go', 'doc/git-apps.md'],
    notes: 'A browser flow driven by the System UI. The 412 is the guard against silently replacing a working App.',
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github/register/callback',
    area: 'Git integration',
    access: 'public',
    purpose: 'Completes GitHub App registration and stores the generated credentials.',
    depth: 'full',
    parameters: [
      { name: 'code', in: 'query', type: 'string', required: true, description: 'Temporary code GitHub returns after the manifest is accepted.' },
      { name: 'state', in: 'query', type: 'string', required: true, description: 'Single-use state that must match the pending registration.' },
    ],
    requestSample: {
      title: 'What GitHub redirects the browser to',
      language: 'text',
      code: 'GET /v1/git-apps/github/register/callback?code=<code>&state=<state>',
      expectedOutput: 'A redirect back into the UI once the App id, private key, and webhook secret are stored.',
    },
    responses: [{ status: 302, description: 'Redirect back to the System UI.', sample: 'Location: https://nopsai.example.com/#/system/git-apps' }],
    errors: [
      { status: 302, cause: 'A state mismatch or an exchange failure redirects back with an error rather than rendering one.', action: 'Restart the registration; a state works once.' },
    ],
    sideEffects: ['Stores the App id, private key, and webhook secret.', 'Consumes the pending registration state.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_registration_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go', 'services/nopsai/http_middleware.go'],
    notes: 'Public because GitHub redirects the operator browser here without a bearer token; it authorizes itself with the single-use state.',
  },
  {
    method: 'POST',
    path: '/v1/git-apps/github/install/start',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Begins a GitHub App installation flow.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Start installing the App on an organisation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/install/start" | jq',
      expectedOutput: 'The GitHub install URL for the browser, plus the state the callback will validate.',
    },
    responses: [
      { status: 200, description: 'The install handoff for the browser.', contentType: 'application/json', sample: '{\n  "url": "https://github.com/apps/nopsai-platform/installations/new",\n  "state": "4b81..."\n}' },
    ],
    errors: [
      { status: 412, cause: 'No GitHub App is registered yet.', action: 'Register the App before installing it.' },
    ],
    sideEffects: ['Creates the pending install state the callback validates.'],
    coveringTests: ['services/nopsai/git_apps_registration_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github/install/callback',
    area: 'Git integration',
    access: 'public',
    purpose: 'Completes an installation and records it.',
    depth: 'full',
    parameters: [
      { name: 'installation_id', in: 'query', type: 'string', required: true, description: 'Installation id GitHub assigns.' },
      { name: 'state', in: 'query', type: 'string', required: true, description: 'Single-use state that must match the pending install.' },
    ],
    requestSample: {
      title: 'What GitHub redirects the browser to',
      language: 'text',
      code: 'GET /v1/git-apps/github/install/callback?installation_id=48210077&state=<state>',
      expectedOutput: 'A redirect back into the UI with the installation recorded.',
    },
    responses: [{ status: 302, description: 'Redirect back to the System UI.', sample: 'Location: https://nopsai.example.com/#/system/git-apps' }],
    errors: [
      { status: 302, cause: 'A state mismatch redirects back with an error.', action: 'Restart the install flow.' },
    ],
    sideEffects: ['Records the installation so git-bot can act for it.', 'Consumes the pending install state.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_registration_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go', 'services/nopsai/http_middleware.go'],
    notes: 'Public for the same reason as the registration callback: a browser redirect carries no bearer token, and the single-use state is the authorization.',
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github/installations',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists GitHub App installations.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List installations',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations" | jq',
      expectedOutput: 'Each installation with the account it belongs to and when it was last verified.',
    },
    responses: [
      { status: 200, description: 'Installations.', contentType: 'application/json', sample: '[\n  {\n    "installation_id": "48210077",\n    "account": "acme",\n    "status": "active",\n    "last_verified_at": "2026-08-19T08:02:11Z"\n  }\n]' },
    ],
    errors: [],
    notes: 'Reachable while first-install setup is still locked, because the wizard connects GitHub before setup completes.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/git-apps/github/installations',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Registers an installation manually.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Record an installation without the browser flow',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/git-apps/github/installations" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"installation_id":"48210077"}\' | jq',
      expectedOutput: 'The installation record. Verify it afterwards to confirm the App can authenticate for it.',
    },
    responses: [
      { status: 201, description: 'Installation recorded.', contentType: 'application/json', sample: '{ "installation_id": "48210077", "account": "acme", "status": "active" }' },
    ],
    errors: [
      { status: 400, cause: 'A missing or unusable installation id.', action: 'The id comes from GitHub, not from NopsAI.' },
      { status: 500, cause: 'The installation could not be recorded.', action: 'Retry.' },
    ],
    sideEffects: ['git-bot may act for the installation once it verifies.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
    notes: 'The escape hatch when the browser callback could not reach the platform. Verify immediately: a recorded installation that cannot authenticate looks healthy in a list.',
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github/installations/{installationID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Reads one installation.',
    depth: 'full',
    parameters: [INSTALL_ID],
    requestSample: {
      title: 'Read an installation',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations/$INSTALLATION_ID" | jq',
      expectedOutput: 'The installation with its account and verification state.',
    },
    responses: [
      { status: 200, description: 'The installation.', contentType: 'application/json', sample: '{ "installation_id": "48210077", "account": "acme", "status": "active" }' },
    ],
    errors: [{ status: 404, cause: 'No installation with that id.', action: 'List the installations.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/git-apps/github/installations/{installationID}',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Removes an installation.',
    depth: 'full',
    parameters: [INSTALL_ID],
    requestSample: {
      title: 'Remove an installation',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations/$INSTALLATION_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Deliveries for its repositories stop producing runs.',
    },
    responses: [{ status: 204, description: 'Installation removed.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use an id from the list.' },
      { status: 404, cause: 'No installation with that id.', action: 'It may already be removed.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['git-bot stops acting for the installation; its repository events stop producing runs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
    notes: 'Removing the record here does not uninstall the App at GitHub. Do both, or GitHub keeps delivering to an install that ignores it.',
  },
  {
    method: 'POST',
    path: '/v1/git-apps/github/installations/{installationID}/verify',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Verifies an installation can authenticate against GitHub.',
    depth: 'full',
    parameters: [INSTALL_ID],
    requestSample: {
      title: 'Verify an installation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations/$INSTALLATION_ID/verify" | jq',
      expectedOutput: 'A real token exchange with GitHub — the difference between recorded and working.',
    },
    responses: [
      { status: 200, description: 'The installation authenticated.', contentType: 'application/json', sample: '{ "installation_id": "48210077", "ok": true, "verified_at": "2026-08-19T13:40:02Z" }' },
    ],
    errors: [
      { status: 404, cause: 'No installation with that id.', action: 'List the installations.' },
      { status: 500, cause: 'Verification could not run, usually a missing or malformed private key.', action: 'Re-check the App settings.' },
    ],
    sideEffects: ['Exchanges a token with GitHub and records the verification time.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
    notes: 'Run this after rotating the App private key. A stale key fails only when a delivery arrives, which is the worst time to find out.',
  },
  {
    method: 'POST',
    path: '/v1/git-apps/github/installations/{installationID}/refresh',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Refreshes cached installation metadata.',
    depth: 'full',
    parameters: [INSTALL_ID],
    requestSample: {
      title: 'Refresh installation metadata',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations/$INSTALLATION_ID/refresh" | jq',
      expectedOutput: 'Account and repository access re-read from GitHub.',
    },
    responses: [
      { status: 200, description: 'Metadata refreshed.', contentType: 'application/json', sample: '{ "installation_id": "48210077", "account": "acme", "repository_count": 12 }' },
    ],
    errors: [
      { status: 404, cause: 'No installation with that id.', action: 'List the installations.' },
      { status: 502, cause: 'GitHub could not be reached or rejected the call.', action: 'Verify the installation first.' },
      { status: 500, cause: 'The refresh could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Calls GitHub and updates the cached account and repository list.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
    notes: 'Repository access granted at GitHub is not pushed to NopsAI. Refresh after changing which repositories the App can see.',
  },
  {
    method: 'GET',
    path: '/v1/git-apps/github/installations/{installationID}/repositories',
    area: 'Git integration',
    access: 'authorized',
    purpose: 'Lists repositories an installation can reach.',
    depth: 'full',
    parameters: [INSTALL_ID],
    requestSample: {
      title: 'List reachable repositories',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-apps/github/installations/$INSTALLATION_ID/repositories" | jq',
      expectedOutput: 'The repositories the App may act on, which bounds what triggers can run.',
    },
    responses: [
      { status: 200, description: 'Reachable repositories.', contentType: 'application/json', sample: '[\n  { "full_name": "acme/payments", "private": true }\n]' },
    ],
    errors: [
      { status: 404, cause: 'No installation with that id.', action: 'List the installations.' },
      { status: 502, cause: 'GitHub could not be reached.', action: 'Verify the installation.' },
    ],
    sideEffects: ['Calls GitHub.'],
    coveringTests: ['services/nopsai/git_apps_handlers_test.go'],
    evidence: ['services/nopsai/git_apps_handlers.go'],
    notes: 'A repository missing here is why its pushes produce nothing: the App was never granted access to it.',
  },
];
