import type { WikiApiRoute } from '../../types.js';

const DRIFT_RESPONSE =
  '{\n  "base_branch": "main",\n  "push_branch": "nopsai/config-sync",\n  "items": [\n    {\n      "path": "pipelines/platform/release-service.yaml",\n      "status": "modified",\n      "git_content": "name: release-service\\n...",\n      "desired_content": "name: release-service\\n..."\n    }\n  ],\n  "summary": { "modified": 1 },\n  "can_push": true,\n  "push_message": "Sync 1 change from NopsAI"\n}';

const SYNC_STATUS =
  '{\n  "state": "idle",\n  "last_sync_at": "2026-08-19T09:58:12Z",\n  "last_commit_sha": "4f2a91c",\n  "message": "synced 42 documents"\n}';

/**
 * GitOps and configuration sync.
 *
 * Two scopes, one shape. The global configuration repository holds system
 * settings; a team repository holds that team's pipelines, steps, schedules,
 * scopes, and triggers. Both expose the same verbs — read, sync, drift, write,
 * validate — so learning one teaches the other.
 */
export const gitops_and_config_syncRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/system/config-repo',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Reads the global configuration repository connection.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read the global repository',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo" | jq',
      expectedOutput: 'The repository, branch, base path, and credential reference. The credential value is never returned.',
    },
    responses: [
      { status: 200, description: 'The configured global repository, or an empty document when none is connected.', contentType: 'application/json', sample: '{\n  "repository": "https://git.example.com/platform/nopsai-config",\n  "branch": "main",\n  "base_path": "",\n  "credential_ref": "platform/git-config"\n}' },
    ],
    errors: [],
    notes: 'A disconnected install answers 200 with an empty document rather than 404, so a client can read unconditionally.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repositories_schema.go'],
  },
  {
    method: 'PUT',
    path: '/v1/system/config-repo',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Connects or replaces the global configuration repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Connect the global repository',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/config-repo" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"repository":"https://git.example.com/platform/nopsai-config","branch":"main","credential_ref":"platform/git-config"}\' | jq',
      expectedOutput: 'The stored connection. Nothing is imported until a sync runs.',
      placeholders: ['`credential_ref` names a stored credential with read access to the repository.'],
    },
    responses: [{ status: 200, description: 'Connection stored.', contentType: 'application/json', sample: '{\n  "repository": "https://git.example.com/platform/nopsai-config",\n  "branch": "main",\n  "credential_ref": "platform/git-config"\n}' }],
    errors: [
      { status: 400, cause: 'An unreachable repository, an unknown branch, or a credential that cannot read it.', action: 'The connection is checked before it is stored.' },
      { status: 500, cause: 'The connection could not be saved.', action: 'Retry.' },
    ],
    sideEffects: ['Stores the connection. Configuration is imported only when a sync runs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repositories_schema.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/system/config-repo',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Disconnects the global configuration repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Disconnect the global repository',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo" -w "%{http_code}\\n"',
      expectedOutput: 'Already-imported configuration stays; it simply stops being refreshed from Git.',
    },
    responses: [{ status: 204, description: 'Disconnected.', sample: '' }],
    errors: [{ status: 500, cause: 'The disconnect could not be persisted.', action: 'Retry.' }],
    sideEffects: ['Imported documents remain in the database and become database-owned.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repositories_schema.go'],
    notes: 'Disconnecting does not remove configuration. It removes the source of truth, which is a different and easily surprising thing.',
  },
  {
    method: 'POST',
    path: '/v1/system/config/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Starts a configuration sync across every connected repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Sync everything',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config/sync" | jq',
      expectedOutput: '202. The sync runs asynchronously; poll the status route for the result.',
    },
    responses: [{ status: 202, description: 'Sync started.', contentType: 'application/json', sample: '{"state":"running"}' }],
    errors: [
      { status: 409, cause: 'A sync is already running.', action: 'Poll the status route rather than starting a second one.' },
    ],
    sideEffects: [
      'Imports pipelines, steps, schedules, scopes, triggers, knowledge, dashboards, and system settings from Git.',
      'Documents removed from Git are removed from the platform.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
    notes: 'A sync is asynchronous and singular: the 409 is the platform refusing to run two at once, not an error in your request.',
  },
  {
    method: 'GET',
    path: '/v1/system/config/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Reads the current sync status.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Poll sync status',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config/sync" | jq',
      expectedOutput: 'The state, the last successful sync, and the commit it imported.',
    },
    responses: [{ status: 200, description: 'Sync status.', contentType: 'application/json', sample: SYNC_STATUS }],
    errors: [],
    notes: 'Safe to poll: it reads recorded state and does not touch Git.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config/sync/cancel',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Cancels a running sync.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Cancel a sync',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config/sync/cancel" | jq',
      expectedOutput: 'The sync stops. Documents already imported stay imported.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"state":"cancelled"}' }],
    errors: [],
    notes: 'Cancelling mid-sync leaves a partial import rather than rolling back. Run another sync to reach a consistent state.',
    sideEffects: ['Stops the run; already-imported documents remain.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/config-repo/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Reads sync status for the global repository specifically.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Poll the global repository sync',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo/sync" | jq',
      expectedOutput: 'The same status shape, narrowed to the global repository.',
    },
    responses: [{ status: 200, description: 'Global repository sync status.', contentType: 'application/json', sample: SYNC_STATUS }],
    errors: [],
    notes: 'Use this when several repositories are connected and you need to know which one failed.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config-repo/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Syncs the global repository only.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Sync the global repository',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo/sync" | jq',
      expectedOutput: '202, with team repositories untouched.',
    },
    responses: [{ status: 202, description: 'Sync started for the global repository.', contentType: 'application/json', sample: '{"state":"running"}' }],
    errors: [{ status: 409, cause: 'A sync is already running.', action: 'Poll the status route.' }],
    sideEffects: ['Imports system settings and global documents.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config-repo/sync/cancel',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Cancels the global repository sync.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Cancel the global sync',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo/sync/cancel" | jq',
      expectedOutput: 'The global sync stops.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"state":"cancelled"}' }],
    errors: [],
    notes: 'As with the platform-wide cancel, a partial import is left in place.',
    sideEffects: ['Stops the run; already-imported documents remain.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'GET',
    path: '/v1/system/config-repo/drift',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Compares Git against desired state for the global repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read global drift',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repo/drift" | jq \'{summary, can_push}\'',
      expectedOutput: 'Per-file status with both contents, plus whether the difference can be pushed back.',
    },
    responses: [{ status: 200, description: 'Drift between the repository and the platform.', contentType: 'application/json', sample: DRIFT_RESPONSE }],
    errors: [],
    notes: 'Each item carries `git_content` and `desired_content`, which is what the UI renders as a side-by-side diff before a push.',
    sideEffects: ['None. Reading drift never writes to Git.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repository_drift.go', 'services/nopsai/internal/configsync/diff.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config-repo/write',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Pushes desired state back to the global repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Push drift back to Git',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/config-repo/write" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"push_message":"Sync settings from NopsAI"}\' | jq',
      expectedOutput: 'A commit on the push branch. Read drift first: this writes to a real repository.',
    },
    responses: [{ status: 200, description: 'Changes written to the push branch.', contentType: 'application/json', sample: '{\n  "branch": "nopsai/config-sync",\n  "commit_sha": "9b31f0c",\n  "written": 1\n}' }],
    errors: [
      { status: 400, cause: 'Nothing to write, or the drift cannot be pushed.', action: 'Check `can_push` and `push_message` on the drift response.' },
      { status: 500, cause: 'The push failed at the provider.', action: 'Check the credential’s write access to the push branch.' },
    ],
    sideEffects: ['Commits to the configured push branch of a real repository.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repository_drift.go'],
    notes: 'This is the one route in the area that changes something outside the platform. Read drift first.',
  },
  {
    method: 'POST',
    path: '/v1/system/config-repo/validate',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Validates configuration documents without storing or pushing them.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Validate a set of configuration files',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/config-repo/validate" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"base_path":"","files":[{"path":"setting/system/auth.yaml","content":"local_enabled: true\\n"}]}\' | jq',
      expectedOutput: 'The `valid`, `errors`, `warnings` shape, with each issue carrying the file it came from.',
    },
    responses: [{ status: 200, description: 'Validation ran. Read `valid` rather than the status code.', contentType: 'application/json', sample: '{\n  "valid": true,\n  "errors": [],\n  "warnings": []\n}' }],
    errors: [
      { status: 400, cause: 'The payload is not valid JSON or names an unusable base path.', action: 'Send `base_path` and a `files` list.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_repositories_schema_test.go'],
    evidence: ['services/nopsai/validation_handlers.go'],
    notes: 'Validating a whole file set at once is what a CI job should call on a configuration repository pull request.',
  },
  {
    method: 'GET',
    path: '/v1/system/config-repos',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Lists every connected configuration repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List configuration repositories',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repos" | jq',
      expectedOutput: 'The global repository and every team repository, with their branches and last sync.',
    },
    responses: [
      { status: 200, description: 'All connected repositories.', contentType: 'application/json', sample: '[\n  {\n    "id": 1,\n    "scope": "global",\n    "repository": "https://git.example.com/platform/nopsai-config",\n    "branch": "main"\n  },\n  {\n    "id": 2,\n    "scope": "team",\n    "team_path": "platform",\n    "repository": "https://git.example.com/platform/team-config",\n    "branch": "main"\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repositories_schema.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config-repos/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Syncs every connected repository.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Sync all repositories',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repos/sync" | jq',
      expectedOutput: '202. Equivalent to the platform-wide sync, addressed by repository rather than by configuration.',
    },
    responses: [{ status: 202, description: 'Sync started.', contentType: 'application/json', sample: '{"state":"running"}' }],
    errors: [{ status: 409, cause: 'A sync is already running.', action: 'Poll the status route.' }],
    sideEffects: ['Imports from every connected repository.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/config-repos/sync/cancel',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Cancels the all-repository sync.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Cancel the all-repository sync',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/config-repos/sync/cancel" | jq',
      expectedOutput: 'The sync stops, leaving whatever was already imported.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"state":"cancelled"}' }],
    errors: [],
    notes: 'Partial imports are left in place; run another sync to converge.',
    sideEffects: ['Stops the run.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/config-repository',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Reads a team’s configuration repository connection.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Read a team repository',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository" | jq',
      expectedOutput: 'The team’s repository, branch, and base path, or an empty document when none is connected.',
    },
    responses: [{ status: 200, description: 'The team connection.', contentType: 'application/json', sample: '{\n  "repository": "https://git.example.com/platform/team-config",\n  "branch": "main",\n  "base_path": "",\n  "credential_ref": "platform/git-config"\n}' }],
    errors: [{ status: 405, cause: 'A method the surface does not support.', action: 'GET, PUT, and DELETE are supported here.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'A team repository owns that team’s pipelines, steps, schedules, scopes, and triggers. The global repository owns system settings.',
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/config-repository',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Connects or replaces a team’s configuration repository.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Connect a team repository',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"repository":"https://git.example.com/platform/team-config","branch":"main","credential_ref":"platform/git-config"}\' | jq',
      expectedOutput: 'The stored connection. Nothing is imported until the team sync runs.',
    },
    responses: [{ status: 200, description: 'Connection stored.', contentType: 'application/json', sample: '{\n  "repository": "https://git.example.com/platform/team-config",\n  "branch": "main"\n}' }],
    errors: [
      { status: 400, cause: 'The repository or credential cannot be used.', action: 'The connection is checked before it is stored.' },
      { status: 405, cause: 'An unsupported method.', action: 'Use GET, PUT, or DELETE.' },
    ],
    sideEffects: ['Stores the connection.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/config-repository',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Disconnects a team’s configuration repository.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Disconnect a team repository',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository" -w "%{http_code}\\n"',
      expectedOutput: 'The team’s imported documents stay and become database-owned.',
    },
    responses: [{ status: 204, description: 'Disconnected.', sample: '' }],
    errors: [{ status: 405, cause: 'An unsupported method.', action: 'Use GET, PUT, or DELETE.' }],
    sideEffects: ['Imported documents remain and stop being refreshed from Git.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/config-repository/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Syncs one team’s repository.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Sync a team repository',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/sync" | jq',
      expectedOutput: '202. Only this team’s documents are touched.',
    },
    responses: [{ status: 202, description: 'Sync started for the team.', contentType: 'application/json', sample: '{"state":"running"}' }],
    errors: [{ status: 409, cause: 'A sync is already running for this team.', action: 'Poll the team sync status.' }],
    sideEffects: ['Imports the team’s pipelines, steps, schedules, scopes, and triggers.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/config-repository/sync',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Reads a team’s sync status.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Poll a team sync',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/sync" | jq',
      expectedOutput: 'State, last sync, and the commit imported for this team.',
    },
    responses: [{ status: 200, description: 'Team sync status.', contentType: 'application/json', sample: SYNC_STATUS }],
    errors: [],
    notes: 'Safe to poll.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/config-repository/sync/cancel',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Cancels a team’s running sync.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Cancel a team sync',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/sync/cancel" | jq',
      expectedOutput: 'The team sync stops, leaving whatever was already imported.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"state":"cancelled"}' }],
    errors: [],
    notes: 'Partial imports are left in place.',
    sideEffects: ['Stops the run.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/config-repository/drift',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Compares a team’s repository against desired state.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Read team drift',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/drift" | jq \'{summary, can_push}\'',
      expectedOutput: 'The same drift shape as the global repository, scoped to this team.',
    },
    responses: [{ status: 200, description: 'Drift for the team repository.', contentType: 'application/json', sample: DRIFT_RESPONSE }],
    errors: [],
    notes: 'Drift appears whenever someone edits a GitOps-managed document through the UI or API: the database becomes the owner until it is pushed or discarded.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repository_drift.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/config-repository/write',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Pushes a team’s desired state back to Git.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Push team drift back to Git',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/write" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"push_message":"Sync platform pipelines from NopsAI"}\' | jq',
      expectedOutput: 'A commit on the team’s push branch.',
    },
    responses: [{ status: 200, description: 'Changes written.', contentType: 'application/json', sample: '{\n  "branch": "nopsai/config-sync",\n  "commit_sha": "1a7de40",\n  "written": 3\n}' }],
    errors: [
      { status: 400, cause: 'Nothing to write, or drift that cannot be pushed.', action: 'Check `can_push` on the drift response.' },
      { status: 500, cause: 'The push failed at the provider.', action: 'Check write access on the push branch.' },
    ],
    sideEffects: ['Commits to a real repository.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/config_sync_test.go'],
    evidence: ['services/nopsai/config_repository_drift.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/config-repository/validate',
    area: 'GitOps and config sync',
    access: 'authorized',
    purpose: 'Validates a team’s configuration documents without storing them.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '12' }],
    requestSample: {
      title: 'Validate team configuration files',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams/$TEAM_ID/config-repository/validate" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @files.json | jq',
      expectedOutput: 'The `valid`, `errors`, `warnings` shape, with each issue naming its file.',
      placeholders: ['`files.json` carries `base_path` and a list of `{path, content}` documents.'],
    },
    responses: [{ status: 200, description: 'Validation ran.', contentType: 'application/json', sample: '{\n  "valid": true,\n  "errors": [],\n  "warnings": []\n}' }],
    errors: [{ status: 400, cause: 'The payload could not be read.', action: 'Send `base_path` and `files`.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/config_repositories_schema_test.go'],
    evidence: ['services/nopsai/validation_handlers.go'],
  },
];
