import type { WikiApiRoute } from '../../types.js';

const USER_LIST =
  '[\n  {\n    "id": "5b0a...",\n    "sub": "admin",\n    "email": "admin@example.com",\n    "provider": "local",\n    "status": "active",\n    "roles": [{ "role": "nopsai-admin" }],\n    "external_managed": false,\n    "authentication_source": "local"\n  }\n]';

const SERVICE_ACCOUNT_LIST =
  '[\n  {\n    "id": "8e3c...",\n    "sub": "release-bot",\n    "email": "release-bot@example.com",\n    "provider": "local",\n    "status": "active",\n    "token_count": 1,\n    "roles": [{ "role": "pipeline-operator" }]\n  }\n]';

const TOKEN_RESPONSE =
  '{\n  "id": "1c77...",\n  "name": "ci",\n  "token": "nopsat_...only-returned-once",\n  "token_suffix": "1c77",\n  "created_at": "2026-08-19T11:20:00Z",\n  "expires_at": "2027-08-19T11:20:00Z"\n}';

/**
 * Identity administration.
 *
 * Users and service accounts are both subjects; roles bind them to permissions,
 * and identity providers decide who may become a subject at all. Every route
 * here is administrator-gated.
 */
export const identity_administrationRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/admin/users',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Lists user accounts.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List users',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/users" | jq \'.[] | {sub, provider, status, external_managed}\'',
      expectedOutput: 'Every account with its provider, status, and whether the identity provider owns it.',
    },
    responses: [{ status: 200, description: 'All user accounts.', contentType: 'application/json', sample: USER_LIST }],
    errors: [{ status: 500, cause: 'The user query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_user_handlers.go', 'services/nopsai/auth_models.go'],
    notes: '`external_managed: true` means the provider owns the record: password and email changes belong there, not here.',
  },
  {
    method: 'POST',
    path: '/v1/admin/users',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Creates a local user account.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a local user',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/users" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"sub":"casey","email":"casey@example.com","password":"<initial>","role":"pipeline-operator"}\' | jq',
      expectedOutput: 'The refreshed user list — this route answers with the list rather than the created record.',
      placeholders: ['`sub` is the identity. Choose it deliberately: email is metadata and can change, the subject cannot.'],
    },
    responses: [{ status: 200, description: 'The user list after the create.', contentType: 'application/json', sample: USER_LIST }],
    errors: [
      { status: 400, cause: 'A missing subject, an unusable password, or an unknown role.', action: 'The message names the field.' },
      { status: 409, cause: 'The subject or email already exists.', action: 'Subjects are unique; reuse the existing account.' },
      { status: 500, cause: 'The account or its role binding could not be saved.', action: 'The create is transactional: retry, nothing partial was stored.' },
    ],
    sideEffects: ['Creates the account and any role binding in one transaction.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_user_handlers.go'],
    notes: 'It answers with the whole user list, not the new account, so a client that expects a single object gets an array.',
  },
  {
    method: 'PUT',
    path: '/v1/admin/users/{userID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Replaces a user record.',
    depth: 'full',
    parameters: [{ name: 'userID', in: 'path', type: 'string', required: true, description: 'User identifier.', example: '5b0a...' }],
    requestSample: {
      title: 'Replace a user record',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/admin/users/$USER_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email":"casey@example.com","status":"active"}\' -w "%{http_code}\\n"',
      expectedOutput: '204. Setting `password` here resets it without knowing the current one.',
    },
    responses: [{ status: 204, description: 'User updated.', sample: '' }],
    errors: [
      { status: 400, cause: 'An unusable status or password.', action: 'The message names the field.' },
      { status: 404, cause: 'No user with that id.', action: 'Confirm the id from the list.' },
      { status: 409, cause: 'The email belongs to another account.', action: 'Resolve the duplicate first.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['An administrator password reset takes effect immediately and does not require the current password.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_user_handlers.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/admin/users/{userID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Partially updates a user record.',
    depth: 'full',
    parameters: [{ name: 'userID', in: 'path', type: 'string', required: true, description: 'User identifier.', example: '5b0a...' }],
    requestSample: {
      title: 'Disable an account',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/admin/users/$USER_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"status":"disabled"}\' -w "%{http_code}\\n"',
      expectedOutput: '204. The account stops authenticating; its tokens stop working with it.',
    },
    responses: [{ status: 204, description: 'User updated.', sample: '' }],
    errors: [
      { status: 400, cause: 'An unusable field value.', action: 'The message names the field.' },
      { status: 404, cause: 'No user with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Disabling stops the account authenticating without deleting its history.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_user_handlers.go'],
    notes: 'Disable rather than delete when someone leaves: the audit trail keeps naming a subject that still resolves.',
  },
  {
    method: 'DELETE',
    path: '/v1/admin/users/{userID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Deletes a user account.',
    depth: 'full',
    parameters: [{ name: 'userID', in: 'path', type: 'string', required: true, description: 'User to delete.', example: '5b0a...' }],
    requestSample: {
      title: 'Delete a user',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/users/$USER_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Their tokens stop working and their grants stop resolving.',
    },
    responses: [{ status: 204, description: 'User deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use an id from the list.' },
      { status: 404, cause: 'No user with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the account. Audit records naming the subject remain but no longer resolve to an account.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_user_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/admin/service-accounts',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Lists service accounts used for automation.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List service accounts',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/service-accounts" | jq \'.[] | {sub, token_count, last_used_at}\'',
      expectedOutput: 'Each account with how many tokens it holds and when one was last used.',
    },
    responses: [{ status: 200, description: 'All service accounts.', contentType: 'application/json', sample: SERVICE_ACCOUNT_LIST }],
    errors: [
      { status: 405, cause: 'A method other than GET.', action: 'Use GET.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
    notes: '`last_used_at` finds the automation nobody remembers configuring — usually the account worth revoking.',
  },
  {
    method: 'POST',
    path: '/v1/admin/service-accounts',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Creates a service account.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a service account with its first token',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/service-accounts" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"sub":"release-bot","email":"release-bot@example.com","role":"pipeline-operator","token_name":"ci","expires_in_days":365}\' | jq',
      expectedOutput: 'The account and its first token. The token value appears here and nowhere else.',
    },
    responses: [
      { status: 201, description: 'Account created with a token.', contentType: 'application/json', sample: '{\n  "service_account": ' + SERVICE_ACCOUNT_LIST.slice(3, -2) + ',\n  "token": ' + TOKEN_RESPONSE + '\n}' },
    ],
    errors: [
      { status: 400, cause: 'A missing subject or an unusable expiry.', action: 'Choose exactly one expiry form.' },
      { status: 409, cause: 'The subject already exists.', action: 'Reuse the account and issue another token instead.' },
      { status: 500, cause: 'The account could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Creates the account, its role binding, and one token in a single call.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
    notes: 'A service account is how a system gets its own identity. Using a person’s personal token instead works until that person leaves.',
  },
  {
    method: 'PUT',
    path: '/v1/admin/service-accounts/{serviceAccountID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Replaces a service account record.',
    depth: 'full',
    parameters: [{ name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account identifier.', example: '8e3c...' }],
    requestSample: {
      title: 'Replace a service account record',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email":"release-bot@example.com","status":"active"}\' -w "%{http_code}\\n"',
      expectedOutput: '204.',
    },
    responses: [{ status: 204, description: 'Service account updated.', sample: '' }],
    errors: [
      { status: 400, cause: 'An unusable status.', action: 'The message names the field.' },
      { status: 404, cause: 'No service account with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/admin/service-accounts/{serviceAccountID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Partially updates a service account.',
    depth: 'full',
    parameters: [{ name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account identifier.', example: '8e3c...' }],
    requestSample: {
      title: 'Disable a service account',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"status":"disabled"}\' -w "%{http_code}\\n"',
      expectedOutput: '204. Every token it holds stops working at once.',
    },
    responses: [{ status: 204, description: 'Service account updated.', sample: '' }],
    errors: [
      { status: 400, cause: 'An unusable status.', action: 'The message names the field.' },
      { status: 404, cause: 'No service account with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Disabling stops every token the account holds without revoking them individually.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
    notes: 'Disabling the account is the fastest kill switch for a misbehaving integration: one call instead of one per token.',
  },
  {
    method: 'DELETE',
    path: '/v1/admin/service-accounts/{serviceAccountID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Deletes a service account.',
    depth: 'full',
    parameters: [{ name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account to delete.', example: '8e3c...' }],
    requestSample: {
      title: 'Delete a service account',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID" -w "%{http_code}\\n"',
      expectedOutput: '204, with its tokens.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No service account with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the account and every token issued to it.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
  },
  {
    method: 'GET',
    path: '/v1/admin/service-accounts/{serviceAccountID}/tokens',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Lists tokens issued to a service account.',
    depth: 'full',
    parameters: [{ name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account identifier.', example: '8e3c...' }],
    requestSample: {
      title: 'List an account’s tokens',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID/tokens" | jq',
      expectedOutput: 'Metadata only: id, name, suffix, expiry, and last use. Values are never listed.',
    },
    responses: [
      { status: 200, description: 'Token metadata.', contentType: 'application/json', sample: '[\n  {\n    "id": "1c77...",\n    "name": "ci",\n    "token_suffix": "1c77",\n    "created_at": "2026-08-19T11:20:00Z",\n    "last_used_at": "2026-08-19T12:44:10Z"\n  }\n]' },
    ],
    errors: [
      { status: 404, cause: 'No service account with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
  },
  {
    method: 'POST',
    path: '/v1/admin/service-accounts/{serviceAccountID}/tokens',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Issues a service account token. The value is returned once.',
    depth: 'full',
    parameters: [{ name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account identifier.', example: '8e3c...' }],
    requestSample: {
      title: 'Issue another token',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID/tokens" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"ci-secondary","expires_in_days":90}\' | jq -r .token',
      expectedOutput: 'The token value, returned once. Issue a second token before revoking the first to rotate without downtime.',
    },
    responses: [{ status: 201, description: 'Token issued.', contentType: 'application/json', sample: TOKEN_RESPONSE }],
    errors: [
      { status: 400, cause: 'A missing name or conflicting expiry fields.', action: 'Choose exactly one expiry form.' },
      { status: 404, cause: 'No service account with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The token could not be stored.', action: 'Retry; no token was issued.' },
    ],
    sideEffects: ['Creates a credential carrying the account’s permissions.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/auth_models.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/admin/service-accounts/{serviceAccountID}/tokens/{tokenID}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Revokes a service account token.',
    depth: 'full',
    parameters: [
      { name: 'serviceAccountID', in: 'path', type: 'string', required: true, description: 'Service account identifier.', example: '8e3c...' },
      { name: 'tokenID', in: 'path', type: 'string', required: true, description: 'Token id from the token list — not the token value.', example: '1c77...' },
    ],
    requestSample: {
      title: 'Revoke one token',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID/tokens/$TOKEN_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. That token stops working immediately; the account and its other tokens are unaffected.',
    },
    responses: [{ status: 204, description: 'Token revoked.', sample: '' }],
    errors: [
      { status: 404, cause: 'No such token for that account.', action: 'Confirm both ids.' },
      { status: 500, cause: 'The revocation failed.', action: 'Retry; the token stays valid until it succeeds.' },
    ],
    sideEffects: ['Invalidates the token immediately.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/personal_tokens_test.go'],
    evidence: ['services/nopsai/personal_tokens.go'],
  },
  {
    method: 'GET',
    path: '/v1/admin/roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Lists product roles.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List roles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/roles" | jq',
      expectedOutput: 'Every role and the object/action pairs it permits.',
    },
    responses: [
      { status: 200, description: 'Product roles.', contentType: 'application/json', sample: '[\n  {\n    "role": "pipeline-operator",\n    "name": "Pipeline operator",\n    "obj": "pipeline",\n    "act": "run",\n    "effect": "allow"\n  }\n]' },
    ],
    errors: [
      { status: 405, cause: 'A method other than GET.', action: 'Use GET.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/admin/roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Creates a product role.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a role',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"role":"pipeline-operator","name":"Pipeline operator","obj":"pipeline","act":"run","effect":"allow"}\' | jq',
      expectedOutput: 'The role, now available to bind to users and service accounts.',
    },
    responses: [{ status: 201, description: 'Role created.', contentType: 'application/json', sample: '{\n  "role": "pipeline-operator",\n  "name": "Pipeline operator",\n  "obj": "pipeline",\n  "act": "run",\n  "effect": "allow"\n}' }],
    errors: [
      { status: 400, cause: 'A missing role name, object, action, or effect.', action: 'All four are required.' },
      { status: 500, cause: 'The role could not be saved.', action: 'Retry.' },
    ],
    sideEffects: ['Adds a role subjects can be bound to.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
    notes: 'A role permits an action on a kind of object. Which concrete resources it reaches is decided by grants, not by the role.',
  },
  {
    method: 'DELETE',
    path: '/v1/admin/roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Deletes a product role.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Delete a role',
      language: 'bash',
      code:
        'curl -sX DELETE "$NOPSAI_URL/v1/admin/roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"role":"pipeline-operator"}\' -w "%{http_code}\\n"',
      expectedOutput: '204. The role is named in the body, not the path.',
    },
    responses: [{ status: 204, description: 'Role deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The body names no role.', action: 'Send `{"role": "..."}`.' },
      { status: 404, cause: 'No such role.', action: 'Confirm the name from the list.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Subjects bound to the role lose what it permitted.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
    notes: 'Deleting a role silently narrows everyone bound to it. Check bindings before removing one.',
  },
  {
    method: 'POST',
    path: '/v1/admin/user-roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Grants a role to a user.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Bind a role to a user',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/user-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"user_id":"5b0a...","role":"pipeline-operator"}\' | jq',
      expectedOutput: 'The binding. It takes effect on the user’s next request.',
    },
    responses: [{ status: 201, description: 'Role bound to the user.', contentType: 'application/json', sample: '{\n  "user_id": "5b0a...",\n  "role": "pipeline-operator"\n}' }],
    errors: [
      { status: 400, cause: 'A missing user or role.', action: 'Both fields are required.' },
      { status: 404, cause: 'The user or role does not exist.', action: 'Confirm both.' },
      { status: 500, cause: 'The binding failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what the user may do.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/admin/user-roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Removes a role from a user.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Unbind a role',
      language: 'bash',
      code:
        'curl -sX DELETE "$NOPSAI_URL/v1/admin/user-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"user_id":"5b0a...","role":"pipeline-operator"}\' -w "%{http_code}\\n"',
      expectedOutput: '204.',
    },
    responses: [{ status: 204, description: 'Binding removed.', sample: '' }],
    errors: [
      { status: 400, cause: 'A missing user or role.', action: 'Both fields are required.' },
      { status: 404, cause: 'No such binding.', action: 'It may already be removed.' },
      { status: 500, cause: 'The removal failed.', action: 'Retry.' },
    ],
    sideEffects: ['Narrows what the user may do immediately.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/admin/service-account-roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Grants a role to a service account.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Bind a role to a service account',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/admin/service-account-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"service_account_id":"8e3c...","role":"pipeline-operator"}\' | jq',
      expectedOutput: 'The binding. Existing tokens pick it up without being reissued.',
    },
    responses: [{ status: 201, description: 'Role bound.', contentType: 'application/json', sample: '{\n  "service_account_id": "8e3c...",\n  "role": "pipeline-operator"\n}' }],
    errors: [
      { status: 400, cause: 'A missing account or role.', action: 'Both fields are required.' },
      { status: 404, cause: 'The account or role does not exist.', action: 'Confirm both.' },
      { status: 500, cause: 'The binding failed.', action: 'Retry.' },
    ],
    sideEffects: ['Existing tokens gain the permission without reissue.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
    notes: 'A token carries the account’s permissions at request time, not at issue time — which is why rebinding roles does not require rotating tokens.',
  },
  {
    method: 'DELETE',
    path: '/v1/admin/service-account-roles',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Removes a role from a service account.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Unbind a service account role',
      language: 'bash',
      code:
        'curl -sX DELETE "$NOPSAI_URL/v1/admin/service-account-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"service_account_id":"8e3c...","role":"pipeline-operator"}\' -w "%{http_code}\\n"',
      expectedOutput: '204. Every token for the account loses the permission at once.',
    },
    responses: [{ status: 204, description: 'Binding removed.', sample: '' }],
    errors: [
      { status: 400, cause: 'A missing account or role.', action: 'Both fields are required.' },
      { status: 404, cause: 'No such binding.', action: 'It may already be removed.' },
      { status: 500, cause: 'The removal failed.', action: 'Retry.' },
    ],
    sideEffects: ['Narrows every token the account holds.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/admin_roles_compat_test.go'],
    evidence: ['services/nopsai/admin_role_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/admin/identity-providers',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Lists configured identity providers.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List providers with their configuration',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/identity-providers" | jq',
      expectedOutput: 'The administrative view, including whether each provider holds a client credential. The credential itself is never returned.',
    },
    responses: [
      { status: 200, description: 'Providers with their settings.', contentType: 'application/json', sample: '{\n  "local_enabled": true,\n  "oidc_enabled": true,\n  "providers": [\n    {\n      "id": "keycloak",\n      "type": "oidc",\n      "display_name": "Corporate SSO",\n      "has_client_credential": true\n    }\n  ]\n}' },
    ],
    errors: [{ status: 405, cause: 'A method other than GET or PUT.', action: 'Use GET to read, PUT to replace.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/auth_oidc_store_test.go'],
    evidence: ['services/nopsai/auth_oidc_models.go'],
    notes: '`has_client_credential` is how you check a provider is configured without the API ever returning the secret.',
  },
  {
    method: 'PUT',
    path: '/v1/admin/identity-providers',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Replaces the whole identity provider configuration.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Replace provider configuration',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/admin/identity-providers" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @providers.json | jq',
      expectedOutput: 'The stored configuration.',
      placeholders: ['`providers.json` carries `local_enabled`, `oidc_enabled`, and the provider list.'],
    },
    responses: [{ status: 200, description: 'Configuration replaced.', contentType: 'application/json' , sample: '{\n  "local_enabled": true,\n  "oidc_enabled": true,\n  "providers": []\n}' }],
    errors: [
      { status: 400, cause: 'Turning local login off while no identity provider remains enabled.', action: 'The platform refuses a configuration that would lock everyone out.' },
      { status: 405, cause: 'An unsupported method.', action: 'Use GET or PUT.' },
    ],
    sideEffects: ['Changes how everyone signs in.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_oidc_store_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: '`local_enabled: false` is accepted only when external auth is enabled and at least one provider remains enabled.',
  },
  {
    method: 'PUT',
    path: '/v1/admin/identity-providers/{provider}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Creates or replaces one identity provider.',
    depth: 'full',
    parameters: [{ name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider id.', example: 'keycloak' }],
    requestSample: {
      title: 'Configure one provider',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/admin/identity-providers/keycloak" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @keycloak.json | jq',
      expectedOutput: 'The stored provider. Identity is provider id, issuer, and subject — changing the issuer changes who existing users are.',
      placeholders: ['`keycloak.json` carries the issuer, client id, credential reference, scopes, and mapping.'],
    },
    responses: [{ status: 200, description: 'Provider stored.', contentType: 'application/json', sample: '{\n  "id": "keycloak",\n  "type": "oidc",\n  "display_name": "Corporate SSO",\n  "has_client_credential": true\n}' }],
    errors: [
      { status: 400, cause: 'An unreachable issuer, a missing client credential, or an invalid mapping.', action: 'The message names the field.' },
      { status: 405, cause: 'An unsupported method.', action: 'Use PUT or DELETE.' },
    ],
    sideEffects: ['Changes how users of this provider authenticate.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_oidc_store_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
    notes: 'Changing the issuer of a live provider re-identifies its users: the subject is scoped by issuer, so existing accounts stop matching.',
  },
  {
    method: 'DELETE',
    path: '/v1/admin/identity-providers/{provider}',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Removes an identity provider.',
    depth: 'full',
    parameters: [{ name: 'provider', in: 'path', type: 'string', required: true, description: 'Provider to remove.', example: 'keycloak' }],
    requestSample: {
      title: 'Remove a provider',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/admin/identity-providers/keycloak" -w "%{http_code}\\n"',
      expectedOutput: 'Users of that provider can no longer sign in. Their accounts remain.',
    },
    responses: [{ status: 204, description: 'Provider removed.', sample: '' }],
    errors: [
      { status: 400, cause: 'Removing the last enabled provider while local login is off.', action: 'Enable local login first, or the install locks itself out.' },
      { status: 405, cause: 'An unsupported method.', action: 'Use PUT or DELETE.' },
    ],
    sideEffects: ['Users of the provider lose their sign-in path; their accounts and grants remain.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/auth_oidc_store_test.go'],
    evidence: ['services/nopsai/auth_oidc_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/audit',
    area: 'Identity administration',
    access: 'admin',
    purpose: 'Reads the audit log.',
    depth: 'full',
    parameters: [
      { name: 'limit', in: 'query', type: 'integer', required: false, description: 'How many records to return.', example: 'limit=200' },
    ],
    requestSample: {
      title: 'Read recent audit records',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/audit?limit=50" | jq',
      expectedOutput: 'Recent decisions and mutations, each naming the actor, the action, and the resource.',
    },
    responses: [
      { status: 200, description: 'Audit records, newest first.', contentType: 'application/json', sample: '[\n  {\n    "actor_type": "user",\n    "actor_id": "admin",\n    "action": "secret.read_value",\n    "resource_type": "secret",\n    "resource_id": "platform/production:REGISTRY_TOKEN",\n    "decision": "allow",\n    "created_at": "2026-08-19T12:31:02Z"\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The audit query failed.', action: 'Platform fault.' }],
    sideEffects: ['None. Reading the audit log is itself audited by the request chain.'],
    coveringTests: ['services/nopsai/auth_middleware_test.go'],
    evidence: ['services/nopsai/routes.go', 'services/nopsai/pkg/audit'],
    notes: 'This is where a secret read shows up. If you want to know who recovered a credential, this is the record that says so.',
  },
];
