import type { WikiApiRoute } from '../../types.js';

/**
 * Internal service routes.
 *
 * Component-to-component traffic: the agent reporting on a run, git-bot fetching
 * its configuration, services pulling runtime config, and the dispatcher asking
 * about routing. They are documented at contract depth — what calls them and why
 * they exist — with no call samples, because they are not a public surface and
 * calling them by hand is a way to corrupt run state rather than a way to
 * integrate.
 *
 * Two of them are worth knowing about even so: `logs/ingest` and `finalize` sit
 * under `/v1/runs/` rather than `/v1/internal/`, so they look public in a route
 * list while being agent-only in practice.
 */
export const internal_service_routesRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/internal/v1/runtime-config/{service}',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Runtime configuration a platform service pulls at startup.',
    depth: 'contract',
    notes: 'Called by aaa, dispatcher, git-bot, and the agent as they start. Not a public API: the shape follows whatever those services need and changes with them.',
    sideEffects: ['None. The caller reads its own configuration.'],
    evidence: ['services/nopsai/runtime_config_api.go'],
  },
  {
    method: 'GET',
    path: '/internal/v1/runtime-config/{service}/watch',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Long-lived watch that pushes runtime configuration changes to a service.',
    depth: 'contract',
    streaming: { contentType: 'text/event-stream', framing: 'Long-lived connection; the service receives a message when its configuration changes.' },
    notes: 'This is why a configuration change through `PUT /v1/system/config` takes effect without restarting services. Not a public API.',
    sideEffects: ['Holds an open connection for the lifetime of the calling service.'],
    evidence: ['services/nopsai/runtime_config_api.go'],
  },
  {
    method: 'POST',
    path: '/v1/internal/config/sync',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Internal trigger for a configuration sync.',
    depth: 'contract',
    notes: 'Used by platform components that need to force a sync. Operators should use `POST /v1/system/config/sync` instead, which is authorized and audited as an operator action.',
    sideEffects: ['Starts a configuration sync.'],
    evidence: ['services/nopsai/config_sync.go'],
  },
  {
    method: 'GET',
    path: '/v1/internal/dispatcher/routing',
    area: 'Internal service routes',
    access: 'authenticated',
    purpose: 'Routing table the dispatcher uses to match work to runner scopes.',
    depth: 'contract',
    notes: 'Read by the dispatcher. The operator-facing equivalents are `GET /v1/system/dispatcher` for the live fleet and `GET /v1/system/dispatcher/scopes` for advertised scopes.',
    sideEffects: ['None.'],
    evidence: ['services/nopsai/routes.go', 'services/nopsai/aaa_helpers.go'],
  },
  {
    method: 'GET',
    path: '/v1/internal/git-bot/bootstrap',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Bootstrap configuration git-bot needs to start handling provider webhooks.',
    depth: 'contract',
    notes: 'Called by git-bot only. It carries GitHub App material, which is why it is service-gated rather than authorized.',
    sideEffects: ['None.'],
    evidence: ['services/nopsai/routes.go', 'doc/git-apps.md'],
  },
  {
    method: 'GET',
    path: '/v1/internal/git-bot/installations',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'GitHub App installations git-bot may act for.',
    depth: 'contract',
    notes: 'Called by git-bot when routing a delivery to the right installation. The operator-facing list is `GET /v1/git-apps/github/installations`.',
    sideEffects: ['None.'],
    evidence: ['services/nopsai/routes.go', 'doc/git-apps.md'],
  },
  {
    method: 'POST',
    path: '/v1/internal/runs/{runID}/ai-usage',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Records the token usage of one LLM call against a run.',
    depth: 'contract',
    notes: 'Reported by the per-run agent as it works. This is where the numbers in `GET /v1/monitoring/ai-usage` come from.',
    sideEffects: ['Appends an AI usage record to the run.'],
    evidence: ['services/nopsai/ai_usage_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/internal/runs/{runID}/approvals/pause',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Pauses a run at an approval checkpoint and releases its runner capacity.',
    depth: 'contract',
    notes: 'Called by the agent when it reaches an approval step. This is the mechanism that makes a checkpoint durable: the run becomes a record rather than a held process.',
    sideEffects: ['Creates the pending approval and releases the runner slot the run held.'],
    evidence: ['services/nopsai/approval_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/internal/runs/{runID}/checkpoints/{checkpointID}',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Reads the checkpoint state an agent needs to resume after an approval.',
    depth: 'contract',
    notes: 'Called by the agent when a paused run is picked up again, possibly by a different runner than the one that paused it.',
    sideEffects: ['None.'],
    evidence: ['services/nopsai/approval_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/internal/runs/{runID}/policy-revision',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'The governance and knowledge policy revision pinned to a run.',
    depth: 'contract',
    notes: 'Called by the agent so a long run keeps evaluating against the policy it started with rather than one edited mid-flight.',
    sideEffects: ['None.'],
    evidence: ['services/nopsai/routes.go'],
  },
  {
    method: 'POST',
    path: '/v1/internal/runs/{runID}/steps/{stepName}/tasks/{taskName}/outputs',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Records the runtime outputs a task produced.',
    depth: 'contract',
    notes: 'Called by the agent after a task writes files under `/nopsai/outputs`. This is what makes `$steps.<step>.<task>.outputs.<NAME>` resolvable downstream.',
    sideEffects: ['Stores the output values, masking any declared sensitive.'],
    evidence: ['services/agent/internal/app/runtime_outputs.go'],
  },
  {
    method: 'POST',
    path: '/v1/internal/runs/{runID}/task-outputs/resolve',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Resolves outputs published by a synchronous child pipeline run.',
    depth: 'contract',
    notes: 'Called by a parent run’s agent to read a child run’s outputs. It is the mechanism behind `sync: true` on a `pipeline:` include.',
    sideEffects: ['None.'],
    evidence: ['services/agent/nopsai_client.go'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/logs/ingest',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Streams run log lines from the agent into durable storage.',
    depth: 'contract',
    notes: 'Agent-only despite sitting under `/v1/runs/` rather than `/v1/internal/`. Read logs with `GET /v1/runs/{runID}/logs`; writing them by hand corrupts a run’s record.',
    sideEffects: ['Appends log lines to the run, applying secret redaction on the way in.'],
    evidence: ['services/nopsai/run_internal_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/steps/{stepName}/tasks/{taskName}',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Reports a task’s status transition.',
    depth: 'contract',
    notes: 'Agent-only, and the source of the per-step and per-task state shown in run detail. It sits under the public run path but is not part of the public surface.',
    sideEffects: ['Advances the run graph and may complete or fail the run.'],
    evidence: ['services/nopsai/run_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/finalize',
    area: 'Internal service routes',
    access: 'service',
    purpose: 'Closes a run and starts final output generation.',
    depth: 'contract',
    notes: 'Agent-only. It is what moves a run to its terminal status and queues the deliverables; calling it by hand ends a run that has not finished.',
    sideEffects: ['Sets the terminal run status and queues final output generation.'],
    evidence: ['services/nopsai/run_handlers.go'],
  },
];
