import type { WikiApiRoute } from '../../types.js';

const KNOWLEDGE_DOC =
  '{\n  "id": "platform/release-notes",\n  "kind": "policy",\n  "title": "Release notes policy",\n  "team": "platform",\n  "source": "config_repo",\n  "updated_at": "2026-08-18T15:41:02Z"\n}';

const CONNECTION =
  '{\n  "id": "platform/confluence",\n  "team": "platform",\n  "name": "confluence",\n  "display_name": "Confluence",\n  "provider": "confluence",\n  "base_url": "https://wiki.example.com",\n  "credential_ref": "platform/confluence",\n  "disabled": false\n}';

/**
 * Knowledge Context.
 *
 * Two halves. Knowledge documents are the governed text merged into an LLM
 * task's context; connections are the provider links that import documents from
 * an external wiki. `guardrail` and `policy` documents also validate direct
 * scripts before execution, which makes them enforcement rather than reference.
 */
export const knowledge_contextRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/knowledge-contexts',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Lists knowledge documents the caller can see.',
    depth: 'full',
    parameters: [
      { name: 'team_path', in: 'query', type: 'string', required: false, description: 'Restrict to documents owned by one team path.', example: 'team_path=platform' },
      { name: 'kind', in: 'query', type: 'string', required: false, allowedValues: ['architecture', 'guardrail', 'policy', 'adr', 'guideline', 'runbook', 'reference', 'example'], description: 'Restrict to one document kind.', example: 'kind=guardrail' },
    ],
    requestSample: {
      title: 'List knowledge documents',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-contexts?kind=guardrail" | jq \'.[] | {id, kind, team}\'',
      expectedOutput: 'Documents the caller may see, filtered per caller by AAA.',
    },
    responses: [{ status: 200, description: 'Knowledge documents.', contentType: 'application/json', sample: '[' + KNOWLEDGE_DOC + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable, so the list cannot be filtered.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_context.go', 'doc/knowledge-context.md'],
    notes: 'Kind is not a label. `guardrail` and `policy` documents participate in script validation; the other kinds only inform the prompt.',
  },
  {
    method: 'GET',
    path: '/v1/knowledge-contexts/{knowledgeID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Reads one knowledge document.',
    depth: 'full',
    parameters: [
      { name: 'knowledgeID', in: 'path', type: 'string', required: true, description: 'Document identifier. A catch-all segment, so a team-prefixed id with slashes is passed as-is.', example: 'platform/release-notes' },
    ],
    requestSample: {
      title: 'Read a knowledge document',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-contexts/platform/release-notes" | jq',
      expectedOutput: 'The document with its kind, content, and provenance.',
    },
    responses: [{ status: 200, description: 'The document.', contentType: 'application/json', sample: KNOWLEDGE_DOC }],
    errors: [
      { status: 400, cause: 'The identifier is empty or malformed.', action: 'Use an id from the list route.' },
      { status: 404, cause: 'No document with that id.', action: 'Check the team prefix.' },
      { status: 409, cause: 'The document is mid-import from a provider connection.', action: 'Wait for the import to finish and read again.' },
      { status: 500, cause: 'The document could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_context.go'],
  },
  {
    method: 'PUT',
    path: '/v1/knowledge-contexts/{knowledgeID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Creates or replaces a knowledge document.',
    depth: 'full',
    parameters: [
      { name: 'knowledgeID', in: 'path', type: 'string', required: true, description: 'Document identifier to store under.', example: 'platform/release-notes' },
    ],
    requestSample: {
      title: 'Store a policy document',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/knowledge-contexts/platform/release-notes" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @knowledge.json | jq',
      expectedOutput: 'The stored document, available to the next run that references it.',
      placeholders: ['`knowledge.json` carries the kind, title, and content.'],
    },
    responses: [{ status: 200, description: 'Document stored.', contentType: 'application/json', sample: KNOWLEDGE_DOC }],
    errors: [
      { status: 400, cause: 'An unknown kind or missing content.', action: 'Kind must be one of the eight documented values.' },
      { status: 404, cause: 'The owning team does not exist.', action: 'Check the team prefix in the identifier.' },
      { status: 409, cause: 'The document is managed by a provider connection.', action: 'Edit it at the provider, or detach the connection first.' },
      { status: 500, cause: 'The document could not be stored.', action: 'Retry.' },
    ],
    sideEffects: [
      'A `guardrail` or `policy` document changes what scripts are allowed to run for pipelines that reference it.',
      'Editing a GitOps-managed document creates drift until it is pushed or discarded.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_context.go', 'doc/knowledge-context.md'],
    notes: 'Storing a blocking guardrail is an enforcement change, not a documentation change: scripts under it are validated before they execute.',
  },
  {
    method: 'POST',
    path: '/v1/knowledge-contexts/{knowledgeID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Runs an action against one knowledge document, such as refreshing it from its provider.',
    depth: 'full',
    parameters: [
      { name: 'knowledgeID', in: 'path', type: 'string', required: true, description: 'Document identifier.', example: 'platform/release-notes' },
    ],
    requestSample: {
      title: 'Refresh a document from its provider',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/knowledge-contexts/platform/release-notes" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @action.json | jq',
      expectedOutput: 'The document after the action. Which actions apply depends on whether it is connection-backed.',
      placeholders: ['`action.json` names the action, for example a refresh from the connected provider.'],
    },
    responses: [{ status: 200, description: 'The document after the action.', contentType: 'application/json', sample: KNOWLEDGE_DOC }],
    errors: [
      { status: 400, cause: 'An unknown action, or one that does not apply to this document.', action: 'A locally authored document cannot be refreshed from a provider.' },
      { status: 404, cause: 'No document with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The action failed.', action: 'Retry; a provider refresh makes a real call.' },
    ],
    sideEffects: ['A refresh replaces the stored content from the provider and records the import.'],
    coveringTests: ['services/nopsai/knowledge_context_external_sync_test.go'],
    evidence: ['services/nopsai/knowledge_context.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/knowledge-contexts/{knowledgeID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Deletes a knowledge document.',
    depth: 'full',
    parameters: [
      { name: 'knowledgeID', in: 'path', type: 'string', required: true, description: 'Document to delete.', example: 'platform/release-notes' },
    ],
    requestSample: {
      title: 'Delete a knowledge document',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-contexts/platform/release-notes" -w "%{http_code}\\n"',
      expectedOutput: '204, unless it is required by a pipeline that references it.',
    },
    responses: [{ status: 204, description: 'Document deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The identifier is empty.', action: 'Name the document.' },
      { status: 404, cause: 'No document with that id.', action: 'It may already be deleted.' },
      { status: 409, cause: 'The document is provider-managed or still required.', action: 'Detach the connection, or remove the `required: true` reference from the pipelines that need it.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: [
      'A pipeline that references the document with `required: true` fails until the reference is removed.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_context.go'],
  },
  {
    method: 'GET',
    path: '/v1/knowledge-context-connections',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Lists provider connections.',
    depth: 'full',
    parameters: [
      { name: 'team_path', in: 'query', type: 'string', required: false, description: 'Restrict to one team’s connections.', example: 'team_path=platform' },
    ],
    requestSample: {
      title: 'List provider connections',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-context-connections" | jq \'.[] | {id, provider, disabled}\'',
      expectedOutput: 'Each connection with its provider and base URL. The credential is a reference, never a value.',
    },
    responses: [{ status: 200, description: 'Connections visible to the caller.', contentType: 'application/json', sample: '[' + CONNECTION + ']' }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
    notes: 'A connection is a link to an external wiki. It imports documents; it does not give a run live access to the provider.',
  },
  {
    method: 'POST',
    path: '/v1/knowledge-context-connections',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Creates a provider connection.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Connect a wiki',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/knowledge-context-connections" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"team":"platform","name":"confluence","provider":"confluence","base_url":"https://wiki.example.com","credential_ref":"platform/confluence"}\' | jq -r .id',
      expectedOutput: 'The connection id. Test it before importing anything.',
    },
    responses: [{ status: 201, description: 'Connection created.', contentType: 'application/json', sample: CONNECTION }],
    errors: [
      { status: 400, cause: 'An unknown provider, a missing base URL, or an unresolvable credential.', action: 'The message names the field.' },
    ],
    sideEffects: ['Creates a link the platform can import from.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go', 'services/nopsai/knowledge_connections_gitops_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'GET',
    path: '/v1/knowledge-context-connections/{connectionID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Reads one provider connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection identifier, including its team prefix.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Read a connection',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-context-connections/platform/confluence" | jq',
      expectedOutput: 'Provider, base URL, scopes, and configuration.',
    },
    responses: [{ status: 200, description: 'The connection.', contentType: 'application/json', sample: CONNECTION }],
    errors: [],
    notes: 'The identifier is a catch-all segment, so a team-prefixed id with slashes needs no encoding.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'PUT',
    path: '/v1/knowledge-context-connections/{connectionID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Replaces a provider connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection to replace.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Replace a connection',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/knowledge-context-connections/platform/confluence" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @connection.json | jq',
      expectedOutput: 'The stored connection. Documents already imported keep their content.',
      placeholders: ['A PUT replaces the whole document; omitted fields are cleared.'],
    },
    responses: [{ status: 200, description: 'Connection stored.', contentType: 'application/json', sample: CONNECTION }],
    errors: [
      { status: 400, cause: 'An invalid provider, URL, or credential reference.', action: 'The message names the field.' },
    ],
    sideEffects: ['Changes where future imports read from.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/knowledge-context-connections/{connectionID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Partially updates a provider connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection to update.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Disable a connection',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/knowledge-context-connections/platform/confluence" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"disabled":true}\' | jq \'{id, disabled}\'',
      expectedOutput: 'Imports stop; documents already imported stay available to runs.',
    },
    responses: [{ status: 200, description: 'Connection updated.', contentType: 'application/json', sample: CONNECTION }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
    ],
    sideEffects: ['Disabling stops imports without removing imported documents.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
    notes: 'Disable rather than delete while investigating: the imported documents keep working while the link is paused.',
  },
  {
    method: 'DELETE',
    path: '/v1/knowledge-context-connections/{connectionID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Deletes a provider connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection to delete.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Delete a connection',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-context-connections/platform/confluence" -w "%{http_code}\\n"',
      expectedOutput: '204, unless documents imported through it still depend on it.',
    },
    responses: [{ status: 204, description: 'Connection deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No connection with that id.', action: 'It may already be deleted.' },
      { status: 409, cause: 'Documents imported through this connection still reference it.', action: 'Detach or delete those documents first.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'POST',
    path: '/v1/knowledge-context-connections/{connectionID...}',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Runs an action against a connection addressed by a nested identifier.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection identifier.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Post an action to a connection',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/knowledge-context-connections/platform/confluence" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @action.json | jq',
      expectedOutput: 'The connection after the action.',
      placeholders: ['`action.json` names the action to run against the connection.'],
    },
    responses: [{ status: 200, description: 'The connection after the action.', contentType: 'application/json', sample: CONNECTION }],
    errors: [
      { status: 400, cause: 'An unknown action or malformed body.', action: 'The dedicated `/test` and `/resolve-page` routes cover the common cases.' },
    ],
    sideEffects: ['Depends on the action; a provider call may be made.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'POST',
    path: '/v1/knowledge-context-connections/{connectionID}/test',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Tests a connection against its provider.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection to test.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Test a connection',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-context-connections/$CONNECTION_ID/test" | jq',
      expectedOutput: 'A real provider call, without importing or storing a document.',
    },
    responses: [{ status: 200, description: 'The provider answered.', contentType: 'application/json', sample: '{ "ok": true, "provider": "confluence" }' }],
    errors: [
      { status: 400, cause: 'The connection is incomplete or disabled.', action: 'Finish configuring it first.' },
      { status: 404, cause: 'No connection with that id.', action: 'Confirm the id.' },
      { status: 502, cause: 'The provider rejected the call or could not be reached.', action: 'Usually an expired credential or blocked egress.' },
    ],
    sideEffects: ['Makes one real provider call. Stores nothing.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  {
    method: 'POST',
    path: '/v1/knowledge-context-connections/{connectionID}/resolve-page',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Resolves a provider page reference to the document it would import.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection identifier.', example: 'platform/confluence' },
    ],
    requestSample: {
      title: 'Preview what a page would import as',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/knowledge-context-connections/$CONNECTION_ID/resolve-page" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"url":"https://wiki.example.com/display/PLAT/Release+policy"}\' | jq',
      expectedOutput: 'The page and the document it maps to — a preview, not an import.',
    },
    responses: [{ status: 200, description: 'The resolved page.', contentType: 'application/json', sample: '{\n  "external_page_id": "482991",\n  "title": "Release policy",\n  "url": "https://wiki.example.com/display/PLAT/Release+policy"\n}' }],
    errors: [
      { status: 400, cause: 'A missing or unparseable page reference.', action: 'Send the provider URL or page id.' },
      { status: 404, cause: 'No connection with that id, or the page does not exist.', action: 'Confirm both.' },
      { status: 502, cause: 'The provider could not be reached.', action: 'Test the connection.' },
    ],
    sideEffects: ['Makes one provider call. Imports nothing.'],
    coveringTests: ['services/nopsai/knowledge_context_external_sync_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
    notes: 'Resolve before importing: it shows exactly which document a URL turns into, including its title and page id.',
  },
  {
    method: 'GET',
    path: '/v1/knowledge-context-connections/{connectionID}/pages/search',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Searches pages available through a connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path', type: 'string', required: true, description: 'Connection identifier.', example: 'platform/confluence' },
      { name: 'q', in: 'query', type: 'string', required: true, description: 'Search text passed to the provider.', example: 'q=release+policy' },
    ],
    requestSample: {
      title: 'Search a connected wiki',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-context-connections/$CONNECTION_ID/pages/search?q=release" | jq',
      expectedOutput: 'Matching pages with their ids, so one can be resolved and imported.',
    },
    responses: [{ status: 200, description: 'Matching pages.', contentType: 'application/json', sample: '[\n  { "external_page_id": "482991", "title": "Release policy" }\n]' }],
    errors: [
      { status: 400, cause: 'A missing search term.', action: 'Send `q`.' },
      { status: 404, cause: 'No connection with that id.', action: 'Confirm the id.' },
      { status: 502, cause: 'The provider search failed.', action: 'Test the connection.' },
    ],
    sideEffects: ['Makes one provider call.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
  },
  { method: 'GET', path: '/v1/knowledge-connections', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for listing provider connections.', notes: 'Same handler as /v1/knowledge-context-connections; prefer that form.' },
  { method: 'POST', path: '/v1/knowledge-connections', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for creating a provider connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'GET', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for reading a connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'PUT', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for replacing a connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'PATCH', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for partially updating a connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'POST', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for connection actions.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'DELETE', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for deleting a connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  { method: 'POST', path: '/v1/knowledge-connections/{connectionID}/test', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for testing a connection.', notes: 'Same handler as the knowledge-context-connections form.' },
  {
    method: 'GET',
    path: '/v1/knowledge-connections/{connectionID}/pages',
    area: 'Knowledge Context',
    access: 'authorized',
    purpose: 'Lists pages available through a connection.',
    depth: 'full',
    parameters: [
      { name: 'connectionID', in: 'path' as const, type: 'string', required: true, description: 'Connection identifier.', example: 'platform/confluence' },
      { name: 'limit', in: 'query' as const, type: 'integer', required: false, description: 'How many pages to return.', example: 'limit=50' },
    ],
    requestSample: {
      title: 'Browse a connected wiki',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/knowledge-connections/$CONNECTION_ID/pages" | jq',
      expectedOutput: 'Pages the connection exposes, for picking one to resolve and import.',
    },
    responses: [
      { status: 200, description: 'Available pages.', contentType: 'application/json', sample: '[\n  { "external_page_id": "482991", "title": "Release policy" }\n]' },
    ],
    errors: [
      { status: 404, cause: 'No connection with that id.', action: 'List the connections.' },
      { status: 502, cause: 'The provider could not be reached.', action: 'Test the connection.' },
    ],
    sideEffects: ['Makes one provider call.'],
    coveringTests: ['services/nopsai/knowledge_connections_test.go'],
    evidence: ['services/nopsai/knowledge_connections.go'],
    notes: 'Browsing is the alternative to searching when you do not know the page title yet. Neither imports anything.',
  },
  { method: 'POST', path: '/v1/knowledge-connections/{connectionID}/resolve-page', area: 'Knowledge Context', access: 'authorized', purpose: 'Compatibility path for resolving a provider page.', notes: 'Same handler as the knowledge-context-connections form.' },
];
