import type { WikiApiRoute } from '../../types.js';

const WINDOW = { name: 'from', in: 'query' as const, type: 'timestamp', required: false, defaultValue: '30 days ago', description: 'Start of the analysis window. The default window is the last 30 days.', example: 'from=2026-08-01' };
const WINDOW_TO = { name: 'to', in: 'query' as const, type: 'timestamp', required: false, defaultValue: 'now', description: 'End of the analysis window. Must be after `from`.', example: 'to=2026-08-19' };
const TEAM_FILTER = { name: 'teamId', in: 'query' as const, type: 'string', required: false, description: 'Restrict to one team. `team_id` is accepted as an alias.', example: 'teamId=18' };
const PIPELINE_FILTER = { name: 'pipelineName', in: 'query' as const, type: 'string', required: false, description: 'Restrict to one pipeline.', example: 'pipelineName=release-service' };

const SUMMARY =
  '{\n  "window": { "from": "2026-07-20T00:00:00Z", "to": "2026-08-19T00:00:00Z" },\n  "total_runs": 412,\n  "successful_runs": 388,\n  "failed_runs": 17,\n  "cancelled_runs": 3,\n  "running_runs": 2,\n  "waiting_approval_runs": 1,\n  "success_rate": 0.94\n}';

const DURATION =
  '{\n  "window": { "from": "2026-07-20T00:00:00Z", "to": "2026-08-19T00:00:00Z" },\n  "items": [\n    {\n      "name": "release-service",\n      "runs": 84,\n      "average_seconds": 196.4,\n      "median_seconds": 181.0,\n      "p95_seconds": 402.7\n    }\n  ]\n}';

const SAVED_VIEW =
  '{\n  "id": "6c1f2a90-3b77-4d22-9a51-8e2b0c4f7d31",\n  "name": "Failing releases",\n  "filters": { "pipelineName": "release-service", "status": "failure" }\n}';

/**
 * Monitoring.
 *
 * Every analytics route shares one filter model: a `from`/`to` window defaulting
 * to the last 30 days, plus the same team, pipeline, branch, and status filters.
 * Learn the filters once and they apply across the area.
 */
export const monitoringRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/monitoring/summary',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Run counts and success rate for a window.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'status', in: 'query', type: 'string', required: false, description: 'Restrict to runs in one status.', example: 'status=failure' },
      { name: 'branch', in: 'query', type: 'string', required: false, description: 'Restrict to one Git ref.', example: 'branch=main' },
    ],
    requestSample: {
      title: 'Read the operational summary',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/summary?from=2026-08-01" | jq',
      expectedOutput: 'Counts per terminal state plus the success rate over the window.',
    },
    responses: [{ status: 200, description: 'Run counts for the window.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An unparseable `from` or `to`, or a `to` that is not after `from`.', action: 'The message names which of the two failed.' },
      { status: 500, cause: 'The analytics query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'Counts are filtered per caller, so a summary is what this caller may see rather than a platform total.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/runs/analytics',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Run trends and breakdowns over a window.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'compare', in: 'query', type: 'boolean', required: false, description: 'Include the previous equivalent window for comparison.', example: 'compare=true' },
      { name: 'triggerSource', in: 'query', type: 'string', required: false, description: 'Restrict to runs from one entry point.', example: 'triggerSource=schedule' },
    ],
    requestSample: {
      title: 'Compare this window with the last',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/runs/analytics?from=2026-08-01&compare=true" | jq',
      expectedOutput: 'Trends for the window and, with `compare`, the preceding one of equal length.',
    },
    responses: [{ status: 200, description: 'Run analytics.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An invalid window or filter value.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: '`compare=true` is what turns a number into a signal: 94% success means little without last month beside it.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/pipelines/performance',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Duration statistics per pipeline.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'minDurationSeconds', in: 'query', type: 'number', required: false, description: 'Only runs at least this long.', example: 'minDurationSeconds=60' },
      { name: 'maxDurationSeconds', in: 'query', type: 'number', required: false, description: 'Only runs at most this long.', example: 'maxDurationSeconds=600' },
    ],
    requestSample: {
      title: 'Find the slowest pipelines',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/pipelines/performance" | jq \'.items | sort_by(-.p95_seconds) | .[0:5]\'',
      expectedOutput: 'Average, median, and p95 per pipeline over the window.',
    },
    responses: [{ status: 200, description: 'Per-pipeline duration statistics.', contentType: 'application/json', sample: DURATION }],
    errors: [
      { status: 400, cause: 'An invalid window or duration filter.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'Read p95 rather than the average. A pipeline with a 3-minute average and a 12-minute p95 is the one people complain about.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/steps/performance',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Duration statistics per step.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'stepName', in: 'query', type: 'string', required: false, description: 'Restrict to one step. `step_name` is accepted as an alias.', example: 'stepName=verify' },
    ],
    requestSample: {
      title: 'Find the slow step inside a pipeline',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/steps/performance?pipelineName=release-service" | jq',
      expectedOutput: 'Per-step statistics, which is how a slow pipeline is narrowed to one step.',
    },
    responses: [{ status: 200, description: 'Per-step duration statistics.', contentType: 'application/json', sample: DURATION }],
    errors: [
      { status: 400, cause: 'An invalid window or filter.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/monitoring/tasks/performance',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Duration statistics per task.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'taskName', in: 'query', type: 'string', required: false, description: 'Restrict to one task. `task_name` is accepted as an alias.', example: 'taskName=unit' },
    ],
    requestSample: {
      title: 'Compare tasks inside a step',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/tasks/performance?stepName=checks" | jq',
      expectedOutput: 'Per-task statistics, which shows whether concurrency is actually helping.',
    },
    responses: [{ status: 200, description: 'Per-task duration statistics.', contentType: 'application/json', sample: DURATION }],
    errors: [
      { status: 400, cause: 'An invalid window or filter.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'A step is only as fast as its slowest task, so a wide spread here means the step is waiting on one outlier.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/triggers/analytics',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'How runs are being started, by trigger.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER,
      { name: 'triggerSource', in: 'query', type: 'string', required: false, description: 'Restrict to one entry point.', example: 'triggerSource=git' },
    ],
    requestSample: {
      title: 'See which triggers are firing',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/triggers/analytics" | jq',
      expectedOutput: 'Run counts grouped by how they started.',
    },
    responses: [{ status: 200, description: 'Trigger analytics.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An invalid window or filter.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/monitoring/external-triggers/analytics',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Invocation analytics for external API triggers.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER,
      { name: 'externalTriggerId', in: 'query', type: 'string', required: false, description: 'Restrict to one external trigger.', example: 'externalTriggerId=3d2b1f88-77aa-4c19-9f3d-52b0c4e7a901' },
    ],
    requestSample: {
      title: 'See how an integration is behaving',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/external-triggers/analytics" | jq',
      expectedOutput: 'Invocation counts and outcomes per trigger.',
    },
    responses: [{ status: 200, description: 'External trigger analytics.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An invalid window or trigger id.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'Aggregate counts live here; the per-call reasons live in the trigger’s own invocation history.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/ai-usage',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Token and model usage across runs and the assistant.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER,
      { name: 'provider', in: 'query', type: 'string', required: false, description: 'Restrict to one provider.', example: 'provider=anthropic' },
      { name: 'model', in: 'query', type: 'string', required: false, description: 'Restrict to one model.', example: 'model=claude-sonnet-4-5' },
      { name: 'feature', in: 'query', type: 'string', required: false, description: 'Restrict to one consuming surface, such as pipeline runs or the assistant.', example: 'feature=assistant' },
    ],
    requestSample: {
      title: 'See where tokens are going',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/ai-usage?from=2026-08-01" | jq \'{window, by_pipeline}\'',
      expectedOutput: 'Totals plus breakdowns by pipeline, task, and the runs that consumed most.',
    },
    responses: [
      { status: 200, description: 'AI usage totals and breakdowns.', contentType: 'application/json', sample: '{\n  "window": { "from": "2026-08-01T00:00:00Z", "to": "2026-08-19T00:00:00Z" },\n  "by_pipeline": [{ "name": "release-service", "input_tokens": 481233, "output_tokens": 61204 }]\n}' },
    ],
    errors: [
      { status: 400, cause: 'An invalid window or filter.', action: 'The message names the parameter.' },
      { status: 500, cause: 'The usage query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'Assistant and evaluation spend is recorded alongside pipeline spend, so this is the whole AI bill rather than the pipeline part of it.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/reliability',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Reliability view: what fails, how often, and where.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER],
    requestSample: {
      title: 'Read the reliability view',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/reliability" | jq',
      expectedOutput: 'Failure concentrations by pipeline and step over the window.',
    },
    responses: [{ status: 200, description: 'Reliability analytics.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An invalid window.', action: 'Check `from` and `to`.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/monitoring/efficiency',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Efficiency view: time and capacity spent per unit of work.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER, PIPELINE_FILTER],
    requestSample: {
      title: 'Read the efficiency view',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/efficiency" | jq',
      expectedOutput: 'Where run time is going, including waiting rather than working.',
    },
    responses: [{ status: 200, description: 'Efficiency analytics.', contentType: 'application/json', sample: DURATION }],
    errors: [
      { status: 400, cause: 'An invalid window.', action: 'Check `from` and `to`.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'Queue time and approval waits are not execution time. Efficiency separates them so "the pipeline is slow" can be answered honestly.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/security',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Security view: authorization denials and sensitive access over a window.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO, TEAM_FILTER],
    requestSample: {
      title: 'Read the security view',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/security" | jq',
      expectedOutput: 'Denials and sensitive operations aggregated over the window.',
    },
    responses: [{ status: 200, description: 'Security analytics.', contentType: 'application/json', sample: SUMMARY }],
    errors: [
      { status: 400, cause: 'An invalid window.', action: 'Check `from` and `to`.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_analytics_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_analytics_handlers.go'],
    notes: 'This aggregates; the audit log has the individual records, including who read which secret.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/dispatcher',
    area: 'Monitoring',
    access: 'authenticated',
    purpose: 'Live dispatcher and runner fleet status.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Check the fleet',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/dispatcher" | jq \'.runners\'',
      expectedOutput: 'Registered runners with their scopes, capacity, and reachability.',
    },
    responses: [
      { status: 200, description: 'Dispatcher and fleet state.', contentType: 'application/json', sample: '{\n  "runners": [\n    { "runner_id": "runner-local-1", "scopes": ["prod"], "capacity": 2, "reachable": true, "dispatch_enabled": true }\n  ]\n}' },
    ],
    errors: [],
    notes: 'Authenticated rather than authorized: any signed-in caller may see whether there is anywhere to run work.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/monitoring/runners/history',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Runner connection and capacity history.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO,
      { name: 'runnerId', in: 'query', type: 'string', required: false, description: 'Restrict to one runner.', example: 'runnerId=runner-local-1' },
    ],
    requestSample: {
      title: 'Check whether a runner has been flapping',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/runners/history" | jq',
      expectedOutput: 'Connect and disconnect events over the window, which is how intermittent capacity is spotted.',
    },
    responses: [
      { status: 200, description: 'Runner history.', contentType: 'application/json', sample: '[\n  { "runner_id": "runner-local-1", "event": "connected", "at": "2026-08-19T08:11:04Z" }\n]' },
    ],
    errors: [
      { status: 400, cause: 'An invalid window.', action: 'Check `from` and `to`.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
    notes: 'A run that queued for a long time and then succeeded usually shows up here as a runner that was away.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/recommendations',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Lists platform recommendations derived from monitoring data.',
    depth: 'full',
    parameters: [
      { name: 'status', in: 'query', type: 'string', required: false, description: 'Restrict to open, acknowledged, or resolved recommendations.', example: 'status=open' },
    ],
    requestSample: {
      title: 'List open recommendations',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/recommendations?status=open" | jq',
      expectedOutput: 'Findings with their severity and what they suggest.',
    },
    responses: [
      { status: 200, description: 'Recommendations.', contentType: 'application/json', sample: '[\n  {\n    "id": "9a2c...",\n    "severity": "medium",\n    "title": "release-service p95 doubled",\n    "status": "open"\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/monitoring/recommendations/{recommendationID}/acknowledge',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Acknowledges a recommendation without resolving it.',
    depth: 'full',
    parameters: [{ name: 'recommendationID', in: 'path', type: 'string', required: true, description: 'Recommendation identifier.', example: '9a2c...' }],
    requestSample: {
      title: 'Acknowledge a recommendation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/recommendations/$RECOMMENDATION_ID/acknowledge" | jq',
      expectedOutput: 'The recommendation moves to acknowledged: seen, not yet fixed.',
    },
    responses: [{ status: 200, description: 'Recommendation acknowledged.', contentType: 'application/json', sample: '{ "id": "9a2c...", "status": "acknowledged" }' }],
    errors: [
      { status: 404, cause: 'No recommendation with that id.', action: 'Confirm the id from the list.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Records who acknowledged it and when.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
    notes: 'Acknowledged and resolved are different states on purpose: one says "we know", the other says "it is fixed".',
  },
  {
    method: 'POST',
    path: '/v1/monitoring/recommendations/{recommendationID}/resolve',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Marks a recommendation resolved.',
    depth: 'full',
    parameters: [{ name: 'recommendationID', in: 'path', type: 'string', required: true, description: 'Recommendation identifier.', example: '9a2c...' }],
    requestSample: {
      title: 'Resolve a recommendation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/recommendations/$RECOMMENDATION_ID/resolve" | jq',
      expectedOutput: 'The recommendation is closed. It can reappear if the underlying signal returns.',
    },
    responses: [{ status: 200, description: 'Recommendation resolved.', contentType: 'application/json', sample: '{ "id": "9a2c...", "status": "resolved" }' }],
    errors: [
      { status: 404, cause: 'No recommendation with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Closes the finding. A recurring signal produces a new recommendation rather than reopening this one.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/monitoring/alert-rules',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Lists alert rules.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List alert rules',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/alert-rules" | jq',
      expectedOutput: 'Each rule with its condition and whether it is enabled.',
    },
    responses: [
      { status: 200, description: 'Alert rules.', contentType: 'application/json', sample: '[\n  {\n    "id": "b41d...",\n    "name": "release-service failure rate",\n    "enabled": true\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/monitoring/alert-rules',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Creates an alert rule.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create an alert rule',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/monitoring/alert-rules" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @rule.json | jq -r .id',
      expectedOutput: 'The created rule. Evaluate it once before trusting it.',
      placeholders: ['`rule.json` carries the rule name, its condition, and the window it evaluates over.'],
    },
    responses: [{ status: 201, description: 'Rule created.', contentType: 'application/json', sample: '{ "id": "b41d...", "name": "release-service failure rate", "enabled": true }' }],
    errors: [
      { status: 400, cause: 'An invalid condition or window.', action: 'The message names the field.' },
      { status: 500, cause: 'The rule could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a rule the platform evaluates on its own schedule.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/monitoring/alert-rules/{ruleID}',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Replaces an alert rule.',
    depth: 'full',
    parameters: [{ name: 'ruleID', in: 'path', type: 'string', required: true, description: 'Rule identifier.', example: 'b41d...' }],
    requestSample: {
      title: 'Update an alert rule',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/monitoring/alert-rules/$RULE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @rule.json | jq',
      expectedOutput: 'The stored rule.',
    },
    responses: [{ status: 200, description: 'Rule stored.', contentType: 'application/json', sample: '{ "id": "b41d...", "name": "release-service failure rate", "enabled": true }' }],
    errors: [
      { status: 400, cause: 'An invalid condition.', action: 'Evaluate the rule to see what it would match.' },
      { status: 404, cause: 'No rule with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what fires and when.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/monitoring/alert-rules/{ruleID}',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Deletes an alert rule.',
    depth: 'full',
    parameters: [{ name: 'ruleID', in: 'path', type: 'string', required: true, description: 'Rule to delete.', example: 'b41d...' }],
    requestSample: {
      title: 'Delete an alert rule',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/alert-rules/$RULE_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Events it already produced stay.',
    },
    responses: [{ status: 204, description: 'Rule deleted.', sample: '' }],
    errors: [
      { status: 404, cause: 'No rule with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Stops future evaluation. Past alert events remain.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/monitoring/alert-rules/{ruleID}/evaluate',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Evaluates a rule now, without waiting for its schedule.',
    depth: 'full',
    parameters: [{ name: 'ruleID', in: 'path', type: 'string', required: true, description: 'Rule to evaluate.', example: 'b41d...' }],
    requestSample: {
      title: 'Test a rule against current data',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/alert-rules/$RULE_ID/evaluate" | jq',
      expectedOutput: 'Whether the rule matches right now — the way to check a threshold before it pages someone at 3am.',
    },
    responses: [{ status: 200, description: 'Evaluation result.', contentType: 'application/json', sample: '{ "id": "b41d...", "matched": false, "observed": 0.03 }' }],
    errors: [
      { status: 400, cause: 'The rule cannot be evaluated as written.', action: 'The message names the problem in the condition.' },
      { status: 404, cause: 'No rule with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'Evaluation failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['Evaluates against live data. A manual evaluation does not fire notifications.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
    notes: 'Always evaluate a new rule before enabling it. A threshold that matches everything is indistinguishable from one that matches nothing until it runs.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/alert-events',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Lists alert events that rules have produced.',
    depth: 'full',
    parameters: [WINDOW, WINDOW_TO,
      { name: 'ruleId', in: 'query', type: 'string', required: false, description: 'Restrict to events from one rule.', example: 'ruleId=b41d...' },
    ],
    requestSample: {
      title: 'Read recent alert events',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/alert-events" | jq',
      expectedOutput: 'What fired, when, and what the rule observed at the time.',
    },
    responses: [
      { status: 200, description: 'Alert events.', contentType: 'application/json', sample: '[\n  { "rule_id": "b41d...", "fired_at": "2026-08-18T02:14:00Z", "observed": 0.21 }\n]' },
    ],
    errors: [
      { status: 400, cause: 'An invalid window.', action: 'Check `from` and `to`.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
    notes: 'Events record the observed value, so a rule that fires constantly can be retuned from evidence rather than guesswork.',
  },
  {
    method: 'GET',
    path: '/v1/monitoring/views',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Lists saved monitoring views.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List saved views',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/views" | jq',
      expectedOutput: 'Named filter sets, so a recurring investigation is one click rather than six parameters.',
    },
    responses: [{ status: 200, description: 'Saved views.', contentType: 'application/json', sample: '[' + SAVED_VIEW + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/monitoring/views',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Saves a monitoring view.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Save a filter set',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/monitoring/views" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"Failing releases","filters":{"pipelineName":"release-service","status":"failure"}}\' | jq -r .id',
      expectedOutput: 'The saved view id.',
    },
    responses: [{ status: 201, description: 'View saved.', contentType: 'application/json', sample: SAVED_VIEW }],
    errors: [
      { status: 400, cause: 'A missing name or unusable filter set.', action: 'Filters use the same parameter names as the analytics routes.' },
      { status: 500, cause: 'The view could not be saved.', action: 'Retry.' },
    ],
    sideEffects: ['Stores a named filter set.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
    notes: 'A view stores filters, not results, so it always reflects current data.',
  },
  {
    method: 'PUT',
    path: '/v1/monitoring/views/{viewID}',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Replaces a saved view.',
    depth: 'full',
    parameters: [{ name: 'viewID', in: 'path', type: 'uuid', required: true, description: 'View identifier.', example: '6c1f2a90-3b77-4d22-9a51-8e2b0c4f7d31' }],
    requestSample: {
      title: 'Update a saved view',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/monitoring/views/$VIEW_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @view.json | jq',
      expectedOutput: 'The stored view.',
    },
    responses: [{ status: 200, description: 'View stored.', contentType: 'application/json', sample: SAVED_VIEW }],
    errors: [
      { status: 400, cause: 'An unusable filter set.', action: 'The message names the field.' },
      { status: 404, cause: 'No view with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['None beyond storing the filters.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/monitoring/views/{viewID}',
    area: 'Monitoring',
    access: 'authorized',
    purpose: 'Deletes a saved view.',
    depth: 'full',
    parameters: [{ name: 'viewID', in: 'path', type: 'uuid', required: true, description: 'View to delete.', example: '6c1f2a90-3b77-4d22-9a51-8e2b0c4f7d31' }],
    requestSample: {
      title: 'Delete a saved view',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/monitoring/views/$VIEW_ID" -w "%{http_code}\\n"',
      expectedOutput: '204.',
    },
    responses: [{ status: 204, description: 'View deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use an id from the list.' },
      { status: 404, cause: 'No view with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the saved filter set. No monitoring data is affected.'],
    coveringTests: ['services/nopsai/monitoring_handlers_test.go'],
    evidence: ['services/nopsai/monitoring_handlers.go'],
  },
];
