import type { WikiApiRoute } from '../../types.js';

const RUN_LIST_ITEM =
  '[\n  {\n    "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n    "pipeline_name": "release-service",\n    "pipeline_path": "platform",\n    "status": "success",\n    "git_ref": "refs/heads/main",\n    "started_at": "2026-08-19T10:44:02Z",\n    "finished_at": "2026-08-19T10:47:18Z",\n    "duration": "3m16s",\n    "is_complete": true\n  }\n]';

const APPROVAL_RECORD =
  '[\n  {\n    "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n    "step_name": "production-gate",\n    "task_name": "production-gate",\n    "approval_type": "production-release",\n    "assigned_teams": ["platform/sre"],\n    "allow_self_approval": false,\n    "status": "pending",\n    "requested_at": "2026-08-19T10:46:10Z",\n    "expires_at": "2026-08-20T10:46:10Z"\n  }\n]';

/**
 * Runs.
 *
 * A run is the durable record of one execution: its graph, its logs, its
 * approvals, and its deliverables. Starting one is the only write here that
 * consumes runner capacity; everything else reads or acts on a record.
 */
export const runsRoutes: WikiApiRoute[] = [
  {
    method: 'POST',
    path: '/v1/run',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Starts a run from an inline or referenced pipeline.',
    depth: 'full',
    parameters: [
      { name: 'X-Nopsai-Scope', in: 'header', type: 'string', required: false, description: 'Run scope. Takes precedence over `scope` in the body.', example: 'platform/production' },
      { name: 'Accept', in: 'header', type: 'string', required: false, defaultValue: 'text/plain', description: 'Send `application/json` to get a JSON body instead of a plain-text confirmation.', example: 'application/json' },
    ],
    requestSample: {
      title: 'Start a run from an inline definition',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/run" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Accept: application/json" \\\n  -H "Content-Type: application/json" \\\n  --data @run-request.json | jq',
      expectedOutput: 'A run id. Without `Accept: application/json` the same call answers with a plain-text confirmation.',
      placeholders: [
        '`run-request.json` carries `pipeline` or `definition`, plus `scope`, `variables`, and `sensitive_variables`.',
      ],
    },
    responses: [
      { status: 201, description: 'The run was accepted and queued.', contentType: 'application/json', sample: '{\n  "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n  "trigger_event_id": ""\n}' },
    ],
    errors: [
      { status: 400, cause: 'Invalid JSON, an unusable definition, or a variable override name outside `^[A-Za-z0-9_.-]+$`.', action: 'The message names the offending variable names rather than just rejecting the request.' },
      { status: 403, cause: 'The caller may not use a resource the run touches — a model, an MCP profile, a scope, or the pipeline itself.', action: 'Authorization covers everything the run would reach, not just the pipeline.' },
      { status: 500, cause: 'The run could not be recorded or dispatched.', action: 'Retry; check the dispatcher has a registered runner.' },
    ],
    sideEffects: [
      'Creates a durable run record before any work starts.',
      'Submits the job to the dispatcher, which assigns it to a runner with matching scopes and free capacity.',
      'Writes an audit record naming the caller and every resource the run was authorized to use.',
    ],
    coveringTests: ['services/nopsai/run_status_test.go', 'services/nopsai/aaa_integration_test.go'],
    evidence: ['services/nopsai/run_handlers.go', 'services/nopsai/run_launcher.go'],
    notes: '`sensitive_variables` names which of the supplied `variables` must be masked in logs. Passing a secret without naming it there puts it in the run record in clear text.',
  },
  {
    method: 'POST',
    path: '/v1/run/{pipelineName...}',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Starts a run of a stored pipeline.',
    depth: 'full',
    parameters: [
      { name: 'pipelineName', in: 'path', type: 'string', required: true, description: 'Stored pipeline identifier, including its team prefix.', example: 'platform/release-service' },
      { name: 'X-Nopsai-Scope', in: 'header', type: 'string', required: false, description: 'Run scope. Takes precedence over `scope` in the body.', example: 'platform/production' },
      { name: 'Accept', in: 'header', type: 'string', required: false, defaultValue: 'text/plain', description: 'Send `application/json` for a JSON response body.', example: 'application/json' },
    ],
    requestSample: {
      title: 'Run a stored pipeline in a scope',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/run/platform/release-service" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Accept: application/json" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"scope":"platform/production","variables":{"RELEASE_CHANNEL":"stable"}}\' | jq -r .run_id',
      expectedOutput: 'The run id of the queued run.',
    },
    responses: [
      { status: 201, description: 'Run queued.', contentType: 'application/json', sample: '{\n  "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n  "trigger_event_id": ""\n}' },
    ],
    errors: [
      { status: 400, cause: 'Invalid payload, unknown pipeline, or invalid variable override names.', action: 'Confirm the identifier with `GET /v1/pipelines`.' },
      { status: 403, cause: 'The caller may not run this pipeline or use something it references.', action: 'Check `/v1/access/effective-permissions` for the pipeline and the scope.' },
      { status: 500, cause: 'The run could not be recorded or dispatched.', action: 'Retry.' },
    ],
    sideEffects: [
      'Creates a run record and submits it to the dispatcher.',
      'Variable overrides are recorded on the run, so a run is reproducible from its own record.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'The scope decides which variables and secrets resolve. Running the right pipeline in the wrong scope is the most common cause of a run that fails before its first step.',
  },
  {
    method: 'GET',
    path: '/v1/runs',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Lists runs. Exposes only lightweight aggregate `final_output_status` metadata.',
    depth: 'full',
    parameters: [
      { name: 'limit', in: 'query', type: 'integer', required: false, defaultValue: '300', description: 'Page size. A value of zero or less becomes 50; anything above 1000 is capped at 1000.', example: 'limit=50' },
      { name: 'offset', in: 'query', type: 'integer', required: false, defaultValue: '0', description: 'Rows to skip. Negative values are ignored.', example: 'offset=100' },
      { name: 'teamId', in: 'query', type: 'string', required: false, description: 'Restrict to one team. Changes the response into a team-by-branch grouping rather than a flat list.', example: 'teamId=12' },
      { name: 'branch', in: 'query', type: 'string', required: false, description: 'Restrict to runs for one Git ref.', example: 'branch=main' },
    ],
    requestSample: {
      title: 'List recent runs',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs?limit=20" | jq \'.[] | {run_id, pipeline_name, status}\'',
      expectedOutput: 'Runs the caller may see, newest first. There is no pipeline filter — select on `pipeline_name` in the response.',
    },
    responses: [
      { status: 200, description: 'A flat list of run records, filtered per caller.', contentType: 'application/json', sample: RUN_LIST_ITEM },
    ],
    errors: [
      { status: 400, cause: '`teamId` is not a known team id or the root alias.', action: 'Read team ids from `GET /v1/teams`.' },
      { status: 503, cause: 'Authorization is unavailable, so runs cannot be filtered safely.', action: 'Check AAA. The platform refuses rather than returning runs the caller may not see.' },
      { status: 500, cause: 'The run query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'Passing `teamId` changes the response shape to a team-by-branch grouping. Code that parses both forms should branch on the parameter it sent.',
  },
  {
    method: 'GET',
    path: '/v1/runs/{runID}',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Full run detail including steps, tasks, and outputs.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run identifier.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'If-None-Match', in: 'header', type: 'string', required: false, description: 'ETag from a previous read. Matching returns 304 with no body, which is how the UI polls a live run cheaply.', example: '"a2f1c9..."' },
    ],
    requestSample: {
      title: 'Read run detail, then poll it cheaply',
      language: 'bash',
      code:
        'ETAG=$(curl -sD - -o run.json -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID" | awk \'/^ETag:/ {print $2}\' | tr -d "\\r")\ncurl -s -o /dev/null -w "%{http_code}\\n" -H "Authorization: Bearer $NOPSAI_TOKEN" -H "If-None-Match: $ETAG" "$NOPSAI_URL/v1/runs/$RUN_ID"',
      expectedOutput: 'The first call returns the run with an ETag; the second returns 304 while nothing has changed.',
    },
    responses: [
      {
        status: 200,
        description: 'The run, its steps and tasks, its child runs, AI usage, and its final outputs.',
        contentType: 'application/json',
        sample: '{\n  "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n  "pipeline_name": "release-service",\n  "status": "success",\n  "steps": [\n    { "name": "build", "status": "success" },\n    { "name": "production-gate", "status": "success" }\n  ]\n}',
      },
      { status: 304, description: 'Nothing changed since the ETag was issued.' },
    ],
    errors: [
      { status: 403, cause: 'The caller may not read this run.', action: 'Run visibility follows the owning team.' },
      { status: 404, cause: 'No run with that id.', action: 'Check the id: a deleted run is gone, not hidden.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'Run detail could not be assembled.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'Poll with the ETag. Polling this route without `If-None-Match` rebuilds the whole detail document every time.',
  },
  {
    method: 'GET',
    path: '/v1/runs/{runID}/status',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Compact run status for polling.',
    depth: 'full',
    parameters: [{ name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run identifier.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' }],
    requestSample: {
      title: 'Poll for completion',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/status" | jq -r .status',
      expectedOutput: 'One of `queued`, `running`, `success`, `failure`, `warning`, `timed_out`, or `canceled`.',
    },
    responses: [{ status: 200, description: 'The current status and nothing else.', contentType: 'application/json', sample: '{"status":"running"}' }],
    errors: [{ status: 404, cause: 'No run with that id.', action: 'Confirm the id from the run list.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_internal_handlers.go'],
    notes: 'This is the route to poll in a script. It answers with one field and does not assemble the run graph.',
  },
  {
    method: 'GET',
    path: '/v1/runs/{runID}/logs',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Durable pipeline run logs.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run identifier.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'after_id', in: 'query', type: 'integer', required: false, defaultValue: '0', description: 'Return only records with a higher id, which is how a tail continues without re-reading.', example: 'after_id=4210' },
      { name: 'include_children', in: 'query', type: 'boolean', required: false, defaultValue: 'false', description: 'Include logs from child pipeline runs.', example: 'include_children=true' },
    ],
    requestSample: {
      title: 'Read run logs',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/logs" \\\n  | jq -r \'.[] | "\\(.timestamp) \\(.step_name // "-") \\(.line)"\' | tail -40',
      expectedOutput: 'Log records in id order. The text is under `line`, with `step_name` and `task_name` when the record came from a step.',
    },
    responses: [
      {
        status: 200,
        description: 'Log records, oldest first.',
        contentType: 'application/json',
        sample: '[\n  {\n    "id": 4211,\n    "timestamp": "2026-08-19T10:44:09Z",\n    "line": "building 1.0.1755600249",\n    "step_name": "build",\n    "stream": "stdout",\n    "level": "info"\n  }\n]',
      },
    ],
    errors: [
      { status: 403, cause: 'The caller may not read this run.', action: 'Log access follows run visibility.' },
      { status: 500, cause: 'The log query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_internal_handlers.go', 'pkg/models/types.go'],
    notes: 'Declared secrets, sensitive variable names, and outputs marked `sensitive` are masked before the response is written. A value a script printed itself cannot be masked, because the platform never knew it was one.',
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/cancel',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Cancels an active run.',
    depth: 'full',
    parameters: [{ name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run to cancel.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' }],
    requestSample: {
      title: 'Cancel a run',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/cancel" | jq',
      expectedOutput: 'The run moves to `canceled`. Work already running is stopped; work already finished stays recorded.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"status":"canceled"}' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use the run id from the list route.' },
      { status: 404, cause: 'No run with that id.', action: 'Confirm the id.' },
      { status: 405, cause: 'A method other than POST.', action: 'Use POST.' },
      { status: 500, cause: 'Cancellation could not be recorded.', action: 'Retry; the run keeps running until it succeeds.' },
    ],
    sideEffects: [
      'Signals the agent to stop and releases the runner capacity the run held.',
      'A pending approval on the run is closed out rather than left waiting.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go', 'doc/runtime-flows.md'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/rerun',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Starts a new run from the same definition and inputs.',
    depth: 'full',
    parameters: [{ name: 'runID', in: 'path', type: 'uuid', required: true, description: 'The run to repeat.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' }],
    requestSample: {
      title: 'Rerun a finished run',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/rerun" | jq -r .runId',
      expectedOutput: 'A new run id. Note the field is `runId` here, while starting a run returns `run_id`.',
    },
    responses: [
      { status: 201, description: 'A new run was queued from the original definition, scope, and Git context.', contentType: 'application/json', sample: '{\n  "runId": "b71e0f22-9a3d-4c81-9d5c-1f0a5d7e2c44",\n  "triggerEventId": ""\n}' },
    ],
    errors: [
      { status: 404, cause: 'The original run does not exist.', action: 'Confirm the id.' },
      { status: 409, cause: 'The original run is still in progress.', action: 'Wait for it to finish. Rerunning a live run is refused rather than queued.' },
      { status: 403, cause: 'The caller may not use a resource the rerun would touch.', action: 'Authorization is re-evaluated for the caller now, not inherited from whoever started the original run.' },
      { status: 405, cause: 'A method other than POST.', action: 'Use POST.' },
      { status: 500, cause: 'The rerun could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a separate run record; the original is untouched.', 'Writes an audit record naming the caller who triggered the rerun.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'A rerun repeats the definition, not the result. A pipeline whose definition changed since the original run reruns with the new definition.',
  },
  {
    method: 'DELETE',
    path: '/v1/runs/{runID}',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Deletes a run record.',
    depth: 'full',
    parameters: [{ name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run to delete.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' }],
    requestSample: {
      title: 'Delete a run record',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. The record, its logs, and its outputs go with it.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The id is malformed.', action: 'Use a run id.' },
      { status: 404, cause: 'No run with that id.', action: 'It may already be deleted.' },
      { status: 500, cause: 'The delete could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Removes the run, its logs, and its generated outputs permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'For bulk retention use the data cleanup routes, which preview before deleting. This route removes one record with no preview.',
  },
  {
    method: 'GET',
    path: '/v1/runs/{runID}/approvals',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Lists approval checkpoints on a run.',
    depth: 'full',
    parameters: [{ name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run identifier.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' }],
    requestSample: {
      title: 'List approvals on a run',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/approvals" | jq',
      expectedOutput: 'Each checkpoint with its assigned teams, status, requester, decision, and expiry.',
    },
    responses: [{ status: 200, description: 'Approval records for the run.', contentType: 'application/json', sample: APPROVAL_RECORD }],
    errors: [
      { status: 403, cause: 'The caller may not read this run.', action: 'Approval visibility follows run visibility.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The approval query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/approval_handlers_test.go', 'services/nopsai/approval_visibility_test.go'],
    evidence: ['services/nopsai/approval_handlers.go'],
    notes: '`expires_at` is when the checkpoint times out. An expired approval produces a `timed_out` run, not a failed one.',
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/approvals/{approvalID}/approve',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Approves a checkpoint. Comment optional.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run holding the checkpoint.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'approvalID', in: 'path', type: 'string', required: true, description: 'Checkpoint identifier from the approvals list.', example: 'production-gate' },
    ],
    requestSample: {
      title: 'Approve a checkpoint',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/runs/$RUN_ID/approvals/$APPROVAL_ID/approve" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"comment":"Change 4821 signed off"}\' | jq',
      expectedOutput: 'The checkpoint moves to approved and the run resumes from where it paused.',
      placeholders: ['`comment` is optional when approving and required when rejecting.'],
    },
    responses: [
      { status: 200, description: 'Decision recorded and the run released.', contentType: 'application/json', sample: '{\n  "step_name": "production-gate",\n  "status": "approved",\n  "decided_by_email": "sre@example.com",\n  "decided_at": "2026-08-19T10:52:03Z",\n  "decision_comment": "Change 4821 signed off"\n}' },
    ],
    errors: [
      { status: 400, cause: 'The body is malformed, or the checkpoint is no longer pending.', action: 'Re-read the approvals list: a decided or timed-out checkpoint cannot be decided again.' },
      { status: 403, cause: 'The caller is not in an assigned team, or is the requester and `allow_self_approval` is false.', action: 'Self-approval is a manifest decision, not an authorization override.' },
      { status: 404, cause: 'No such run or checkpoint.', action: 'Confirm both ids.' },
    ],
    sideEffects: [
      'Releases the paused run to continue.',
      'Records who decided, when, and with what comment, permanently on the run.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/approval_handlers_test.go'],
    evidence: ['services/nopsai/approval_handlers.go', 'services/nopsai/approval_schema.go'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/approvals/{approvalID}/reject',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Rejects a checkpoint. Comment required.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run holding the checkpoint.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'approvalID', in: 'path', type: 'string', required: true, description: 'Checkpoint identifier from the approvals list.', example: 'production-gate' },
    ],
    requestSample: {
      title: 'Reject a checkpoint',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/runs/$RUN_ID/approvals/$APPROVAL_ID/reject" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"comment":"Blocked: pending incident 2291"}\' | jq',
      expectedOutput: 'The checkpoint is rejected and the run fails closed at the gate.',
      placeholders: ['`comment` is required here — rejecting without one returns 400.'],
    },
    responses: [
      { status: 200, description: 'Rejection recorded.', contentType: 'application/json', sample: '{\n  "step_name": "production-gate",\n  "status": "rejected",\n  "decided_by_email": "sre@example.com",\n  "decided_at": "2026-08-19T10:53:41Z",\n  "decision_comment": "Blocked: pending incident 2291"\n}' },
    ],
    errors: [
      { status: 400, cause: 'No comment was supplied, or the checkpoint is no longer pending.', action: 'The message is `comment is required when rejecting an approval`. A rejection without a reason is not accepted.' },
      { status: 403, cause: 'The caller is not in an assigned team.', action: 'Only assigned teams decide.' },
      { status: 404, cause: 'No such run or checkpoint.', action: 'Confirm both ids.' },
    ],
    sideEffects: ['Fails the run closed at the checkpoint.', 'Records the decision and its comment permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/approval_handlers_test.go'],
    evidence: ['services/nopsai/approval_handlers.go'],
    notes: 'Approval failures always fail closed. `ignore_failure` on the step does not apply to a rejected gate.',
  },
  {
    method: 'GET',
    path: '/v1/runs/{runID}/outputs/{outputID}/download',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Downloads generated final output content.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run that produced the deliverable.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'outputID', in: 'path', type: 'string', required: true, description: 'Output identifier from run detail.', example: 'release-summary' },
    ],
    requestSample: {
      title: 'Download a deliverable',
      language: 'bash',
      code: 'curl -s -OJ -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/outputs/$OUTPUT_ID/download"',
      expectedOutput: 'The generated file, with the content type of its declared output type.',
    },
    responses: [
      { status: 200, description: 'The generated content: Markdown, JSON, HTML, PDF, or a spreadsheet, depending on the item type.', contentType: 'application/octet-stream' },
    ],
    errors: [
      { status: 400, cause: 'The ids are malformed.', action: 'Take both ids from run detail.' },
      { status: 403, cause: 'The caller may not read this run.', action: 'Generated content stays on authorized detail paths; run lists only expose an aggregate status.' },
      { status: 404, cause: 'No such run or output.', action: 'Confirm the output id.' },
      { status: 409, cause: 'The output has not been generated, or generation failed.', action: 'Check its status in run detail and retry generation before downloading.' },
      { status: 500, cause: 'The content could not be read.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/pipeline_final_output_contract_test.go'],
    evidence: ['services/nopsai/pipeline_final_output_specs.go', 'doc/final-output-rendering.md'],
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/outputs/{outputID}/retry',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Retries a failed final output.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run that owns the deliverable.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'outputID', in: 'path', type: 'string', required: true, description: 'Output identifier from run detail.', example: 'release-summary' },
    ],
    requestSample: {
      title: 'Retry a failed deliverable',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/outputs/$OUTPUT_ID/retry" | jq',
      expectedOutput: 'Generation restarts for that item alone. The pipeline is not re-run.',
    },
    responses: [{ status: 200, description: 'Retry accepted.', contentType: 'application/json', sample: '{"status":"pending"}' }],
    errors: [
      { status: 400, cause: 'The ids are malformed.', action: 'Take both from run detail.' },
      { status: 404, cause: 'No such run or output.', action: 'Confirm the output id.' },
      { status: 409, cause: 'The output is already generating or already succeeded.', action: 'Cancel it first if you need to regenerate.' },
      { status: 500, cause: 'The retry could not be queued.', action: 'Retry.' },
    ],
    sideEffects: ['Re-runs generation for one item; the pipeline itself is not executed again.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/pipeline_final_output_contract_test.go'],
    evidence: ['services/nopsai/pipeline_final_output_specs.go'],
    notes: 'Provider and network errors are not retried automatically, which is why this route exists: a renderer failing is not the work failing.',
  },
  {
    method: 'POST',
    path: '/v1/runs/{runID}/outputs/{outputID}/cancel',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Cancels in-progress final output generation.',
    depth: 'full',
    parameters: [
      { name: 'runID', in: 'path', type: 'uuid', required: true, description: 'Run that owns the deliverable.', example: '9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11' },
      { name: 'outputID', in: 'path', type: 'string', required: true, description: 'Output identifier from run detail.', example: 'release-summary' },
    ],
    requestSample: {
      title: 'Cancel a deliverable that is still generating',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs/$RUN_ID/outputs/$OUTPUT_ID/cancel" | jq',
      expectedOutput: 'Generation stops and the item is marked cancelled. The run status itself is unaffected.',
    },
    responses: [{ status: 200, description: 'Cancellation accepted.', contentType: 'application/json', sample: '{"status":"canceled"}' }],
    errors: [
      { status: 400, cause: 'The ids are malformed.', action: 'Take both from run detail.' },
      { status: 404, cause: 'No such run or output.', action: 'Confirm the output id.' },
      { status: 409, cause: 'The output is not generating.', action: 'Only in-progress generation can be cancelled.' },
      { status: 500, cause: 'The cancellation could not be recorded.', action: 'Retry.' },
    ],
    sideEffects: ['Stops generation for one item.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/pipeline_final_output_contract_test.go'],
    evidence: ['services/nopsai/pipeline_final_output_specs.go'],
  },
  {
    method: 'GET',
    path: '/v1/runs-by-check/{checkRunID}',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Resolves the run behind a GitHub check run.',
    depth: 'full',
    parameters: [
      { name: 'checkRunID', in: 'path', type: 'string', required: true, description: 'GitHub check run id, as it appears in the check URL.', example: '28374652109' },
    ],
    requestSample: {
      title: 'Find the run behind a check',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs-by-check/$CHECK_RUN_ID" | jq -r .run_id',
      expectedOutput: 'The run id, so a reviewer landing on a failing check can reach the run that produced it.',
    },
    responses: [{ status: 200, description: 'The run linked to that check run.', contentType: 'application/json', sample: '{\n  "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n  "pipeline_name": "release-service",\n  "status": "failure"\n}' }],
    errors: [{ status: 404, cause: 'No run is linked to that check run id.', action: 'The check may predate the link, or belong to another install.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/repositories/{repoOwner}/{repoName}/branches/{branch...}',
    area: 'Runs',
    access: 'authorized',
    purpose: 'Deletes runs recorded for a deleted branch.',
    depth: 'full',
    parameters: [
      { name: 'repoOwner', in: 'path', type: 'string', required: true, description: 'Repository owner.', example: 'acme' },
      { name: 'repoName', in: 'path', type: 'string', required: true, description: 'Repository name.', example: 'payments' },
      { name: 'branch', in: 'path', type: 'string', required: true, description: 'Branch name. A catch-all segment, so a branch with slashes is passed as-is.', example: 'feature/new-checkout' },
    ],
    requestSample: {
      title: 'Clear runs for a deleted branch',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  "$NOPSAI_URL/v1/repositories/acme/payments/branches/feature/new-checkout" -w "%{http_code}\\n"',
      expectedOutput: '204. Every run recorded for that branch is removed.',
    },
    responses: [{ status: 204, description: 'Runs for the branch were deleted.', sample: '' }],
    errors: [
      { status: 400, cause: 'The owner, repository, or branch is empty.', action: 'All three segments are required.' },
      { status: 500, cause: 'The delete could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Deletes every run recorded for that branch, with their logs and outputs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/run_status_test.go'],
    evidence: ['services/nopsai/run_handlers.go'],
    notes: 'Housekeeping after a branch is merged and deleted. It is bulk and irreversible: there is no preview.',
  },
];
