import type { WikiApiRoute } from '../../types.js';

const SCHEDULE_RECORD =
  '{\n  "id": "0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44",\n  "path": "platform",\n  "name": "nightly-release-check",\n  "identifier": "platform/nightly-release-check",\n  "pipeline": "platform/release-service",\n  "schedule_kind": "recurring",\n  "cron_expression": "0 2 * * *",\n  "timezone": "Europe/Berlin",\n  "enabled": true,\n  "scope": "platform/production",\n  "run_team_path": "platform/payments",\n  "variables": { "RELEASE_CHANNEL": "stable" }\n}';

/**
 * Schedules.
 *
 * A schedule is a stored intent to run a pipeline: recurring on a cron
 * expression, or once at a moment. It carries its own scope, team path, and
 * variables, so a scheduled run is not the same thing as a manual one.
 */
export const schedulesRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/schedules',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Lists schedules the caller can see.',
    depth: 'full',
    parameters: [
      { name: 'team_path', in: 'query', type: 'string', required: false, description: 'Restrict to schedules owned by one team path.', example: 'team_path=platform/payments' },
      { name: 'enabled', in: 'query', type: 'boolean', required: false, description: 'Restrict to enabled or disabled schedules.', example: 'enabled=false' },
    ],
    requestSample: {
      title: 'List schedules',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules" | jq \'.[] | {identifier, cron_expression, enabled}\'',
      expectedOutput: 'One entry per schedule, filtered to what the caller may see.',
    },
    responses: [{ status: 200, description: 'Schedules visible to the caller.', contentType: 'application/json', sample: '[' + SCHEDULE_RECORD + ']' }],
    errors: [
      { status: 400, cause: 'A filter value cannot be parsed.', action: 'Check `enabled` is a boolean and `team_path` is a real path.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
  },
  {
    method: 'POST',
    path: '/v1/schedules',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Creates a schedule.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a recurring schedule',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/schedules" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"path":"platform","name":"nightly-release-check","pipeline":"platform/release-service","schedule_kind":"recurring","cron_expression":"0 2 * * *","timezone":"Europe/Berlin","scope":"platform/production","enabled":true}\' | jq -r .id',
      expectedOutput: 'The created schedule, including the identifier built from its path and name.',
      placeholders: ['`timezone` is an IANA name. Without it, a cron expression means something different twice a year.'],
    },
    responses: [{ status: 201, description: 'Schedule created.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [
      { status: 400, cause: 'An invalid cron expression, an unknown timezone, a missing pipeline, or a one-time schedule without `run_at`.', action: 'The message names the field that failed.' },
      { status: 403, cause: 'The caller may not schedule this pipeline, or may not use its scope.', action: 'A schedule runs later with the same authorization it was created under, so it is checked now.' },
      { status: 409, cause: 'A schedule with that path and name already exists.', action: 'Update it instead, or pick another name.' },
      { status: 500, cause: 'The schedule could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Registers the next fire time.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
    notes: '`schedule_kind` decides which timing field is read: `recurring` uses `cron_expression`, one-time uses `run_at`.',
  },
  {
    method: 'GET',
    path: '/v1/schedules/{scheduleID}',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Reads one schedule, including its recent runs.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule identifier.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Read a schedule',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID" | jq',
      expectedOutput: 'The schedule with its timing, ownership, variables, and the runs it recently produced.',
    },
    responses: [{ status: 200, description: 'The schedule.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [{ status: 404, cause: 'No schedule with that id.', action: 'Confirm the id from the list route.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
    notes: 'The attached run history is the fastest way to tell "never fired" from "fired and failed".',
  },
  {
    method: 'PUT',
    path: '/v1/schedules/{scheduleID}',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Replaces a schedule definition.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to replace.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Replace a schedule',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @schedule.json | jq',
      expectedOutput: 'The stored schedule after replacement, with a recalculated next fire time.',
      placeholders: ['A PUT replaces the whole document: omitted fields are cleared, not preserved.'],
    },
    responses: [{ status: 200, description: 'Schedule replaced.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [
      { status: 400, cause: 'Invalid timing, timezone, or pipeline reference.', action: 'The message names the field.' },
      { status: 403, cause: 'The caller may not schedule this pipeline or use its scope.', action: 'Authorization is re-checked on every write.' },
      { status: 409, cause: 'The new path and name collide with another schedule.', action: 'Pick a different name.' },
      { status: 500, cause: 'The update could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Recalculates the next fire time.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
  },
  {
    method: 'PATCH',
    path: '/v1/schedules/{scheduleID}',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Partially updates a schedule.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to update.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Move a schedule an hour later',
      language: 'bash',
      code:
        'curl -sX PATCH "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"cron_expression":"0 3 * * *"}\' | jq \'{identifier, cron_expression}\'',
      expectedOutput: 'Only the supplied fields change; the rest of the schedule is untouched.',
    },
    responses: [{ status: 200, description: 'Schedule updated.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [
      { status: 400, cause: 'A supplied field is invalid.', action: 'The message names the field.' },
      { status: 403, cause: 'The caller may not modify this schedule.', action: 'Check ownership of the team path.' },
      { status: 500, cause: 'The update could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Recalculates the next fire time when timing changed.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/schedules/{scheduleID}',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Deletes a schedule.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to delete.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Delete a schedule',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Runs it already produced stay in history.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete could not be persisted.', action: 'Retry.' }],
    sideEffects: ['Stops future fires. Existing runs are untouched.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
    notes: 'Disabling is usually better than deleting while investigating: it stops the fires and keeps the definition and its history.',
  },
  {
    method: 'POST',
    path: '/v1/schedules/{scheduleID}/enable',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Enables a schedule.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to enable.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Enable a schedule',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID/enable" | jq \'{identifier, enabled}\'',
      expectedOutput: 'The schedule with `enabled: true` and a next fire time.',
    },
    responses: [{ status: 200, description: 'Schedule enabled.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [
      { status: 403, cause: 'The caller may not modify this schedule.', action: 'Check team ownership.' },
      { status: 404, cause: 'No schedule with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The change could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Schedules the next fire from now, not from when it was disabled: missed occurrences are not replayed.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
  },
  {
    method: 'POST',
    path: '/v1/schedules/{scheduleID}/disable',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Disables a schedule without deleting it.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to disable.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Disable a schedule',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID/disable" | jq \'{identifier, enabled}\'',
      expectedOutput: 'The schedule with `enabled: false`. It stops firing and keeps its definition and history.',
    },
    responses: [{ status: 200, description: 'Schedule disabled.', contentType: 'application/json', sample: SCHEDULE_RECORD }],
    errors: [
      { status: 403, cause: 'The caller may not modify this schedule.', action: 'Check team ownership.' },
      { status: 404, cause: 'No schedule with that id.', action: 'Confirm the id.' },
      { status: 500, cause: 'The change could not be persisted.', action: 'Retry.' },
    ],
    sideEffects: ['Stops future fires. A run already in flight is not cancelled.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
  },
  {
    method: 'POST',
    path: '/v1/schedules/{scheduleID}/run',
    area: 'Schedules',
    access: 'authorized',
    purpose: 'Runs a schedule now, without waiting for its next fire.',
    depth: 'full',
    parameters: [{ name: 'scheduleID', in: 'path', type: 'uuid', required: true, description: 'Schedule to run.', example: '0f4b9c21-8d33-4e77-8a10-3c6f9b2d5a44' }],
    requestSample: {
      title: 'Fire a schedule immediately',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID/run" | jq',
      expectedOutput: '202 with the run it queued, using the schedule’s scope, team path, and variables.',
    },
    responses: [{ status: 202, description: 'A run was queued from the schedule.', contentType: 'application/json', sample: '{\n  "run_id": "9c1f7a5e-2b44-4d2f-8f2a-2c9f0b6d4e11",\n  "status": "queued"\n}' }],
    errors: [
      { status: 400, cause: 'The id is malformed, or the schedule cannot produce a run — a missing pipeline, for instance.', action: 'Read the schedule first: the same reason would fail its next scheduled fire.' },
      { status: 403, cause: 'The caller may not run this schedule.', action: 'Check team ownership and scope access.' },
      { status: 500, cause: 'The run could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Creates a run as if the schedule had fired.', 'Does not change the next scheduled fire time.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/schedules_test.go'],
    evidence: ['services/nopsai/schedules.go'],
    notes: 'Running now is the cheapest way to test a schedule’s scope and variables without waiting for 2am.',
  },
];
