import type { WikiApiRoute } from '../../types.js';

const TEAM_TREE =
  '[\n  {\n    "id": 12,\n    "name": "platform",\n    "kind": "team",\n    "parent_id": null,\n    "children": [\n      { "id": 18, "name": "payments", "kind": "team", "parent_id": 12, "children": [] }\n    ]\n  }\n]';

const APPLICATION_RECORD =
  '{\n  "id": 31,\n  "name": "payments-api",\n  "kind": "application",\n  "parent_id": 18,\n  "repository_full_name": "acme/payments",\n  "repo_url": "https://git.example.com/acme/payments"\n}';

const MCP_PROFILE =
  '{\n  "name": "jira-readonly",\n  "enabled": true,\n  "allowed_scopes": ["platform/production"],\n  "servers": [{ "server": "jira", "tools": ["search"] }]\n}';

/**
 * Teams.
 *
 * A team path is the ownership boundary every other resource refers to.
 * Underneath it sit applications (repository-backed leaves) and the team-owned
 * AI resources: models, agent roles, and MCP profiles.
 */
export const teamsRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/teams',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Lists the team tree.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Read the team tree',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams" | jq',
      expectedOutput: 'A nested tree. `children` is populated, so one call gives the whole hierarchy.',
    },
    responses: [{ status: 200, description: 'The team tree the caller may see.', contentType: 'application/json', sample: TEAM_TREE }],
    errors: [],
    notes: 'Returns a tree rather than a flat list, so a client walks `children` instead of joining on `parent_id`.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go', 'pkg/models/types.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates a team.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Create a team under another',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"payments","parent_id":12}\' | jq',
      expectedOutput: 'The created team. Omit `parent_id` to create at the root.',
    },
    responses: [{ status: 201, description: 'Team created.', contentType: 'application/json', sample: '{\n  "id": 18,\n  "name": "payments",\n  "kind": "team",\n  "parent_id": 12,\n  "children": []\n}' }],
    errors: [
      { status: 400, cause: 'A missing name, an unusable name, or a parent that does not exist.', action: 'The message names the field.' },
    ],
    sideEffects: ['Creates an ownership boundary other resources can be assigned to.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'The team path is built from the hierarchy, so a team’s position is part of its identity for scopes, grants, and notifications.',
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Reads one team.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Read a team',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID" | jq',
      expectedOutput: 'The team with its children and repository metadata.',
    },
    responses: [{ status: 200, description: 'The team.', contentType: 'application/json', sample: '{\n  "id": 18,\n  "name": "payments",\n  "kind": "team",\n  "parent_id": 12,\n  "children": []\n}' }],
    errors: [{ status: 500, cause: 'The team could not be loaded.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Renames or moves a team.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team to update.', example: '18' }],
    requestSample: {
      title: 'Move a team to the root',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"payments","parent_id":null}\' | jq',
      expectedOutput: 'The updated team. An explicit null parent moves it to Global; omitting the field keeps the current parent.',
      placeholders: ['Omitted parent fields keep the current parent — only an explicit `null` moves a team.'],
    },
    responses: [{ status: 200, description: 'Team updated.', contentType: 'application/json', sample: '{\n  "id": 18,\n  "name": "payments",\n  "kind": "team",\n  "parent_id": null,\n  "children": []\n}' }],
    errors: [
      { status: 400, cause: 'A name collision, or a move that would make the tree cyclic.', action: 'A team cannot become its own descendant.' },
    ],
    sideEffects: [
      'Moving a team changes its path, and with it every scope, grant, and notification that referenced the old path.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'Moving a team is not a cosmetic rename: the path is the identity other resources refer to.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Deletes a team.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team to delete.', example: '18' }],
    requestSample: {
      title: 'Delete a team',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID" -w "%{http_code}\\n"',
      expectedOutput: '204.',
    },
    responses: [{ status: 204, description: 'Team deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Resources that referenced the team path stop resolving their owner.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'Check what the team owns first — pipelines, scopes, dashboards, and grants all hang off its path.',
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/applications',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Lists applications under a team.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'List applications',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/applications" | jq',
      expectedOutput: 'Repository-backed leaves under the team.',
    },
    responses: [{ status: 200, description: 'Applications under the team.', contentType: 'application/json', sample: '[' + APPLICATION_RECORD + ']' }],
    errors: [],
    notes: 'An application is a team whose `kind` is `application`: it owns a repository rather than other teams.',
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/applications',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates an application under a team.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Parent team.', example: '18' }],
    requestSample: {
      title: 'Create an application',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams/$TEAM_ID/applications" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"payments-api","repository_full_name":"acme/payments"}\' | jq',
      expectedOutput: 'The application, now the owner of runs triggered from that repository.',
    },
    responses: [{ status: 201, description: 'Application created.', contentType: 'application/json', sample: APPLICATION_RECORD }],
    errors: [
      { status: 400, cause: 'A missing name or an unusable repository reference.', action: 'The message names the field.' },
      { status: 500, cause: 'The application could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Runs triggered from the repository resolve their owner to this application.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/applications/{applicationID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Updates or moves an application.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Target parent team — moving an application means calling this under the new parent.', example: '18' },
      { name: 'applicationID', in: 'path', type: 'integer', required: true, description: 'Application identifier.', example: '31' },
    ],
    requestSample: {
      title: 'Move an application to another team',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$NEW_TEAM_ID/applications/$APPLICATION_ID" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"payments-api"}\' | jq',
      expectedOutput: 'The application under its new parent. The move is expressed by the team in the URL, not a field in the body.',
    },
    responses: [{ status: 200, description: 'Application updated.', contentType: 'application/json', sample: APPLICATION_RECORD }],
    errors: [
      { status: 400, cause: 'An unusable name or repository reference.', action: 'The message names the field.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes which team owns runs from the repository.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'The target parent is the team in the URL. Sending a parent in the body does not move anything.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/applications/{applicationID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Deletes an application.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Parent team.', example: '18' },
      { name: 'applicationID', in: 'path', type: 'integer', required: true, description: 'Application to delete.', example: '31' },
    ],
    requestSample: {
      title: 'Delete an application',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/applications/$APPLICATION_ID" -w "%{http_code}\\n"',
      expectedOutput: '204. Runs already recorded against it stay.',
    },
    responses: [{ status: 204, description: 'Application deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Repository events lose their owner resolution until another application claims the repository.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/defaults',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Reads a team’s default AI resources.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Read team defaults',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/defaults" | jq',
      expectedOutput: 'The model and agent role a pipeline in this team gets when it names none.',
    },
    responses: [{ status: 200, description: 'Team defaults.', contentType: 'application/json', sample: '{\n  "default_model": "reasoning-large",\n  "default_agent_role": "senior-release-engineer"\n}' }],
    errors: [
      { status: 405, cause: 'A method other than GET or PUT.', action: 'Use GET to read, PUT to set.' },
      { status: 500, cause: 'Defaults could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_resolution_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'Defaults are what a pipeline resolves to when it names no model or agent role. They do not override a pipeline that names one.',
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/defaults',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Sets a team’s default AI resources.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Set team defaults',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/defaults" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"default_model":"reasoning-large"}\' | jq',
      expectedOutput: 'The stored defaults, applied to the team’s next runs.',
    },
    responses: [{ status: 200, description: 'Defaults stored.', contentType: 'application/json', sample: '{\n  "default_model": "reasoning-large"\n}' }],
    errors: [
      { status: 400, cause: 'A profile that does not exist or is not allowed for the team.', action: 'List the team’s models first.' },
      { status: 500, cause: 'The defaults could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what pipelines in this team resolve to when they name nothing.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_resolution_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/notifications',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Reads a team’s notification settings.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Read team notifications',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/notifications" | jq',
      expectedOutput: 'What the team is told about, and where. Delivery itself is configured platform-wide.',
    },
    responses: [{ status: 200, description: 'Notification settings for the team.', contentType: 'application/json', sample: '{\n  "recipients": ["sre@example.com"],\n  "events": ["run.failure", "approval.requested"]\n}' }],
    errors: [{ status: 405, cause: 'A method other than GET, PUT, or DELETE.', action: 'Those three are supported.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'Teams choose what they hear about; the platform decides how it is delivered. The two are configured in different places on purpose.',
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/notifications',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Sets a team’s notification settings.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Subscribe a team to run failures',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/notifications" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"recipients":["sre@example.com"],"events":["run.failure"]}\' | jq',
      expectedOutput: 'The stored settings. Nothing is delivered until platform mail settings work.',
    },
    responses: [{ status: 200, description: 'Settings stored.', contentType: 'application/json', sample: '{\n  "recipients": ["sre@example.com"],\n  "events": ["run.failure"]\n}' }],
    errors: [
      { status: 400, cause: 'An unusable recipient or unknown event.', action: 'The message names the value.' },
      { status: 405, cause: 'An unsupported method.', action: 'Use GET, PUT, or DELETE.' },
    ],
    sideEffects: ['Changes who is emailed about this team’s runs.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
    notes: 'Test platform mail settings before trusting a subscription: a valid subscription with broken delivery looks identical to no subscription.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/notifications',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Clears a team’s notification settings.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Unsubscribe a team',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/notifications" -w "%{http_code}\\n"',
      expectedOutput: 'The team stops being notified.',
    },
    responses: [{ status: 204, description: 'Settings cleared.', sample: '' }],
    errors: [{ status: 405, cause: 'An unsupported method.', action: 'Use GET, PUT, or DELETE.' }],
    sideEffects: ['The team stops receiving notifications.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_handlers_test.go'],
    evidence: ['services/nopsai/team_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/models',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Lists a team’s model profiles.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'List team models',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/models" | jq',
      expectedOutput: 'The team’s own profiles plus the inherited ones it may use.',
    },
    responses: [
      { status: 200, description: 'Model profiles available to the team.', contentType: 'application/json', sample: '[\n  {\n    "name": "reasoning-large",\n    "provider": "anthropic",\n    "enabled": true,\n    "is_default": true\n  }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'The list includes cached team-owned profiles and what the team inherits, which is why a profile can appear here without being defined here.',
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/models',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Replaces a team’s model profile set.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Replace the team’s models',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/models" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @models.json | jq',
      expectedOutput: 'The stored set. Omitted profiles are removed.',
      placeholders: ['`models.json` is the full profile list for this team.'],
    },
    responses: [{ status: 200, description: 'Profiles stored.', contentType: 'application/json', sample: '[\n  { "name": "reasoning-large", "provider": "anthropic", "enabled": true }\n]' }],
    errors: [
      { status: 400, cause: 'An invalid profile or a credential reference that does not resolve.', action: 'The message names the profile.' },
      { status: 500, cause: 'The profiles could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Pipelines naming a removed profile fail authorization on their next run.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/models/default',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Sets the team’s default model profile.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Set the default model',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/models/default" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name":"reasoning-large"}\' | jq',
      expectedOutput: 'The default a pipeline resolves to when it names no model.',
    },
    responses: [{ status: 200, description: 'Default set.', contentType: 'application/json', sample: '{ "name": "reasoning-large", "is_default": true }' }],
    errors: [
      { status: 400, cause: 'The profile does not exist or is disabled.', action: 'List the team’s models first.' },
      { status: 500, cause: 'The default could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what unnamed model references resolve to.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_resolution_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'The path segment is the literal word `default`, which is why a profile may not be named `default`.',
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/models/{profileName}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates or replaces one team model profile.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'reasoning-large' },
    ],
    requestSample: {
      title: 'Upsert one model profile',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/models/reasoning-large" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @profile.json | jq',
      expectedOutput: 'The stored profile, leaving the team’s other profiles untouched.',
      placeholders: ['`profile.json` carries the provider, model, and credential reference.'],
    },
    responses: [{ status: 200, description: 'Profile stored.', contentType: 'application/json', sample: '{ "name": "reasoning-large", "provider": "anthropic", "enabled": true }' }],
    errors: [
      { status: 400, cause: 'An invalid profile or unresolvable credential.', action: 'The message names the field.' },
      { status: 500, cause: 'The profile could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'Use this rather than the collection PUT when changing one profile: the collection form removes anything it omits.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/models/{profileName}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Deletes a team model profile.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to delete.', example: 'reasoning-large' },
    ],
    requestSample: {
      title: 'Delete a model profile',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/models/reasoning-large" -w "%{http_code}\\n"',
      expectedOutput: 'Pipelines naming it fail authorization on their next run.',
    },
    responses: [{ status: 204, description: 'Profile deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Pipelines referencing the profile stop resolving it.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/agent-roles',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Lists a team’s agent roles.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'List team agent roles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles" | jq',
      expectedOutput: 'The personas a pipeline in this team may name.',
    },
    responses: [
      { status: 200, description: 'Agent roles available to the team.', contentType: 'application/json', sample: '[\n  { "id": "senior-release-engineer", "name": "Senior release engineer", "enabled": true }\n]' },
    ],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/agent-roles',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates a team agent role.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Create an agent role',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @role.json | jq -r .id',
      expectedOutput: 'The created role, ready to name from `agent_role` in a pipeline or step.',
      placeholders: ['`role.json` carries the display name and instructions.'],
    },
    responses: [{ status: 201, description: 'Agent role created.', contentType: 'application/json', sample: '{ "id": "senior-release-engineer", "name": "Senior release engineer", "enabled": true }' }],
    errors: [
      { status: 400, cause: 'A missing name or instructions.', action: 'The message names the field.' },
      { status: 500, cause: 'The role could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'A task cannot set `agent_role`; it comes from the pipeline or the step. Creating one here makes it nameable at those two levels.',
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/agent-roles/{profileID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Reads one team agent role.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role identifier.', example: 'senior-release-engineer' },
    ],
    requestSample: {
      title: 'Read an agent role',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles/senior-release-engineer" | jq',
      expectedOutput: 'The role with its instructions, which become part of the prompt for steps that name it.',
    },
    responses: [{ status: 200, description: 'The agent role.', contentType: 'application/json', sample: '{ "id": "senior-release-engineer", "name": "Senior release engineer", "enabled": true }' }],
    errors: [{ status: 500, cause: 'The role could not be loaded.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/agent-roles/{profileID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Replaces a team agent role.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role identifier.', example: 'senior-release-engineer' },
    ],
    requestSample: {
      title: 'Update an agent role',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles/senior-release-engineer" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @role.json | jq',
      expectedOutput: 'The stored role. Runs already executing keep the instructions they started with.',
    },
    responses: [{ status: 200, description: 'Role stored.', contentType: 'application/json', sample: '{ "id": "senior-release-engineer", "name": "Senior release engineer", "enabled": true }' }],
    errors: [
      { status: 400, cause: 'Invalid instructions or a disabled state that conflicts with the team default.', action: 'The message names the field.' },
      { status: 500, cause: 'The update failed.', action: 'Retry.' },
    ],
    sideEffects: ['Changes the prompt for every future step naming this role.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/agent-roles/default',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Sets the team’s default agent role.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Set the default agent role',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles/default" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"id":"senior-release-engineer"}\' | jq',
      expectedOutput: 'The role a pipeline resolves to when it names none.',
    },
    responses: [{ status: 200, description: 'Default set.', contentType: 'application/json', sample: '{ "id": "senior-release-engineer", "is_default": true }' }],
    errors: [
      { status: 400, cause: 'The role does not exist or is disabled.', action: 'List the team’s agent roles first.' },
      { status: 500, cause: 'The default could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what unnamed agent role references resolve to.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_resolution_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'As with models, `default` is a literal path segment rather than a role id.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/agent-roles/{profileID}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Deletes a team agent role.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileID', in: 'path', type: 'string', required: true, description: 'Agent role to delete.', example: 'senior-release-engineer' },
    ],
    requestSample: {
      title: 'Delete an agent role',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/agent-roles/senior-release-engineer" -w "%{http_code}\\n"',
      expectedOutput: 'Pipelines naming it fail to resolve it on their next run.',
    },
    responses: [{ status: 204, description: 'Role deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Pipelines referencing the role stop resolving it.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/mcp-profiles',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Lists a team’s MCP profiles.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'List team MCP profiles',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/mcp-profiles" | jq',
      expectedOutput: 'The tool sets a pipeline in this team may name in `mcp_profiles`.',
    },
    responses: [{ status: 200, description: 'MCP profiles available to the team.', contentType: 'application/json', sample: '[' + MCP_PROFILE + ']' }],
    errors: [{ status: 500, cause: 'The query failed.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'A profile names servers and the tools allowed from them. Pipeline YAML cannot declare a server URL directly, which is why this list is the boundary.',
  },
  {
    method: 'POST',
    path: '/v1/teams/{teamID}/mcp-profiles',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates a team MCP profile.',
    depth: 'full',
    parameters: [{ name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' }],
    requestSample: {
      title: 'Create an MCP profile',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/teams/$TEAM_ID/mcp-profiles" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @profile.json | jq',
      expectedOutput: 'The created profile, nameable from `mcp_profiles` in a pipeline, step, or goal task.',
      placeholders: ['`profile.json` names the servers and the tools allowed from each.'],
    },
    responses: [{ status: 201, description: 'Profile created.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [
      { status: 400, cause: 'An unknown server, an empty tool list, or a scope the team may not use.', action: 'The message names the field.' },
      { status: 500, cause: 'The profile could not be created.', action: 'Retry.' },
    ],
    sideEffects: ['Widens what LLM steps in this team can reach.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/teams/{teamID}/mcp-profiles/{profileName}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Reads one team MCP profile.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'jira-readonly' },
    ],
    requestSample: {
      title: 'Read an MCP profile',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/mcp-profiles/jira-readonly" | jq',
      expectedOutput: 'The servers and tools the profile permits.',
    },
    responses: [{ status: 200, description: 'The profile.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [{ status: 500, cause: 'The profile could not be loaded.', action: 'Platform fault.' }],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/teams/{teamID}/mcp-profiles/{profileName}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Creates or replaces a team MCP profile.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile name.', example: 'jira-readonly' },
    ],
    requestSample: {
      title: 'Upsert an MCP profile',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/teams/$TEAM_ID/mcp-profiles/jira-readonly" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @profile.json | jq',
      expectedOutput: 'The stored profile. Narrowing its tools narrows every pipeline that names it.',
    },
    responses: [{ status: 200, description: 'Profile stored.', contentType: 'application/json', sample: MCP_PROFILE }],
    errors: [
      { status: 400, cause: 'An invalid server or tool list.', action: 'The message names the field.' },
      { status: 500, cause: 'The profile could not be stored.', action: 'Retry.' },
    ],
    sideEffects: ['Changes what every pipeline naming this profile can reach.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
    notes: 'Profiles are additive at run time: a step cannot narrow what the pipeline granted. Narrowing happens here.',
  },
  {
    method: 'DELETE',
    path: '/v1/teams/{teamID}/mcp-profiles/{profileName}',
    area: 'Teams',
    access: 'authorized',
    purpose: 'Deletes a team MCP profile.',
    depth: 'full',
    parameters: [
      { name: 'teamID', in: 'path', type: 'integer', required: true, description: 'Team identifier.', example: '18' },
      { name: 'profileName', in: 'path', type: 'string', required: true, description: 'Profile to delete.', example: 'jira-readonly' },
    ],
    requestSample: {
      title: 'Delete an MCP profile',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/mcp-profiles/jira-readonly" -w "%{http_code}\\n"',
      expectedOutput: 'Pipelines naming it fail authorization on their next run.',
    },
    responses: [{ status: 204, description: 'Profile deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['LLM steps naming the profile lose those tools.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/team_profile_handlers_test.go'],
    evidence: ['services/nopsai/team_profile_handlers.go'],
  },
  { method: 'GET', path: '/v1/teams/{teamID}/mcp/profiles', area: 'Teams', access: 'authorized', purpose: 'Compatibility path for listing team MCP profiles.', notes: 'Same handler as /v1/teams/{teamID}/mcp-profiles; prefer the hyphenated form.' },
  { method: 'POST', path: '/v1/teams/{teamID}/mcp/profiles', area: 'Teams', access: 'authorized', purpose: 'Compatibility path for creating a team MCP profile.', notes: 'Same handler as the hyphenated form.' },
  { method: 'GET', path: '/v1/teams/{teamID}/mcp/profiles/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Compatibility path for reading a team MCP profile.', notes: 'Same handler as the hyphenated form.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/mcp/profiles/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Compatibility path for replacing a team MCP profile.', notes: 'Same handler as the hyphenated form.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/mcp/profiles/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Compatibility path for deleting a team MCP profile.', notes: 'Same handler as the hyphenated form.' },
];
