import type { WikiApiRoute } from '../../types.js';

const CREDENTIAL =
  '{\n  "id": "d61a4b02-7c39-4e58-9a11-40b2c7e35f18",\n  "reference": "platform/anthropic",\n  "kind": "api_key",\n  "status": "enabled",\n  "has_value": true,\n  "active_version": 3,\n  "last_rotated_at": "2026-08-12T09:20:41Z",\n  "managed_by_config_repo": false\n}';

const CRED_ID = { name: 'credentialID', in: 'path' as const, type: 'uuid', required: true, description: 'Credential identifier.', example: 'd61a4b02-7c39-4e58-9a11-40b2c7e35f18' };

const VERSION = { name: 'version', in: 'path' as const, type: 'integer', required: true, description: 'Credential version number.', example: '2' };

const REPO_OWNER = { name: 'repoOwner', in: 'path' as const, type: 'string', required: true, description: 'Repository owner.', example: 'acme' };

const REPO_NAME = { name: 'repoName', in: 'path' as const, type: 'string', required: true, description: 'Repository name.', example: 'payments' };

const SCOPE_LIST = '[\n  { "scope": "platform/production" },\n  { "scope": "platform/shared" }\n]';

/**
 * Variables and secrets.
 *
 * Three separate stores share this area. Runtime variables and secrets resolve
 * per scope for a run; repository-scoped values belong to one repository; and
 * the credential store holds versioned platform credentials whose values the API
 * never returns.
 *
 * A scope secret is not write-only: `GET /v1/secrets/{secretName}` decrypts and
 * returns the value to a caller holding `secret.read_value` on that secret. The
 * credential store behaves differently and returns metadata only.
 */
export const variables_and_secretsRoutes: WikiApiRoute[] = [
  {
    method: 'GET',
    path: '/v1/variables',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists runtime variables in a scope.',
    depth: 'full',
    permission: 'variable.list',
    parameters: [
      { name: 'scope', in: 'query', type: 'string', required: false, defaultValue: 'the default scope', description: 'Scope to list. Values are stored per scope, so the same name can exist in several.', example: 'scope=platform/production' },
      { name: 'include_source', in: 'query', type: 'boolean', required: false, defaultValue: 'false', description: 'Include whether each value came from the database or a configuration repository.', example: 'include_source=true' },
    ],
    requestSample: {
      title: 'List variables in a scope',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/variables?scope=platform/production&include_source=true" | jq',
      expectedOutput: 'Variable names and values for that scope. Variables are configuration, not credentials, so values are listed.',
    },
    responses: [
      { status: 200, description: 'Variables in the requested scope.', contentType: 'application/json', sample: '[\n  {\n    "name": "RELEASE_CHANNEL",\n    "value": "stable",\n    "scope": "platform/production",\n    "source": "database",\n    "updated_at": "2026-08-19T09:12:44Z"\n  }\n]' },
    ],
    errors: [
      { status: 503, cause: 'Authorization is unavailable, so the list cannot be filtered.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'Variable values are readable by design. Anything that should not be is a secret, not a variable.',
  },
  {
    method: 'GET',
    path: '/v1/variables/scopes',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists the scopes that hold variables.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'List variable scopes',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/variables/scopes" | jq',
      expectedOutput: 'Every scope the caller may see that holds at least one variable.',
    },
    responses: [{ status: 200, description: 'Scopes holding variables.', contentType: 'application/json', sample: SCOPE_LIST }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'Useful before writing a value: a typo in a scope name creates a new scope silently rather than failing.',
  },
  {
    method: 'GET',
    path: '/v1/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Reads one variable value.',
    depth: 'full',
    parameters: [
      { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable name. Must match `^[A-Za-z0-9_.-]+$`.', example: 'RELEASE_CHANNEL' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to read from.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Read a variable',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/variables/RELEASE_CHANNEL?scope=platform/production" | jq -r .value',
      expectedOutput: 'The stored value for that scope.',
    },
    responses: [{ status: 200, description: 'The variable value.', contentType: 'application/json', sample: '{"value":"stable"}' }],
    errors: [
      { status: 404, cause: 'No variable with that name in that scope.', action: 'Check the scope: the same name in another scope is a different variable.' },
      { status: 500, cause: 'The read failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Creates or replaces a variable in a scope.',
    depth: 'full',
    parameters: [
      { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable name.', example: 'RELEASE_CHANNEL' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to write into. An unknown scope is created rather than rejected.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Set a variable',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/variables/RELEASE_CHANNEL?scope=platform/production" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"value":"stable"}\'',
      expectedOutput: '201. The body carries only `value`; the name and scope come from the path and query.',
    },
    responses: [{ status: 201, description: 'Stored, for both create and replace.', contentType: 'application/json', sample: '{"name":"RELEASE_CHANNEL","scope":"platform/production","source":"database"}' }],
    errors: [
      { status: 400, cause: 'The body is not valid JSON, or the name is unusable.', action: 'Send `{"value": "..."}` and a name matching `^[A-Za-z0-9_.-]+$`.' },
      { status: 500, cause: 'The write failed.', action: 'Retry.' },
    ],
    sideEffects: [
      'Marks the value as database-owned, which takes it out of GitOps management until the configuration repository is reconciled.',
      'Writes an audit record.',
    ],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'Writing over a GitOps-managed variable makes the database the owner. The next config sync reports drift rather than silently restoring Git.',
  },
  {
    method: 'DELETE',
    path: '/v1/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a variable from a scope.',
    depth: 'full',
    parameters: [
      { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable to delete.', example: 'RELEASE_CHANNEL' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to delete from.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Delete a variable',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/variables/RELEASE_CHANNEL?scope=platform/production" -w "%{http_code}\\n"',
      expectedOutput: '204, whether or not the variable existed.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Pipelines that declare the variable fail before execution until it resolves again.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'Deleting is silent about whether anything was there. Read it first if you need to know.',
  },
  {
    method: 'GET',
    path: '/v1/secrets',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists secret names and metadata in a scope.',
    depth: 'full',
    permission: 'secret.list_metadata',
    parameters: [
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to list.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'List secrets in a scope',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/secrets?scope=platform/production" | jq',
      expectedOutput: 'Names and metadata only. This route never returns values, whatever the caller holds.',
    },
    responses: [
      { status: 200, description: 'Secret metadata for the scope.', contentType: 'application/json', sample: '[\n  {\n    "name": "REGISTRY_TOKEN",\n    "scope": "platform/production",\n    "source": "database",\n    "updated_at": "2026-08-19T09:15:02Z"\n  }\n]' },
    ],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go', 'services/nopsai/pkg/routeauthz/routeauthz.go'],
    notes: 'Listing needs `secret.list_metadata`, which is a weaker action than reading a value. The two are granted separately on purpose.',
  },
  {
    method: 'GET',
    path: '/v1/secrets/scopes',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists the scopes that hold secrets.',
    depth: 'full',
    permission: 'secret.list_metadata',
    parameters: [],
    requestSample: {
      title: 'List secret scopes',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/secrets/scopes" | jq',
      expectedOutput: 'Scope names only, no secret names and no values.',
    },
    responses: [{ status: 200, description: 'Scopes holding secrets.', contentType: 'application/json', sample: SCOPE_LIST }],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/secrets/{secretName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Reads and decrypts one secret value.',
    depth: 'full',
    permission: 'secret.read_value',
    parameters: [
      { name: 'secretName', in: 'path', type: 'string', required: true, description: 'Secret name.', example: 'REGISTRY_TOKEN' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to read from.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Read a secret value',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/secrets/REGISTRY_TOKEN?scope=platform/production" | jq -r .value',
      expectedOutput: 'The decrypted value — for a caller holding `secret.read_value` on that secret, and only for them.',
    },
    responses: [{ status: 200, description: 'The decrypted secret value.', contentType: 'application/json', sample: '{"value":"<the stored secret>"}' }],
    errors: [
      { status: 400, cause: 'No secret name in the path.', action: 'Name the secret.' },
      { status: 403, cause: 'The caller does not hold `secret.read_value` on this secret.', action: 'This is the action that governs recovering a stored credential. Grant it deliberately.' },
      { status: 404, cause: 'No secret with that name in that scope.', action: 'Check the scope.' },
      { status: 409, cause: 'The secret exists but has no value set.', action: 'Write a value before reading one.' },
      { status: 500, cause: 'Decryption failed, which usually means the master key changed.', action: 'Restore the original `NOPSAI_MASTER_KEY` or rotate the secret.' },
    ],
    sideEffects: ['Writes an audit record naming the caller and the secret. Reading a secret is an audited event, not a silent one.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go', 'services/nopsai/pkg/routeauthz/routeauthz.go'],
    notes: 'This route is the reason `secret.read_value` exists as a separate action from `secret.list_metadata` and `secret.write_value`. Anyone holding it can recover any secret in scope.',
  },
  {
    method: 'PUT',
    path: '/v1/secrets/{secretName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Creates or replaces a secret value.',
    depth: 'full',
    permission: 'secret.write_value',
    parameters: [
      { name: 'secretName', in: 'path', type: 'string', required: true, description: 'Secret name. Must match `^[A-Za-z0-9_.-]+$`.', example: 'REGISTRY_TOKEN' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to write into.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Store a secret',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/secrets/REGISTRY_TOKEN?scope=platform/production" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"value\\":\\"$TOKEN\\"}"',
      expectedOutput: '201. The value is encrypted with the master key before it is stored.',
      placeholders: ['`$TOKEN` is the secret material; keep it out of shell history.'],
    },
    responses: [{ status: 201, description: 'Stored, for both create and replace.', contentType: 'application/json', sample: '{"name":"REGISTRY_TOKEN","scope":"platform/production","source":"database"}' }],
    errors: [
      { status: 400, cause: 'The body is not valid JSON or the name is unusable.', action: 'Send `{"value": "..."}`.' },
      { status: 500, cause: 'Encryption or storage failed.', action: 'Retry. A failed write leaves the previous value in place.' },
    ],
    sideEffects: ['Encrypts with `NOPSAI_MASTER_KEY` before storage.', 'Takes the value out of GitOps ownership until reconciled.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/secrets/{secretName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a secret from a scope.',
    depth: 'full',
    permission: 'secret.delete',
    parameters: [
      { name: 'secretName', in: 'path', type: 'string', required: true, description: 'Secret to delete.', example: 'REGISTRY_TOKEN' },
      { name: 'scope', in: 'query', type: 'string', required: false, description: 'Scope to delete from.', example: 'scope=platform/production' },
    ],
    requestSample: {
      title: 'Delete a secret',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/secrets/REGISTRY_TOKEN?scope=platform/production" -w "%{http_code}\\n"',
      expectedOutput: '204. Steps declaring the secret fail to resolve on their next run.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Removes the encrypted value permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/secrets/encrypt',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Encrypts a value into a GitOps-safe envelope.',
    depth: 'full',
    permission: 'secret.write_value',
    parameters: [],
    requestSample: {
      title: 'Encrypt a value for a configuration repository',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/secrets/encrypt" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"value\\":\\"$TOKEN\\"}" | jq -r .encrypted',
      expectedOutput: 'An envelope that is safe to commit and resolves at run time on this install.',
      placeholders: ['`$TOKEN` is the plaintext to protect.'],
    },
    responses: [{ status: 200, description: 'The encrypted envelope.', contentType: 'application/json', sample: '{"encrypted":"enc:v1:9f2c..."}' }],
    errors: [
      { status: 400, cause: 'The body carries no value.', action: 'Send `{"value": "..."}`.' },
      { status: 500, cause: 'Encryption failed.', action: 'Check that `NOPSAI_MASTER_KEY` is configured.' },
    ],
    sideEffects: ['Stores nothing. The envelope is returned and forgotten.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'The envelope is bound to this install’s master key. Another install cannot decrypt it, which is what makes committing it safe and what makes the key a restore dependency.',
  },
  {
    method: 'GET',
    path: '/v1/system/credentials',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists platform credentials. Metadata only.',
    depth: 'full',
    parameters: [
      { name: 'kind', in: 'query', type: 'string', required: false, description: 'Restrict to one credential kind.', example: 'kind=api_key' },
    ],
    requestSample: {
      title: 'List credentials',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials" | jq \'.[] | {reference, kind, status, active_version}\'',
      expectedOutput: 'References, kinds, and rotation state. Unlike a scope secret, no route returns a credential value.',
    },
    responses: [{ status: 200, description: 'Credential metadata.', contentType: 'application/json', sample: '[' + CREDENTIAL + ']' }],
    errors: [
      { status: 401, cause: 'No usable caller identity.', action: 'Send a token.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go', 'services/nopsai/credential_models.go'],
    notes: '`has_value` answers "is this configured?" without exposing anything. That is the whole read surface for a credential value.',
  },
  {
    method: 'POST',
    path: '/v1/system/credentials',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Creates a platform credential.',
    depth: 'full',
    parameters: [],
    requestSample: {
      title: 'Store a provider API key',
      language: 'bash',
      code:
        'curl -sX POST "$NOPSAI_URL/v1/system/credentials" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"reference\\":\\"platform/anthropic\\",\\"kind\\":\\"api_key\\",\\"value\\":\\"$API_KEY\\"}" | jq \'{id, reference, has_value}\'',
      expectedOutput: 'The credential record. The value is stored encrypted and never returned again.',
      placeholders: ['`reference` is what other resources name — a model profile, an MCP server, a Git connection.'],
    },
    responses: [{ status: 201, description: 'Credential created.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [
      { status: 400, cause: 'A missing reference, an unknown kind, or an empty value.', action: 'The message names the field.' },
      { status: 401, cause: 'No usable caller identity.', action: 'Send a token.' },
      { status: 403, cause: 'The caller may not create credentials.', action: 'Credential creation is separately authorized from reading metadata.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
    ],
    sideEffects: ['Encrypts the value with the master key and stores it as version 1.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
    notes: 'A credential is referenced by name from everywhere else, which is what keeps provider keys out of pipeline YAML and out of profile documents.',
  },
  {
    method: 'GET',
    path: '/v1/system/credentials/{credentialID}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Reads credential metadata and version history. The value is never returned.',
    depth: 'full',
    parameters: [CRED_ID],
    requestSample: {
      title: 'Read a credential and its versions',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID" | jq',
      expectedOutput: 'Metadata plus the version list — which version is active, and what is available to roll back to.',
    },
    responses: [{ status: 200, description: 'Credential metadata and versions.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [
      { status: 403, cause: 'The caller may not read this credential.', action: 'Metadata access is authorized per credential.' },
      { status: 404, cause: 'No credential with that id.', action: 'List the credentials.' },
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The versions could not be loaded.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/system/credentials/{credentialID}/value',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Rotates a credential by adding a new version.',
    depth: 'full',
    parameters: [CRED_ID],
    requestSample: {
      title: 'Rotate a credential',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/value" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"value\\":\\"$NEW_KEY\\"}" | jq \'{active_version, last_rotated_at}\'',
      expectedOutput: 'A new version becomes active. The previous versions remain, which is what makes a bad rotation recoverable.',
    },
    responses: [{ status: 200, description: 'Rotated; the new version is active.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [
      { status: 400, cause: 'An empty value or an unusable credential id.', action: 'Send `{"value": "..."}`.' },
    ],
    sideEffects: ['Adds a version and activates it. Everything referencing the credential uses the new value on its next call.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go', 'doc/credential-management.md'],
    notes: 'Rotation is additive rather than destructive, which is the difference between this and a scope secret: a bad rotation is undone by activating the previous version.',
  },
  {
    method: 'POST',
    path: '/v1/system/credentials/{credentialID}/versions/{version}/activate',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Activates a stored credential version.',
    depth: 'full',
    parameters: [CRED_ID, VERSION],
    requestSample: {
      title: 'Roll back a bad rotation',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/versions/2/activate" | jq \'{active_version}\'',
      expectedOutput: 'The named version becomes active immediately.',
    },
    responses: [{ status: 200, description: 'Version activated.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [
      { status: 400, cause: 'An unknown version or a malformed id.', action: 'Read the version list first.' },
    ],
    sideEffects: ['Everything referencing the credential uses this version on its next call.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
    notes: 'This is the rollback path. Test the provider afterwards — an older key may itself have been revoked at the provider.',
  },
  {
    method: 'DELETE',
    path: '/v1/system/credentials/{credentialID}/versions/{version}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a credential version.',
    depth: 'full',
    parameters: [CRED_ID, VERSION],
    requestSample: {
      title: 'Remove a superseded version',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/versions/1" -w "%{http_code}\\n"',
      expectedOutput: 'The version is gone permanently, which removes it as a rollback target.',
    },
    responses: [{ status: 200, description: 'Version deleted.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [
      { status: 400, cause: 'The version is active, or does not exist.', action: 'Activate another version before deleting this one.' },
    ],
    sideEffects: ['Removes a rollback target permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/credentials/{credentialID}/enable',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Enables a disabled credential.',
    depth: 'full',
    parameters: [CRED_ID],
    requestSample: {
      title: 'Enable a credential',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/enable" | jq \'{reference, status}\'',
      expectedOutput: 'Resources referencing it start resolving again.',
    },
    responses: [{ status: 200, description: 'Credential enabled.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [],
    notes: 'Enabling does not validate the value against the provider. Run the relevant test route afterwards.',
    sideEffects: ['Resources referencing the credential resolve it again.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
  },
  {
    method: 'POST',
    path: '/v1/system/credentials/{credentialID}/disable',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Disables a credential without deleting it.',
    depth: 'full',
    parameters: [CRED_ID],
    requestSample: {
      title: 'Disable a leaked credential',
      language: 'bash',
      code: 'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/disable" | jq \'{reference, status}\'',
      expectedOutput: 'Everything referencing it stops resolving immediately, while the versions stay for investigation.',
    },
    responses: [{ status: 200, description: 'Credential disabled.', contentType: 'application/json', sample: CREDENTIAL }],
    errors: [],
    notes: 'The containment step for a suspected leak: disable first, rotate second, delete last. Disabling keeps the history an investigation needs.',
    sideEffects: ['Model profiles, MCP servers, and Git connections referencing it fail to resolve.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/system/credentials/{credentialID}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a credential and all its versions.',
    depth: 'full',
    parameters: [CRED_ID],
    requestSample: {
      title: 'Delete a credential',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID" -w "%{http_code}\\n"',
      expectedOutput: '204, unless something still references it.',
    },
    responses: [{ status: 204, description: 'Credential deleted.', sample: '' }],
    errors: [
      { status: 409, cause: 'A profile, server, or connection still references the credential.', action: 'The platform refuses rather than breaking them. Repoint the dependants first.' },
      { status: 500, cause: 'The delete failed.', action: 'Retry.' },
    ],
    sideEffects: ['Removes every version permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/credential_service_test.go'],
    evidence: ['services/nopsai/credential_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/repositories/{repoOwner}/{repoName}/secrets',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists repository-scoped secret names. Metadata only.',
    depth: 'full',
    permission: 'secret.list_metadata',
    parameters: [REPO_OWNER, REPO_NAME],
    requestSample: {
      title: 'List repository secrets',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/secrets" | jq',
      expectedOutput: 'Names and metadata for secrets bound to this repository rather than to a scope.',
    },
    responses: [
      { status: 200, description: 'Repository secret metadata.', contentType: 'application/json', sample: '[\n  { "name": "DEPLOY_KEY", "repository_name": "acme/payments", "source": "database" }\n]' },
    ],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
    notes: 'Repository-scoped values are resolved for runs triggered from that repository. A scope secret and a repository secret with the same name are different values.',
  },
  {
    method: 'PUT',
    path: '/v1/repositories/{repoOwner}/{repoName}/secrets/{secretName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Creates or replaces a repository-scoped secret value.',
    depth: 'full',
    permission: 'secret.write_value',
    parameters: [REPO_OWNER, REPO_NAME, { name: 'secretName', in: 'path', type: 'string', required: true, description: 'Secret name.', example: 'DEPLOY_KEY' }],
    requestSample: {
      title: 'Store a repository secret',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/repositories/acme/payments/secrets/DEPLOY_KEY" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d "{\\"value\\":\\"$DEPLOY_KEY\\"}"',
      expectedOutput: '201. Encrypted with the master key, exactly as a scope secret is.',
    },
    responses: [{ status: 201, description: 'Stored.', contentType: 'application/json', sample: '{ "name": "DEPLOY_KEY", "repository_name": "acme/payments", "source": "database" }' }],
    errors: [
      { status: 400, cause: 'The body is not valid JSON or the name is unusable.', action: 'Send `{"value": "..."}`.' },
      { status: 500, cause: 'Encryption or storage failed.', action: 'Retry.' },
    ],
    sideEffects: ['Encrypts with the master key before storage.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/repositories/{repoOwner}/{repoName}/secrets/{secretName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a repository-scoped secret.',
    depth: 'full',
    permission: 'secret.delete',
    parameters: [REPO_OWNER, REPO_NAME, { name: 'secretName', in: 'path', type: 'string', required: true, description: 'Secret to delete.', example: 'DEPLOY_KEY' }],
    requestSample: {
      title: 'Delete a repository secret',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/secrets/DEPLOY_KEY" -w "%{http_code}\\n"',
      expectedOutput: '204. Steps declaring it fail to resolve on their next run from that repository.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Removes the encrypted value permanently.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/repositories/{repoOwner}/{repoName}/variables',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Lists repository-scoped variables.',
    depth: 'full',
    parameters: [REPO_OWNER, REPO_NAME],
    requestSample: {
      title: 'List repository variables',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/variables" | jq',
      expectedOutput: 'Variables bound to this repository, with their values.',
    },
    responses: [
      { status: 200, description: 'Repository variables.', contentType: 'application/json', sample: '[\n  { "name": "DEPLOY_ENVIRONMENT", "value": "staging", "repository_name": "acme/payments" }\n]' },
    ],
    errors: [
      { status: 503, cause: 'Authorization is unavailable.', action: 'Check AAA.' },
      { status: 500, cause: 'The query failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'GET',
    path: '/v1/repositories/{repoOwner}/{repoName}/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Reads one repository-scoped variable value.',
    depth: 'full',
    parameters: [REPO_OWNER, REPO_NAME, { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable name.', example: 'DEPLOY_ENVIRONMENT' }],
    requestSample: {
      title: 'Read a repository variable',
      language: 'bash',
      code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/variables/DEPLOY_ENVIRONMENT" | jq -r .value',
      expectedOutput: 'The stored value for that repository.',
    },
    responses: [{ status: 200, description: 'The variable value.', contentType: 'application/json', sample: '{"value":"staging"}' }],
    errors: [
      { status: 404, cause: 'No variable with that name for this repository.', action: 'A scope variable of the same name is a different value.' },
      { status: 500, cause: 'The read failed.', action: 'Platform fault.' },
    ],
    sideEffects: ['None.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'PUT',
    path: '/v1/repositories/{repoOwner}/{repoName}/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Creates or replaces a repository-scoped variable.',
    depth: 'full',
    parameters: [REPO_OWNER, REPO_NAME, { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable name.', example: 'DEPLOY_ENVIRONMENT' }],
    requestSample: {
      title: 'Set a repository variable',
      language: 'bash',
      code:
        'curl -sX PUT "$NOPSAI_URL/v1/repositories/acme/payments/variables/DEPLOY_ENVIRONMENT" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"value":"staging"}\'',
      expectedOutput: '201. The body carries only `value`; the name and repository come from the path.',
    },
    responses: [{ status: 201, description: 'Stored.', contentType: 'application/json', sample: '{ "name": "DEPLOY_ENVIRONMENT", "repository_name": "acme/payments", "source": "database" }' }],
    errors: [
      { status: 400, cause: 'The body is not valid JSON or the name is unusable.', action: 'Send `{"value": "..."}`.' },
      { status: 500, cause: 'The write failed.', action: 'Retry.' },
    ],
    sideEffects: ['Marks the value database-owned, taking it out of GitOps management until reconciled.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
  {
    method: 'DELETE',
    path: '/v1/repositories/{repoOwner}/{repoName}/variables/{variableName}',
    area: 'Variables and secrets',
    access: 'authorized',
    purpose: 'Deletes a repository-scoped variable.',
    depth: 'full',
    parameters: [REPO_OWNER, REPO_NAME, { name: 'variableName', in: 'path', type: 'string', required: true, description: 'Variable to delete.', example: 'DEPLOY_ENVIRONMENT' }],
    requestSample: {
      title: 'Delete a repository variable',
      language: 'bash',
      code: 'curl -sX DELETE -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/repositories/acme/payments/variables/DEPLOY_ENVIRONMENT" -w "%{http_code}\\n"',
      expectedOutput: '204, whether or not the variable existed.',
    },
    responses: [{ status: 204, description: 'Deleted.', sample: '' }],
    errors: [{ status: 500, cause: 'The delete failed.', action: 'Retry.' }],
    sideEffects: ['Pipelines declaring the variable fail before execution until it resolves again.', 'Writes an audit record.'],
    coveringTests: ['services/nopsai/secrets_variables_handlers_test.go'],
    evidence: ['services/nopsai/secrets_variables_handlers.go'],
  },
];
