gemini_api_key: "AIzaSyCdyZBcvjWrroxGem8l0ER62WNPlg8s7xU"
llm_model_name: "gemini-2.5-flash"
verbose: true
llm_max_output_tokens: 8192
llm_temperature: 2
executor_runtime: "docker" # Can be "docker" or "local"
