// main.go
package main

import (
	"fmt"
	"log"
	"nopsai/config"
	"nopsai/executor"
	"nopsai/llm"
	"nopsai/pipeline"
	"os"
	"regexp"
	"strings"
	"sync"
)

const defaultGeminiModel = "gemini-1.5-flash"

type StepState string

const (
	StatePending      StepState = "PENDING"
	StateRunning      StepState = "RUNNING"
	StateSucceeded    StepState = "SUCCEEDED"
	StateFailed       StepState = "FAILED"
	StateSkipped      StepState = "SKIPPED"
	StateUserRejected StepState = "USER_REJECTED"
)

// Represents a step in the execution plan generated by the LLM in Phase 1
type PlannedExecutionStep struct {
	OriginalUserStepName string
	ActionName           string
	ActionPrompt         string
	Dependencies         []string
	IgnoreFailure        bool
	State                StepState
	Output               string
	Error                error
}

func main() {
	cfg, err := config.LoadConfig(".")
	if err != nil {
		log.Printf("warning: could not load config.yaml: %v. using defaults and env vars", err)
		cfg = &config.Config{Verbose: false}
	} else if cfg == nil {
		cfg = &config.Config{Verbose: false}
	}

	apiKey := cfg.GeminiAPIKey
	if apiKey == "" {
		apiKey = os.Getenv("GEMINI_API_KEY")
	}
	if apiKey == "" {
		log.Fatal("GEMINI_API_KEY is not set. please provide it")
	}

	llmModel := cfg.LLMModelName
	if llmModel == "" {
		llmModel = defaultGeminiModel
		if cfg.Verbose {
			log.Printf("LLM model name not set, defaulting to '%s'", llmModel)
		}
	}
	verbose := cfg.Verbose

	if verbose {
		log.Println("verbose mode enabled")
		log.Printf("using LLM Model: %s", llmModel)
	}

	if len(os.Args) < 2 {
		log.Fatal("usage: nopsai <pipeline_yaml_file>")
	}
	pipelineFilePath := os.Args[1]

	userPipeline, err := pipeline.LoadPipeline(pipelineFilePath)
	if err != nil {
		log.Fatalf("error loading user pipeline: %v", err)
	}

	if verbose {
		log.Printf("successfully loaded user pipeline: %s", userPipeline.Name)
		log.Printf("found %d user-defined steps.\n", len(userPipeline.Steps))
	}

	llmClient := llm.NewClient(apiKey, llmModel)

	// --- Phase 1: LLM Analyzes Entire Pipeline and Creates an Execution Plan ---
	if verbose {
		log.Println("\n--- Phase 1: Requesting LLM to plan the pipeline ---")
	}
	var planningContext strings.Builder
	planningContext.WriteString(fmt.Sprintf("User's pipeline name: %s\nDescription: %s\nSteps:\n", userPipeline.Name, userPipeline.Description))
	for i, step := range userPipeline.Steps {
		planningContext.WriteString(fmt.Sprintf("- Step %d (Name: '%s'): Prompt: \"%s\", Dependencies: %v, IgnoreFailure: %t\n",
			i+1, step.Name, step.Prompt, step.Dependencies, step.IgnoreFailure))
	}

	llmExecutionPlan, err := llmClient.GenerateExecutionPlan(planningContext.String(), verbose)
	if err != nil {
		log.Fatalf("LLM failed to generate an execution plan: %v", err)
	}
	if llmExecutionPlan == nil || len(llmExecutionPlan.PlannedActions) == 0 {
		log.Fatal("LLM returned an empty or invalid execution plan.")
	}

	if verbose {
		log.Println("LLM Execution Plan Received:")
		for i, action := range llmExecutionPlan.PlannedActions {
			log.Printf("  Planned Action %d: Name='%s', OriginalStep='%s', Description='%s'",
				i+1, action.ActionName, action.OriginalUserStepName, action.Description)
		}
	}

	// --- Setup Executor and Prepare Container Environment ---
	currentExecutor := executor.NewDockerExecutor(executor.NewDockerCLIRuntime())
	if verbose {
		log.Printf("\n--- Preparing Execution Environment (Executor: %s) ---", currentExecutor.GetType())
	}

	hostWorkspace := userPipeline.WorkspaceMount
	if hostWorkspace == "" {
		hostWorkspace = "."
		if verbose {
			log.Printf("pipeline.yaml does not specify 'workspace_mount', defaulting host workspace to current directory '.'")
		}
	}

	pipelineCtx := executor.PipelineContext{
		PipelineName:      userPipeline.Name,
		ImageName:         userPipeline.ContainerImage,
		HostWorkspacePath: hostWorkspace,
		Environment:       userPipeline.Environment,
	}

	if err := currentExecutor.PrepareEnvironment(pipelineCtx, verbose); err != nil {
		log.Fatalf("failed to prepare execution environment: %v", err)
	}
	defer func() {
		if err := currentExecutor.CleanupEnvironment(verbose); err != nil {
			log.Printf("warning: error during environment cleanup: %v", err)
		}
	}()

	// --- Phase 2: Execute Planned Actions ---
	if verbose {
		log.Println("\n--- Phase 2: Executing LLM's Planned Actions ---")
	}
	plannedStepInfos := make(map[string]*PlannedExecutionStep)
	actionOutputs := make(map[string]string)
	var outputsMutex sync.Mutex

	for i := range llmExecutionPlan.PlannedActions {
		action := llmExecutionPlan.PlannedActions[i]
		plannedStepInfos[action.ActionName] = &PlannedExecutionStep{
			OriginalUserStepName: action.OriginalUserStepName,
			ActionName:           action.ActionName,
			ActionPrompt:         action.ActionPrompt,
			Dependencies:         action.Dependencies,
			IgnoreFailure:        action.IgnoreFailure,
			State:                StatePending,
		}
	}

	sortedActionNames, err := TopologicalSortPlannedSteps(llmExecutionPlan.PlannedActions)
	if err != nil {
		log.Fatalf("pipeline validation error in LLM's plan: %v", err)
	}

	if verbose {
		log.Println("Execution order for planned actions:", sortedActionNames)
	}

	pipelineFailed := false
	for _, actionName := range sortedActionNames {
		psi := plannedStepInfos[actionName]

		if pipelineFailed {
			psi.State = StateSkipped
			psi.Error = fmt.Errorf("pipeline halted due to previous critical failure")
			if verbose {
				log.Printf("Planned Action '%s' SKIPPED because pipeline halted.", actionName)
			}
			continue
		}

		psi.State = StateRunning
		fmt.Printf("\n--- Processing Planned Action: %s (for User Step: %s) ---\n", psi.ActionName, psi.OriginalUserStepName)

		resolvedActionPrompt := psi.ActionPrompt
		outputsMutex.Lock()
		placeholderRegex := regexp.MustCompile(`{outputs\.([a-zA-Z0-9_]+)}`)
		resolvedActionPrompt = placeholderRegex.ReplaceAllStringFunc(resolvedActionPrompt, func(match string) string {
			parts := placeholderRegex.FindStringSubmatch(match)
			if len(parts) == 2 {
				depActionName := parts[1]
				if output, ok := actionOutputs[depActionName]; ok {
					if verbose {
						log.Printf("  Substituting placeholder '%s' with output from '%s'", match, depActionName)
					}
					return strings.TrimSpace(output)
				}
				if verbose {
					log.Printf("  Warning: Output for placeholder '%s' (action '%s') not found.", match, depActionName)
				}
				return match
			}
			return match
		})
		outputsMutex.Unlock()

		if verbose {
			log.Printf("  Resolved Action Prompt (for LLM code gen): %s\n", resolvedActionPrompt)
		}

		llmCodeContext := llm.PromptContextForCode{
			PreciseActionPrompt: resolvedActionPrompt,
		}

		generatedCode, err := llmClient.GenerateCodeForAction(llmCodeContext, verbose)
		if err != nil {
			psi.Error = fmt.Errorf("LLM code generation failed for action '%s': %w", actionName, err)
			psi.State = StateFailed
			log.Printf("  Planned Action '%s': Status: %s - %v\n", actionName, psi.State, psi.Error)
			if !psi.IgnoreFailure {
				log.Printf("critical planned action '%s' failed. stopping pipeline", actionName)
				pipelineFailed = true
			} else {
				log.Printf("planned action '%s' failed but IgnoreFailure is true. continuing pipeline", actionName)
			}
			continue
		}

		actionCtx := executor.ActionContext{
			ActionName:          psi.ActionName,
			ActionScriptContent: generatedCode,
		}

		execResult := currentExecutor.ExecuteAction(actionCtx, verbose)

		outputsMutex.Lock()
		actionOutputs[actionName] = execResult.Stdout
		psi.Output = execResult.Stdout
		outputsMutex.Unlock()

		if execResult.Error != nil {
			psi.Error = execResult.Error
			psi.State = StateFailed
		} else if execResult.ExitCode != 0 {
			psi.Error = fmt.Errorf("script failed with exit code %d. Stderr: %s", execResult.ExitCode, execResult.Stderr)
			psi.State = StateFailed
		} else {
			psi.State = StateSucceeded
		}

		log.Printf("  Planned Action '%s': Finished with Status: %s\n", actionName, psi.State)
		if psi.Error != nil && verbose {
			log.Printf("  Planned Action '%s': Error details: %v\n", actionName, psi.Error)
		}

		if psi.State == StateFailed && !psi.IgnoreFailure {
			log.Printf("critical planned action '%s' failed. stopping pipeline", actionName)
			pipelineFailed = true
		}
	}

	fmt.Println("\n--- Pipeline Execution Summary (Based on LLM's Plan) ---")
	for _, actionName := range sortedActionNames {
		psi := plannedStepInfos[actionName]
		fmt.Printf("Planned Action: %s (Original User Step: %s), Status: %s\n", psi.ActionName, psi.OriginalUserStepName, psi.State)
		if psi.Error != nil {
			fmt.Printf("  Error: %v\n", psi.Error)
		}
		if psi.Output != "" {
			summaryOutput := psi.Output
			if len(summaryOutput) > 200 {
				summaryOutput = summaryOutput[:200] + "..."
			}
			fmt.Printf("  Output Preview: %s\n", summaryOutput)
		}
	}
	if verbose {
		userStepsProcessed := make(map[string]bool)
		for _, actionName := range sortedActionNames {
			if psi, ok := plannedStepInfos[actionName]; ok && (psi.State == StateSucceeded || psi.State == StateFailed || psi.State == StateSkipped) {
				userStepsProcessed[psi.OriginalUserStepName] = true
			}
		}

		log.Println("--- User Step Summary ---")
		for _, userStep := range userPipeline.Steps {
			if _, processed := userStepsProcessed[userStep.Name]; processed {
				// Status reflected in Planned Action summary
			} else {
				fmt.Printf("User Step: %s, Status: SKIPPED (no planned actions executed or pipeline halted early)\n", userStep.Name)
			}
		}
	}

	fmt.Println("\nPipeline processing finished.")
}

// TopologicalSortPlannedSteps sorts the LLM's planned actions based on their dependencies.
func TopologicalSortPlannedSteps(actions []llm.PlannedAction) ([]string, error) {
	inDegree := make(map[string]int)
	graph := make(map[string][]string)
	actionMap := make(map[string]bool)

	for _, action := range actions {
		if action.ActionName == "" {
			return nil, fmt.Errorf("found a planned action with an empty ActionName")
		}
		actionMap[action.ActionName] = true
		if _, ok := inDegree[action.ActionName]; !ok {
			inDegree[action.ActionName] = 0
		}
		graph[action.ActionName] = []string{}
	}

	for _, action := range actions {
		for _, depName := range action.Dependencies {
			if _, ok := actionMap[depName]; !ok {
				return nil, fmt.Errorf("planned action '%s' has an unknown dependency action '%s' in LLM's plan", action.ActionName, depName)
			}
			graph[depName] = append(graph[depName], action.ActionName)
			inDegree[action.ActionName]++
		}
	}

	queue := []string{}
	for name, degree := range inDegree {
		if degree == 0 {
			queue = append(queue, name)
		}
	}

	var sortedOrder []string
	for len(queue) > 0 {
		u := queue[0]
		queue = queue[1:]
		sortedOrder = append(sortedOrder, u)

		for _, v := range graph[u] {
			inDegree[v]--
			if inDegree[v] == 0 {
				queue = append(queue, v)
			}
		}
	}

	if len(sortedOrder) != len(actions) {
		return nil, fmt.Errorf("cycle detected in LLM's planned action dependencies")
	}
	return sortedOrder, nil
}
