package platform

import "strings"

const installKubernetesReadmeFile = "installation.md"

type kubernetesSecretKeyReference struct {
	Purpose string
	Key     string
}

func renderKubernetesInstallReadme(version, releaseName, namespace, valuesFile, secretFile, existingSecret, bootstrapAdminEmail, bootstrapAdminPasswordSecretKey, postgresDatabase, postgresUser string, wait bool) []byte {
	secretKeys := kubernetesInstallSecretKeys(bootstrapAdminPasswordSecretKey)
	var builder strings.Builder
	builder.WriteString("# NopsAI Kubernetes Installation\n\n")
	builder.WriteString("Generated by `nopsai install kubernetes` for NopsAI ")
	builder.WriteString(version)
	builder.WriteString(". Review this guide before applying `")
	builder.WriteString(secretFile)
	builder.WriteString("` or deploying the Helm chart.\n\n")

	builder.WriteString("## Requirements\n\n")
	builder.WriteString("- Kubernetes cluster access through `kubectl`.\n")
	builder.WriteString("- Helm 3 access to the target cluster.\n")
	builder.WriteString("- Persistent storage for the bundled PostgreSQL StatefulSet, or an edited `")
	builder.WriteString(valuesFile)
	builder.WriteString("` that disables bundled PostgreSQL and points `")
	builder.WriteString(secretFile)
	builder.WriteString("` at an external database.\n")
	builder.WriteString("- Registry pull credentials when release images are private.\n")
	builder.WriteString("- Ingress controller, DNS, and TLS configuration when `ingress.enabled` is true.\n\n")

	builder.WriteString("## Registry Pull Secrets\n\n")
	builder.WriteString("Create a registry pull Secret only when your NopsAI images are private:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "create", "namespace", namespace, "--dry-run=client", "-o", "yaml"}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString(shellJoin([]string{
		"kubectl", "-n", namespace, "create", "secret", "docker-registry", "nopsai-registry",
		"--docker-server=ghcr.io",
		"--docker-username=REPLACE_ME",
		"--docker-password=REPLACE_ME",
		"--dry-run=client", "-o", "yaml",
	}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString("```\n\n")

	builder.WriteString("## Image Pull Secrets\n\n")
	builder.WriteString("Reference the pull Secret from `")
	builder.WriteString(valuesFile)
	builder.WriteString("` when needed:\n\n")
	builder.WriteString("```yaml\nglobal:\n  imagePullSecrets:\n    - name: nopsai-registry\n```\n\n")
	builder.WriteString("The chart attaches `global.imagePullSecrets` to the API and runner ServiceAccounts and pod specs.\n\n")

	builder.WriteString("## Service Accounts\n\n")
	builder.WriteString("By default the chart creates `nopsai-api`, `nopsai-runner`, and the runner workload ServiceAccount. If you set any `*.serviceAccount.create` value to `false`, create those ServiceAccounts and required RBAC before deploying. For private images with pre-created ServiceAccounts, patch the pull Secret onto them:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "patch", "serviceaccount", "nopsai-api", "-p", `{"imagePullSecrets":[{"name":"nopsai-registry"}]}`}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "patch", "serviceaccount", "nopsai-runner", "-p", `{"imagePullSecrets":[{"name":"nopsai-registry"}]}`}))
	builder.WriteString("\n```\n\n")

	builder.WriteString("## Apply Secrets\n\n")
	builder.WriteString("The generated Secret manifest is `")
	builder.WriteString(secretFile)
	builder.WriteString("`. It creates Secret `")
	builder.WriteString(existingSecret)
	builder.WriteString("` in namespace `")
	builder.WriteString(namespace)
	builder.WriteString("` with these keys:\n\n")
	builder.WriteString("| Purpose | Secret key |\n| --- | --- |\n")
	for _, key := range secretKeys {
		builder.WriteString("| ")
		builder.WriteString(key.Purpose)
		builder.WriteString(" | `")
		builder.WriteString(key.Key)
		builder.WriteString("` |\n")
	}
	builder.WriteString("\nApply the namespace and Secret before Helm:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "create", "namespace", namespace, "--dry-run=client", "-o", "yaml"}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString(shellJoin([]string{"kubectl", "apply", "-f", secretFile}))
	builder.WriteString("\n```\n\n")

	builder.WriteString("## Review Values\n\n")
	builder.WriteString("- Keep `")
	builder.WriteString(valuesFile)
	builder.WriteString("` non-secret and GitOps tracked.\n")
	builder.WriteString("- Review `global.releaseVersion`, image repositories/tags/digests, `postgres.*`, `topology.*`, `bootstrapAdmin.email`, ingress, resources, storage class, and runner settings. Blank NopsAI image tags inherit `global.releaseVersion`; set an image tag or digest only for a deliberate per-image override.\n")
	builder.WriteString("- Bundled PostgreSQL defaults to database `")
	builder.WriteString(postgresDatabase)
	builder.WriteString("` and user `")
	builder.WriteString(postgresUser)
	builder.WriteString("`; the generated Secret keeps `database-url` and `postgres-password` aligned.\n")
	builder.WriteString("- The bootstrap admin email is `")
	builder.WriteString(bootstrapAdminEmail)
	builder.WriteString("`; the generated password is in Secret key `")
	builder.WriteString(bootstrapAdminPasswordSecretKey)
	builder.WriteString("`.\n")
	builder.WriteString("- Put environment-specific overrides in additional values files and pass them with `--values` during CLI deploy or `--values` during Helm deploy.\n\n")

	builder.WriteString("## Deploy NopsAI Helm\n\n")
	builder.WriteString("Preferred CLI deploy from this directory, which also writes `.nopsai/release.lock` after a successful Helm upgrade:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin(kubernetesDeployArgs(releaseName, namespace, valuesFile, wait)))
	builder.WriteString("\n")
	builder.WriteString(shellJoin(append(kubernetesDeployArgs(releaseName, namespace, valuesFile, wait), "--values", "overrides/prod.yaml")))
	builder.WriteString("  # optional overlay example\n")
	builder.WriteString("```\n\n")
	builder.WriteString("Direct Helm deploy, if you do not need the CLI deployment lock:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin(kubernetesHelmDeployArgs(releaseName, namespace, valuesFile, version, wait)))
	builder.WriteString("\n")
	builder.WriteString("```\n\n")

	builder.WriteString("## Verify\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "get", "pods"}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "get", "svc"}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "port-forward", "service/nopsai-ui", "8080:80"}))
	builder.WriteString("\n```\n\n")
	builder.WriteString("Open `http://localhost:8080` when ingress is disabled, or the configured ingress host when it is enabled.\n\n")

	builder.WriteString("## Generated Secrets\n\n")
	builder.WriteString("`")
	builder.WriteString(secretFile)
	builder.WriteString("` is generated by the CLI with a PostgreSQL password, database URL, master key, JWT signing keys, service JWT key, AAA shared token, dispatcher TLS secret, and bootstrap admin password. Keep it private, or encrypt/seal it before committing it to GitOps. Rotating `postgres-password` after PostgreSQL has initialized also requires changing the database role password or recreating disposable storage.\n")
	return []byte(builder.String())
}

func kubernetesInstallSecretKeys(bootstrapAdminPasswordSecretKey string) []kubernetesSecretKeyReference {
	return []kubernetesSecretKeyReference{
		{Purpose: "Database URL", Key: "database-url"},
		{Purpose: "PostgreSQL password for bundled PostgreSQL", Key: "postgres-password"},
		{Purpose: "Master encryption key", Key: "master-key"},
		{Purpose: "Browser JWT signing key", Key: "jwt-signing-key"},
		{Purpose: "Service JWT signing key", Key: "service-jwt-signing-key"},
		{Purpose: "AAA shared internal token", Key: "aaa-shared-internal-token"},
		{Purpose: "Dispatcher TLS secret", Key: "dispatcher-tls-secret"},
		{Purpose: "Bootstrap admin password", Key: bootstrapAdminPasswordSecretKey},
	}
}

func kubernetesHelmDeployArgs(releaseName, namespace, valuesFile, version string, wait bool) []string {
	args := []string{
		"helm", "upgrade", "--install", releaseName,
		DefaultInstallChartReference,
		"--version", version,
		"--namespace", namespace,
		"--create-namespace",
		"--values", valuesFile,
	}
	if wait {
		args = append(args, "--wait")
	}
	return args
}

func kubernetesHelmTemplateArgs(releaseName, namespace, valuesFile, version string) []string {
	return []string{
		"helm", "template", releaseName,
		DefaultInstallChartReference,
		"--version", version,
		"--namespace", namespace,
		"--values", valuesFile,
	}
}
