package platform

import "strings"

const installKubernetesReadmeFile = "README.md"

type kubernetesSecretKeyReference struct {
	Purpose string
	Key     string
}

func renderKubernetesInstallReadme(version, releaseName, namespace, valuesFile, existingSecret, bootstrapAdminEmail, bootstrapAdminPasswordSecretKey string, wait bool) []byte {
	secretKeys := kubernetesInstallSecretKeys(bootstrapAdminPasswordSecretKey)
	var builder strings.Builder
	builder.WriteString("# NopsAI Kubernetes Install Notes\n\n")
	builder.WriteString("Generated by `nopsai install kubernetes` for NopsAI ")
	builder.WriteString(version)
	builder.WriteString(". Keep this file with `")
	builder.WriteString(valuesFile)
	builder.WriteString("` and `.nopsai/install.lock` so the deployment can be reviewed and repeated.\n\n")

	builder.WriteString("## Requirements\n\n")
	builder.WriteString("- Kubernetes cluster access through `kubectl`.\n")
	builder.WriteString("- Helm 3 access to the target cluster.\n")
	builder.WriteString("- Persistent storage for the chart-managed PostgreSQL StatefulSet, or set `postgres.enabled=false` and provide an external database URL.\n")
	builder.WriteString("- A Kubernetes Secret named `")
	builder.WriteString(existingSecret)
	builder.WriteString("` in namespace `")
	builder.WriteString(namespace)
	builder.WriteString("` with the keys listed below.\n")
	builder.WriteString("- Registry pull access in `global.imagePullSecrets` when release images are private.\n")
	builder.WriteString("- Ingress controller, DNS, and TLS configuration when `ingress.enabled` is true.\n\n")

	builder.WriteString("## Secret Keys\n\n")
	builder.WriteString("The generated values reference `secrets.existingSecret: ")
	builder.WriteString(existingSecret)
	builder.WriteString("`. Do not put plaintext secret values in `")
	builder.WriteString(valuesFile)
	builder.WriteString("` or Git. Use External Secrets, SOPS, Sealed Secrets, or your cluster secret manager for production.\n\n")
	builder.WriteString("| Purpose | Secret key |\n| --- | --- |\n")
	for _, key := range secretKeys {
		builder.WriteString("| ")
		builder.WriteString(key.Purpose)
		builder.WriteString(" | `")
		builder.WriteString(key.Key)
		builder.WriteString("` |\n")
	}

	builder.WriteString("\n## Registry Pull Secret\n\n")
	builder.WriteString("If your NopsAI release images are private, create a registry pull Secret in namespace `")
	builder.WriteString(namespace)
	builder.WriteString("` and reference it from `")
	builder.WriteString(valuesFile)
	builder.WriteString("`. The chart attaches `global.imagePullSecrets` to the API and runner service accounts and pod specs.\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "create", "namespace", namespace, "--dry-run=client", "-o", "yaml"}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString(shellJoin([]string{
		"kubectl", "-n", namespace, "create", "secret", "docker-registry", "nopsai-registry",
		"--docker-server=ghcr.io",
		"--docker-username=REPLACE_ME",
		"--docker-password=REPLACE_ME",
		"--dry-run=client", "-o", "yaml",
	}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString("```\n\n")
	builder.WriteString("Then add this non-secret reference to `")
	builder.WriteString(valuesFile)
	builder.WriteString("`:\n\n")
	builder.WriteString("```yaml\nglobal:\n  imagePullSecrets:\n    - name: nopsai-registry\n```\n")
	builder.WriteString("\nWhen `api.serviceAccount.create=true` and `k8sRunner.serviceAccount.create=true`, the chart writes this pull Secret onto the `nopsai-api` and `nopsai-runner` ServiceAccounts and onto workload pod specs. The runner ServiceAccount is also used by dynamically created agent and step pods.\n\n")
	builder.WriteString("If you bring your own ServiceAccounts by setting either `*.serviceAccount.create` to `false`, create or patch those ServiceAccounts before deploy:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "patch", "serviceaccount", "nopsai-api", "-p", `{"imagePullSecrets":[{"name":"nopsai-registry"}]}`}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "patch", "serviceaccount", "nopsai-runner", "-p", `{"imagePullSecrets":[{"name":"nopsai-registry"}]}`}))
	builder.WriteString("\n```\n")

	builder.WriteString("\n### Secret Manifest Option\n\n")
	builder.WriteString("Create an encrypted/managed Secret manifest, or use this plaintext example only as a local starting point before encrypting it:\n\n")
	builder.WriteString("```yaml\n")
	builder.WriteString("apiVersion: v1\nkind: Secret\nmetadata:\n  name: ")
	builder.WriteString(existingSecret)
	builder.WriteString("\n  namespace: ")
	builder.WriteString(namespace)
	builder.WriteString("\ntype: Opaque\nstringData:\n")
	builder.WriteString("  ")
	builder.WriteString(secretKeys[0].Key)
	builder.WriteString(": \"postgres://nopsai_user:REPLACE_ME@postgres:5432/nopsai_db?sslmode=disable\"\n")
	for _, key := range secretKeys[1:] {
		builder.WriteString("  ")
		builder.WriteString(key.Key)
		builder.WriteString(": \"REPLACE_ME\"\n")
	}
	builder.WriteString("```\n\n")
	builder.WriteString("Save it as `nopsai-secrets.yaml`, then apply the Secret after it has been encrypted or safely generated:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "create", "namespace", namespace, "--dry-run=client", "-o", "yaml"}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString(shellJoin([]string{"kubectl", "apply", "-f", "nopsai-secrets.yaml"}))
	builder.WriteString("\n```\n\n")

	builder.WriteString("### Command-Line Option\n\n")
	builder.WriteString("For a one-off installation, create or update the Secret from command-line literals. The default database URL targets the bundled `postgres` Service; change it and set `postgres.enabled=false` when using a managed database. Keep the printed bootstrap password:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString("POSTGRES_PASSWORD=\"$(openssl rand -hex 24)\"\n")
	builder.WriteString("DATABASE_URL=\"postgres://nopsai_user:${POSTGRES_PASSWORD}@postgres:5432/nopsai_db?sslmode=disable\"\n")
	builder.WriteString("MASTER_KEY=\"$(openssl rand -base64 32)\"\n")
	builder.WriteString("JWT_SIGNING_KEY=\"$(openssl rand -base64 48)\"\n")
	builder.WriteString("SERVICE_JWT_SIGNING_KEY=\"$(openssl rand -base64 48)\"\n")
	builder.WriteString("AAA_SHARED_INTERNAL_TOKEN=\"$(openssl rand -base64 32)\"\n")
	builder.WriteString("DISPATCHER_TLS_SECRET=\"$(openssl rand -base64 48)\"\n")
	builder.WriteString("BOOTSTRAP_ADMIN_PASSWORD=\"$(openssl rand -base64 24)\"\n")
	builder.WriteString("printf 'Bootstrap admin password for %s: %s\\n' ")
	builder.WriteString(shellQuote(bootstrapAdminEmail))
	builder.WriteString(" \"$BOOTSTRAP_ADMIN_PASSWORD\"\n\n")
	builder.WriteString(shellJoin([]string{"kubectl", "create", "namespace", namespace, "--dry-run=client", "-o", "yaml"}))
	builder.WriteString(" | kubectl apply -f -\n")
	builder.WriteString("kubectl -n ")
	builder.WriteString(shellQuote(namespace))
	builder.WriteString(" create secret generic ")
	builder.WriteString(shellQuote(existingSecret))
	builder.WriteString(" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[0].Key)
	builder.WriteString("=\"$DATABASE_URL\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[1].Key)
	builder.WriteString("=\"$POSTGRES_PASSWORD\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[2].Key)
	builder.WriteString("=\"$MASTER_KEY\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[3].Key)
	builder.WriteString("=\"$JWT_SIGNING_KEY\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[4].Key)
	builder.WriteString("=\"$SERVICE_JWT_SIGNING_KEY\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[5].Key)
	builder.WriteString("=\"$AAA_SHARED_INTERNAL_TOKEN\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[6].Key)
	builder.WriteString("=\"$DISPATCHER_TLS_SECRET\" \\\n")
	builder.WriteString("  --from-literal=")
	builder.WriteString(secretKeys[7].Key)
	builder.WriteString("=\"$BOOTSTRAP_ADMIN_PASSWORD\" \\\n")
	builder.WriteString("  --dry-run=client -o yaml | kubectl apply -f -\n")
	builder.WriteString("```\n\n")

	builder.WriteString("## Review Values\n\n")
	builder.WriteString("- Keep `")
	builder.WriteString(valuesFile)
	builder.WriteString("` non-secret and GitOps tracked.\n")
	builder.WriteString("- Review `global.releaseVersion`, image repositories/tags/digests, `postgres.*`, `topology.*`, `bootstrapAdmin.email`, ingress, resources, storage class, and runner settings.\n")
	builder.WriteString("- The bootstrap admin email is `")
	builder.WriteString(bootstrapAdminEmail)
	builder.WriteString("`; the password is read from Secret key `")
	builder.WriteString(bootstrapAdminPasswordSecretKey)
	builder.WriteString("` and should be changed during first setup/login.\n")
	builder.WriteString("- Put environment-specific overrides in additional values files and pass them with `--values` during CLI deploy or `--values` during Helm deploy.\n\n")

	builder.WriteString("## Deploy\n\n")
	builder.WriteString("Preferred CLI deploy from this directory, which also writes `.nopsai/release.lock` after a successful Helm upgrade:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin(kubernetesDeployArgs(releaseName, namespace, valuesFile, wait)))
	builder.WriteString("\n")
	builder.WriteString(shellJoin(append(kubernetesDeployArgs(releaseName, namespace, valuesFile, wait), "--values", "overrides/prod.yaml")))
	builder.WriteString("  # optional overlay example\n")
	builder.WriteString("```\n\n")
	builder.WriteString("Direct Helm deploy, if you do not need the CLI deployment lock:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin(kubernetesHelmDeployArgs(releaseName, namespace, valuesFile, version, wait)))
	builder.WriteString("\n")
	builder.WriteString("```\n\n")
	builder.WriteString("Render before applying when you want a review artifact:\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin(kubernetesHelmTemplateArgs(releaseName, namespace, valuesFile, version)))
	builder.WriteString(" > rendered.yaml\n")
	builder.WriteString("```\n\n")

	builder.WriteString("## Verify\n\n")
	builder.WriteString("```bash\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "get", "pods"}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "get", "svc"}))
	builder.WriteString("\n")
	builder.WriteString(shellJoin([]string{"kubectl", "-n", namespace, "port-forward", "service/nopsai-ui", "8080:80"}))
	builder.WriteString("\n")
	builder.WriteString("```\n\n")
	builder.WriteString("Open `http://localhost:8080` when ingress is disabled, or the configured ingress host when it is enabled.\n")
	return []byte(builder.String())
}

func kubernetesInstallSecretKeys(bootstrapAdminPasswordSecretKey string) []kubernetesSecretKeyReference {
	return []kubernetesSecretKeyReference{
		{Purpose: "Database URL", Key: "database-url"},
		{Purpose: "PostgreSQL password for bundled PostgreSQL", Key: "postgres-password"},
		{Purpose: "Master encryption key", Key: "master-key"},
		{Purpose: "Browser JWT signing key", Key: "jwt-signing-key"},
		{Purpose: "Service JWT signing key", Key: "service-jwt-signing-key"},
		{Purpose: "AAA shared internal token", Key: "aaa-shared-internal-token"},
		{Purpose: "Dispatcher TLS secret", Key: "dispatcher-tls-secret"},
		{Purpose: "Bootstrap admin password", Key: bootstrapAdminPasswordSecretKey},
	}
}

func kubernetesHelmDeployArgs(releaseName, namespace, valuesFile, version string, wait bool) []string {
	args := []string{
		"helm", "upgrade", "--install", releaseName,
		DefaultInstallChartReference,
		"--version", version,
		"--namespace", namespace,
		"--create-namespace",
		"--values", valuesFile,
	}
	if wait {
		args = append(args, "--wait")
	}
	return args
}

func kubernetesHelmTemplateArgs(releaseName, namespace, valuesFile, version string) []string {
	return []string{
		"helm", "template", releaseName,
		DefaultInstallChartReference,
		"--version", version,
		"--namespace", namespace,
		"--values", valuesFile,
	}
}
