triggers:
  - on: push
    branches:
      - main
    scope: dev
    pipelines:
      - platform/prod/platform-maintenance

  - on: pull_request
    scope: dev
    pipelines:
      - platform/prod/platform-maintenance
