import type { WikiField } from '../types.js';

/** Model settings in `models/<name>.yaml`, where a team-scoped model lives at `models/<team>/<name>.yaml`. */
export const llmProfileFields: WikiField[] = [
  {
    path: 'provider',
    scope: 'llm profile',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Model provider client used for this profile.',
    example: 'provider: anthropic',
    allowedValues: [
      'gemini',
      'lmstudio',
      'openai',
      'anthropic',
      'groq',
      'mistral',
      'ollama',
      'openrouter',
      'azure-openai',
    ],
    evidence: 'config/config.go',
  },
  {
    path: 'model',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'Provider default',
    description: 'Model identifier passed to the provider.',
    example: 'model: claude-sonnet-4-5',
  },
  {
    path: 'base_url',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'Provider default endpoint',
    description: 'Endpoint override for self-hosted, proxied, or Azure deployments.',
    example: 'base_url: http://host.docker.internal:1234/v1',
    constraints: [
      'Must be reachable from the API runtime. Inside containers use a LAN IP or host.docker.internal, not localhost.',
    ],
  },
  {
    path: 'credential_ref',
    scope: 'llm profile',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Reference into the encrypted credential registry holding the provider API key.',
    example: 'credential_ref: llm/anthropic-prod',
    constraints: ['Required for providers that authenticate; local providers such as Ollama may not need one.'],
    security: 'The credential value is never returned by the API after submission.',
    evidence: 'config/config.go',
  },
  {
    path: 'api_key_secret',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Legacy inline secret name. Kept for migration compatibility.',
    example: 'api_key_secret: OPENAI_API_KEY',
    deprecatedIn: 'Superseded by credential_ref',
  },
  {
    path: 'allowed_scopes',
    scope: 'llm profile',
    type: 'string[]',
    required: false,
    defaultValue: 'All scopes',
    description: 'Runtime scopes allowed to select this profile. An empty list permits every scope.',
    example: 'allowed_scopes:\n  - platform/production',
    constraints: ['Scope comparison trims surrounding slashes and is case-insensitive.'],
    permission: 'Scope restriction is applied in addition to AAA authorization, not instead of it.',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'timeout_seconds',
    scope: 'llm profile',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Per-request timeout for provider calls made with this profile.',
    example: 'timeout_seconds: 120',
  },
  {
    path: 'max_tokens',
    scope: 'llm profile',
    type: 'integer',
    required: false,
    defaultValue: 'Provider default',
    description: 'Maximum output tokens per request. Supported by every current provider.',
    example: 'max_tokens: 8192',
    evidence: 'config/config.go',
  },
  {
    path: 'pricing',
    scope: 'llm profile',
    type: 'object',
    required: false,
    defaultValue: 'Unpriced (zero for local providers)',
    description: 'Optional rate card in USD per million tokens, used to report AI usage as money. Takes input_per_million_usd and output_per_million_usd, plus optional cached_input_per_million_usd and cache_write_per_million_usd that default to the input rate. Leave it out when the rate is unknown: the model still runs and its cost records as unknown rather than zero, so dashboards report it as unpriced instead of understating spend. Local providers default to explicit zeroes because they have no per-token charge.',
    example: 'pricing:\n  input_per_million_usd: 0.30\n  output_per_million_usd: 2.50',
    evidence: 'config/config.go',
  },
  {
    path: 'temperature',
    scope: 'llm profile',
    type: 'float',
    required: false,
    defaultValue: 'Provider default',
    description: 'Sampling temperature. Unset leaves the provider default in place.',
    example: 'temperature: 0.2',
  },
  {
    path: 'reasoning',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Generic reasoning level. Supported only for the LM Studio provider.',
    example: 'reasoning: high',
    allowedValues: ['off', 'low', 'medium', 'high', 'on'],
    constraints: ['Other providers reject a generic value rather than silently ignoring stale configuration.'],
    evidence: 'config/config.go',
  },
  {
    path: 'thinking',
    scope: 'llm profile',
    type: 'boolean',
    required: false,
    defaultValue: 'None',
    description: 'Boolean form of the reasoning toggle. Supported only for LM Studio; `reasoning` takes precedence.',
    example: 'thinking: true',
    evidence: 'config/config.go',
  },
  {
    path: 'prompt_cache.mode',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Provider prompt-cache behavior for this profile.',
    example: 'prompt_cache:\n  mode: auto',
  },
  {
    path: 'prompt_cache.scope',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Cache partition boundary applied to prompt caching.',
    example: 'prompt_cache:\n  scope: run',
  },
  {
    path: 'prompt_cache.retention',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'How long a cached prompt prefix stays valid.',
    example: 'prompt_cache:\n  retention: 1h',
  },
  {
    path: 'provider_state.mode',
    scope: 'llm profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Whether provider-side conversation state is used for multi-turn goal work.',
    example: 'provider_state:\n  mode: auto',
  },
  {
    path: 'extra',
    scope: 'llm profile',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description: 'Provider-specific settings passed through unchanged.',
    example: 'extra:\n  api_version: "2024-10-21"',
  },
];

/** Agent role settings in `agent-roles/<name>.yaml`, where a team-scoped role lives at `agent-roles/<team>/<name>.yaml`. */
export const agentProfileFields: WikiField[] = [
  {
    path: 'id',
    scope: 'agent role',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Profile identifier referenced by `agent_role` on a pipeline or step.',
    example: 'id: senior-release-engineer',
    evidence: 'pkg/models/agent_profile.go',
  },
  {
    path: 'display_name',
    scope: 'agent role',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Name shown in the Agent roles workspace and profile pickers.',
    example: 'display_name: Senior Release Engineer',
  },
  {
    path: 'role',
    scope: 'agent role',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Short role label used in prompt framing.',
    example: 'role: Release engineer',
  },
  {
    path: 'description',
    scope: 'agent role',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Human-readable purpose shown to authors choosing a persona.',
    example: 'description: Cautious operator persona for production release work.',
  },
  {
    path: 'instructions',
    scope: 'agent role',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Prompt instructions injected for conditions and LLM goals that select this profile.',
    example: 'instructions: |\n  Prefer reversible actions. Never skip a failing check.',
    security: 'Instructions shape behavior only. They do not grant provider access, tools, credentials, or permissions.',
    evidence: 'pkg/models/agent_profile.go',
  },
  {
    path: 'enabled',
    scope: 'agent role',
    type: 'boolean',
    required: true,
    defaultValue: 'None',
    description: 'Whether the profile can be selected. Referencing a disabled profile fails validation.',
    example: 'enabled: true',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'built_in',
    scope: 'agent role',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Marks a profile shipped with the platform rather than authored by an operator.',
    example: 'built_in: true',
  },
  {
    path: 'source',
    scope: 'agent role',
    type: 'string',
    required: false,
    defaultValue: 'database',
    description: 'Where the profile definition came from, used to reason about GitOps ownership.',
    example: 'source: gitops',
  },
];

/** External MCP server definitions in `mcp/servers/<name>.yaml`. */
export const mcpServerFields: WikiField[] = [
  {
    path: 'name',
    scope: 'mcp server',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Server identifier referenced by MCP profiles.',
    example: 'name: jira',
    evidence: 'pkg/models/mcp.go',
  },
  {
    path: 'display_name',
    scope: 'mcp server',
    type: 'string',
    required: false,
    defaultValue: 'The server name',
    description: 'Label shown in the MCP workspace.',
    example: 'display_name: Jira (read only)',
  },
  {
    path: 'enabled',
    scope: 'mcp server',
    type: 'boolean',
    required: true,
    defaultValue: 'None',
    description: 'Whether the server can be used by profiles and discovery.',
    example: 'enabled: true',
  },
  {
    path: 'transport',
    scope: 'mcp server',
    type: 'string',
    required: false,
    defaultValue: 'streamable HTTP',
    description: 'Transport used to reach the server. External MCP currently uses streamable HTTP.',
    example: 'transport: streamable-http',
    evidence: 'pkg/models/mcp.go',
  },
  {
    path: 'url',
    scope: 'mcp server',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Server endpoint. Must be reachable from the API runtime.',
    example: 'url: https://mcp.internal.example.com/jira',
    constraints: [
      'Inside containers, `localhost` refers to the container. Use a LAN IP or host.docker.internal for host-launched tools.',
    ],
  },
  {
    path: 'auth_type',
    scope: 'mcp server',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Authentication scheme used when calling the server.',
    example: 'auth_type: bearer',
  },
  {
    path: 'credential_ref',
    scope: 'mcp server',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Reference into the encrypted credential registry for the server credential.',
    example: 'credential_ref: mcp/jira-token',
    security: 'Credential values are write-only; they are not readable after submission.',
  },
  {
    path: 'auth_secret',
    scope: 'mcp server',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Legacy inline secret name kept for migration compatibility.',
    example: 'auth_secret: JIRA_TOKEN',
    deprecatedIn: 'Superseded by credential_ref',
  },
  {
    path: 'headers',
    scope: 'mcp server',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description: 'Static headers added to every request to this server.',
    example: 'headers:\n  X-Tenant: platform',
  },
  {
    path: 'timeout',
    scope: 'mcp server',
    type: 'duration',
    required: false,
    defaultValue: 'Platform default',
    description: 'Per-call timeout for this server.',
    example: 'timeout: 30s',
  },
  {
    path: 'allowed_scopes',
    scope: 'mcp server',
    type: 'string[]',
    required: false,
    defaultValue: 'All scopes',
    description: 'Runtime scopes allowed to reach this server.',
    example: 'allowed_scopes:\n  - platform/production',
  },
];

/** MCP Profile definitions: the allowlist pipelines are actually allowed to reference. */
export const mcpProfileFields: WikiField[] = [
  {
    path: 'name',
    scope: 'mcp profile',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Profile name used by `mcp_profiles` in pipeline, step, and task YAML.',
    example: 'name: jira-readonly',
    evidence: 'pkg/models/mcp.go',
  },
  {
    path: 'description',
    scope: 'mcp profile',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Purpose shown to authors selecting the profile.',
    example: 'description: Read-only Jira issue lookups for release notes.',
  },
  {
    path: 'enabled',
    scope: 'mcp profile',
    type: 'boolean',
    required: true,
    defaultValue: 'None',
    description: 'Whether the profile can be referenced. Referencing a disabled profile fails validation.',
    example: 'enabled: true',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'servers[].server',
    scope: 'mcp profile',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Name of a configured MCP server included in this profile.',
    example: 'servers:\n  - server: jira',
    evidence: 'pkg/models/mcp.go',
  },
  {
    path: 'servers[].tools',
    scope: 'mcp profile',
    type: 'string[]',
    required: false,
    defaultValue: 'All tools on the server',
    description: 'Tool allowlist for that server. The agent only accepts server/tool pairs from the resolved set.',
    example: 'servers:\n  - server: jira\n    tools: [search_issues, get_issue]',
    security: 'Narrowing this list is the primary way to limit what LLM goal work can do through MCP.',
    evidence: 'pkg/models/mcp.go',
  },
  {
    path: 'allowed_scopes',
    scope: 'mcp profile',
    type: 'string[]',
    required: false,
    defaultValue: 'All scopes',
    description: 'Runtime scopes allowed to select this profile.',
    example: 'allowed_scopes:\n  - platform/production',
  },
];

/** Knowledge Context references used in pipeline, step, and task YAML. */
export const knowledgeFields: WikiField[] = [
  {
    path: 'knowledge_context[].kind',
    scope: 'knowledge ref',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Document kind. `guardrail` and `policy` are blocking kinds that also validate direct scripts.',
    example: 'kind: guardrail',
    allowedValues: ['architecture', 'guardrail', 'policy', 'adr', 'guideline', 'runbook', 'reference', 'example'],
    constraints: ['Matching is case-insensitive; unsupported kinds fail validation.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'knowledge_context[].ref',
    scope: 'knowledge ref',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Managed document reference in `team/document` form.',
    example: 'ref: security/repo-check',
    constraints: [
      'Exactly one of `ref` or `path` must be set.',
      'Must be relative and contain at least two segments.',
      'Segments may not be empty, `.`, or `..`.',
    ],
    permission: 'Requires `knowledge_context.use` on the referenced document.',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'knowledge_context[].path',
    scope: 'knowledge ref',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Repository-local document loaded from the run repository at the run commit.',
    example: 'path: .nopsai/docs/backend.md',
    constraints: ['Exactly one of `ref` or `path` must be set.', 'Must be a relative path without `.` or `..` segments.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'knowledge_context[].required',
    scope: 'knowledge ref',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'When true, the run fails before execution if the document cannot be resolved or authorized.',
    example: 'required: true',
    security: 'Leaving this false lets a run proceed without a guardrail the author expected to be applied.',
  },
];

/** How NopsAI acts on the AI policy review decision. */
export const governanceLevels: WikiField[] = [
  {
    path: 'advisory',
    scope: 'governance level',
    type: 'enforcement',
    required: false,
    defaultValue: 'Not the default',
    description: 'Log and warn on an evaluated policy concern. Execution proceeds.',
    example: 'governance_level: advisory',
    constraints: [
      'Advisory downgrades a judgment the model made. It never skips the evaluation: if no judgment can be obtained, the task still fails closed.',
    ],
    evidence: 'pkg/models/policy_merge.go',
  },
  {
    path: 'strict',
    scope: 'governance level',
    type: 'enforcement',
    required: false,
    defaultValue: 'Default when unset',
    description:
      'Proceed only on a clear allow. Violations, conflicts, uncertainty, and unsupported decisions all block.',
    example: 'governance_level: strict',
    constraints: [
      'An empty value normalizes to `strict`.',
      'Any value other than `advisory` or `strict` is a validation error.',
    ],
    evidence: 'pkg/models/policy_merge.go',
  },
];
