import type { WikiApiRoute } from '../types.js';

/**
 * REST surface registered in services/nopsai/routes.go.
 *
 * Every route passes the same chain: request ID, CORS, body limit, logging,
 * recovery, audit, authentication, then authorization. `access` describes the
 * gate before resource-level AAA checks run.
 */
export const apiRoutes: WikiApiRoute[] = [
  // Platform probes
  { method: 'GET', path: '/healthz', area: 'Platform probes', access: 'public', purpose: 'Readiness. Stays unready while setup preflight is retrying an unreachable database.' },
  { method: 'GET', path: '/livez', area: 'Platform probes', access: 'public', purpose: 'Liveness. Answers as soon as the process is up, independent of database state.' },
  { method: 'GET', path: '/version', area: 'Platform probes', access: 'public', purpose: 'Build identity: version, commit, build date, and release manifest digest.' },
  { method: 'GET', path: '/metrics', area: 'Platform probes', access: 'public', purpose: 'Prometheus metrics, including identity-provider capability and authorization grant ownership series.', notes: 'Set METRICS_REQUIRE_AUTH=true to require a bearer token.' },
  { method: 'GET', path: '/favicon.ico', area: 'Platform probes', access: 'public', purpose: 'Empty cacheable browser probe so missing-favicon requests do not create bearer token errors in audit logs.' },

  // Setup
  { method: 'GET', path: '/v1/setup/preflight', area: 'First-install setup', access: 'public', purpose: 'Reports what still blocks setup, including a database that is still starting.' },
  { method: 'GET', path: '/v1/setup/status', area: 'First-install setup', access: 'public', purpose: 'Whether first-install setup has already completed.' },
  { method: 'POST', path: '/v1/setup/bootstrap', area: 'First-install setup', access: 'public', purpose: 'Runs the one-time bootstrap. Normal authenticated routes stay locked until this succeeds once.', notes: 'Apply errors include the actionable write or configuration reason.' },
  { method: 'GET', path: '/v1/setup/templates', area: 'First-install setup', access: 'public', purpose: 'GitOps seed templates offered by the wizard.' },
  { method: 'GET', path: '/v1/setup/templates.zip', area: 'First-install setup', access: 'public', purpose: 'Same templates as a downloadable archive.' },

  // Authentication
  { method: 'GET', path: '/v1/auth/providers', area: 'Authentication', access: 'public', purpose: 'Login methods offered by this installation.' },
  { method: 'POST', path: '/v1/auth/discover', area: 'Authentication', access: 'public', purpose: 'Resolves which provider should handle a given login identifier.' },
  { method: 'POST', path: '/v1/auth/login', area: 'Authentication', access: 'public', purpose: 'Local username and password login.', notes: 'Rate limited and lockout protected.' },
  { method: 'GET', path: '/v1/auth/oidc/{provider}/start', area: 'Authentication', access: 'public', purpose: 'Begins an OIDC authorization code flow.' },
  { method: 'GET', path: '/v1/auth/oidc/{provider}/callback', area: 'Authentication', access: 'public', purpose: 'Completes the OIDC flow and establishes identity from provider ID, issuer, and subject.' },
  { method: 'GET', path: '/v1/auth/oauth2/{provider}/start', area: 'Authentication', access: 'public', purpose: 'Begins an OAuth2 flow for providers without full OIDC discovery.' },
  { method: 'GET', path: '/v1/auth/oauth2/{provider}/callback', area: 'Authentication', access: 'public', purpose: 'Completes the OAuth2 flow.' },
  { method: 'POST', path: '/v1/auth/session/exchange', area: 'Authentication', access: 'public', purpose: 'Exchanges a browser session artifact for API tokens.' },
  { method: 'POST', path: '/v1/auth/refresh', area: 'Authentication', access: 'public', purpose: 'Issues a new access token from a refresh token.' },
  { method: 'POST', path: '/v1/auth/logout', area: 'Authentication', access: 'authenticated', purpose: 'Ends the current session and invalidates its refresh token.' },
  { method: 'GET', path: '/v1/auth/me', area: 'Authentication', access: 'authenticated', purpose: 'Current identity, roles, and effective capabilities.' },
  { method: 'POST', path: '/v1/auth/password', area: 'Authentication', access: 'authenticated', purpose: 'Changes the caller password, including the forced first-login rotation.' },
  { method: 'POST', path: '/v1/auth/email', area: 'Authentication', access: 'authenticated', purpose: 'Updates the caller email. Email is metadata, not identity.' },
  { method: 'GET', path: '/v1/auth/personal-tokens', area: 'Authentication', access: 'authenticated', purpose: 'Lists the caller personal access tokens.' },
  { method: 'POST', path: '/v1/auth/personal-tokens', area: 'Authentication', access: 'authenticated', purpose: 'Creates a personal access token. The value is returned once.' },
  { method: 'DELETE', path: '/v1/auth/personal-tokens/{tokenID}', area: 'Authentication', access: 'authenticated', purpose: 'Revokes a personal access token.' },

  // Administration
  { method: 'GET', path: '/v1/admin/users', area: 'Identity administration', access: 'admin', purpose: 'Lists user accounts.' },
  { method: 'POST', path: '/v1/admin/users', area: 'Identity administration', access: 'admin', purpose: 'Creates a local user account.' },
  { method: 'PUT', path: '/v1/admin/users/{userID}', area: 'Identity administration', access: 'admin', purpose: 'Replaces a user record.' },
  { method: 'PATCH', path: '/v1/admin/users/{userID}', area: 'Identity administration', access: 'admin', purpose: 'Partially updates a user record.' },
  { method: 'DELETE', path: '/v1/admin/users/{userID}', area: 'Identity administration', access: 'admin', purpose: 'Deletes a user account.' },
  { method: 'GET', path: '/v1/admin/service-accounts', area: 'Identity administration', access: 'admin', purpose: 'Lists service accounts used for automation.' },
  { method: 'POST', path: '/v1/admin/service-accounts', area: 'Identity administration', access: 'admin', purpose: 'Creates a service account.' },
  { method: 'PUT', path: '/v1/admin/service-accounts/{serviceAccountID}', area: 'Identity administration', access: 'admin', purpose: 'Replaces a service account record.' },
  { method: 'PATCH', path: '/v1/admin/service-accounts/{serviceAccountID}', area: 'Identity administration', access: 'admin', purpose: 'Partially updates a service account.' },
  { method: 'DELETE', path: '/v1/admin/service-accounts/{serviceAccountID}', area: 'Identity administration', access: 'admin', purpose: 'Deletes a service account.' },
  { method: 'GET', path: '/v1/admin/service-accounts/{serviceAccountID}/tokens', area: 'Identity administration', access: 'admin', purpose: 'Lists tokens issued to a service account.' },
  { method: 'POST', path: '/v1/admin/service-accounts/{serviceAccountID}/tokens', area: 'Identity administration', access: 'admin', purpose: 'Issues a service account token. The value is returned once.' },
  { method: 'DELETE', path: '/v1/admin/service-accounts/{serviceAccountID}/tokens/{tokenID}', area: 'Identity administration', access: 'admin', purpose: 'Revokes a service account token.' },
  { method: 'GET', path: '/v1/admin/roles', area: 'Identity administration', access: 'admin', purpose: 'Lists product roles.' },
  { method: 'POST', path: '/v1/admin/roles', area: 'Identity administration', access: 'admin', purpose: 'Creates a product role.' },
  { method: 'DELETE', path: '/v1/admin/roles', area: 'Identity administration', access: 'admin', purpose: 'Deletes a product role.' },
  { method: 'POST', path: '/v1/admin/user-roles', area: 'Identity administration', access: 'admin', purpose: 'Grants a role to a user.' },
  { method: 'DELETE', path: '/v1/admin/user-roles', area: 'Identity administration', access: 'admin', purpose: 'Removes a role from a user.' },
  { method: 'POST', path: '/v1/admin/service-account-roles', area: 'Identity administration', access: 'admin', purpose: 'Grants a role to a service account.' },
  { method: 'DELETE', path: '/v1/admin/service-account-roles', area: 'Identity administration', access: 'admin', purpose: 'Removes a role from a service account.' },
  { method: 'GET', path: '/v1/admin/identity-providers', area: 'Identity administration', access: 'admin', purpose: 'Lists configured identity providers.' },
  { method: 'PUT', path: '/v1/admin/identity-providers', area: 'Identity administration', access: 'admin', purpose: 'Replaces the provider set.', notes: 'Only one external provider can be active per installation.' },
  { method: 'PUT', path: '/v1/admin/identity-providers/{provider}', area: 'Identity administration', access: 'admin', purpose: 'Creates or updates one provider.' },
  { method: 'DELETE', path: '/v1/admin/identity-providers/{provider}', area: 'Identity administration', access: 'admin', purpose: 'Removes a provider.' },
  { method: 'GET', path: '/v1/audit', area: 'Identity administration', access: 'authorized', purpose: 'Reads authorization and mutation audit records.' },

  // Access control
  { method: 'GET', path: '/v1/access/teams', area: 'Access control', access: 'authenticated', purpose: 'Lists product team paths, including the selectable `global` bucket.' },
  { method: 'GET', path: '/v1/access/auth-teams', area: 'Access control', access: 'authenticated', purpose: 'Lists AAA auth-team subjects mirrored from product teams and SSO mapping.' },
  { method: 'GET', path: '/v1/access/grants', area: 'Access control', access: 'authorized', purpose: 'Lists access grants.' },
  { method: 'POST', path: '/v1/access/grants', area: 'Access control', access: 'authorized', purpose: 'Creates an access grant.', notes: 'IdP sync owns only `source: idp` grants; local grants stay editable.' },
  { method: 'DELETE', path: '/v1/access/grants/{grantID}', area: 'Access control', access: 'authorized', purpose: 'Removes an access grant.' },
  { method: 'GET', path: '/v1/access/effective-permissions', area: 'Access control', access: 'authenticated', purpose: 'Resolves what the caller may do, optionally for a `team_path` or `run_team_path` that has no resource row yet.', notes: 'This is how team-scoped create preflight works before a first resource exists.' },
  { method: 'POST', path: '/v1/authz/resource-use/check', area: 'Access control', access: 'authenticated', purpose: 'Checks whether the caller may use one referenced resource.' },
  { method: 'POST', path: '/v1/authz/resource-use/batch-check', area: 'Access control', access: 'authenticated', purpose: 'Batch form of the resource-use check.' },
  { method: 'ANY', path: '/v1/resources/...', area: 'Access control', access: 'authorized', purpose: 'Reads settings, changes visibility, and adds or removes use grants for a concrete resource.', notes: 'Handler-authorized: middleware defers, then the handler resolves the resource and checks owner-level manage access.' },

  // Pipelines and steps
  { method: 'GET', path: '/v1/pipelines', area: 'Pipelines and steps', access: 'authorized', purpose: 'Lists pipelines the caller can see.' },
  { method: 'GET', path: '/v1/pipelines/{pipelineName...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Reads one pipeline definition.' },
  { method: 'PUT', path: '/v1/pipelines/{pipelineName...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Creates or updates a pipeline.', notes: 'Editing a GitOps-managed pipeline creates a database override.' },
  { method: 'DELETE', path: '/v1/pipelines/{pipelineName...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Deletes a pipeline.' },
  { method: 'POST', path: '/v1/pipelines/validate', area: 'Pipelines and steps', access: 'authenticated', purpose: 'Validates pipeline YAML without saving it.' },
  { method: 'GET', path: '/v1/steps', area: 'Pipelines and steps', access: 'authorized', purpose: 'Lists reusable step definitions.' },
  { method: 'GET', path: '/v1/steps/{stepPath...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Reads one reusable step.' },
  { method: 'PUT', path: '/v1/steps/{stepName...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Creates or updates a reusable step.' },
  { method: 'DELETE', path: '/v1/steps/{stepName...}', area: 'Pipelines and steps', access: 'authorized', purpose: 'Deletes a reusable step.' },
  { method: 'POST', path: '/v1/steps/validate', area: 'Pipelines and steps', access: 'authenticated', purpose: 'Validates a reusable step definition.' },

  // Runs
  { method: 'POST', path: '/v1/run', area: 'Runs', access: 'authorized', purpose: 'Starts a run from an inline or referenced pipeline.' },
  { method: 'POST', path: '/v1/run/{pipelineName...}', area: 'Runs', access: 'authorized', purpose: 'Starts a run of a stored pipeline.' },
  { method: 'GET', path: '/v1/runs', area: 'Runs', access: 'authorized', purpose: 'Lists runs. Exposes only lightweight aggregate `final_output_status` metadata.' },
  { method: 'GET', path: '/v1/runs/{runID}', area: 'Runs', access: 'authorized', purpose: 'Full run detail including steps, tasks, and outputs.' },
  { method: 'GET', path: '/v1/runs/{runID}/status', area: 'Runs', access: 'authorized', purpose: 'Compact run status for polling.' },
  { method: 'GET', path: '/v1/runs/{runID}/logs', area: 'Runs', access: 'authorized', purpose: 'Durable pipeline run logs.', notes: 'Declared secrets, sensitive variable names, and outputs marked `sensitive` are masked.' },
  { method: 'POST', path: '/v1/runs/{runID}/cancel', area: 'Runs', access: 'authorized', purpose: 'Cancels an active run.' },
  { method: 'POST', path: '/v1/runs/{runID}/rerun', area: 'Runs', access: 'authorized', purpose: 'Starts a new run from the same definition and inputs.' },
  { method: 'DELETE', path: '/v1/runs/{runID}', area: 'Runs', access: 'authorized', purpose: 'Deletes a run record.' },
  { method: 'GET', path: '/v1/runs/{runID}/approvals', area: 'Runs', access: 'authorized', purpose: 'Lists approval checkpoints on a run.' },
  { method: 'POST', path: '/v1/runs/{runID}/approvals/{approvalID}/approve', area: 'Runs', access: 'authorized', purpose: 'Approves a checkpoint. Comment optional.' },
  { method: 'POST', path: '/v1/runs/{runID}/approvals/{approvalID}/reject', area: 'Runs', access: 'authorized', purpose: 'Rejects a checkpoint. Comment required.' },
  { method: 'GET', path: '/v1/runs/{runID}/outputs/{outputID}/download', area: 'Runs', access: 'authorized', purpose: 'Downloads generated final output content.' },
  { method: 'POST', path: '/v1/runs/{runID}/outputs/{outputID}/retry', area: 'Runs', access: 'authorized', purpose: 'Retries a failed final output.', notes: 'Provider and network errors are not retried automatically.' },
  { method: 'POST', path: '/v1/runs/{runID}/outputs/{outputID}/cancel', area: 'Runs', access: 'authorized', purpose: 'Cancels in-progress final output generation.' },
  { method: 'GET', path: '/v1/runs-by-check/{checkRunID}', area: 'Runs', access: 'authorized', purpose: 'Resolves the run behind a GitHub check run.' },
  { method: 'DELETE', path: '/v1/repositories/{repoOwner}/{repoName}/branches/{branch...}', area: 'Runs', access: 'authorized', purpose: 'Deletes runs recorded for a deleted branch.' },

  // Schedules
  { method: 'GET', path: '/v1/schedules', area: 'Schedules', access: 'authorized', purpose: 'Lists pipeline schedules.' },
  { method: 'POST', path: '/v1/schedules', area: 'Schedules', access: 'authorized', purpose: 'Creates a schedule.' },
  { method: 'GET', path: '/v1/schedules/{scheduleID}', area: 'Schedules', access: 'authorized', purpose: 'Reads one schedule.' },
  { method: 'PUT', path: '/v1/schedules/{scheduleID}', area: 'Schedules', access: 'authorized', purpose: 'Replaces a schedule.' },
  { method: 'PATCH', path: '/v1/schedules/{scheduleID}', area: 'Schedules', access: 'authorized', purpose: 'Partially updates a schedule.' },
  { method: 'DELETE', path: '/v1/schedules/{scheduleID}', area: 'Schedules', access: 'authorized', purpose: 'Deletes a schedule.' },
  { method: 'POST', path: '/v1/schedules/{scheduleID}/enable', area: 'Schedules', access: 'authorized', purpose: 'Enables a schedule.' },
  { method: 'POST', path: '/v1/schedules/{scheduleID}/disable', area: 'Schedules', access: 'authorized', purpose: 'Disables a schedule without deleting it.' },
  { method: 'POST', path: '/v1/schedules/{scheduleID}/run', area: 'Schedules', access: 'authorized', purpose: 'Runs the schedule immediately, outside its cadence.' },

  // External triggers
  { method: 'GET', path: '/v1/external-triggers', area: 'External triggers', access: 'authorized', purpose: 'Lists external API triggers.' },
  { method: 'POST', path: '/v1/external-triggers', area: 'External triggers', access: 'authorized', purpose: 'Creates an external trigger.' },
  { method: 'GET', path: '/v1/external-triggers/{id}', area: 'External triggers', access: 'authorized', purpose: 'Reads one external trigger.' },
  { method: 'PUT', path: '/v1/external-triggers/{id}', area: 'External triggers', access: 'authorized', purpose: 'Replaces an external trigger.' },
  { method: 'PATCH', path: '/v1/external-triggers/{id}', area: 'External triggers', access: 'authorized', purpose: 'Partially updates an external trigger.' },
  { method: 'DELETE', path: '/v1/external-triggers/{id}', area: 'External triggers', access: 'authorized', purpose: 'Deletes an external trigger.' },
  { method: 'POST', path: '/v1/external-triggers/{id}/invoke', area: 'External triggers', access: 'authorized', purpose: 'Invokes the trigger and starts a run.', notes: 'Honours allowed_callers, payload_schema, rate_limit.per_minute, and idempotency_key.' },
  { method: 'GET', path: '/v1/external-triggers/{id}/invocations', area: 'External triggers', access: 'authorized', purpose: 'Invocation history for the trigger.' },

  // Git integration
  { method: 'POST', path: '/v1/git/webhooks/{sourceID}', area: 'Git integration', access: 'public', purpose: 'Signed webhook ingress for GitLab, Bitbucket, Gitea, and generic sources.' },
  { method: 'POST', path: '/v1/git/events', area: 'Git integration', access: 'service', purpose: 'Internal ingress for GitHub App events forwarded by git-bot.', notes: 'Requires a git-bot service token. This is not public webhook ingress.' },
  { method: 'GET', path: '/v1/git-webhook-sources', area: 'Git integration', access: 'authorized', purpose: 'Lists managed Git webhook sources.' },
  { method: 'POST', path: '/v1/git-webhook-sources', area: 'Git integration', access: 'authorized', purpose: 'Creates a webhook source and its signing secret.' },
  { method: 'GET', path: '/v1/git-webhook-sources/{sourceID}', area: 'Git integration', access: 'authorized', purpose: 'Reads one webhook source.' },
  { method: 'PUT', path: '/v1/git-webhook-sources/{sourceID}', area: 'Git integration', access: 'authorized', purpose: 'Replaces a webhook source.' },
  { method: 'PATCH', path: '/v1/git-webhook-sources/{sourceID}', area: 'Git integration', access: 'authorized', purpose: 'Partially updates a webhook source.' },
  { method: 'DELETE', path: '/v1/git-webhook-sources/{sourceID}', area: 'Git integration', access: 'authorized', purpose: 'Deletes a webhook source.' },
  { method: 'GET', path: '/v1/git-webhook-sources/{sourceID}/deliveries', area: 'Git integration', access: 'authorized', purpose: 'Recent deliveries for diagnosis.' },
  { method: 'GET', path: '/v1/git-apps/github', area: 'Git integration', access: 'authorized', purpose: 'Reads GitHub App configuration.' },
  { method: 'PUT', path: '/v1/git-apps/github', area: 'Git integration', access: 'authorized', purpose: 'Updates GitHub App configuration.', notes: 'Writes land in setting/git-apps/github.yaml.' },
  { method: 'GET', path: '/v1/git-apps/github/installations', area: 'Git integration', access: 'authorized', purpose: 'Lists App installations.' },
  { method: 'POST', path: '/v1/git-apps/github/installations', area: 'Git integration', access: 'authorized', purpose: 'Adds an installation.' },
  { method: 'GET', path: '/v1/git-apps/github/installations/{installationID}', area: 'Git integration', access: 'authorized', purpose: 'Reads one installation.' },
  { method: 'DELETE', path: '/v1/git-apps/github/installations/{installationID}', area: 'Git integration', access: 'authorized', purpose: 'Removes an installation.' },
  { method: 'POST', path: '/v1/git-apps/github/installations/{installationID}/verify', area: 'Git integration', access: 'authorized', purpose: 'Verifies credentials and reachability.' },
  { method: 'POST', path: '/v1/git-apps/github/installations/{installationID}/refresh', area: 'Git integration', access: 'authorized', purpose: 'Refreshes cached installation metadata.' },
  { method: 'GET', path: '/v1/git-apps/github/installations/{installationID}/repositories', area: 'Git integration', access: 'authorized', purpose: 'Lists repositories the installation can reach.' },
  { method: 'GET', path: '/v1/overrides', area: 'Git integration', access: 'authorized', purpose: 'Lists NopsAI-managed trigger overrides.' },
  { method: 'GET', path: '/v1/overrides/{repoOwner}/{repoName}', area: 'Git integration', access: 'authorized', purpose: 'Reads the override for one repository.' },
  { method: 'PUT', path: '/v1/overrides/{repoOwner}/{repoName}', area: 'Git integration', access: 'authorized', purpose: 'Sets a trigger override for a repository.' },
  { method: 'DELETE', path: '/v1/overrides/{repoOwner}/{repoName}', area: 'Git integration', access: 'authorized', purpose: 'Removes a trigger override.' },
  { method: 'POST', path: '/v1/overrides/validate', area: 'Git integration', access: 'authenticated', purpose: 'Validates trigger override content before saving.' },

  // Teams
  { method: 'GET', path: '/v1/teams', area: 'Teams', access: 'authorized', purpose: 'Lists the team hierarchy.' },
  { method: 'POST', path: '/v1/teams', area: 'Teams', access: 'authorized', purpose: 'Creates a team.' },
  { method: 'GET', path: '/v1/teams/{teamID}', area: 'Teams', access: 'authorized', purpose: 'Reads one team.' },
  { method: 'PUT', path: '/v1/teams/{teamID}', area: 'Teams', access: 'authorized', purpose: 'Updates a team.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}', area: 'Teams', access: 'authorized', purpose: 'Deletes a team.' },
  { method: 'GET', path: '/v1/teams/{teamID}/applications', area: 'Teams', access: 'authorized', purpose: 'Lists applications owned by a team.' },
  { method: 'POST', path: '/v1/teams/{teamID}/applications', area: 'Teams', access: 'authorized', purpose: 'Creates a team application.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/applications/{applicationID}', area: 'Teams', access: 'authorized', purpose: 'Updates a team application.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/applications/{applicationID}', area: 'Teams', access: 'authorized', purpose: 'Deletes a team application.' },
  { method: 'GET', path: '/v1/teams/{teamID}/defaults', area: 'Teams', access: 'authorized', purpose: 'Reads team default profiles and settings.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/defaults', area: 'Teams', access: 'authorized', purpose: 'Updates team defaults.' },
  { method: 'GET', path: '/v1/teams/{teamID}/notifications', area: 'Teams', access: 'authorized', purpose: 'Reads team notification routes.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/notifications', area: 'Teams', access: 'authorized', purpose: 'Sets team notification routes.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/notifications', area: 'Teams', access: 'authorized', purpose: 'Removes team notification routes.' },
  { method: 'GET', path: '/v1/teams/{teamID}/models', area: 'Teams', access: 'authorized', purpose: 'Lists team-owned models.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/models', area: 'Teams', access: 'authorized', purpose: 'Replaces the team model set.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/models/default', area: 'Teams', access: 'authorized', purpose: 'Sets the team default model.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/models/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Creates or updates one team model.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/models/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Deletes a team model.' },
  { method: 'GET', path: '/v1/teams/{teamID}/agent-roles', area: 'Teams', access: 'authorized', purpose: 'Lists team-owned Agent roles.' },
  { method: 'POST', path: '/v1/teams/{teamID}/agent-roles', area: 'Teams', access: 'authorized', purpose: 'Creates a team Agent role.' },
  { method: 'GET', path: '/v1/teams/{teamID}/agent-roles/{profileID}', area: 'Teams', access: 'authorized', purpose: 'Reads one team Agent role.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/agent-roles/{profileID}', area: 'Teams', access: 'authorized', purpose: 'Updates a team Agent role.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/agent-roles/default', area: 'Teams', access: 'authorized', purpose: 'Sets the team default Agent role.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/agent-roles/{profileID}', area: 'Teams', access: 'authorized', purpose: 'Deletes a team Agent role.' },
  { method: 'GET', path: '/v1/teams/{teamID}/mcp/profiles', area: 'Teams', access: 'authorized', purpose: 'Lists team-owned MCP profiles.' },
  { method: 'POST', path: '/v1/teams/{teamID}/mcp/profiles', area: 'Teams', access: 'authorized', purpose: 'Creates a team MCP profile.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/mcp/profiles/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Updates a team MCP profile.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/mcp/profiles/{profileName}', area: 'Teams', access: 'authorized', purpose: 'Deletes a team MCP profile.' },

  // GitOps
  { method: 'GET', path: '/v1/teams/{teamID}/config-repository', area: 'GitOps and config sync', access: 'authorized', purpose: 'Reads the team configuration repository binding.' },
  { method: 'PUT', path: '/v1/teams/{teamID}/config-repository', area: 'GitOps and config sync', access: 'authorized', purpose: 'Binds a team to a configuration repository.' },
  { method: 'DELETE', path: '/v1/teams/{teamID}/config-repository', area: 'GitOps and config sync', access: 'authorized', purpose: 'Unbinds the team repository.' },
  { method: 'POST', path: '/v1/teams/{teamID}/config-repository/sync', area: 'GitOps and config sync', access: 'authorized', purpose: 'Starts a sync from the team repository.' },
  { method: 'GET', path: '/v1/teams/{teamID}/config-repository/sync', area: 'GitOps and config sync', access: 'authorized', purpose: 'Reads sync state and history.' },
  { method: 'POST', path: '/v1/teams/{teamID}/config-repository/sync/cancel', area: 'GitOps and config sync', access: 'authorized', purpose: 'Cancels a running sync.', notes: 'If no worker is registered but the row is still running, the row is marked canceled so operators can retry.' },
  { method: 'GET', path: '/v1/teams/{teamID}/config-repository/drift', area: 'GitOps and config sync', access: 'authorized', purpose: 'Line-level drift between Git and desired state.' },
  { method: 'POST', path: '/v1/teams/{teamID}/config-repository/write', area: 'GitOps and config sync', access: 'authorized', purpose: 'Pushes desired state back to the repository.' },
  { method: 'POST', path: '/v1/teams/{teamID}/config-repository/validate', area: 'GitOps and config sync', access: 'authorized', purpose: 'Validates repository content without applying it.' },
  { method: 'GET', path: '/v1/system/config-repo', area: 'GitOps and config sync', access: 'admin', purpose: 'Reads the global configuration repository binding.' },
  { method: 'PUT', path: '/v1/system/config-repo', area: 'GitOps and config sync', access: 'admin', purpose: 'Sets the global configuration repository.' },
  { method: 'DELETE', path: '/v1/system/config-repo', area: 'GitOps and config sync', access: 'admin', purpose: 'Removes the global binding.' },
  { method: 'POST', path: '/v1/system/config-repo/sync', area: 'GitOps and config sync', access: 'admin', purpose: 'Syncs the global configuration repository.' },
  { method: 'POST', path: '/v1/system/config-repo/sync/cancel', area: 'GitOps and config sync', access: 'admin', purpose: 'Cancels the global sync.' },
  { method: 'GET', path: '/v1/system/config-repo/drift', area: 'GitOps and config sync', access: 'admin', purpose: 'Global drift review.' },
  { method: 'POST', path: '/v1/system/config-repo/write', area: 'GitOps and config sync', access: 'admin', purpose: 'Pushes global desired state to Git.' },
  { method: 'POST', path: '/v1/system/config-repo/validate', area: 'GitOps and config sync', access: 'admin', purpose: 'Validates global repository content.' },
  { method: 'GET', path: '/v1/system/config-repos', area: 'GitOps and config sync', access: 'admin', purpose: 'Lists every bound configuration repository.' },
  { method: 'POST', path: '/v1/system/config-repos/sync', area: 'GitOps and config sync', access: 'admin', purpose: 'Syncs all bound repositories.' },
  { method: 'POST', path: '/v1/system/config-repos/sync/cancel', area: 'GitOps and config sync', access: 'admin', purpose: 'Cancels all running syncs.' },

  // Scopes, variables, secrets, credentials
  { method: 'GET', path: '/v1/variables', area: 'Variables and secrets', access: 'authorized', purpose: 'Lists scope variables.' },
  { method: 'GET', path: '/v1/variables/scopes', area: 'Variables and secrets', access: 'authorized', purpose: 'Lists scopes that contain variables.' },
  { method: 'GET', path: '/v1/variables/{variableName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Reads one variable value.' },
  { method: 'PUT', path: '/v1/variables/{variableName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Creates or updates a variable.' },
  { method: 'DELETE', path: '/v1/variables/{variableName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Deletes a variable.' },
  { method: 'GET', path: '/v1/secrets', area: 'Variables and secrets', access: 'authorized', purpose: 'Lists secret names and metadata.', notes: 'Secret values are write-only and never returned.' },
  { method: 'GET', path: '/v1/secrets/scopes', area: 'Variables and secrets', access: 'authorized', purpose: 'Lists scopes that contain secrets.' },
  { method: 'GET', path: '/v1/secrets/{secretName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Reads secret metadata.' },
  { method: 'PUT', path: '/v1/secrets/{secretName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Creates or updates a secret value.' },
  { method: 'DELETE', path: '/v1/secrets/{secretName}', area: 'Variables and secrets', access: 'authorized', purpose: 'Deletes a secret.' },
  { method: 'POST', path: '/v1/secrets/encrypt', area: 'Variables and secrets', access: 'authorized', purpose: 'Produces a GitOps-safe encrypted envelope for a secret value.' },
  { method: 'GET', path: '/v1/system/credentials', area: 'Variables and secrets', access: 'admin', purpose: 'Lists registry credentials and their versions.' },
  { method: 'POST', path: '/v1/system/credentials', area: 'Variables and secrets', access: 'admin', purpose: 'Creates a credential.' },
  { method: 'GET', path: '/v1/system/credentials/{credentialID}', area: 'Variables and secrets', access: 'admin', purpose: 'Reads credential metadata. The value is not returned.' },
  { method: 'PUT', path: '/v1/system/credentials/{credentialID}/value', area: 'Variables and secrets', access: 'admin', purpose: 'Rotates the credential value, creating a new version.' },
  { method: 'POST', path: '/v1/system/credentials/{credentialID}/versions/{version}/activate', area: 'Variables and secrets', access: 'admin', purpose: 'Activates a specific credential version.' },
  { method: 'DELETE', path: '/v1/system/credentials/{credentialID}/versions/{version}', area: 'Variables and secrets', access: 'admin', purpose: 'Deletes a credential version.' },
  { method: 'POST', path: '/v1/system/credentials/{credentialID}/enable', area: 'Variables and secrets', access: 'admin', purpose: 'Enables a credential.' },
  { method: 'POST', path: '/v1/system/credentials/{credentialID}/disable', area: 'Variables and secrets', access: 'admin', purpose: 'Disables a credential without deleting it.' },
  { method: 'DELETE', path: '/v1/system/credentials/{credentialID}', area: 'Variables and secrets', access: 'admin', purpose: 'Deletes a credential.' },

  // AI configuration
  { method: 'GET', path: '/v1/system/models', area: 'AI configuration', access: 'admin', purpose: 'Lists system models.' },
  { method: 'PUT', path: '/v1/system/models', area: 'AI configuration', access: 'admin', purpose: 'Replaces the system model registry.' },
  { method: 'PUT', path: '/v1/system/models/{profileName}', area: 'AI configuration', access: 'admin', purpose: 'Creates or updates one model.' },
  { method: 'DELETE', path: '/v1/system/models/{profileName}', area: 'AI configuration', access: 'admin', purpose: 'Deletes an model.' },
  { method: 'POST', path: '/v1/system/models/{profileName}/test', area: 'AI configuration', access: 'admin', purpose: 'Sends a test request through the profile and its credential.' },
  { method: 'GET', path: '/v1/system/agent-roles', area: 'AI configuration', access: 'admin', purpose: 'Lists system Agent roles.' },
  { method: 'POST', path: '/v1/system/agent-roles', area: 'AI configuration', access: 'admin', purpose: 'Creates an Agent role.' },
  { method: 'GET', path: '/v1/system/agent-roles/{profileID}', area: 'AI configuration', access: 'admin', purpose: 'Reads one Agent role.' },
  { method: 'PUT', path: '/v1/system/agent-roles/{profileID}', area: 'AI configuration', access: 'admin', purpose: 'Updates an Agent role.' },
  { method: 'DELETE', path: '/v1/system/agent-roles/{profileID}', area: 'AI configuration', access: 'admin', purpose: 'Deletes an Agent role.' },
  { method: 'PUT', path: '/v1/system/agent-roles/default', area: 'AI configuration', access: 'admin', purpose: 'Sets the platform default Agent role.' },
  { method: 'GET', path: '/v1/system/agent-roles/{profileID}/usage', area: 'AI configuration', access: 'admin', purpose: 'Shows which pipelines and steps reference the profile.' },
  { method: 'POST', path: '/v1/system/agent-roles/validate', area: 'AI configuration', access: 'admin', purpose: 'Validates an Agent role definition.' },
  { method: 'GET', path: '/v1/system/mcp/servers', area: 'AI configuration', access: 'admin', purpose: 'Lists external MCP servers.' },
  { method: 'POST', path: '/v1/system/mcp/servers', area: 'AI configuration', access: 'admin', purpose: 'Registers an MCP server.' },
  { method: 'GET', path: '/v1/system/mcp/servers/{serverName}', area: 'AI configuration', access: 'admin', purpose: 'Reads one MCP server.' },
  { method: 'PUT', path: '/v1/system/mcp/servers/{serverName}', area: 'AI configuration', access: 'admin', purpose: 'Updates an MCP server.' },
  { method: 'DELETE', path: '/v1/system/mcp/servers/{serverName}', area: 'AI configuration', access: 'admin', purpose: 'Removes an MCP server.' },
  { method: 'POST', path: '/v1/system/mcp/servers/{serverName}/test', area: 'AI configuration', access: 'admin', purpose: 'Tests reachability and authentication.' },
  { method: 'POST', path: '/v1/system/mcp/servers/{serverName}/discover-tools', area: 'AI configuration', access: 'admin', purpose: 'Discovers the tool list the server exposes.' },
  { method: 'GET', path: '/v1/system/mcp/profiles', area: 'AI configuration', access: 'admin', purpose: 'Lists MCP profiles.' },
  { method: 'POST', path: '/v1/system/mcp/profiles', area: 'AI configuration', access: 'admin', purpose: 'Creates an MCP profile allowlist.' },
  { method: 'GET', path: '/v1/system/mcp/profiles/{profileName}', area: 'AI configuration', access: 'admin', purpose: 'Reads one MCP profile.' },
  { method: 'PUT', path: '/v1/system/mcp/profiles/{profileName}', area: 'AI configuration', access: 'admin', purpose: 'Updates an MCP profile.' },
  { method: 'DELETE', path: '/v1/system/mcp/profiles/{profileName}', area: 'AI configuration', access: 'admin', purpose: 'Deletes an MCP profile.' },
  { method: 'POST', path: '/v1/system/mcp/profiles/{profileName}/test', area: 'AI configuration', access: 'admin', purpose: 'Tests every server in the profile.' },

  // Knowledge
  { method: 'GET', path: '/v1/knowledge-contexts', area: 'Knowledge Context', access: 'authorized', purpose: 'Lists managed knowledge documents.' },
  { method: 'GET', path: '/v1/knowledge-contexts/{knowledgeID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Reads one document and its revision metadata.' },
  { method: 'PUT', path: '/v1/knowledge-contexts/{knowledgeID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Creates or updates a document.', notes: 'Run snapshots are immutable; later edits do not rewrite run history.' },
  { method: 'POST', path: '/v1/knowledge-contexts/{knowledgeID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Document sub-actions such as revision operations.' },
  { method: 'DELETE', path: '/v1/knowledge-contexts/{knowledgeID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Deletes a document.' },
  { method: 'GET', path: '/v1/knowledge-connections', area: 'Knowledge Context', access: 'authorized', purpose: 'Lists external knowledge connections.' },
  { method: 'POST', path: '/v1/knowledge-connections', area: 'Knowledge Context', access: 'authorized', purpose: 'Creates an external knowledge connection.' },
  { method: 'POST', path: '/v1/knowledge-connections/{connectionID}/test', area: 'Knowledge Context', access: 'authorized', purpose: 'Tests connection credentials and reachability.' },
  { method: 'GET', path: '/v1/knowledge-connections/{connectionID}/pages', area: 'Knowledge Context', access: 'authorized', purpose: 'Lists pages available through the connection.' },
  { method: 'POST', path: '/v1/knowledge-connections/{connectionID}/resolve-page', area: 'Knowledge Context', access: 'authorized', purpose: 'Resolves a page reference into an importable document.' },
  { method: 'DELETE', path: '/v1/knowledge-connections/{connectionID...}', area: 'Knowledge Context', access: 'authorized', purpose: 'Deletes a knowledge connection.' },

  // Dashboards
  { method: 'GET', path: '/v1/dashboards', area: 'Dashboards', access: 'authorized', purpose: 'Lists team dashboards.' },
  { method: 'POST', path: '/v1/dashboards', area: 'Dashboards', access: 'authorized', purpose: 'Creates a dashboard.', notes: 'The UI create flow requires selecting at least one matching dashboard-output pipeline.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}', area: 'Dashboards', access: 'authorized', purpose: 'Reads dashboard configuration.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/view', area: 'Dashboards', access: 'authorized', purpose: 'Reads the rendered dashboard with current entries.' },
  { method: 'PUT', path: '/v1/dashboards/{dashboardID}', area: 'Dashboards', access: 'authorized', purpose: 'Replaces a dashboard.' },
  { method: 'PATCH', path: '/v1/dashboards/{dashboardID}', area: 'Dashboards', access: 'authorized', purpose: 'Partially updates a dashboard.' },
  { method: 'DELETE', path: '/v1/dashboards/{dashboardID}', area: 'Dashboards', access: 'authorized', purpose: 'Deletes a dashboard.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/sections', area: 'Dashboards', access: 'authorized', purpose: 'Lists sections that pipeline outputs publish into.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/sections', area: 'Dashboards', access: 'authorized', purpose: 'Creates a section.' },
  { method: 'PUT', path: '/v1/dashboards/{dashboardID}/sections/{sectionID}', area: 'Dashboards', access: 'authorized', purpose: 'Replaces a section.' },
  { method: 'PATCH', path: '/v1/dashboards/{dashboardID}/sections/{sectionID}', area: 'Dashboards', access: 'authorized', purpose: 'Partially updates a section.' },
  { method: 'DELETE', path: '/v1/dashboards/{dashboardID}/sections/{sectionID}', area: 'Dashboards', access: 'authorized', purpose: 'Deletes a section.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/sources', area: 'Dashboards', access: 'authorized', purpose: 'Lists pipeline source bindings feeding the dashboard.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/sources', area: 'Dashboards', access: 'authorized', purpose: 'Binds a pipeline source.' },
  { method: 'PUT', path: '/v1/dashboards/{dashboardID}/sources/{sourceID}', area: 'Dashboards', access: 'authorized', purpose: 'Replaces a source binding.' },
  { method: 'DELETE', path: '/v1/dashboards/{dashboardID}/sources/{sourceID}', area: 'Dashboards', access: 'authorized', purpose: 'Removes a source binding.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/history', area: 'Dashboards', access: 'authorized', purpose: 'Publication history for the dashboard.' },
  { method: 'DELETE', path: '/v1/dashboards/{dashboardID}/publications/{publicationID}', area: 'Dashboards', access: 'authorized', purpose: 'Deletes one published entry.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refresh', area: 'Dashboards', access: 'authorized', purpose: 'Refreshes the dashboard by running its bound sources.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/refreshes', area: 'Dashboards', access: 'authorized', purpose: 'Lists refresh operations.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}', area: 'Dashboards', access: 'authorized', purpose: 'Reads one refresh operation.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}/cancel', area: 'Dashboards', access: 'authorized', purpose: 'Cancels a running refresh.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refreshes/{refreshID}/retry-failed', area: 'Dashboards', access: 'authorized', purpose: 'Retries only the failed parts of a refresh.' },
  { method: 'GET', path: '/v1/dashboards/{dashboardID}/refresh-schedules', area: 'Dashboards', access: 'authorized', purpose: 'Lists scheduled refreshes.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refresh-schedules', area: 'Dashboards', access: 'authorized', purpose: 'Creates a scheduled refresh.' },
  { method: 'PUT', path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}', area: 'Dashboards', access: 'authorized', purpose: 'Replaces a scheduled refresh.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/enable', area: 'Dashboards', access: 'authorized', purpose: 'Enables a scheduled refresh.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/disable', area: 'Dashboards', access: 'authorized', purpose: 'Disables a scheduled refresh.' },
  { method: 'POST', path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/run', area: 'Dashboards', access: 'authorized', purpose: 'Runs a scheduled refresh immediately.' },
  { method: 'DELETE', path: '/v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}', area: 'Dashboards', access: 'authorized', purpose: 'Deletes a scheduled refresh.' },

  // Monitoring
  { method: 'GET', path: '/v1/monitoring/summary', area: 'Monitoring', access: 'authorized', purpose: 'Authorization-filtered platform summary.' },
  { method: 'GET', path: '/v1/monitoring/runs/analytics', area: 'Monitoring', access: 'authorized', purpose: 'Run volume, outcome, and duration analytics.' },
  { method: 'GET', path: '/v1/monitoring/pipelines/performance', area: 'Monitoring', access: 'authorized', purpose: 'Per-pipeline performance.' },
  { method: 'GET', path: '/v1/monitoring/steps/performance', area: 'Monitoring', access: 'authorized', purpose: 'Per-step performance.' },
  { method: 'GET', path: '/v1/monitoring/tasks/performance', area: 'Monitoring', access: 'authorized', purpose: 'Per-task performance.' },
  { method: 'GET', path: '/v1/monitoring/triggers/analytics', area: 'Monitoring', access: 'authorized', purpose: 'Git trigger match and run analytics.' },
  { method: 'GET', path: '/v1/monitoring/external-triggers/analytics', area: 'Monitoring', access: 'authorized', purpose: 'External trigger invocation analytics.' },
  { method: 'GET', path: '/v1/monitoring/ai-usage', area: 'Monitoring', access: 'authorized', purpose: 'LLM usage and cost telemetry.', notes: 'Records hashes, revision markers, and token counts without storing prompt bodies.' },
  { method: 'GET', path: '/v1/monitoring/reliability', area: 'Monitoring', access: 'authorized', purpose: 'Reliability view across runs and runners.' },
  { method: 'GET', path: '/v1/monitoring/efficiency', area: 'Monitoring', access: 'authorized', purpose: 'Efficiency and resource-use view.' },
  { method: 'GET', path: '/v1/monitoring/security', area: 'Monitoring', access: 'authorized', purpose: 'Security-relevant events and authorization outcomes.' },
  { method: 'GET', path: '/v1/monitoring/dispatcher', area: 'Monitoring', access: 'authorized', purpose: 'Dispatcher and runner fleet state.' },
  { method: 'GET', path: '/v1/monitoring/runners/history', area: 'Monitoring', access: 'authorized', purpose: 'Runner connection and capacity history.' },
  { method: 'GET', path: '/v1/monitoring/recommendations', area: 'Monitoring', access: 'authorized', purpose: 'Maintenance and cost recommendations.' },
  { method: 'POST', path: '/v1/monitoring/recommendations/{recommendationID}/acknowledge', area: 'Monitoring', access: 'authorized', purpose: 'Acknowledges a recommendation.' },
  { method: 'POST', path: '/v1/monitoring/recommendations/{recommendationID}/resolve', area: 'Monitoring', access: 'authorized', purpose: 'Resolves a recommendation.' },
  { method: 'GET', path: '/v1/monitoring/alert-rules', area: 'Monitoring', access: 'authorized', purpose: 'Lists alert rules.' },
  { method: 'POST', path: '/v1/monitoring/alert-rules', area: 'Monitoring', access: 'authorized', purpose: 'Creates an alert rule.' },
  { method: 'PUT', path: '/v1/monitoring/alert-rules/{ruleID}', area: 'Monitoring', access: 'authorized', purpose: 'Updates an alert rule.' },
  { method: 'DELETE', path: '/v1/monitoring/alert-rules/{ruleID}', area: 'Monitoring', access: 'authorized', purpose: 'Deletes an alert rule.' },
  { method: 'POST', path: '/v1/monitoring/alert-rules/{ruleID}/evaluate', area: 'Monitoring', access: 'authorized', purpose: 'Evaluates a rule immediately.' },
  { method: 'GET', path: '/v1/monitoring/alert-events', area: 'Monitoring', access: 'authorized', purpose: 'Lists alert events.' },
  { method: 'GET', path: '/v1/monitoring/views', area: 'Monitoring', access: 'authorized', purpose: 'Lists saved monitoring views.' },
  { method: 'POST', path: '/v1/monitoring/views', area: 'Monitoring', access: 'authorized', purpose: 'Creates a saved view.' },
  { method: 'PUT', path: '/v1/monitoring/views/{viewID}', area: 'Monitoring', access: 'authorized', purpose: 'Updates a saved view.' },
  { method: 'DELETE', path: '/v1/monitoring/views/{viewID}', area: 'Monitoring', access: 'authorized', purpose: 'Deletes a saved view.' },

  // System operations
  { method: 'GET', path: '/v1/system/config', area: 'System operations', access: 'admin', purpose: 'Reads effective runtime configuration.' },
  { method: 'PUT', path: '/v1/system/config', area: 'System operations', access: 'admin', purpose: 'Updates runtime configuration.' },
  { method: 'GET', path: '/v1/system/dispatcher', area: 'System operations', access: 'admin', purpose: 'Dispatcher overview and runner fleet.' },
  { method: 'GET', path: '/v1/system/dispatcher/scopes', area: 'System operations', access: 'admin', purpose: 'Effective routing view derived from registered runner scopes.' },
  { method: 'POST', path: '/v1/system/dispatcher/runners/{runnerID}/dispatch', area: 'System operations', access: 'admin', purpose: 'Pauses or resumes dispatch to one runner.' },
  { method: 'DELETE', path: '/v1/system/dispatcher/runners/{runnerID}', area: 'System operations', access: 'admin', purpose: 'Ejects a runner: disconnects it, clears status, and adds the ID to `ejected_runner_ids`.', notes: 'Ordinary network disconnects keep the registration available for reconnect.' },
  { method: 'GET', path: '/v1/system/dispatcher/runner-bootstrap', area: 'System operations', access: 'admin', purpose: 'Generates Docker runner bootstrap material.' },
  { method: 'GET', path: '/v1/system/dispatcher/runner-bootstrap-command', area: 'System operations', access: 'admin', purpose: 'Generates the one-line Docker runner install command.' },
  { method: 'GET', path: '/v1/system/dispatcher/runner-compose', area: 'System operations', access: 'admin', purpose: 'Generates a Compose file for a standalone Docker runner.' },
  { method: 'GET', path: '/v1/system/dispatcher/kubernetes-runner-manifest', area: 'System operations', access: 'admin', purpose: 'Generates Kubernetes runner manifests.' },
  { method: 'GET', path: '/v1/system/dispatcher/kubernetes-runner-bootstrap-command', area: 'System operations', access: 'admin', purpose: 'Generates the Kubernetes runner install command.' },
  { method: 'GET', path: '/v1/system/logs/sources', area: 'System operations', access: 'admin', purpose: 'Lists allow-listed platform log sources, including `runner:<runner-id>` entries.' },
  { method: 'GET', path: '/v1/system/logs/sources/{sourceID}/stream', area: 'System operations', access: 'admin', purpose: 'Live log stream over authenticated SSE.' },
  { method: 'GET', path: '/v1/system/logs/sources/{sourceID}/tail', area: 'System operations', access: 'admin', purpose: 'Bounded tail of recent lines.' },
  { method: 'GET', path: '/v1/system/notifications/mail', area: 'System operations', access: 'admin', purpose: 'Reads SMTP notification settings.' },
  { method: 'PUT', path: '/v1/system/notifications/mail', area: 'System operations', access: 'admin', purpose: 'Updates SMTP notification settings.' },
  { method: 'POST', path: '/v1/system/notifications/mail/test', area: 'System operations', access: 'admin', purpose: 'Sends a test notification email.' },
  { method: 'GET', path: '/v1/system/data/backups', area: 'System operations', access: 'admin', purpose: 'Lists backups with checksum metadata.' },
  { method: 'POST', path: '/v1/system/data/backups', area: 'System operations', access: 'admin', purpose: 'Creates a gzip-compressed JSON Lines backup.' },
  { method: 'GET', path: '/v1/system/data/backups/{backupID}/download', area: 'System operations', access: 'admin', purpose: 'Downloads a backup file.' },
  { method: 'DELETE', path: '/v1/system/data/backups/{backupID}', area: 'System operations', access: 'admin', purpose: 'Deletes a backup.' },
  { method: 'POST', path: '/v1/system/data/cleanup/preview', area: 'System operations', access: 'admin', purpose: 'Previews what a cleanup would remove.' },
  { method: 'POST', path: '/v1/system/data/cleanup/run', area: 'System operations', access: 'admin', purpose: 'Runs a cleanup immediately.' },
  { method: 'GET', path: '/v1/system/data/cleanup/jobs', area: 'System operations', access: 'admin', purpose: 'Lists cleanup jobs and their outcomes.' },
  { method: 'GET', path: '/v1/system/data/cleanup/schedules', area: 'System operations', access: 'admin', purpose: 'Lists cleanup schedules.' },
  { method: 'POST', path: '/v1/system/data/cleanup/schedules', area: 'System operations', access: 'admin', purpose: 'Creates a cleanup schedule.' },
  { method: 'PUT', path: '/v1/system/data/cleanup/schedules/{scheduleID}', area: 'System operations', access: 'admin', purpose: 'Updates a cleanup schedule.' },
  { method: 'POST', path: '/v1/system/data/cleanup/schedules/{scheduleID}/run', area: 'System operations', access: 'admin', purpose: 'Runs a cleanup schedule now.' },
  { method: 'DELETE', path: '/v1/system/data/cleanup/schedules/{scheduleID}', area: 'System operations', access: 'admin', purpose: 'Deletes a cleanup schedule.' },

  // Assistant, analysis, hosted MCP
  { method: 'GET', path: '/v1/assistant/config', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Assistant availability and enabled feature flags.' },
  { method: 'GET', path: '/v1/assistant/models', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'models the caller may select for Assistant and AI Evaluation.' },
  { method: 'GET', path: '/v1/assistant/conversations', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Lists the caller conversations.' },
  { method: 'POST', path: '/v1/assistant/conversations', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Starts a conversation.' },
  { method: 'GET', path: '/v1/assistant/conversations/{id}', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Reads one conversation.' },
  { method: 'POST', path: '/v1/assistant/conversations/{id}/messages', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Sends a message.', notes: 'Page context is metadata only: route, area, tab, team/scope, selected IDs, allow-listed filters.' },
  { method: 'POST', path: '/v1/assistant/conversations/{id}/summarize-memory', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Compacts conversation memory.' },
  { method: 'DELETE', path: '/v1/assistant/conversations/{id}', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Deletes a conversation.' },
  { method: 'POST', path: '/v1/analysis/evaluate', area: 'Assistant and AI surfaces', access: 'authorized', purpose: 'Runs a structured AI Evaluation over a redacted reviewer snapshot.', notes: 'Does not create an Assistant conversation or ask hosted MCP to inspect resources.' },
  { method: 'POST', path: '/v1/mcp', area: 'Assistant and AI surfaces', access: 'authenticated', purpose: 'Hosted NopsAI MCP endpoint, filtered by the caller AAA permissions.' },

  // Internal service routes
  { method: 'POST', path: '/v1/internal/config/sync', area: 'Internal service routes', access: 'service', purpose: 'Config sync worker callback.' },
  { method: 'GET', path: '/v1/internal/dispatcher/routing', area: 'Internal service routes', access: 'service', purpose: 'Routing map read by the dispatcher.' },
  { method: 'GET', path: '/v1/internal/git-bot/bootstrap', area: 'Internal service routes', access: 'service', purpose: 'git-bot bootstrap configuration.' },
  { method: 'GET', path: '/v1/internal/git-bot/installations', area: 'Internal service routes', access: 'service', purpose: 'Installation list for git-bot routing.' },
  { method: 'POST', path: '/v1/internal/runs/{runID}/ai-usage', area: 'Internal service routes', access: 'service', purpose: 'Agent reports LLM usage telemetry.' },
  { method: 'POST', path: '/v1/internal/runs/{runID}/approvals/pause', area: 'Internal service routes', access: 'service', purpose: 'Agent pauses a run at an approval checkpoint and releases capacity.' },
  { method: 'GET', path: '/v1/internal/runs/{runID}/checkpoints/{checkpointID}', area: 'Internal service routes', access: 'service', purpose: 'Agent reads durable checkpoint state on resume.' },
  { method: 'GET', path: '/v1/internal/runs/{runID}/policy-revision', area: 'Internal service routes', access: 'service', purpose: 'Agent reads the pinned policy revision for the run.' },
  { method: 'POST', path: '/v1/internal/runs/{runID}/steps/{stepName}/tasks/{taskName}/outputs', area: 'Internal service routes', access: 'service', purpose: 'Agent publishes runtime task outputs.' },
  { method: 'POST', path: '/v1/internal/runs/{runID}/task-outputs/resolve', area: 'Internal service routes', access: 'service', purpose: 'Agent resolves upstream output references.' },
  { method: 'POST', path: '/v1/runs/{runID}/logs/ingest', area: 'Internal service routes', access: 'service', purpose: 'Durable run-log ingestion.', notes: 'Applies best-effort credential-pattern redaction, including escaped JSON inside agent messages.' },
  { method: 'POST', path: '/v1/runs/{runID}/steps/{stepName}/tasks/{taskName}', area: 'Internal service routes', access: 'service', purpose: 'Agent reports task status transitions.' },
  { method: 'POST', path: '/v1/runs/{runID}/finalize', area: 'Internal service routes', access: 'service', purpose: 'Agent finalizes a run and triggers final output generation.' },
];
