import type { WikiField } from '../types.js';

/**
 * Bootstrap values a deployment must supply before GitOps can take over.
 * `scope` names the service that reads the value.
 */
export const bootstrapEnvironmentFields: WikiField[] = [
  {
    path: 'DATABASE_URL',
    scope: 'api, aaa',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description:
      'PostgreSQL connection string for runtime state, config sync state, auth records, run records, logs, and evidence.',
    example: 'DATABASE_URL=postgres://nopsai:***@db:5432/nopsai?sslmode=disable',
    constraints: ['Compose fails fast with `set DATABASE_URL` when it is missing.'],
    security: 'Holds every durable product record. Treat as a top-tier secret.',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'NOPSAI_MASTER_KEY',
    scope: 'api',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Root application encryption material for the credential registry and encrypted envelopes.',
    example: 'NOPSAI_MASTER_KEY=<32+ byte random value>',
    security: 'Losing this key makes every stored credential unrecoverable; rotating it requires re-encrypting the registry.',
    evidence: 'config/config.go',
  },
  {
    path: 'JWT_SIGNING_KEY',
    scope: 'api',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description:
      'Signs user, personal-access, service-account, browser, CLI, automation, and hosted MCP tokens.',
    example: 'JWT_SIGNING_KEY=<high-entropy value>',
    security: 'Must be a different secret from SERVICE_JWT_SIGNING_KEY so user tokens cannot impersonate services.',
    evidence: 'config/config.go',
  },
  {
    path: 'SERVICE_JWT_SIGNING_KEY',
    scope: 'api, dispatcher, git-bot, runners, agents',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Signs internal REST and dispatcher service tokens between platform components.',
    example: 'SERVICE_JWT_SIGNING_KEY=<high-entropy value>',
    security:
      'Shared by every component. Rotating it, together with DISPATCHER_TLS_SECRET, is what stops retired runners from rejoining.',
    evidence: 'config/config.go',
  },
  {
    path: 'AAA_SHARED_INTERNAL_TOKEN',
    scope: 'api, aaa',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Authenticates internal authorization checks from the API to the AAA service.',
    example: 'AAA_SHARED_INTERNAL_TOKEN=<high-entropy value>',
    security: 'Anyone holding this token can ask AAA for authorization decisions directly.',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_BOOTSTRAP_ADMIN_EMAIL',
    scope: 'api',
    type: 'string',
    required: true,
    defaultValue: 'admin@example.com in Compose',
    description: 'Email address of the first local bootstrap administrator.',
    example: 'NOPSAI_BOOTSTRAP_ADMIN_EMAIL=platform-admin@example.com',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'NOPSAI_BOOTSTRAP_ADMIN_PASSWORD',
    scope: 'api',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Initial password used to create or rotate the first local bootstrap administrator.',
    example: 'NOPSAI_BOOTSTRAP_ADMIN_PASSWORD=<generated value>',
    constraints: ['Generated Docker Compose installs reject the built-in development `admin` password.'],
    security: 'Rotates on first login by default. See NOPSAI_BOOTSTRAP_ADMIN_MUST_CHANGE_PASSWORD.',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'NOPSAI_BOOTSTRAP_ADMIN_PASSWORD_FILE',
    scope: 'api',
    type: 'path',
    required: false,
    defaultValue: 'None',
    description: 'File path form of the bootstrap password, for secret managers that mount files.',
    example: 'NOPSAI_BOOTSTRAP_ADMIN_PASSWORD_FILE=/run/secrets/bootstrap-admin-password',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_BOOTSTRAP_ADMIN_MUST_CHANGE_PASSWORD',
    scope: 'api',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    description: 'Forces the bootstrap administrator to rotate the password at first login.',
    example: 'NOPSAI_BOOTSTRAP_ADMIN_MUST_CHANGE_PASSWORD=true',
    security: 'Turning this off leaves a deployment-provisioned password in place indefinitely.',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'NOPSAI_BOOTSTRAP_ADMIN_ALLOW_DEFAULT_PASSWORD',
    scope: 'api',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Allows the built-in development password. Intended for throwaway local environments only.',
    example: 'NOPSAI_BOOTSTRAP_ADMIN_ALLOW_DEFAULT_PASSWORD=false',
    security: 'Must stay false in any environment reachable by more than one person.',
    evidence: 'docker-compose.yaml',
  },
];

/** Where each component finds the others. */
export const serviceTopologyFields: WikiField[] = [
  {
    path: 'NOPSAI_API_URL',
    scope: 'dispatcher, git-bot, runners',
    type: 'url',
    required: true,
    defaultValue: 'http://nopsai:8080 in Compose',
    description: 'Private API callback URL used by components that report back to the control plane.',
    example: 'NOPSAI_API_URL=http://nopsai:8080',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'AAA_API_URL',
    scope: 'api',
    type: 'url',
    required: true,
    defaultValue: 'http://aaa:8082 in Compose',
    description: 'Private URL of the AAA authorization service.',
    example: 'AAA_API_URL=http://aaa:8082',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'GIT_BOT_API_URL',
    scope: 'api',
    type: 'url',
    required: true,
    defaultValue: 'None',
    description: 'Private git-bot URL used for repository fetch/write and GitHub check-run updates.',
    example: 'GIT_BOT_API_URL=http://git-bot:8083',
    evidence: 'config/config.go',
  },
  {
    path: 'DISPATCHER_GRPC_ADDRESS',
    scope: 'api, runners, agents',
    type: 'host:port',
    required: true,
    defaultValue: 'dispatcher:9090 in Helm, dispatcher:9091 in Compose',
    description:
      'Dispatcher gRPC endpoint. Cross-namespace Kubernetes runners normally need the fully qualified `dispatcher.<platform-namespace>.svc.cluster.local:9090`.',
    example: 'DISPATCHER_GRPC_ADDRESS=dispatcher.nopsai.svc.cluster.local:9090',
    constraints: [
      'The dispatcher container itself listens on :9090 unless DISPATCHER_LISTEN_ADDRESS overrides it.',
      'Helm reads this from `topology.dispatcherGRPCAddress`.',
    ],
    evidence: 'deploy/helm/nopsai/values.yaml',
  },
  {
    path: 'NOPSAI_LISTEN_ADDRESS',
    scope: 'api',
    type: 'host:port',
    required: false,
    defaultValue: ':8080',
    description: 'Bind address for the API HTTP server.',
    example: 'NOPSAI_LISTEN_ADDRESS=:8080',
    evidence: 'config/config.go',
  },
  {
    path: 'AAA_LISTEN_ADDRESS',
    scope: 'aaa',
    type: 'host:port',
    required: false,
    defaultValue: ':8082',
    description: 'Bind address for the AAA service.',
    example: 'AAA_LISTEN_ADDRESS=:8082',
    evidence: 'config/config.go',
  },
  {
    path: 'DISPATCHER_LISTEN_ADDRESS',
    scope: 'dispatcher',
    type: 'host:port',
    required: false,
    defaultValue: ':9090',
    description: 'Bind address for the dispatcher gRPC server.',
    example: 'DISPATCHER_LISTEN_ADDRESS=:9090',
    evidence: 'services/dispatcher/internal/app/app.go',
  },
  {
    path: 'GIT_BOT_LISTEN_ADDRESS',
    scope: 'git-bot',
    type: 'host:port',
    required: false,
    defaultValue: ':8083',
    description: 'Bind address for the git-bot service.',
    example: 'GIT_BOT_LISTEN_ADDRESS=:8083',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_PUBLIC_URL',
    scope: 'api',
    type: 'url',
    required: false,
    defaultValue: 'None',
    description: 'Externally reachable base URL, used in notification links and OIDC redirect construction.',
    example: 'NOPSAI_PUBLIC_URL=https://nopsai.example.com',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_PLATFORM_ID',
    scope: 'api, runners',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description:
      'Ownership boundary that keeps bundled runners and generated runner installs attributed to the same platform.',
    example: 'NOPSAI_PLATFORM_ID=prod-eu',
    evidence: 'config/config.go',
  },
];

/** Transport security between the control plane and the execution plane. */
export const dispatcherSecurityFields: WikiField[] = [
  {
    path: 'DISPATCHER_TLS_MODE',
    scope: 'dispatcher, runners, agents',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Transport mode for dispatcher gRPC.',
    example: 'DISPATCHER_TLS_MODE=mtls',
    allowedValues: ['mtls', 'tls', 'disabled'],
    security: 'Production must not use `disabled`. Startup gates check this when production gates are required.',
    evidence: 'config/config.go',
  },
  {
    path: 'DISPATCHER_TLS_SECRET',
    scope: 'dispatcher, runners, agents',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Shared high-entropy TLS or mTLS bootstrap secret. Required unless the mode is `disabled`.',
    example: 'DISPATCHER_TLS_SECRET=<high-entropy value>',
    security:
      'Rotate together with SERVICE_JWT_SIGNING_KEY before exposing a fresh dispatcher, otherwise old runner definitions can authenticate again.',
    evidence: 'config/config.go',
  },
  {
    path: 'DISPATCHER_TLS_SERVER_NAME',
    scope: 'runners, agents',
    type: 'string',
    required: false,
    defaultValue: 'Host from DISPATCHER_GRPC_ADDRESS',
    description: 'Server name presented during TLS verification when it differs from the dial address.',
    example: 'DISPATCHER_TLS_SERVER_NAME=dispatcher.nopsai.svc',
    evidence: 'config/config.go',
  },
  {
    path: 'DISPATCHER_ROUTING',
    scope: 'dispatcher',
    type: 'map<string,string[]>',
    required: false,
    defaultValue: 'None',
    description: 'Configured route map from scope to runner IDs. GitOps owns this; the live view is derived from registered runners.',
    example: 'DISPATCHER_ROUTING=platform/production=runner-a,runner-b',
    evidence: 'config/config.go',
  },
];

/** Runner and execution-plane settings. */
export const runnerEnvironmentFields: WikiField[] = [
  {
    path: 'RUNTIME',
    scope: 'runner',
    type: 'string',
    required: false,
    defaultValue: 'docker',
    description: 'Execution runtime the runner provides. Hybrid deployments use a comma-separated list.',
    example: 'RUNTIME=docker,kubernetes',
    allowedValues: ['docker', 'kubernetes'],
    evidence: 'config/config.go',
  },
  {
    path: 'RUNNER_ID',
    scope: 'runner',
    type: 'string',
    required: true,
    defaultValue: 'Generated with a unique suffix',
    description: 'Dispatcher identity for this runner. Generated installs add a unique suffix to the friendly name.',
    example: 'RUNNER_ID=eu-build-01-7f2a',
    constraints: ['Deliberate runner removal adds this ID to `ejected_runner_ids` and blocks reconnection.'],
    evidence: 'config/config.go',
  },
  {
    path: 'RUNNER_NAME',
    scope: 'runner',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Friendly name preserved by generated installs and shown in the dispatcher fleet view.',
    example: 'RUNNER_NAME=eu-build-01',
  },
  {
    path: 'RUNNER_SCOPES',
    scope: 'runner',
    type: 'string',
    required: false,
    defaultValue: 'All scopes',
    description: 'Scopes this runner accepts work for. An explicit empty value means all scopes.',
    example: 'RUNNER_SCOPES=platform/production,platform/staging',
    evidence: 'config/config.go',
  },
  {
    path: 'RUNNER_CAPACITY',
    scope: 'runner',
    type: 'integer',
    required: false,
    defaultValue: 'Runner default',
    description: 'Number of concurrent runs this runner advertises to the dispatcher.',
    example: 'RUNNER_CAPACITY=4',
    evidence: 'config/config.go',
  },
  {
    path: 'DOCKER_NETWORK_NAME',
    scope: 'docker runner',
    type: 'string',
    required: false,
    defaultValue: 'Docker bridge',
    description:
      'Network joined by step containers. Blank, `bridge`, or `default` keeps normal egress; `none` disables step networking; any other value joins that network.',
    example: 'DOCKER_NETWORK_NAME=none',
    allowedValues: ['bridge', 'default', 'none', '<custom network name>'],
    security: 'Use `none` when step workloads must run without egress, or a dedicated network for controlled egress.',
    evidence: 'config/config.go',
  },
  {
    path: 'RUNTIME_POOLS',
    scope: 'kubernetes runner',
    type: 'map',
    required: false,
    defaultValue: 'None',
    description: 'Named Kubernetes runtime pools selectable through pipeline or step `runtime_pool`.',
    example: 'RUNTIME_POOLS=gpu:node-role=gpu',
    evidence: 'config/config.go',
  },
  {
    path: 'KUBERNETES_NAMESPACE',
    scope: 'kubernetes runner',
    type: 'string',
    required: false,
    defaultValue: 'Runner namespace',
    description: 'Namespace where the runner creates agent pods, step pods, and workspace PVCs.',
    example: 'KUBERNETES_NAMESPACE=nopsai-runners',
    evidence: 'config/config.go',
  },
  {
    path: 'KUBERNETES_SERVICE_ACCOUNT',
    scope: 'kubernetes runner',
    type: 'string',
    required: false,
    defaultValue: 'Chart-managed runner service account',
    description: 'RBAC-bearing service account used by the runner Deployment and agent pods.',
    example: 'KUBERNETES_SERVICE_ACCOUNT=nopsai-runner',
    evidence: 'deploy/helm/nopsai',
  },
  {
    path: 'KUBERNETES_WORKLOAD_SERVICE_ACCOUNT',
    scope: 'kubernetes runner',
    type: 'string',
    required: false,
    defaultValue: 'Chart-managed no-RBAC service account',
    description: 'Separate service account for step pods, deliberately without cluster permissions.',
    example: 'KUBERNETES_WORKLOAD_SERVICE_ACCOUNT=nopsai-workload',
    security: 'Keeping step pods on a no-RBAC account is what stops workload code from calling the Kubernetes API.',
    evidence: 'deploy/helm/nopsai',
  },
  {
    path: 'KUBERNETES_IMAGE_PULL_SECRETS',
    scope: 'kubernetes runner',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Infrastructure-owned pull secrets attached to runner and step pods for private registries.',
    example: 'KUBERNETES_IMAGE_PULL_SECRETS=regcred',
    evidence: 'config/config.go',
  },
  {
    path: 'KUBERNETES_STORAGE_CLASS',
    scope: 'kubernetes runner',
    type: 'string',
    required: false,
    defaultValue: 'Cluster default',
    description: 'Storage class used for the agent-owned workspace PVC.',
    example: 'KUBERNETES_STORAGE_CLASS=fast-ssd',
  },
  {
    path: 'KUBERNETES_DEFAULT_WORKSPACE_SIZE',
    scope: 'kubernetes runner',
    type: 'string',
    required: false,
    defaultValue: 'Chart default',
    description: 'Requested size of the run workspace PVC.',
    example: 'KUBERNETES_DEFAULT_WORKSPACE_SIZE=20Gi',
  },
  {
    path: 'KUBERNETES_AFFINITY_ENABLED',
    scope: 'kubernetes runner',
    type: 'boolean',
    required: false,
    defaultValue: 'Chart default',
    description: 'Whether step pods in a run are scheduled onto the same node by default.',
    example: 'KUBERNETES_AFFINITY_ENABLED=true',
    overriddenBy: ['pipeline affinity_enabled'],
  },
  {
    path: 'KUBERNETES_CLEANUP_FINISHED_PODS',
    scope: 'kubernetes runner',
    type: 'boolean',
    required: false,
    defaultValue: 'Chart default',
    description: 'Whether finished step pods are deleted after their status is reported.',
    example: 'KUBERNETES_CLEANUP_FINISHED_PODS=true',
  },
  {
    path: 'NOPSAI_REGISTRY_DOCKER_CONFIG_B64',
    scope: 'docker runner',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description:
      'Base64 Docker config delivered at runner bootstrap so Docker runners can build per-image RegistryAuth locally.',
    example: 'NOPSAI_REGISTRY_DOCKER_CONFIG_B64=<base64 docker config json>',
    constraints: ['The legacy `/v1/internal/registry-auth/docker` broker route has been removed.'],
    security: 'Keeps registry credentials on the runner instead of brokering them per image pull.',
    evidence: 'doc/runner-registry-auth.md',
  },
];

/** Operational and rendering settings on the API. */
export const operationsEnvironmentFields: WikiField[] = [
  {
    path: 'SYSTEM_LOGS_PROVIDER',
    scope: 'api',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Provider used to read live platform logs. Hybrid deployments use a comma-separated list.',
    example: 'SYSTEM_LOGS_PROVIDER=docker,kubernetes',
    allowedValues: ['docker', 'kubernetes'],
    evidence: 'config/config.go',
  },
  {
    path: 'SYSTEM_LOGS_DOCKER_HOST',
    scope: 'api',
    type: 'url',
    required: 'conditional',
    defaultValue: 'tcp://docker-socket-proxy:2375 in Compose',
    description: 'Restricted Docker endpoint used for System Logs. Required for the docker provider.',
    example: 'SYSTEM_LOGS_DOCKER_HOST=tcp://docker-socket-proxy:2375',
    security:
      'Point this at the restricted socket proxy, never the raw Docker socket. The proxy allow-lists the reads System Logs needs.',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'SYSTEM_LOGS_KUBERNETES_NAMESPACE',
    scope: 'api',
    type: 'string',
    required: false,
    defaultValue: 'Platform namespace',
    description: 'Namespace searched for platform pods when the kubernetes provider is used.',
    example: 'SYSTEM_LOGS_KUBERNETES_NAMESPACE=nopsai',
  },
  {
    path: 'SYSTEM_LOGS_KUBERNETES_LABEL_SELECTOR',
    scope: 'api',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Label selector limiting which pods appear as System Logs sources.',
    example: 'SYSTEM_LOGS_KUBERNETES_LABEL_SELECTOR=app.kubernetes.io/part-of=nopsai',
  },
  {
    path: 'FINAL_OUTPUT_PDF_RENDERER_URL',
    scope: 'api',
    type: 'url',
    required: 'conditional',
    defaultValue: 'http://gotenberg:3000 in Compose',
    description: 'Gotenberg endpoint used to render PDF final outputs. Required for `type: pdf`.',
    example: 'FINAL_OUTPUT_PDF_RENDERER_URL=http://gotenberg:3000',
    evidence: 'docker-compose.yaml',
  },
  {
    path: 'FINAL_OUTPUT_PDF_TIMEOUT_SECONDS',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: '45',
    description: 'Timeout applied to a single PDF render request.',
    example: 'FINAL_OUTPUT_PDF_TIMEOUT_SECONDS=45',
    evidence: 'config.yml',
  },
  {
    path: 'RUNTIME_OUTPUT_MAX_BYTES',
    scope: 'api, agent',
    type: 'integer',
    required: false,
    defaultValue: '65536',
    description: 'Maximum size of a single runtime output value written under /nopsai/outputs.',
    example: 'RUNTIME_OUTPUT_MAX_BYTES=65536',
    evidence: 'config.yml',
  },
  {
    path: 'DEFAULT_PIPELINE_TIMEOUT',
    scope: 'api',
    type: 'duration',
    required: false,
    defaultValue: 'None',
    description: 'Fallback whole-run timeout applied when a pipeline does not declare `timeout`.',
    example: 'DEFAULT_PIPELINE_TIMEOUT=2h',
    evidence: 'config/config.go',
  },
  {
    path: 'DATA_BACKUP_DIR',
    scope: 'api',
    type: 'path',
    required: false,
    defaultValue: '/data/backups',
    description: 'Directory where product backups are written as gzip-compressed JSON Lines files.',
    example: 'DATA_BACKUP_DIR=/data/backups',
    constraints: ['The default Compose topology does not mount this path as durable storage.'],
    evidence: 'config/config.go',
  },
  {
    path: 'METRICS_REQUIRE_AUTH',
    scope: 'api',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Whether `GET /metrics` requires a bearer token. Public by default for scraper compatibility.',
    example: 'METRICS_REQUIRE_AUTH=true',
    security: 'Enable when the metrics endpoint is reachable outside the cluster network.',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_REQUIRE_PRODUCTION_GATES',
    scope: 'api',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Enforces the production startup gates, refusing to start on an unsafe configuration.',
    example: 'NOPSAI_REQUIRE_PRODUCTION_GATES=true',
    security: 'Turn this on in production so weak transport and default credentials fail startup instead of running.',
    evidence: 'pkg/startupgates/startupgates.go',
  },
  {
    path: 'AUTO_REMOVAL_AGENT_CONTAINER',
    scope: 'docker runner',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    description: 'Whether the per-run agent container is removed after the run completes.',
    example: 'AUTO_REMOVAL_AGENT_CONTAINER=false',
    evidence: 'config/config.go',
  },
  {
    path: 'LOG_LEVEL',
    scope: 'all services',
    type: 'string',
    required: false,
    defaultValue: 'info',
    description: 'Minimum severity written to service logs.',
    example: 'LOG_LEVEL=debug',
    allowedValues: ['debug', 'info', 'warn', 'error'],
    evidence: 'config/config.go',
  },
  {
    path: 'LOG_FORMAT',
    scope: 'all services',
    type: 'string',
    required: false,
    defaultValue: 'json',
    description: 'Service log encoding.',
    example: 'LOG_FORMAT=console',
    evidence: 'config/config.go',
  },
  {
    path: 'NOPSAI_ENVIRONMENT',
    scope: 'all services',
    type: 'string',
    required: false,
    defaultValue: 'local',
    description: 'Environment label attached to logs, metrics, and audit metadata.',
    example: 'NOPSAI_ENVIRONMENT=production',
    evidence: 'config/config.go',
  },
];

/** Authentication and session settings. */
export const authEnvironmentFields: WikiField[] = [
  {
    path: 'AUTH_PROVIDER_LOCAL_ENABLED',
    scope: 'api',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    description: 'Whether local username and password login is offered.',
    example: 'AUTH_PROVIDER_LOCAL_ENABLED=false',
    constraints: [
      'Can only be disabled while external authentication is enabled with at least one enabled provider.',
      'The protected break-glass administrator remains available regardless.',
    ],
    evidence: 'config/config.go',
  },
  {
    path: 'JWT_EXPIRY_MINUTES',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Lifetime of an issued access token.',
    example: 'JWT_EXPIRY_MINUTES=60',
    evidence: 'config/config.go',
  },
  {
    path: 'REFRESH_TOKEN_TTL_MINUTES',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Lifetime of a refresh token.',
    example: 'REFRESH_TOKEN_TTL_MINUTES=10080',
    evidence: 'config/config.go',
  },
  {
    path: 'IDLE_TIMEOUT_MINUTES',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Idle period after which a browser session is ended.',
    example: 'IDLE_TIMEOUT_MINUTES=30',
    evidence: 'config/config.go',
  },
  {
    path: 'RATE_LIMIT_LOGIN_PER_MINUTE',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Login attempts accepted per minute before requests are throttled.',
    example: 'RATE_LIMIT_LOGIN_PER_MINUTE=10',
    security: 'Together with the lockout settings, this is the brute-force control for local login.',
    evidence: 'config/config.go',
  },
  {
    path: 'LOGIN_LOCKOUT_THRESHOLD',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Failed attempts within the lockout window before an account is locked.',
    example: 'LOGIN_LOCKOUT_THRESHOLD=5',
    evidence: 'config/config.go',
  },
  {
    path: 'LOGIN_LOCKOUT_WINDOW_MINUTES',
    scope: 'api',
    type: 'integer',
    required: false,
    defaultValue: 'Platform default',
    description: 'Window over which failed login attempts are counted.',
    example: 'LOGIN_LOCKOUT_WINDOW_MINUTES=15',
    evidence: 'config/config.go',
  },
  {
    path: 'JWT_ISSUER',
    scope: 'api',
    type: 'string',
    required: false,
    defaultValue: 'Platform default',
    description: 'Issuer claim written into user and API tokens.',
    example: 'JWT_ISSUER=https://nopsai.example.com',
    evidence: 'config/config.go',
  },
  {
    path: 'JWT_AUDIENCE',
    scope: 'api',
    type: 'string',
    required: false,
    defaultValue: 'Platform default',
    description: 'Audience claim written into user and API tokens.',
    example: 'JWT_AUDIENCE=nopsai-api',
    evidence: 'config/config.go',
  },
  {
    path: 'JWT_RSA_KEY_PATH',
    scope: 'api',
    type: 'path',
    required: false,
    defaultValue: 'None',
    description: 'RSA private key path for asymmetric token signing instead of the shared HMAC key.',
    example: 'JWT_RSA_KEY_PATH=/run/secrets/jwt-rsa.pem',
    evidence: 'config/config.go',
  },
  {
    path: 'SERVICE_JWT_ISSUER',
    scope: 'all services',
    type: 'string',
    required: false,
    defaultValue: 'Platform default',
    description: 'Issuer claim for internal service tokens.',
    example: 'SERVICE_JWT_ISSUER=nopsai-internal',
    evidence: 'config/config.go',
  },
  {
    path: 'SERVICE_JWT_AUDIENCE',
    scope: 'all services',
    type: 'string',
    required: false,
    defaultValue: 'Platform default',
    description: 'Audience claim for internal service tokens.',
    example: 'SERVICE_JWT_AUDIENCE=nopsai-services',
    evidence: 'config/config.go',
  },
];

/** GitHub App bootstrap values read before GitOps takes over. */
export const gitAppEnvironmentFields: WikiField[] = [
  {
    path: 'GITHUB_APP_ID',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'GitHub App ID. The long-term source of truth is `setting/git-apps/github.yaml`.',
    example: 'GITHUB_APP_ID=1234567',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_INSTALLATION_ID',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Single-installation bootstrap value. Multi-installation setups use the GitOps file instead.',
    example: 'GITHUB_INSTALLATION_ID=87654321',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_PRIVATE_KEY_CREDENTIAL_REF',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Credential registry reference holding the GitHub App private key.',
    example: 'GITHUB_PRIVATE_KEY_CREDENTIAL_REF=git-apps/github-private-key',
    security: 'Preferred over the legacy inline key and key-path variables.',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_WEBHOOK_CREDENTIAL_REF',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Credential registry reference holding the GitHub webhook signing secret.',
    example: 'GITHUB_WEBHOOK_CREDENTIAL_REF=git-apps/github-webhook-secret',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_PRIVATE_KEY',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Legacy inline private key.',
    example: 'GITHUB_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----...',
    deprecatedIn: 'Superseded by GITHUB_PRIVATE_KEY_CREDENTIAL_REF',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_PRIVATE_KEY_PATH',
    scope: 'api, git-bot',
    type: 'path',
    required: false,
    defaultValue: 'None',
    description: 'Legacy private key file path.',
    example: 'GITHUB_PRIVATE_KEY_PATH=/run/secrets/github-app.pem',
    deprecatedIn: 'Superseded by GITHUB_PRIVATE_KEY_CREDENTIAL_REF',
    evidence: 'config/config.go',
  },
  {
    path: 'GITHUB_WEBHOOK_SECRET',
    scope: 'api, git-bot',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Legacy inline webhook signing secret.',
    example: 'GITHUB_WEBHOOK_SECRET=<shared secret>',
    deprecatedIn: 'Superseded by GITHUB_WEBHOOK_CREDENTIAL_REF',
    evidence: 'config/config.go',
  },
];

/** Every environment variable the wiki documents, in reading order. */
export const allEnvironmentFields: WikiField[] = [
  ...bootstrapEnvironmentFields,
  ...serviceTopologyFields,
  ...dispatcherSecurityFields,
  ...runnerEnvironmentFields,
  ...operationsEnvironmentFields,
  ...authEnvironmentFields,
  ...gitAppEnvironmentFields,
];
