import type { WikiField } from '../types.js';

/** `.nopsai.yaml` Git trigger manifest, read from the run repository. */
export const gitTriggerFields: WikiField[] = [
  {
    path: 'provider',
    scope: 'trigger manifest',
    type: 'string',
    required: false,
    defaultValue: 'github',
    description: 'Git provider the manifest is written for. Non-GitHub providers route through a managed Git Webhook Source.',
    example: 'provider: gitlab',
    allowedValues: ['github', 'gitlab', 'bitbucket', 'gitea', 'generic'],
    evidence: 'pkg/models/model.go',
  },
  {
    path: 'team',
    scope: 'trigger manifest',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Owning team or application boundary. Runs started by this manifest inherit it for ownership and notification lineage.',
    example: 'team: platform/payments',
  },
  {
    path: 'team_path',
    scope: 'trigger manifest',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Explicit product team path when the short `team` name is ambiguous.',
    example: 'team_path: platform/payments',
  },
  {
    path: 'webhook_source',
    scope: 'trigger manifest',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Managed Git Webhook Source ID. Required for GitLab, Bitbucket, Gitea, and generic providers.',
    example: 'webhook_source: gitlab-main',
    evidence: 'pkg/models/model.go',
  },
  {
    path: 'management',
    scope: 'trigger manifest',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Marks the manifest as NopsAI-managed so platform trigger overrides apply.',
    example: 'management: nopsai',
  },
  {
    path: 'triggers[].on',
    scope: 'trigger rule',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Event name to match. `all` matches any event from the provider.',
    example: 'on: push',
    allowedValues: ['all', 'push', 'pull_request', 'tag', 'provider-specific event names'],
    evidence: 'pkg/gittrigger/matcher.go',
  },
  {
    path: 'triggers[].branches',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Branch globs that must match. An empty list matches every branch.',
    example: 'branches:\n  - main\n  - release/*',
    evidence: 'pkg/gittrigger/matcher.go',
  },
  {
    path: 'triggers[].skip_branches',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Branch globs removed after include matching.',
    example: 'skip_branches:\n  - dependabot/*',
    evidence: 'pkg/gittrigger/matcher.go',
  },
  {
    path: 'triggers[].tags',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Tag globs matched on push tag events.',
    example: 'tags:\n  - "v*"',
  },
  {
    path: 'triggers[].skip_repos',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Repository patterns that skip this rule entirely.',
    example: 'skip_repos:\n  - acme/sandbox-*',
  },
  {
    path: 'triggers[].include_paths',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Changed-file globs that must match when changed-file metadata is available.',
    example: 'include_paths:\n  - "services/payments/**"',
    constraints: [
      'Path matching intentionally fails open: when the provider does not report changed files, the rule still matches so CI is not silently skipped.',
    ],
    evidence: 'pkg/gittrigger/matcher.go',
  },
  {
    path: 'triggers[].exclude_paths',
    scope: 'trigger rule',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Changed-file globs removed before include matching is evaluated.',
    example: 'exclude_paths:\n  - "**/*.md"',
    evidence: 'pkg/gittrigger/matcher.go',
  },
  {
    path: 'triggers[].pipelines',
    scope: 'trigger rule',
    type: 'string[]',
    required: true,
    defaultValue: 'None',
    description: 'Pipeline paths started when the rule matches. Declared as plain scalar paths.',
    example: 'pipelines:\n  - .nopsai/pipelines/ci.yaml',
    constraints: ['Only scalar path values are supported; an empty path is rejected at parse time.'],
    evidence: 'pkg/models/model.go',
  },
  {
    path: 'triggers[].scope',
    scope: 'trigger rule',
    type: 'string',
    required: false,
    defaultValue: 'Default runtime scope',
    description: 'Runtime scope used to resolve variables and secrets for the started run.',
    example: 'scope: platform/production',
  },
];

/** Pipeline schedule documents under `schedules/`. */
export const scheduleFields: WikiField[] = [
  {
    path: 'name',
    scope: 'schedule',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Schedule name, unique within its team path.',
    example: 'name: nightly-report',
    evidence: 'services/nopsai/config_repository_resource_export.go',
  },
  {
    path: 'description',
    scope: 'schedule',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Human-readable purpose shown in the schedule registry.',
    example: 'description: Nightly compliance report for the payments team.',
  },
  {
    path: 'pipeline',
    scope: 'schedule',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Stored pipeline identifier the schedule runs.',
    example: 'pipeline: platform/compliance-report',
    evidence: 'services/nopsai/config_repository_resource_export.go',
  },
  {
    path: 'schedule_kind',
    scope: 'schedule',
    type: 'string',
    required: false,
    defaultValue: 'cron',
    description: 'Whether the schedule repeats on a cron expression or fires once.',
    example: 'schedule_kind: once',
    allowedValues: ['cron', 'once'],
    evidence: 'services/nopsai/config_repository_resource_export.go',
  },
  {
    path: 'cron_expression',
    scope: 'schedule',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Cron expression for repeating schedules. The API also accepts `cron` as an alias.',
    example: 'cron_expression: "0 2 * * *"',
    constraints: ['Required when `schedule_kind: cron`.'],
  },
  {
    path: 'run_at',
    scope: 'schedule',
    type: 'timestamp',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Single execution timestamp for one-time schedules.',
    example: 'run_at: "2026-09-01T02:00:00Z"',
    constraints: ['Required when `schedule_kind: once`.', 'An enabled one-time schedule must be in the future.'],
  },
  {
    path: 'timezone',
    scope: 'schedule',
    type: 'string',
    required: false,
    defaultValue: 'UTC',
    description: 'IANA timezone used to interpret the cron expression or timestamp.',
    example: 'timezone: Europe/Amsterdam',
    evidence: 'services/nopsai/config_repository_resource_export.go',
  },
  {
    path: 'enabled',
    scope: 'schedule',
    type: 'boolean',
    required: true,
    defaultValue: 'None',
    description: 'Whether the schedule is active. Disabled schedules stay visible in the registry.',
    example: 'enabled: true',
  },
  {
    path: 'scope',
    scope: 'schedule',
    type: 'string',
    required: false,
    defaultValue: 'Default runtime scope',
    description: 'Runtime scope used to resolve variables and secrets for scheduled runs.',
    example: 'scope: platform/production',
  },
  {
    path: 'run_team_path',
    scope: 'schedule',
    type: 'string',
    required: false,
    defaultValue: 'global',
    description:
      'Team path applied to the resulting Pipeline Run for ownership and notification lineage. `global` means no concrete team assignment.',
    example: 'run_team_path: platform/payments',
    constraints: ['The Schedules UI groups the registry by this value, falling back to the schedule path for older rows.'],
    evidence: 'services/nopsai/config_repository_resource_export.go',
  },
  {
    path: 'variables',
    scope: 'schedule',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description: 'Run variable overrides supplied by the schedule.',
    example: 'variables:\n  REPORT_WINDOW: 24h',
  },
];

/** External API trigger documents under `external-triggers/`. */
export const externalTriggerFields: WikiField[] = [
  {
    path: 'name',
    scope: 'external trigger',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Trigger name used in the API path and the UI registry.',
    example: 'name: deploy-from-servicenow',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'pipeline',
    scope: 'external trigger',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Pipeline started when the trigger is invoked.',
    example: 'pipeline: platform/deploy-service',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'enabled',
    scope: 'external trigger',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    description: 'Whether invocations are accepted. Disabled triggers reject calls without starting a run.',
    example: 'enabled: true',
  },
  {
    path: 'scope',
    scope: 'external trigger',
    type: 'string',
    required: false,
    defaultValue: 'Default runtime scope',
    description: 'Runtime scope used to resolve variables and secrets for triggered runs.',
    example: 'scope: platform/production',
  },
  {
    path: 'run_team_path',
    scope: 'external trigger',
    type: 'string',
    required: false,
    defaultValue: 'global',
    description: 'Team path applied to the resulting Pipeline Run for ownership and notifications.',
    example: 'run_team_path: platform/payments',
  },
  {
    path: 'allowed_callers',
    scope: 'external trigger',
    type: 'object[]',
    required: false,
    defaultValue: 'None',
    description: 'Explicit callers permitted to invoke the trigger.',
    example: 'allowed_callers:\n  - service_account: release-bot\n  - auth_team: platform/sre',
    allowedValues: ['user', 'service_account', 'auth_team'],
    security: 'An empty list does not widen access; AAA still authorizes the caller against the trigger resource.',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'variable_mapping',
    scope: 'external trigger',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description:
      'Maps invocation data into run variables. Sources are `event_type`, `payload.<path>`, `variables.<name>`, a direct payload path, or `literal:<value>`.',
    example: 'variable_mapping:\n  SERVICE: payload.service.name\n  ENVIRONMENT: literal:production',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'payload_schema',
    scope: 'external trigger',
    type: 'object',
    required: false,
    defaultValue: 'None',
    description: 'Object-schema guard with required fields and basic property type checks applied before a run starts.',
    example: 'payload_schema:\n  type: object\n  required: [service]\n  properties:\n    service:\n      type: string',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'rate_limit.per_minute',
    scope: 'external trigger',
    type: 'integer',
    required: false,
    defaultValue: 'None',
    description: 'Maximum invocations accepted for this trigger over the previous minute.',
    example: 'rate_limit:\n  per_minute: 30',
    evidence: 'services/nopsai/external_triggers_gitops.go',
  },
  {
    path: 'idempotency_key',
    scope: 'invoke request',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description:
      'Retry key sent on the invoke request. Scoped by trigger and caller so a repeated call returns the original run instead of starting a second one.',
    example: '{"idempotency_key": "change-4821"}',
    evidence: 'services/nopsai/external_triggers.go',
  },
];
