import type { WikiField } from '../types.js';

/** Final deliverable directives under `output`. */
export const finalOutputFields: WikiField[] = [
  {
    path: 'output.llm_profile',
    scope: 'output',
    type: 'string',
    required: false,
    defaultValue: 'Pipeline `llm_profile`, otherwise configured default',
    description: 'Model profile used to generate every output item that does not set its own.',
    example: 'output:\n  llm_profile: report-writer',
    constraints: ['Setting this without at least one output item is a validation error.'],
    overriddenBy: ['output.items[].llm_profile'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].name',
    scope: 'output item',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Display name of the deliverable and the default dashboard entry key.',
    example: 'name: Executive summary',
    constraints: ['Duplicate names are rejected (case-insensitive).'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].type',
    scope: 'output item',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Deliverable format produced after the run finishes.',
    example: 'type: pdf',
    allowedValues: ['markdown', 'pdf', 'excel', 'json', 'html', 'dashboard'],
    constraints: ['`pdf` rendering requires a reachable Gotenberg service.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].when',
    scope: 'output item',
    type: 'string',
    required: false,
    defaultValue: 'always',
    description: 'Run outcome that triggers generation of this item.',
    example: 'when: failure',
    allowedValues: ['always', 'success', 'failure'],
    constraints: ['An omitted or empty value is treated as `always`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].prompt',
    scope: 'output item',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Instruction used to generate the deliverable content from run evidence.',
    example: 'prompt: Summarize the release, its approvals, and any ignored failures.',
    constraints: ['An empty prompt is a validation error.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].llm_profile',
    scope: 'output item',
    type: 'string',
    required: false,
    defaultValue: '`output.llm_profile`, then pipeline, then configured default',
    description: 'Most specific model profile override for this deliverable.',
    example: 'llm_profile: reasoning-large',
  },
];

/** Dashboard publication target. Valid only when the item type is `dashboard`. */
export const dashboardOutputFields: WikiField[] = [
  {
    path: 'output.items[].dashboard.ref',
    scope: 'dashboard output',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Target dashboard in `team/dashboard-slug` form.',
    example: 'ref: platform/release-health',
    constraints: [
      'Requires `type: dashboard`.',
      'Must be a relative path with at least two segments.',
      'Segments may not be empty, `.`, or `..`.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].dashboard.section',
    scope: 'dashboard output',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Dashboard section key the publication is written into.',
    example: 'section: deployments',
    constraints: ['Requires `type: dashboard`.', 'Must match ^[a-zA-Z0-9_.-]+$.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].dashboard.entry_key',
    scope: 'dashboard output',
    type: 'string',
    required: false,
    defaultValue: 'The output item name',
    description: 'Stable key that identifies the entry across runs so `replace` and `series` can find it.',
    example: 'entry_key: payments/prod',
    constraints: ['Requires `type: dashboard`.', 'Must match ^[a-zA-Z0-9_.:/-]+$.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].dashboard.mode',
    scope: 'dashboard output',
    type: 'string',
    required: false,
    defaultValue: 'replace',
    description: 'How the publication interacts with existing entries under the same key.',
    example: 'mode: series',
    allowedValues: ['replace', 'append', 'snapshot', 'series'],
    constraints: ['Requires `type: dashboard`.', 'An empty value is accepted and means `replace`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].dashboard.preset',
    scope: 'dashboard output',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description:
      'Prompt preset hint for the generated layout: narrative `report`, primary `table`, current-state `status`, chronological `timeline`, side-by-side `comparison`, numbers-first `metrics`, or cohesive `mixed`.',
    example: 'preset: metrics',
    allowedValues: ['auto', 'report', 'table', 'status', 'timeline', 'comparison', 'metrics', 'mixed'],
    constraints: ['Requires `type: dashboard`.', 'An empty value is accepted.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'output.items[].dashboard.ttl',
    scope: 'dashboard output',
    type: 'duration',
    required: false,
    defaultValue: 'None',
    description: 'How long the published entry is treated as current before it is shown as stale.',
    example: 'ttl: 7d',
    constraints: ['Requires `type: dashboard`.'],
  },
];
