import type { WikiField } from '../types.js';

const NAME_PATTERN = 'Must match ^[a-zA-Z0-9_.-]+$.';

/** Top-level pipeline YAML directives, verified against models.Pipeline and validation.ValidatePipeline. */
export const pipelineFields: WikiField[] = [
  {
    path: 'name',
    scope: 'pipeline',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Stable pipeline identifier used by runs, triggers, schedules, includes, and the API.',
    example: 'name: release-service',
    constraints: [NAME_PATTERN],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'version',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'latest',
    description: 'Pipeline version label. Validation writes back `latest` when the field is omitted.',
    example: 'version: "2.4"',
    constraints: [NAME_PATTERN],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'description',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Human-readable summary shown in the UI, API responses, and review surfaces.',
    example: 'description: Build, test, and publish the payments service.',
  },
  {
    path: 'container_image',
    scope: 'pipeline',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description:
      'Default image for executable steps. Required unless every executable step sets its own `image`; approval steps never need one.',
    example: 'container_image: ghcr.io/acme/build-tools:1.4',
    constraints: [
      'Validation fails with "container_image is a required field if executable steps don\'t have their own image" when any non-approval step has no image.',
    ],
    overriddenBy: ['steps[].image'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'working_directory',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: '/workspace',
    description: 'Working directory inside every step container or pod.',
    example: 'working_directory: services/api',
    constraints: [
      'Empty and `.` both resolve to /workspace.',
      'Relative paths are joined onto /workspace and may not escape it with `..`.',
      'Rejects the container root `/`, NUL bytes, and any value containing `:`.',
    ],
    evidence: 'pkg/models/pipeline_paths.go',
  },
  {
    path: 'display_options.github_view',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'flat list',
    description: 'How git-bot renders run progress inside a GitHub check run.',
    example: 'display_options:\n  github_view: mermaid',
    allowedValues: ['mermaid', 'tree'],
    constraints: ['Any other value, including an empty one, renders the flat Markdown list.'],
    evidence: 'services/git-bot/internal/checkrender/render.go',
  },
  {
    path: 'variables',
    scope: 'pipeline',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description:
      'Runtime variables the pipeline requires. A bare name resolves in the run scope; `scope/path:NAME` resolves an explicit scope and injects it as `NAME`.',
    example: 'variables:\n  - REGISTRY_HOST\n  - platform/shared:ARTIFACT_BUCKET',
    constraints: [
      'Names must match ^[A-Za-z0-9_.-]+$.',
      'The same runtime name may not be declared twice, even from different scopes.',
      'Scope segments may not be absolute or contain `.` / `..`.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps',
    scope: 'pipeline',
    type: 'step[]',
    required: true,
    defaultValue: 'None',
    description: 'Ordered list of step definitions. Execution order comes from `depends_on`, not from list position.',
    example: 'steps:\n  - name: build\n    script: make build',
    constraints: [
      'At least one step is required.',
      'Maximum 256 steps per pipeline.',
      'Step names must be unique.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'timeout',
    scope: 'pipeline',
    type: 'duration',
    required: false,
    defaultValue: 'Falls back to `default_pipeline_timeout`',
    description: 'Whole-run duration budget. When omitted, the platform default from system configuration applies.',
    example: 'timeout: 45m',
    evidence: 'services/nopsai/run_handlers.go',
  },
  {
    path: 'llm_enabled',
    scope: 'pipeline',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    description: 'Set `false` to declare a script-only pipeline. Validation then rejects every LLM-backed construct.',
    example: 'llm_enabled: false',
    constraints: [
      'With `false`, the pipeline cannot define `output.items`, any step `condition`, any `goal`, or a script that carries blocking guardrail/policy knowledge context.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'agent_role',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'Configured default agent role',
    description: 'Default AI persona and instruction profile for conditions and goals.',
    example: 'agent_role: senior-release-engineer',
    allowedValues: ['Any enabled Agent role ID'],
    constraints: [
      'Referenced profile must exist and be enabled.',
      'Tasks cannot set `agent_role`; parsing fails with an explicit error.',
    ],
    overriddenBy: ['steps[].agent_role'],
    evidence: 'pkg/models/model.go',
  },
  {
    path: 'model',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'Configured default model',
    description: 'Default provider/model profile for conditions, goals, and final outputs.',
    example: 'model: reasoning-large',
    constraints: ['The profile must be configured and allowed in the run scope.'],
    overriddenBy: ['steps[].model', 'tasks[].model', 'output.model', 'output.items[].model'],
    permission: 'AAA still decides whether the original caller may use the selected profile.',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'mcp_profiles',
    scope: 'pipeline',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Approved MCP tool profiles available to LLM goal work anywhere in the pipeline.',
    example: 'mcp_profiles:\n  - jira-readonly',
    constraints: [
      'Each profile must be configured, enabled, and allowed in the run scope.',
      'Pipeline, step, and task profiles are additive and deduplicated, not overriding.',
      'Pipeline YAML cannot declare arbitrary MCP server URLs.',
    ],
    security: 'The agent only accepts server/tool pairs present in the resolved profile allowlist.',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'governance_level',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'strict',
    description: 'How NopsAI enforces the AI policy review decision. An unset value normalizes to `strict`.',
    example: 'governance_level: guarded',
    allowedValues: ['advisory', 'guarded', 'strict', 'exception_based'],
    constraints: ['Cannot be combined with the deprecated `policy_merge_mode` in the same object.'],
    overriddenBy: ['steps[].governance_level', 'tasks[].governance_level'],
    security: 'Lowering this from the default weakens fail-closed enforcement for the whole run.',
    evidence: 'pkg/models/policy_merge.go',
  },
  {
    path: 'policy_merge_mode',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Deprecated alias kept for existing manifests. Prompts and telemetry use `governance_level`.',
    example: 'policy_merge_mode: restrictive',
    allowedValues: ['restrictive', 'override', 'fail_on_conflict'],
    constraints: [
      '`restrictive` and `fail_on_conflict` normalize to `strict`; `override` normalizes to `guarded`.',
      'Setting this together with `governance_level` is a validation error.',
    ],
    deprecatedIn: 'Superseded by governance_level',
    evidence: 'pkg/models/policy_merge.go',
  },
  {
    path: 'runtime_pool',
    scope: 'pipeline',
    type: 'string',
    required: false,
    defaultValue: 'Runner default pool',
    description: 'Kubernetes runtime pool for the run. Docker runners ignore this field.',
    example: 'runtime_pool: gpu',
    overriddenBy: ['steps[].runtime_pool'],
    evidence: 'services/k8s-runner',
  },
  {
    path: 'affinity_enabled',
    scope: 'pipeline',
    type: 'boolean',
    required: false,
    defaultValue: 'Runner `KUBERNETES_AFFINITY_ENABLED` setting',
    description: 'Overrides same-node affinity for step pods in this run. Docker runners ignore this field.',
    example: 'affinity_enabled: true',
    evidence: 'services/k8s-runner',
  },
  {
    path: 'knowledge_context',
    scope: 'pipeline',
    type: 'knowledge_ref[]',
    required: false,
    defaultValue: 'None',
    description:
      'Knowledge documents merged into every effective LLM task context. `guardrail` and `policy` entries also validate direct scripts before execution.',
    example: 'knowledge_context:\n  - kind: guardrail\n    ref: security/repo-check\n    required: true',
    constraints: ['Merged with step and task knowledge context rather than replaced by it.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'llm_content_sharing',
    scope: 'pipeline',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description:
      'Whether workspace file listings and contents are shared automatically with LLM goal resolution. Bounded workspace tools can still retrieve files on demand when this is false.',
    example: 'llm_content_sharing: true',
    security:
      'Shared and retrieved files carry path, SHA-256, size, and workspace revision metadata so stale file replacements are rejected.',
    evidence: 'pkg/models/model.go',
  },
  {
    path: 'llm_content_include',
    scope: 'pipeline',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Include filters applied to files shared with LLM goal context.',
    example: 'llm_content_include:\n  - "src/**/*.go"',
  },
  {
    path: 'llm_content_ignore',
    scope: 'pipeline',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Ignore filters applied to files shared with LLM goal context. Applied after include filters.',
    example: 'llm_content_ignore:\n  - "**/testdata/**"',
  },
  {
    path: 'llm_output_sharing',
    scope: 'pipeline',
    type: 'boolean',
    required: false,
    defaultValue: 'None',
    description: 'Default for whether task output is written into later LLM execution history.',
    example: 'llm_output_sharing: false',
    overriddenBy: ['steps[].llm_output_sharing', 'tasks[].llm_output_sharing'],
  },
  {
    path: 'output',
    scope: 'pipeline',
    type: 'object',
    required: false,
    defaultValue: 'None',
    description: 'Final deliverables and dashboard publications generated after the run finishes.',
    example: 'output:\n  items:\n    - name: Summary\n      type: markdown\n      prompt: Summarize the run.',
    constraints: ['Rejected when `llm_enabled: false`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
];

/** Limits the pipeline validator enforces before a run is accepted. */
export const pipelineStructuralLimits: WikiField[] = [
  {
    path: 'steps',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '256 maximum',
    description: 'Maximum number of steps in one pipeline.',
    example: 'pipeline has 257 steps; maximum is 256',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].tasks',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '256 maximum per step',
    description: 'Maximum number of tasks inside a single step.',
    example: "step 'build' has 257 tasks; maximum is 256",
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'tasks (total)',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '1024 maximum',
    description: 'Maximum number of tasks across every step in the pipeline.',
    example: 'pipeline has 1025 tasks; maximum is 1024',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'depends_on (per node)',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '256 maximum',
    description: 'Maximum dependencies declared on a single step or task.',
    example: "step 'deploy' has 257 dependencies; maximum is 256",
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'depends_on (total)',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '4096 maximum',
    description: 'Maximum dependency edges across the whole pipeline graph.',
    example: 'pipeline has 4097 dependencies; maximum is 4096',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].volumes',
    scope: 'limit',
    type: 'count',
    required: false,
    defaultValue: '32 maximum per step',
    description: 'Maximum volume mounts declared on a single step.',
    example: "step 'build' has 33 volumes; maximum is 32",
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
];
