import type { WikiField } from '../types.js';

/** Directives valid on every step regardless of execution mode. */
export const stepCommonFields: WikiField[] = [
  {
    path: 'steps[].name',
    scope: 'step',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Unique step name. Dependencies and runtime output references address the step by this name.',
    example: 'name: build',
    constraints: ['Must be unique within the pipeline.', 'A step without a name fails validation.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].image',
    scope: 'step',
    type: 'string',
    required: 'conditional',
    defaultValue: 'Pipeline `container_image`',
    description: 'Executable image for this step. Required when the pipeline has no `container_image`.',
    example: 'image: golang:1.24',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].depends_on',
    scope: 'step',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description:
      'Steps or qualified producer tasks that must finish first. Values may be a step name or `step.task`.',
    example: 'depends_on:\n  - prepare\n  - prepare.generate-tag',
    constraints: [
      'Maximum 256 dependencies per step.',
      'A runtime output reference (`$steps...`) is not a valid dependency value.',
      'Undefined dependency names fail validation.',
      'The full graph is cycle-checked; a cycle reports the exact path.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].condition',
    scope: 'step',
    type: 'string',
    required: false,
    defaultValue: 'None',
    description: 'Natural-language condition evaluated by the LLM before the step runs.',
    example: 'condition: Only run when the changed files include a migration.',
    constraints: [
      'Rejected when `llm_enabled: false`.',
      'A false result normally skips the step; under blocking guardrail or policy context it fails closed instead.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].secrets',
    scope: 'step',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Scoped secret references injected into the step as environment variables.',
    example: 'secrets:\n  - REGISTRY_TOKEN\n  - platform/shared:SIGNING_KEY',
    constraints: [
      'Names must match ^[A-Za-z0-9_.-]+$.',
      'The same runtime name may not resolve from two different scopes in one step.',
    ],
    security: 'Declared secret values are masked in run logs.',
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].variables',
    scope: 'step',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description: 'Environment overrides applied to every task in the step.',
    example: 'variables:\n  BUILD_MODE: release',
    constraints: [
      'Keys must match ^[A-Za-z0-9_.-]+$.',
      'A runtime output reference must be the entire value, not embedded in a larger expression.',
      'Consuming an output requires a dependency path to the producing task.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].volumes',
    scope: 'step',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description:
      'Named Docker volume or Kubernetes PVC mounts in `volume:/mount/path` form. Existing storage is reused; missing storage is created.',
    example: 'volumes:\n  - build-cache:/root/.cache',
    constraints: [
      'Maximum 32 volumes per step.',
      'Mounting the reserved runtime output path /nopsai/outputs is rejected.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].ignore_failure',
    scope: 'step',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description:
      'Treat failures in this step as ignored so the graph can continue. The run finishes with status `warning` instead of `failure`.',
    example: 'ignore_failure: true',
    constraints: [
      'Also applies to every task in the step.',
      'Ignored failures stay auditable as `failure (ignored)`.',
      'Approval failures and explicit policy or guardrail enforcement failures still fail closed.',
    ],
  },
  {
    path: 'steps[].outputs',
    scope: 'step',
    type: 'output[]',
    required: false,
    defaultValue: 'None',
    description:
      'Runtime output contract for single-task steps and for sync `pipeline:` includes. Steps with `tasks` declare outputs on the tasks instead.',
    example: 'outputs:\n  - name: IMAGE_TAG\n  - name: DEPLOY_TOKEN\n    sensitive: true',
    constraints: [
      'Names must match ^[A-Za-z_][A-Za-z0-9_]*$.',
      'Duplicate output names in one producer are rejected.',
      'A step with `tasks` cannot declare step-level outputs.',
      'An approval step cannot declare outputs.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].outputs[].sensitive',
    scope: 'step',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Marks the runtime output value as sensitive so it is masked in run logs.',
    example: 'outputs:\n  - name: DEPLOY_TOKEN\n    sensitive: true',
    security:
      'Non-sensitive output JSON stays visible in logs so release evidence such as versions and change IDs remains reviewable.',
  },
  {
    path: 'steps[].agent_role',
    scope: 'step',
    type: 'string',
    required: false,
    defaultValue: 'Pipeline `agent_role`',
    description: 'Persona override for the step condition and any LLM goals in the step.',
    example: 'agent_role: security-reviewer',
    constraints: ['Referenced profile must exist and be enabled.', 'Not valid at task level.'],
  },
  {
    path: 'steps[].model',
    scope: 'step',
    type: 'string',
    required: false,
    defaultValue: 'Pipeline `model`',
    description: 'Model-client override applied to the step condition and to tasks that do not set their own.',
    example: 'model: fast-small',
    overriddenBy: ['tasks[].model'],
  },
  {
    path: 'steps[].mcp_profiles',
    scope: 'step',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'MCP profiles added for LLM goals in this step. Additive with pipeline and task profiles.',
    example: 'mcp_profiles:\n  - github-readonly',
    constraints: [
      'Invalid on `include` steps.',
      'Invalid on `script` steps.',
      'Each profile must be configured, enabled, and allowed in the run scope.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].governance_level',
    scope: 'step',
    type: 'string',
    required: false,
    defaultValue: 'Pipeline `governance_level`, otherwise strict',
    description: 'AI governance enforcement override for this step.',
    example: 'governance_level: strict',
    allowedValues: ['advisory', 'strict'],
    overriddenBy: ['tasks[].governance_level'],
  },
  {
    path: 'steps[].runtime_pool',
    scope: 'step',
    type: 'string',
    required: false,
    defaultValue: 'Pipeline `runtime_pool`, otherwise runner default',
    description: 'Kubernetes runtime pool override for this step. Docker runners ignore it.',
    example: 'runtime_pool: gpu',
  },
  {
    path: 'steps[].knowledge_context',
    scope: 'step',
    type: 'knowledge_ref[]',
    required: false,
    defaultValue: 'None',
    description: 'Knowledge references merged with pipeline and task context for this step.',
    example: 'knowledge_context:\n  - kind: policy\n    ref: platform/deploy-policy',
  },
];

/** Exactly one of these must be present on every step. */
export const stepModeFields: WikiField[] = [
  {
    path: 'steps[].include',
    scope: 'step mode',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description:
      '`step:<identifier>` expands a reusable step definition. `pipeline:<identifier>` launches a child pipeline.',
    example: 'include: pipeline:platform/deploy-service',
    allowedValues: ['step:<identifier>', 'pipeline:<identifier>'],
    constraints: [
      'Cannot be combined with `tasks`, `goal`, `script`, or `approval`.',
      'Cannot define `mcp_profiles`.',
      'Only `pipeline:` includes may declare parent-visible `outputs`, and only with `sync: true`.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].sync',
    scope: 'step mode',
    type: 'boolean',
    required: 'conditional',
    defaultValue: 'false',
    description: 'Runs a `pipeline:` include synchronously so the parent waits for the child and can import its outputs.',
    example: 'include: pipeline:platform/deploy-service\nsync: true',
    constraints: ['Required when a `pipeline:` include declares `outputs`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].tasks',
    scope: 'step mode',
    type: 'task[]',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Multi-task step. Each task defines exactly one of `goal` or `script`.',
    example: 'tasks:\n  - name: unit\n    script: go test ./...',
    constraints: [
      'Maximum 256 tasks per step, 1024 across the pipeline.',
      'Cannot be combined with `goal`, `script`, `include`, or `approval`.',
      'Task names must be unique within the step.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].goal',
    scope: 'step mode',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Single LLM-backed goal for the step.',
    example: 'goal: Update the changelog with every merged pull request since the last tag.',
    constraints: ['Rejected when `llm_enabled: false`.', 'Cannot be combined with `script` or `tasks`.'],
  },
  {
    path: 'steps[].script',
    scope: 'step mode',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description:
      'Direct shell step. With blocking guardrail or policy knowledge context, the exact command is LLM-validated before execution.',
    example: 'script: |\n  make build\n  make test',
    constraints: [
      'Cannot be combined with `goal` or `tasks`.',
      'Cannot define `mcp_profiles`.',
      'With `llm_enabled: false`, blocking knowledge context on the script is rejected.',
    ],
  },
  {
    path: 'steps[].approval',
    scope: 'step mode',
    type: 'object',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Durable human checkpoint that pauses the run and releases runner capacity.',
    example: 'approval:\n  type: production-release\n  teams:\n    - platform/sre',
    constraints: ['Cannot be combined with `tasks`, `goal`, `script`, or `include`.', 'Cannot declare outputs.'],
  },
];

/** Directives valid on tasks inside a multi-task step. */
export const taskFields: WikiField[] = [
  {
    path: 'tasks[].name',
    scope: 'task',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Unique task name within the step.',
    example: 'name: unit-tests',
    constraints: ['Must be unique within the step.'],
  },
  {
    path: 'tasks[].goal',
    scope: 'task',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'LLM-backed task goal. Mutually exclusive with `script`; exactly one of the two is required.',
    example: 'goal: Summarize the failing tests and propose a fix.',
    constraints: ['Rejected when `llm_enabled: false`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'tasks[].script',
    scope: 'task',
    type: 'string',
    required: 'conditional',
    defaultValue: 'None',
    description: 'Direct shell task. Mutually exclusive with `goal`; exactly one of the two is required.',
    example: 'script: go test ./...',
    constraints: ['Cannot define `mcp_profiles`.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'tasks[].depends_on',
    scope: 'task',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'Tasks in the same step, or qualified `step.task` producers in an upstream step.',
    example: 'depends_on:\n  - checkout\n  - prepare.generate-tag',
    constraints: [
      'A bare step name is not a valid task dependency; use `step.task`.',
      'Maximum 256 dependencies per task.',
      'Runtime output references are not valid dependency values.',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'tasks[].outputs',
    scope: 'task',
    type: 'output[]',
    required: false,
    defaultValue: 'None',
    description: 'Runtime values this task publishes for downstream consumers.',
    example: 'outputs:\n  - name: IMAGE_TAG',
    constraints: [
      'Names must match ^[A-Za-z_][A-Za-z0-9_]*$.',
      'Duplicate names within one task are rejected.',
    ],
  },
  {
    path: 'tasks[].variables',
    scope: 'task',
    type: 'map<string,string>',
    required: false,
    defaultValue: 'None',
    description: 'Task-local environment overrides. Applied after step variables.',
    example: 'variables:\n  IMAGE_TAG: $steps.prepare.generate-tag.outputs.IMAGE_TAG',
    constraints: [
      'A runtime output reference must be the whole value.',
      'Consuming an output requires a dependency path to the producer.',
    ],
  },
  {
    path: 'tasks[].ignore_failure',
    scope: 'task',
    type: 'boolean',
    required: false,
    defaultValue: 'Step `ignore_failure`, otherwise false',
    description: 'Treat this task failure as ignored. The run finishes with status `warning`.',
    example: 'ignore_failure: true',
    constraints: ['Approval and explicit policy or guardrail enforcement failures still fail closed.'],
  },
  {
    path: 'tasks[].model',
    scope: 'task',
    type: 'string',
    required: false,
    defaultValue: 'Step `model`, then pipeline, then configured default',
    description: 'Most specific model-client override for this task.',
    example: 'model: reasoning-large',
  },
  {
    path: 'tasks[].mcp_profiles',
    scope: 'task',
    type: 'string[]',
    required: false,
    defaultValue: 'None',
    description: 'MCP profiles for this LLM goal task. Additive with pipeline and step profiles.',
    example: 'mcp_profiles:\n  - jira-readonly',
    constraints: ['Invalid on script tasks.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'tasks[].governance_level',
    scope: 'task',
    type: 'string',
    required: false,
    defaultValue: 'Step, then pipeline, otherwise strict',
    description: 'Most specific AI governance enforcement override.',
    example: 'governance_level: advisory',
    allowedValues: ['advisory', 'strict'],
  },
  {
    path: 'tasks[].knowledge_context',
    scope: 'task',
    type: 'knowledge_ref[]',
    required: false,
    defaultValue: 'None',
    description: 'Most specific knowledge references for this task, merged with step and pipeline context.',
    example: 'knowledge_context:\n  - kind: example\n    path: .nopsai/docs/migration-example.md',
  },
  {
    path: 'tasks[].agent_role',
    scope: 'task',
    type: 'not supported',
    required: false,
    defaultValue: 'None',
    description:
      'Not valid on tasks. Parsing fails with `task "<name>" cannot define agent_role; set agent_role on the pipeline or step`.',
    example: '# set agent_role on the pipeline or step instead',
    constraints: ['Rejected during YAML and JSON unmarshaling, not only at validation time.'],
    evidence: 'pkg/models/model.go',
  },
];

/** Approval checkpoint directives. */
export const approvalFields: WikiField[] = [
  {
    path: 'steps[].approval.type',
    scope: 'approval',
    type: 'string',
    required: true,
    defaultValue: 'None',
    description: 'Approval kind recorded on the checkpoint and used for audit and notification routing.',
    example: 'type: production-release',
    constraints: ['Must match ^[a-zA-Z0-9_.-]+$.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].approval.teams',
    scope: 'approval',
    type: 'string[]',
    required: true,
    defaultValue: 'None',
    description: 'Relative team paths allowed to approve or reject the checkpoint.',
    example: 'teams:\n  - platform/sre\n  - security',
    constraints: [
      'At least one team is required.',
      'Paths must be relative; absolute paths and `~` are rejected.',
      'Segments may not be empty, `.`, or `..`.',
      'Repeating the same team is rejected (case-insensitive).',
    ],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
  {
    path: 'steps[].approval.allow_self_approval',
    scope: 'approval',
    type: 'boolean',
    required: false,
    defaultValue: 'false',
    description: 'Whether the user who started the run may approve this checkpoint.',
    example: 'allow_self_approval: false',
    security: 'Leaving this false preserves four-eyes separation between requester and approver.',
  },
  {
    path: 'steps[].approval.timeout',
    scope: 'approval',
    type: 'duration',
    required: false,
    defaultValue: 'None',
    description: 'How long the checkpoint waits before the run is marked `timed_out`.',
    example: 'timeout: 24h',
    constraints: ['Must parse as a positive Go duration; `0` and negative values are rejected.'],
    evidence: 'services/nopsai/pkg/validation/pipeline.go',
  },
];
