import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  CalendarClock,
  Code2,
  Database,
  FileText,
  GitBranch,
  KeyRound,
  Lock,
  Play,
  Route,
  Server,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  UsersRound,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const objectIconTypes = [
  'pipeline-run',
  'monitoring',
  'dashboard',
  'team',
  'application',
  'repository-owner',
  'pipeline',
  'schedule',
  'trigger',
  'external-trigger',
  'git-webhook-source',
  'scope',
  'lab',
  'step',
  'knowledge-context',
  'system',
  'system-config',
  'setup',
  'llm-profile',
  'agent-profile',
  'mcp-server',
  'mcp-profile',
  'credential',
  'data-management',
  'dispatcher',
  'system-logs',
  'access',
  'gitops',
  'knowledge-guardrail',
  'knowledge-policy',
  'knowledge-runbook',
  'knowledge-reference',
  'knowledge-example',
  'knowledge-default',
  'assistant',
] as const;

export type ObjectIconType = (typeof objectIconTypes)[number];

export const objectIconRegistry = {
  'pipeline-run': Play,
  monitoring: Activity,
  dashboard: BarChart3,
  team: UsersRound,
  application: Boxes,
  'repository-owner': UsersRound,
  pipeline: Workflow,
  schedule: CalendarClock,
  trigger: Bell,
  'external-trigger': Zap,
  'git-webhook-source': Webhook,
  scope: SlidersHorizontal,
  lab: Code2,
  step: Boxes,
  'knowledge-context': BookOpen,
  system: Settings,
  'system-config': Settings,
  setup: ShieldCheck,
  'llm-profile': Bot,
  'agent-profile': FileText,
  'mcp-server': Server,
  'mcp-profile': Route,
  credential: KeyRound,
  'data-management': Database,
  dispatcher: Server,
  'system-logs': FileText,
  access: ShieldCheck,
  gitops: GitBranch,
  'knowledge-guardrail': ShieldCheck,
  'knowledge-policy': Lock,
  'knowledge-runbook': Braces,
  'knowledge-reference': BookOpen,
  'knowledge-example': FileText,
  'knowledge-default': FileText,
  assistant: Bot,
} satisfies Record<ObjectIconType, LucideIcon>;

export function getObjectIconComponent(type: ObjectIconType): LucideIcon {
  return objectIconRegistry[type];
}
