package nopsai

import "net/http"

func (a *App) registerAuthRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/auth/providers", a.handleAuthProviders)
	mux.HandleFunc("POST /v1/auth/discover", a.handleAuthDiscover)
	mux.HandleFunc("GET /v1/auth/oidc/{provider}/start", a.handleAuthOIDCStart)
	mux.HandleFunc("GET /v1/auth/oidc/{provider}/callback", a.handleAuthOIDCCallback)
	mux.HandleFunc("POST /v1/auth/session/exchange", a.handleAuthSessionExchange)
	mux.HandleFunc("POST /v1/auth/login", a.handleAuthLogin)
	mux.HandleFunc("POST /v1/auth/refresh", a.handleAuthRefresh)
	mux.HandleFunc("POST /v1/auth/logout", a.handleAuthLogout)
	mux.HandleFunc("POST /v1/auth/password", a.handleAuthChangePassword)
	mux.HandleFunc("POST /v1/auth/email", a.handleAuthUpdateEmail)
	mux.HandleFunc("GET /v1/auth/personal-tokens", a.handleListPersonalAccessTokens)
	mux.HandleFunc("POST /v1/auth/personal-tokens", a.handleCreatePersonalAccessToken)
	mux.HandleFunc("DELETE /v1/auth/personal-tokens/{tokenID}", a.handleRevokePersonalAccessToken)
	mux.HandleFunc("GET /v1/auth/me", a.handleAuthMe)
	mux.HandleFunc("GET /v1/audit", a.handleListAuditLogs)
	mux.HandleFunc("GET /v1/admin/users", a.handleListUsers)
	mux.HandleFunc("POST /v1/admin/users", a.handleCreateUser)
	mux.HandleFunc("PUT /v1/admin/users/{userID}", a.handleUpdateUser)
	mux.HandleFunc("PATCH /v1/admin/users/{userID}", a.handleUpdateUser)
	mux.HandleFunc("DELETE /v1/admin/users/{userID}", a.handleDeleteUser)
	mux.HandleFunc("GET /v1/admin/service-accounts", a.handleListServiceAccounts)
	mux.HandleFunc("POST /v1/admin/service-accounts", a.handleCreateServiceAccount)
	mux.HandleFunc("PUT /v1/admin/service-accounts/{serviceAccountID}", a.handleUpdateServiceAccount)
	mux.HandleFunc("PATCH /v1/admin/service-accounts/{serviceAccountID}", a.handleUpdateServiceAccount)
	mux.HandleFunc("DELETE /v1/admin/service-accounts/{serviceAccountID}", a.handleDeleteServiceAccount)
	mux.HandleFunc("GET /v1/admin/service-accounts/{serviceAccountID}/tokens", a.handleListServiceAccountTokens)
	mux.HandleFunc("POST /v1/admin/service-accounts/{serviceAccountID}/tokens", a.handleCreateServiceAccountToken)
	mux.HandleFunc("DELETE /v1/admin/service-accounts/{serviceAccountID}/tokens/{tokenID}", a.handleRevokeServiceAccountToken)
	mux.HandleFunc("POST /v1/admin/user-roles", a.handleAddUserRole)
	mux.HandleFunc("DELETE /v1/admin/user-roles", a.handleDeleteUserRole)
	mux.HandleFunc("POST /v1/admin/service-account-roles", a.handleAddServiceAccountRole)
	mux.HandleFunc("DELETE /v1/admin/service-account-roles", a.handleDeleteServiceAccountRole)
	mux.HandleFunc("GET /v1/admin/roles", a.handleListRoles)
	mux.HandleFunc("POST /v1/admin/roles", a.handleCreateRole)
	mux.HandleFunc("DELETE /v1/admin/roles", a.handleDeleteRole)
	mux.HandleFunc("GET /v1/admin/identity-providers", a.handleAdminIdentityProviders)
	mux.HandleFunc("PUT /v1/admin/identity-providers", a.handleAdminIdentityProviders)
	mux.HandleFunc("PUT /v1/admin/identity-providers/{provider}", a.handleAdminIdentityProvider)
	mux.HandleFunc("DELETE /v1/admin/identity-providers/{provider}", a.handleAdminIdentityProvider)
}

func (a *App) registerAccessRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /v1/access/grants", a.handleCreateAccessGrant)
	mux.HandleFunc("GET /v1/access/grants", a.handleListAccessGrants)
	mux.HandleFunc("DELETE /v1/access/grants/{grantID}", a.handleDeleteAccessGrant)
	mux.HandleFunc("GET /v1/access/auth-teams", a.handleListAccessAuthTeams)
	mux.HandleFunc("GET /v1/access/teams", a.handleListAccessTeams)
	mux.HandleFunc("GET /v1/access/effective-permissions", a.handleGetEffectivePermissions)
	mux.HandleFunc("POST /v1/authz/resource-use/check", a.handleResourceUseCheck)
	mux.HandleFunc("POST /v1/authz/resource-use/batch-check", a.handleResourceUseBatchCheck)
	mux.HandleFunc("/v1/resources/", a.handleResourceAccessRoute)
}

func (a *App) registerGitHubRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/internal/git-bot/bootstrap", a.handleGitBotBootstrap)
	mux.HandleFunc("POST /v1/git/events", a.handleGitEvent)
	mux.HandleFunc("POST /v1/git/webhooks/{sourceID}", a.handleGitWebhookDelivery)
}

func (a *App) registerGitWebhookSourceRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/git-webhook-sources", a.handleListGitWebhookSources)
	mux.HandleFunc("POST /v1/git-webhook-sources", a.handleCreateGitWebhookSource)
	mux.HandleFunc("GET /v1/git-webhook-sources/{sourceID}", a.handleGetGitWebhookSource)
	mux.HandleFunc("PUT /v1/git-webhook-sources/{sourceID}", a.handleUpdateGitWebhookSource)
	mux.HandleFunc("PATCH /v1/git-webhook-sources/{sourceID}", a.handleUpdateGitWebhookSource)
	mux.HandleFunc("DELETE /v1/git-webhook-sources/{sourceID}", a.handleDeleteGitWebhookSource)
	mux.HandleFunc("GET /v1/git-webhook-sources/{sourceID}/deliveries", a.handleListGitWebhookDeliveries)
}

func (a *App) registerTeamRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/teams", a.handleListTeams)
	mux.HandleFunc("POST /v1/teams", a.handleCreateTeam)
	mux.HandleFunc("GET /v1/teams/{teamID}", a.handleGetTeam)
	mux.HandleFunc("PUT /v1/teams/{teamID}", a.handleUpdateTeam)
	mux.HandleFunc("DELETE /v1/teams/{teamID}", a.handleDeleteTeam)
	mux.HandleFunc("GET /v1/teams/{teamID}/applications", a.handleListTeamApplications)
	mux.HandleFunc("POST /v1/teams/{teamID}/applications", a.handleCreateTeamApplication)
	mux.HandleFunc("PUT /v1/teams/{teamID}/applications/{applicationID}", a.handleUpdateTeamApplication)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/applications/{applicationID}", a.handleDeleteTeamApplication)
	mux.HandleFunc("GET /v1/teams/{teamID}/config-repository", a.handleTeamConfigRepository)
	mux.HandleFunc("PUT /v1/teams/{teamID}/config-repository", a.handleTeamConfigRepository)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/config-repository", a.handleTeamConfigRepository)
	mux.HandleFunc("GET /v1/teams/{teamID}/config-repository/sync", a.handleTeamConfigRepository)
	mux.HandleFunc("POST /v1/teams/{teamID}/config-repository/sync", a.handleTeamConfigRepository)
	mux.HandleFunc("GET /v1/teams/{teamID}/config-repository/drift", a.handleTeamConfigRepository)
	mux.HandleFunc("POST /v1/teams/{teamID}/config-repository/write", a.handleTeamConfigRepository)
	mux.HandleFunc("GET /v1/teams/{teamID}/notifications", a.handleTeamNotificationRoute)
	mux.HandleFunc("PUT /v1/teams/{teamID}/notifications", a.handleTeamNotificationRoute)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/notifications", a.handleTeamNotificationRoute)
	mux.HandleFunc("GET /v1/teams/{teamID}/llm-profiles", a.handleListTeamLLMProfiles)
	mux.HandleFunc("PUT /v1/teams/{teamID}/llm-profiles", a.handleReplaceTeamLLMProfiles)
	mux.HandleFunc("PUT /v1/teams/{teamID}/llm-profiles/default", a.handleSetTeamDefaultLLMProfile)
	mux.HandleFunc("PUT /v1/teams/{teamID}/llm-profiles/{profileName}", a.handleUpsertTeamLLMProfile)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/llm-profiles/{profileName}", a.handleDeleteTeamLLMProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/agent-profiles", a.handleListTeamAgentProfiles)
	mux.HandleFunc("POST /v1/teams/{teamID}/agent-profiles", a.handleCreateTeamAgentProfile)
	mux.HandleFunc("PUT /v1/teams/{teamID}/agent-profiles/default", a.handleSetTeamDefaultAgentProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/agent-profiles/{profileID}", a.handleGetTeamAgentProfile)
	mux.HandleFunc("PUT /v1/teams/{teamID}/agent-profiles/{profileID}", a.handleUpsertTeamAgentProfile)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/agent-profiles/{profileID}", a.handleDeleteTeamAgentProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/mcp-profiles", a.handleListTeamMCPProfiles)
	mux.HandleFunc("POST /v1/teams/{teamID}/mcp-profiles", a.handleCreateTeamMCPProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/mcp-profiles/{profileName}", a.handleGetTeamMCPProfile)
	mux.HandleFunc("PUT /v1/teams/{teamID}/mcp-profiles/{profileName}", a.handleUpsertTeamMCPProfile)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/mcp-profiles/{profileName}", a.handleDeleteTeamMCPProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/mcp/profiles", a.handleListTeamMCPProfiles)
	mux.HandleFunc("POST /v1/teams/{teamID}/mcp/profiles", a.handleCreateTeamMCPProfile)
	mux.HandleFunc("GET /v1/teams/{teamID}/mcp/profiles/{profileName}", a.handleGetTeamMCPProfile)
	mux.HandleFunc("PUT /v1/teams/{teamID}/mcp/profiles/{profileName}", a.handleUpsertTeamMCPProfile)
	mux.HandleFunc("DELETE /v1/teams/{teamID}/mcp/profiles/{profileName}", a.handleDeleteTeamMCPProfile)
}

func (a *App) registerSystemRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/system/logs/sources", a.handleListSystemLogSources)
	mux.HandleFunc("GET /v1/system/logs/sources/{sourceID}/tail", a.handleTailSystemLogs)
	mux.HandleFunc("GET /v1/system/logs/sources/{sourceID}/stream", a.handleStreamSystemLogs)
	mux.HandleFunc("GET /v1/system/credentials", a.handleListCredentials)
	mux.HandleFunc("POST /v1/system/credentials", a.handleCreateCredential)
	mux.HandleFunc("GET /v1/system/credentials/{credentialID}", a.handleGetCredential)
	mux.HandleFunc("PUT /v1/system/credentials/{credentialID}/value", a.handleRotateCredential)
	mux.HandleFunc("POST /v1/system/credentials/{credentialID}/versions/{version}/activate", a.handleActivateCredentialVersion)
	mux.HandleFunc("DELETE /v1/system/credentials/{credentialID}/versions/{version}", a.handleDeleteCredentialVersion)
	mux.HandleFunc("POST /v1/system/credentials/{credentialID}/disable", a.handleDisableCredential)
	mux.HandleFunc("POST /v1/system/credentials/{credentialID}/enable", a.handleEnableCredential)
	mux.HandleFunc("DELETE /v1/system/credentials/{credentialID}", a.handleDeleteCredential)
	mux.HandleFunc("GET /v1/system/config", a.handleGetSystemConfig)
	mux.HandleFunc("PUT /v1/system/config", a.handleUpdateSystemConfig)
	mux.HandleFunc("GET /v1/system/notifications/mail", a.handleGetNotificationMailSettings)
	mux.HandleFunc("PUT /v1/system/notifications/mail", a.handleUpdateNotificationMailSettings)
	mux.HandleFunc("POST /v1/system/notifications/mail/test", a.handleTestNotificationMailSettings)
	mux.HandleFunc("GET /v1/system/llm-profiles", a.handleListLLMProfiles)
	mux.HandleFunc("PUT /v1/system/llm-profiles", a.handleReplaceLLMProfiles)
	mux.HandleFunc("PUT /v1/system/llm-profiles/{profileName}", a.handleUpsertLLMProfile)
	mux.HandleFunc("DELETE /v1/system/llm-profiles/{profileName}", a.handleDeleteLLMProfile)
	mux.HandleFunc("POST /v1/system/llm-profiles/{profileName}/test", a.handleTestLLMProfile)
	mux.HandleFunc("GET /v1/system/agent-profiles", a.handleListAgentProfiles)
	mux.HandleFunc("POST /v1/system/agent-profiles", a.handleCreateAgentProfile)
	mux.HandleFunc("POST /v1/system/agent-profiles/validate", a.handleValidateAgentProfile)
	mux.HandleFunc("PUT /v1/system/agent-profiles/default", a.handleSetDefaultAgentProfile)
	mux.HandleFunc("GET /v1/system/agent-profiles/{profileID}", a.handleGetAgentProfile)
	mux.HandleFunc("PUT /v1/system/agent-profiles/{profileID}", a.handleUpsertAgentProfile)
	mux.HandleFunc("DELETE /v1/system/agent-profiles/{profileID}", a.handleDeleteAgentProfile)
	mux.HandleFunc("GET /v1/system/agent-profiles/{profileID}/usage", a.handleGetAgentProfileUsage)
	mux.HandleFunc("GET /v1/system/mcp/servers", a.handleListMCPServers)
	mux.HandleFunc("POST /v1/system/mcp/servers", a.handleCreateMCPServer)
	mux.HandleFunc("GET /v1/system/mcp/servers/{serverName}", a.handleGetMCPServer)
	mux.HandleFunc("PUT /v1/system/mcp/servers/{serverName}", a.handleUpsertMCPServer)
	mux.HandleFunc("DELETE /v1/system/mcp/servers/{serverName}", a.handleDeleteMCPServer)
	mux.HandleFunc("POST /v1/system/mcp/servers/{serverName}/test", a.handleTestMCPServer)
	mux.HandleFunc("POST /v1/system/mcp/servers/{serverName}/discover-tools", a.handleDiscoverMCPServerTools)
	mux.HandleFunc("GET /v1/system/mcp/profiles", a.handleListMCPProfiles)
	mux.HandleFunc("POST /v1/system/mcp/profiles", a.handleCreateMCPProfile)
	mux.HandleFunc("GET /v1/system/mcp/profiles/{profileName}", a.handleGetMCPProfile)
	mux.HandleFunc("PUT /v1/system/mcp/profiles/{profileName}", a.handleUpsertMCPProfile)
	mux.HandleFunc("DELETE /v1/system/mcp/profiles/{profileName}", a.handleDeleteMCPProfile)
	mux.HandleFunc("POST /v1/system/mcp/profiles/{profileName}/test", a.handleTestMCPProfile)
	mux.HandleFunc("GET /v1/system/config/sync", a.handleGetConfigSyncStatus)
	mux.HandleFunc("POST /v1/system/config/sync", a.handleConfigSync)
	mux.HandleFunc("GET /v1/system/config-repo", a.handleGetGlobalConfigRepository)
	mux.HandleFunc("PUT /v1/system/config-repo", a.handleUpsertGlobalConfigRepository)
	mux.HandleFunc("DELETE /v1/system/config-repo", a.handleDeleteGlobalConfigRepository)
	mux.HandleFunc("GET /v1/system/config-repo/sync", a.handleGetGlobalConfigRepositorySyncStatus)
	mux.HandleFunc("POST /v1/system/config-repo/sync", a.handleSyncGlobalConfigRepository)
	mux.HandleFunc("GET /v1/system/config-repo/drift", a.handleGetGlobalConfigRepositoryDrift)
	mux.HandleFunc("POST /v1/system/config-repo/write", a.handleWriteGlobalConfigRepository)
	mux.HandleFunc("GET /v1/system/config-repos", a.handleListConfigRepositories)
	mux.HandleFunc("POST /v1/system/config-repos/sync", a.handleSyncAllConfigRepositories)
	mux.HandleFunc("GET /v1/system/data/backups", a.handleListDataBackups)
	mux.HandleFunc("POST /v1/system/data/backups", a.handleCreateDataBackup)
	mux.HandleFunc("GET /v1/system/data/backups/{backupID}/download", a.handleDownloadDataBackup)
	mux.HandleFunc("DELETE /v1/system/data/backups/{backupID}", a.handleDeleteDataBackup)
	mux.HandleFunc("POST /v1/system/data/cleanup/preview", a.handlePreviewDataCleanup)
	mux.HandleFunc("POST /v1/system/data/cleanup/run", a.handleRunDataCleanup)
	mux.HandleFunc("GET /v1/system/data/cleanup/jobs", a.handleListDataCleanupJobs)
	mux.HandleFunc("GET /v1/system/data/cleanup/schedules", a.handleListDataCleanupSchedules)
	mux.HandleFunc("POST /v1/system/data/cleanup/schedules", a.handleCreateDataCleanupSchedule)
	mux.HandleFunc("PUT /v1/system/data/cleanup/schedules/{scheduleID}", a.handleUpdateDataCleanupSchedule)
	mux.HandleFunc("DELETE /v1/system/data/cleanup/schedules/{scheduleID}", a.handleDeleteDataCleanupSchedule)
	mux.HandleFunc("POST /v1/system/data/cleanup/schedules/{scheduleID}/run", a.handleRunDataCleanupScheduleNow)
	mux.HandleFunc("POST /v1/system/data/cleanup/schedules/{scheduleID}/enable", a.handleEnableDataCleanupSchedule)
	mux.HandleFunc("POST /v1/system/data/cleanup/schedules/{scheduleID}/disable", a.handleDisableDataCleanupSchedule)
	mux.HandleFunc("POST /v1/internal/config/sync", a.handleConfigSync)
	mux.HandleFunc("GET /v1/internal/dispatcher/routing", a.handleInternalDispatcherRouting)
	mux.HandleFunc("GET /internal/v1/runtime-config/{service}", a.handleInternalRuntimeConfig)
	mux.HandleFunc("GET /internal/v1/runtime-config/{service}/watch", a.handleInternalRuntimeConfigWatch)
	mux.HandleFunc("GET /v1/system/dispatcher", a.handleDispatcherStatus)
	mux.HandleFunc("GET /v1/system/dispatcher/scopes", a.handleListRuntimeScopes)
	mux.HandleFunc("GET /v1/system/dispatcher/runner-compose", a.handleGenerateRunnerCompose)
	mux.HandleFunc("GET /v1/system/dispatcher/runner-bootstrap-command", a.handleGenerateRunnerBootstrapCommand)
	mux.HandleFunc("GET /v1/system/dispatcher/kubernetes-runner-bootstrap-command", a.handleGenerateKubernetesRunnerBootstrapCommand)
	mux.HandleFunc("GET /v1/system/dispatcher/kubernetes-runner-manifest", a.handleGenerateKubernetesRunnerManifest)
	mux.HandleFunc("GET /v1/system/dispatcher/runner-bootstrap", a.handleRunnerBootstrap)
	mux.HandleFunc("POST /v1/system/dispatcher/runners/{runnerID}/dispatch", a.handleUpdateRunnerDispatch)
}

func (a *App) registerMonitoringRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /metrics", a.handleMetrics)
	mux.HandleFunc("GET /v1/monitoring/dispatcher", a.handleMonitoringDispatcherStatus)
	mux.HandleFunc("GET /v1/monitoring/runners/history", a.handleMonitoringRunnerHistory)
	mux.HandleFunc("GET /v1/monitoring/summary", a.handleMonitoringSummary)
	mux.HandleFunc("GET /v1/monitoring/runs/analytics", a.handleMonitoringRunAnalytics)
	mux.HandleFunc("GET /v1/monitoring/pipelines/performance", a.handleMonitoringPipelinePerformance)
	mux.HandleFunc("GET /v1/monitoring/steps/performance", a.handleMonitoringStepPerformance)
	mux.HandleFunc("GET /v1/monitoring/tasks/performance", a.handleMonitoringTaskPerformance)
	mux.HandleFunc("GET /v1/monitoring/triggers/analytics", a.handleMonitoringTriggerAnalytics)
	mux.HandleFunc("GET /v1/monitoring/external-triggers/analytics", a.handleMonitoringExternalTriggerAnalytics)
	mux.HandleFunc("GET /v1/monitoring/ai-usage", a.handleMonitoringAIUsage)
	mux.HandleFunc("GET /v1/monitoring/reliability", a.handleMonitoringReliability)
	mux.HandleFunc("GET /v1/monitoring/efficiency", a.handleMonitoringEfficiency)
	mux.HandleFunc("GET /v1/monitoring/security", a.handleMonitoringSecurity)
	mux.HandleFunc("GET /v1/monitoring/views", a.handleListMonitoringSavedViews)
	mux.HandleFunc("POST /v1/monitoring/views", a.handleCreateMonitoringSavedView)
	mux.HandleFunc("PUT /v1/monitoring/views/{viewID}", a.handleUpdateMonitoringSavedView)
	mux.HandleFunc("DELETE /v1/monitoring/views/{viewID}", a.handleDeleteMonitoringSavedView)
	mux.HandleFunc("GET /v1/monitoring/alert-rules", a.handleListMonitoringAlertRules)
	mux.HandleFunc("POST /v1/monitoring/alert-rules", a.handleCreateMonitoringAlertRule)
	mux.HandleFunc("PUT /v1/monitoring/alert-rules/{ruleID}", a.handleUpdateMonitoringAlertRule)
	mux.HandleFunc("DELETE /v1/monitoring/alert-rules/{ruleID}", a.handleDeleteMonitoringAlertRule)
	mux.HandleFunc("POST /v1/monitoring/alert-rules/{ruleID}/evaluate", a.handleEvaluateMonitoringAlertRule)
	mux.HandleFunc("GET /v1/monitoring/alert-events", a.handleListMonitoringAlertEvents)
	mux.HandleFunc("GET /v1/monitoring/recommendations", a.handleListMonitoringRecommendations)
	mux.HandleFunc("POST /v1/monitoring/recommendations/{recommendationID}/acknowledge", a.handleAcknowledgeMonitoringRecommendation)
	mux.HandleFunc("POST /v1/monitoring/recommendations/{recommendationID}/resolve", a.handleResolveMonitoringRecommendation)
}

func (a *App) registerSetupRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/setup/preflight", a.handleSetupPreflight)
	mux.HandleFunc("GET /v1/setup/status", a.handleGetSetupStatus)
	mux.HandleFunc("GET /v1/setup/templates", a.handleGetSetupTemplates)
	mux.HandleFunc("GET /v1/setup/templates.zip", a.handleDownloadSetupTemplates)
	mux.HandleFunc("POST /v1/setup/bootstrap", a.handleBootstrapSetup)
}

func (a *App) registerPipelineRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/pipelines", a.handleListPipelines)
	mux.HandleFunc("GET /v1/pipelines/{pipelineName...}", a.handleGetPipeline)
	mux.HandleFunc("PUT /v1/pipelines/{pipelineName...}", a.handleCreateOrUpdatePipeline)
	mux.HandleFunc("DELETE /v1/pipelines/{pipelineName...}", a.handleDeletePipeline)
	mux.HandleFunc("GET /v1/steps", a.handleListReusableSteps)
	mux.HandleFunc("GET /v1/steps/{stepPath...}", a.handleGetStepRoute)
	mux.HandleFunc("PUT /v1/steps/{stepName...}", a.handleCreateOrUpdateReusableStep)
	mux.HandleFunc("DELETE /v1/steps/{stepName...}", a.handleDeleteReusableStep)
	mux.HandleFunc("GET /v1/overrides", a.handleListTriggerOverrides)
	mux.HandleFunc("GET /v1/overrides/{repoOwner}/{repoName}", a.handleGetTriggerOverride)
	mux.HandleFunc("PUT /v1/overrides/{repoOwner}/{repoName}", a.handleCreateOrUpdateTriggerOverride)
	mux.HandleFunc("DELETE /v1/overrides/{repoOwner}/{repoName}", a.handleDeleteTriggerOverride)
}

func (a *App) registerScheduleRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/schedules", a.handleListSchedules)
	mux.HandleFunc("POST /v1/schedules", a.handleCreateSchedule)
	mux.HandleFunc("GET /v1/schedules/{scheduleID}", a.handleGetSchedule)
	mux.HandleFunc("PUT /v1/schedules/{scheduleID}", a.handleUpdateSchedule)
	mux.HandleFunc("PATCH /v1/schedules/{scheduleID}", a.handleUpdateSchedule)
	mux.HandleFunc("DELETE /v1/schedules/{scheduleID}", a.handleDeleteSchedule)
	mux.HandleFunc("POST /v1/schedules/{scheduleID}/enable", a.handleEnableSchedule)
	mux.HandleFunc("POST /v1/schedules/{scheduleID}/disable", a.handleDisableSchedule)
	mux.HandleFunc("POST /v1/schedules/{scheduleID}/run", a.handleRunScheduleNow)
}

func (a *App) registerDashboardRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/dashboards", a.handleListDashboards)
	mux.HandleFunc("POST /v1/dashboards", a.handleCreateDashboard)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}", a.handleGetDashboard)
	mux.HandleFunc("PUT /v1/dashboards/{dashboardID}", a.handleUpdateDashboard)
	mux.HandleFunc("PATCH /v1/dashboards/{dashboardID}", a.handleUpdateDashboard)
	mux.HandleFunc("DELETE /v1/dashboards/{dashboardID}", a.handleDeleteDashboard)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/view", a.handleGetDashboardView)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/history", a.handleGetDashboardHistory)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refresh", a.handleStartDashboardRefresh)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/refreshes", a.handleListDashboardRefreshes)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/refreshes/{refreshID}", a.handleGetDashboardRefresh)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refreshes/{refreshID}/cancel", a.handleCancelDashboardRefresh)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refreshes/{refreshID}/retry-failed", a.handleRetryDashboardRefreshFailed)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/refresh-schedules", a.handleListDashboardRefreshSchedules)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refresh-schedules", a.handleCreateDashboardRefreshSchedule)
	mux.HandleFunc("PUT /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}", a.handleUpdateDashboardRefreshSchedule)
	mux.HandleFunc("PATCH /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}", a.handleUpdateDashboardRefreshSchedule)
	mux.HandleFunc("DELETE /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}", a.handleDeleteDashboardRefreshSchedule)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/enable", a.handleEnableDashboardRefreshSchedule)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/disable", a.handleDisableDashboardRefreshSchedule)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/refresh-schedules/{scheduleID}/run", a.handleRunDashboardRefreshScheduleNow)
	mux.HandleFunc("GET /v1/dashboards/{dashboardID}/sources", a.handleListDashboardSources)
	mux.HandleFunc("POST /v1/dashboards/{dashboardID}/sources", a.handleCreateDashboardSource)
	mux.HandleFunc("PUT /v1/dashboards/{dashboardID}/sources/{sourceID}", a.handleUpdateDashboardSource)
	mux.HandleFunc("PATCH /v1/dashboards/{dashboardID}/sources/{sourceID}", a.handleUpdateDashboardSource)
	mux.HandleFunc("DELETE /v1/dashboards/{dashboardID}/sources/{sourceID}", a.handleDeleteDashboardSource)
}

func (a *App) registerExternalTriggerRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/external-triggers", a.handleListExternalTriggers)
	mux.HandleFunc("POST /v1/external-triggers", a.handleCreateExternalTrigger)
	mux.HandleFunc("GET /v1/external-triggers/{id}", a.handleGetExternalTrigger)
	mux.HandleFunc("PUT /v1/external-triggers/{id}", a.handleUpdateExternalTrigger)
	mux.HandleFunc("PATCH /v1/external-triggers/{id}", a.handleUpdateExternalTrigger)
	mux.HandleFunc("DELETE /v1/external-triggers/{id}", a.handleDeleteExternalTrigger)
	mux.HandleFunc("GET /v1/external-triggers/{id}/invocations", a.handleListExternalTriggerInvocations)
	mux.HandleFunc("POST /v1/external-triggers/{id}/invoke", a.handleInvokeExternalTrigger)
}

func (a *App) registerKnowledgeContextRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/knowledge-contexts", a.handleListKnowledgeContexts)
	mux.HandleFunc("GET /v1/knowledge-context-connections", a.handleListKnowledgeConnections)
	mux.HandleFunc("POST /v1/knowledge-context-connections", a.handleCreateKnowledgeConnection)
	mux.HandleFunc("POST /v1/knowledge-context-connections/{connectionID}/test", a.handleTestKnowledgeConnection)
	mux.HandleFunc("GET /v1/knowledge-context-connections/{connectionID}/pages/search", a.handleSearchKnowledgeConnectionPages)
	mux.HandleFunc("POST /v1/knowledge-context-connections/{connectionID}/resolve-page", a.handleResolveKnowledgeConnectionPage)
	mux.HandleFunc("POST /v1/knowledge-context-connections/{connectionID...}", a.handleKnowledgeConnectionPost)
	mux.HandleFunc("GET /v1/knowledge-context-connections/{connectionID...}", a.handleGetKnowledgeConnection)
	mux.HandleFunc("PUT /v1/knowledge-context-connections/{connectionID...}", a.handleUpdateKnowledgeConnection)
	mux.HandleFunc("PATCH /v1/knowledge-context-connections/{connectionID...}", a.handleUpdateKnowledgeConnection)
	mux.HandleFunc("DELETE /v1/knowledge-context-connections/{connectionID...}", a.handleDeleteKnowledgeConnection)
	mux.HandleFunc("GET /v1/knowledge-connections", a.handleListKnowledgeConnections)
	mux.HandleFunc("POST /v1/knowledge-connections", a.handleCreateKnowledgeConnection)
	mux.HandleFunc("POST /v1/knowledge-connections/{connectionID}/test", a.handleTestKnowledgeConnection)
	mux.HandleFunc("GET /v1/knowledge-connections/{connectionID}/pages", a.handleSearchKnowledgeConnectionPages)
	mux.HandleFunc("POST /v1/knowledge-connections/{connectionID}/resolve-page", a.handleResolveKnowledgeConnectionPage)
	mux.HandleFunc("POST /v1/knowledge-connections/{connectionID...}", a.handleKnowledgeConnectionPost)
	mux.HandleFunc("GET /v1/knowledge-connections/{connectionID...}", a.handleGetKnowledgeConnection)
	mux.HandleFunc("PUT /v1/knowledge-connections/{connectionID...}", a.handleUpdateKnowledgeConnection)
	mux.HandleFunc("PATCH /v1/knowledge-connections/{connectionID...}", a.handleUpdateKnowledgeConnection)
	mux.HandleFunc("DELETE /v1/knowledge-connections/{connectionID...}", a.handleDeleteKnowledgeConnection)
	mux.HandleFunc("POST /v1/knowledge-contexts/{knowledgeID...}", a.handleKnowledgeContextPost)
	mux.HandleFunc("GET /v1/knowledge-contexts/{knowledgeID...}", a.handleGetKnowledgeContext)
	mux.HandleFunc("PUT /v1/knowledge-contexts/{knowledgeID...}", a.handleUpsertKnowledgeContext)
	mux.HandleFunc("DELETE /v1/knowledge-contexts/{knowledgeID...}", a.handleDeleteKnowledgeContext)
}

func (a *App) registerSecretVariableRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/secrets", a.handleListGeneralSecrets)
	mux.HandleFunc("GET /v1/secrets/scopes", a.handleListSecretScopes)
	mux.HandleFunc("POST /v1/secrets/encrypt", a.handleEncryptSecretForGitOps)
	mux.HandleFunc("GET /v1/secrets/{secretName}", a.handleGetGeneralSecretValue)
	mux.HandleFunc("PUT /v1/secrets/{secretName}", a.handleCreateOrUpdateGeneralSecret)
	mux.HandleFunc("DELETE /v1/secrets/{secretName}", a.handleDeleteGeneralSecret)
	mux.HandleFunc("GET /v1/repositories/{repoOwner}/{repoName}/secrets", a.handleListRepoSecrets)
	mux.HandleFunc("PUT /v1/repositories/{repoOwner}/{repoName}/secrets/{secretName}", a.handleCreateOrUpdateRepoSecret)
	mux.HandleFunc("DELETE /v1/repositories/{repoOwner}/{repoName}/secrets/{secretName}", a.handleDeleteRepoSecret)
	mux.HandleFunc("GET /v1/repositories/{repoOwner}/{repoName}/branches", a.handleListRepoBranches)
	mux.HandleFunc("GET /v1/variables", a.handleListGeneralVariables)
	mux.HandleFunc("GET /v1/variables/scopes", a.handleListVariableScopes)
	mux.HandleFunc("GET /v1/variables/{variableName}", a.handleGetGeneralVariableValue)
	mux.HandleFunc("PUT /v1/variables/{variableName}", a.handleCreateOrUpdateGeneralVariable)
	mux.HandleFunc("DELETE /v1/variables/{variableName}", a.handleDeleteGeneralVariable)
	mux.HandleFunc("GET /v1/repositories/{repoOwner}/{repoName}/variables", a.handleListRepoVariables)
	mux.HandleFunc("GET /v1/repositories/{repoOwner}/{repoName}/variables/{variableName}", a.handleGetRepoVariableValue)
	mux.HandleFunc("PUT /v1/repositories/{repoOwner}/{repoName}/variables/{variableName}", a.handleCreateOrUpdateRepoVariable)
	mux.HandleFunc("DELETE /v1/repositories/{repoOwner}/{repoName}/variables/{variableName}", a.handleDeleteRepoVariable)
}

func (a *App) registerRunRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/runs/{runID}/status", a.handleGetRunStatus)
	mux.HandleFunc("POST /v1/internal/runs/{runID}/approvals/pause", a.handlePauseRunForApproval)
	mux.HandleFunc("GET /v1/internal/runs/{runID}/checkpoints/{checkpointID}", a.handleGetRunCheckpoint)
	mux.HandleFunc("POST /v1/internal/runs/{runID}/ai-usage", a.handleRecordAIUsage)
	mux.HandleFunc("POST /v1/run", a.handleRunPipeline)
	mux.HandleFunc("POST /v1/run/{pipelineName...}", a.handleRunPipeline)
	mux.HandleFunc("GET /v1/runs", a.handleListRuns)
	mux.HandleFunc("GET /v1/runs/{runID}/approvals", a.handleListRunApprovals)
	mux.HandleFunc("POST /v1/runs/{runID}/approvals/{approvalID}/approve", a.handleApproveRunApproval)
	mux.HandleFunc("POST /v1/runs/{runID}/approvals/{approvalID}/reject", a.handleRejectRunApproval)
	mux.HandleFunc("GET /v1/runs/{runID}/outputs/{outputID}/download", a.handleDownloadRunFinalOutput)
	mux.HandleFunc("GET /v1/runs/{runID}", a.handleGetRunDetails)
	mux.HandleFunc("DELETE /v1/runs/{runID}", a.handleDeleteRun)
	mux.HandleFunc("GET /v1/runs-by-check/{checkRunID}", a.handleGetRunByCheckID)
	mux.HandleFunc("POST /v1/runs/{runID}/rerun", a.handleRerunPipeline)
	mux.HandleFunc("POST /v1/runs/{runID}/cancel", a.handleCancelRun)
	mux.HandleFunc("POST /v1/runs/{runID}/finalize", a.handleFinalizeRun)
	mux.HandleFunc("POST /v1/runs/{runID}/steps/{stepName}/tasks/{taskName}", a.handleTaskUpdate)
	mux.HandleFunc("POST /v1/runs/{runID}/logs/ingest", a.handleIngestLogs)
	mux.HandleFunc("GET /v1/runs/{runID}/logs", a.handleGetRunLogs)
	mux.HandleFunc("DELETE /v1/repositories/{repoOwner}/{repoName}/branches/{branch...}", a.handleDeleteRepoBranchRuns)
}

func (a *App) buildHTTPHandler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /version", handleVersion)
	a.registerAuthRoutes(mux)
	a.registerAccessRoutes(mux)
	a.registerGitHubRoutes(mux)
	a.registerTeamRoutes(mux)
	a.registerSystemRoutes(mux)
	a.registerMonitoringRoutes(mux)
	a.registerAssistantRoutes(mux)
	a.registerHostedMCPRoutes(mux)
	a.registerPipelineRoutes(mux)
	a.registerScheduleRoutes(mux)
	a.registerDashboardRoutes(mux)
	a.registerExternalTriggerRoutes(mux)
	a.registerGitWebhookSourceRoutes(mux)
	a.registerKnowledgeContextRoutes(mux)
	a.registerSecretVariableRoutes(mux)
	a.registerRunRoutes(mux)
	a.registerSetupRoutes(mux)

	var handler http.Handler = mux
	handler = a.authzMiddleware(handler)
	handler = a.authMiddleware(handler)
	handler = a.auditMiddleware(handler)
	handler = recoveryMiddleware(handler)
	handler = loggingMiddleware(handler)
	handler = requestIDMiddleware(handler)
	handler = corsMiddleware(handler)
	return handler
}
