package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"

	"nopsai/internal/cli/apicatalog/internal/discovery"
)

func main() {
	root := flag.String("root", "", "repository root")
	output := flag.String("output", "catalog_generated.go", "generated output path")
	flag.Parse()
	if *root == "" {
		fatal("repository root is required")
	}
	routes, err := discovery.Discover(*root)
	if err != nil {
		fatal(err.Error())
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	source.WriteString("package apicatalog\n\n")
	source.WriteString("var generatedRoutes = []Route{\n")
	for _, route := range routes {
		fmt.Fprintf(&source, "\tnewRoute(%s, %s),\n", strconv.Quote(route.Method), strconv.Quote(route.Path))
	}
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatal("format generated catalog: " + err.Error())
	}
	outputPath := *output
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Clean(outputPath)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil { // #nosec G306 -- generated Go source is not sensitive.
		fatal("write generated catalog: " + err.Error())
	}
}

func fatal(message string) {
	_, _ = fmt.Fprintln(os.Stderr, "generate API catalog:", message)
	os.Exit(1)
}
