import { authEnvironmentFields } from '../fields/environment.js';
import type { WikiSection } from '../types.js';

export const administrationSection: WikiSection = {
  id: 'administration',
  title: 'Administration',
  group: 'run',
  owner: 'Platform administration',
  description: 'Teams, access, identity, credentials, GitOps authority, notifications, and data lifecycle.',
  articles: [
    {
      id: 'teams-and-ownership',
      title: 'Teams and resource ownership',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'Team paths are the ownership boundary for access, notifications, and GitOps authority.',
      keywords: ['team', 'ownership', 'team path', 'global', 'hierarchy', 'application'],
      keyFacts: [
        'Product team paths are canonical. Team sync and OIDC `team_mapping` mirror those paths into AAA auth-team subjects.',
        'Pipelines, reusable steps, schedules, scopes, and Knowledge Context expose a selectable `global` bucket for resources without a concrete team path.',
        '`root` and `general` are not accepted aliases for `global`.',
        '`All teams` is an aggregate filter only and must never be persisted as the resource owner.',
        'Mapped SSO teams get viewer access to the matching product team path when it exists, unless a stronger `basic_role_mapping` is configured.',
        'Team-scoped create authorization works before any resource row exists.',
      ],
      details: [
        'Create preflight that depends on manifest ownership can pass `team_path` or `run_team_path` to `GET /v1/access/effective-permissions`. That is how an inherited team owner creates the first schedule, trigger, external trigger, webhook source, or scope under their team without a seed resource.',
        'Teams can own applications, configuration repository bindings, notification routes, defaults, and their own LLM, Agent, and MCP profiles.',
        'Run ownership comes from `run_team_path` on the entry point, which is what drives notification lineage and Pipeline Runs grouping.',
      ],
      related: ['access-control', 'gitops-and-config-repositories', 'notifications'],
      sources: [
        { repositoryPath: 'doc/team-resource-ownership-design.md', purpose: 'Separation of Teams from Pipeline Runs and team-scoped profiles.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Team, application, defaults, and profile routes.' },
      ],
    },
    {
      id: 'access-control',
      title: 'Access control and AAA',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'How authorization decisions are made, where grants come from, and what is audited.',
      keywords: ['aaa', 'authorization', 'permissions', 'grants', 'roles', 'acl', 'audit'],
      keyFacts: [
        'AAA owns authorization decisions, policy checks, ACL expansion, filtering, and decision audit records.',
        'Every interface — UI, CLI, REST, hosted MCP, runners — passes through the same authorization boundary.',
        'AAA authorizes the original caller for every referenced resource, not only the entry point.',
        '`/v1/resources/...` routes are handler-authorized: middleware defers, then the handler resolves the concrete resource and checks owner-level manage access.',
        '`GET /v1/access/effective-permissions` answers "what may I do here", including for a team path with no resource row yet.',
        'IdP sync owns only `source: idp` grants for its provider; local UI, API, and GitOps grants stay editable.',
      ],
      details: [
        'Resource access has two questions: may the caller manage this resource, and may the caller use it inside a run. `POST /v1/authz/resource-use/check` and its batch form answer the second, which is what pipeline validation relies on when a run names a profile or knowledge document.',
        'System Access is presented as a compact settings workspace with Basic and Advanced modes over the existing AAA, GitOps, identity-provider, and service-account token APIs. The page introduces no separate policy mutation path.',
        'Authorization outcomes are auditable through `GET /v1/audit` and surface in monitoring under the security view.',
      ],
      related: ['teams-and-ownership', 'authentication-and-sso', 'tokens-and-service-accounts', 'api'],
      sources: [
        { repositoryPath: 'doc/access-control.md', purpose: 'AAA service, product roles, access grants, route authorization, and audit behavior.' },
        { repositoryPath: 'services/nopsai/resource_authz.go', purpose: 'Handler-level resource authorization.' },
      ],
    },
    {
      id: 'authentication-and-sso',
      title: 'Authentication and SSO',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary: 'Local login, OIDC and OAuth2 providers, and what actually constitutes identity.',
      keywords: ['auth', 'login', 'sso', 'oidc', 'oauth2', 'keycloak', 'identity', 'email'],
      keyFacts: [
        'Authentication identity is provider ID, issuer, and the ID-token subject. Email is nullable metadata and may be duplicated.',
        'Email carries a status: verified, unverified, unknown, or not-provided. Only an explicitly verified email may be used by opt-in email-linking policy.',
        'Malformed `email_verified` claims continue login as unknown email assurance and produce auth audit metadata.',
        'Local login and the protected break-glass administrator are always available.',
        'Only one external provider can be active per installation.',
        'Local username and password login can be disabled only while external authentication is enabled with at least one enabled provider.',
      ],
      details: [
        'Production authority lives in `setting/system/auth.yaml`, credential references, AAA ownership, and runtime IdP-managed identity state. The runnable fixtures under `examples/sso/keycloak` and `examples/sso/idp-test-pack` are test fixtures for local scenario testing, not production configuration.',
        'The identity-provider tab lists providers directly, while provider create and edit flows own provider details, OIDC connection, login defaults, mapping, and review panels.',
        'Login is rate limited and lockout protected through `RATE_LIMIT_LOGIN_PER_MINUTE`, `LOGIN_LOCKOUT_THRESHOLD`, and `LOGIN_LOCKOUT_WINDOW_MINUTES`.',
      ],
      fields: authEnvironmentFields,
      related: ['access-control', 'tokens-and-service-accounts', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Local auth, SSO/OIDC, user and service tokens, refresh behavior.' },
        { repositoryPath: 'doc/local-keycloak-sso.md', purpose: 'The local Keycloak fixture with seeded users and teams.' },
        { repositoryPath: 'examples/sso/README.md', purpose: 'Runnable SSO example fixtures. Test material only.' },
      ],
    },
    {
      id: 'tokens-and-service-accounts',
      title: 'Tokens and service accounts',
      docType: 'reference',
      audiences: ['administrator', 'developer', 'security'],
      summary: 'Personal access tokens, service accounts, and the internal service tokens components use.',
      keywords: ['token', 'pat', 'service account', 'jwt', 'api key', 'automation'],
      keyFacts: [
        '`JWT_SIGNING_KEY` signs user, personal-access, service-account, browser, CLI, automation, and hosted MCP tokens.',
        '`SERVICE_JWT_SIGNING_KEY` signs internal REST and dispatcher service tokens and must be a different secret.',
        'Personal access tokens are created and revoked by the owning user under `/v1/auth/personal-tokens`.',
        'Service account tokens are administrator-managed under `/v1/admin/service-accounts/{id}/tokens`.',
        'Token values are returned once at creation and cannot be read back.',
        'A service account is a first-class caller for AAA, so it can be named in external trigger `allowed_callers`.',
      ],
      details: [
        'Use a service account for machine-to-machine automation rather than a human personal access token. It survives staff changes and carries its own roles and grants.',
        'Internal service tokens are not part of the public surface. Routes under `/v1/internal/` and the git-bot event ingress require them and should never be exposed as public endpoints.',
      ],
      related: ['authentication-and-sso', 'access-control', 'external-triggers', 'api'],
      sources: [
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Token types, signing keys, and refresh behavior.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Personal token and service account token routes.' },
      ],
    },
    {
      id: 'credentials',
      title: 'Credentials and secrets store',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'One encrypted registry behind every credential reference, with versions, rotation, and GitOps envelopes.',
      keywords: ['credential', 'secret', 'rotation', 'encryption', 'registry', 'envelope', 'master key'],
      keyFacts: [
        'There is a single credential interface. LLM Profiles, MCP servers, Git Apps, webhook sources, and registry auth all reference it rather than storing values themselves.',
        '`NOPSAI_MASTER_KEY` is the root encryption material for the registry.',
        'Credential values are write-only: the API returns metadata but never the value after submission.',
        'Credentials are versioned. A rotation creates a new version, and a specific version can be activated or deleted.',
        'A credential can be disabled without being deleted.',
        '`POST /v1/secrets/encrypt` produces a GitOps-safe envelope so a secret can live in a configuration repository without being readable there.',
      ],
      details: [
        'Legacy inline forms — `api_key_secret` on an LLM profile, `auth_secret` on an MCP server, `GITHUB_PRIVATE_KEY` and `GITHUB_WEBHOOK_SECRET` — remain only for migration. New configuration should use credential references.',
        'Losing the master key makes stored credentials unrecoverable. Rotating it requires re-encrypting the registry, so treat it as the most sensitive value in the deployment.',
      ],
      related: ['variables-secrets-scopes', 'llm-profiles', 'private-registry-auth', 'production-hardening'],
      sources: [
        { repositoryPath: 'doc/credential-management.md', purpose: 'Encrypted registry, GitOps envelopes, AAA, rotation, and migration.' },
        { repositoryPath: 'services/nopsai/credential_schema.go', purpose: 'Credential schema and version handling.' },
      ],
    },
    {
      id: 'gitops-and-config-repositories',
      title: 'GitOps and configuration repositories',
      docType: 'reference',
      audiences: ['administrator', 'automation-author'],
      summary: 'Which resources Git can own, how sync applies them, and what happens when the UI edits a managed resource.',
      keywords: ['gitops', 'config repository', 'sync', 'drift', 'desired state', 'override'],
      keyFacts: [
        'GitOps can manage `pipelines/`, `steps/`, `schedules/`, `triggers/`, `external-triggers/`, `git-webhook-sources/`, `dashboards/`, `scopes/`, `knowledge/`, `access/`, `config-repositories/`, `setting/git-apps/`, and `setting/system/`.',
        'Canonical system files: `credentials.yaml`, `runner.yaml`, `auth.yaml`, `mail.yaml`, `data-management.yaml`, `llm_profile.yaml`, `mcp.yaml`, `agent-profiles.yaml`, plus `setting/git-apps/github.yaml`.',
        'UI or API edits to GitOps-managed resources create database overrides. The next sync can replace or recreate them unless the change is pushed back.',
        'Sync applies dependency roots first: team hierarchy from `config-repositories/`, then team-owned dashboards and notification routes, then pipeline dashboard outputs.',
        'Long-running syncs can be canceled. If no worker is registered but the row is still `running`, cancellation marks it `canceled` so operators can retry without editing the database.',
        '`setting/git-apps/github.yaml` is app-scoped; the legacy `setting/system/github.yaml` is read for migration compatibility for one release.',
      ],
      details: [
        'Drift review presents Git and NopsAI panes side by side with line numbers, synchronized scrolling, and highlighted removed Git lines and added desired lines before a push.',
        'Both a global configuration repository and per-team repositories are supported. Team repositories are bound through `PUT /v1/teams/{teamID}/config-repository`.',
        'Internal service URLs stay in system configuration rather than in the app-scoped Git App file.',
      ],
      examples: [
        {
          title: 'Configuration repository layout',
          language: 'text',
          code: [
            'pipelines/            steps/               schedules/',
            'triggers/             external-triggers/   git-webhook-sources/',
            'dashboards/           scopes/              knowledge/',
            'access/               config-repositories/',
            'setting/git-apps/github.yaml',
            'setting/system/credentials.yaml',
            'setting/system/runner.yaml',
            'setting/system/auth.yaml',
            'setting/system/mail.yaml',
            'setting/system/data-management.yaml',
            'setting/system/llm_profile.yaml',
            'setting/system/mcp.yaml',
            'setting/system/agent-profiles.yaml',
          ].join('\n'),
        },
      ],
      related: ['teams-and-ownership', 'credentials', 'schedules', 'dashboards'],
      sources: [
        { repositoryPath: 'examples/sample-config-repo/README.md', purpose: 'Full GitOps sample repository layout.' },
        { repositoryPath: 'services/nopsai/config_sync_apply.go', purpose: 'Apply order and upsert behavior.' },
      ],
    },
    {
      id: 'notifications',
      title: 'Notifications',
      docType: 'how-to',
      audiences: ['administrator', 'operator'],
      summary: 'Team-routed mail notifications for run outcomes, approvals, and alerts.',
      keywords: ['notification', 'email', 'smtp', 'mail', 'alert', 'routing'],
      keyFacts: [
        'SMTP settings live in `setting/system/mail.yaml` and are managed through `/v1/system/notifications/mail`.',
        '`POST /v1/system/notifications/mail/test` sends a test message so delivery can be verified before an incident depends on it.',
        'Notification routes are owned per team through `/v1/teams/{teamID}/notifications`.',
        'Run notification lineage follows `run_team_path`, which is why schedules and external triggers set it.',
        'Branding is controlled by `NOPSAI_MAIL_LOGO_URL`, `NOPSAI_MAIL_WEBSITE_URL`, `NOPSAI_MAIL_SUPPORT_URL`, and `NOPSAI_MAIL_FOOTER_ADDRESS`.',
      ],
      details: [
        'Approval checkpoints are the most valuable notification target: a paused run costs nothing but blocks delivery until someone decides.',
        'Monitoring alert rules are a separate mechanism from run notifications. Rules evaluate metric conditions and produce alert events.',
      ],
      related: ['teams-and-ownership', 'approvals', 'monitoring'],
      sources: [
        { repositoryPath: 'services/nopsai/notification_schema.go', purpose: 'Notification route and mail settings schema.' },
      ],
    },
    {
      id: 'data-management',
      title: 'Backups and data cleanup',
      docType: 'how-to',
      audiences: ['administrator', 'operator'],
      summary: 'Creating backups, scheduling cleanup, and the restore boundary you need to plan around.',
      keywords: ['backup', 'cleanup', 'retention', 'restore', 'data management', 'archive'],
      keyFacts: [
        'Backups are gzip-compressed JSON Lines files written under `DATA_BACKUP_DIR`, defaulting to `/data/backups`.',
        'The product supports backup creation, listing, checksum metadata, download, and cleanup.',
        'Cleanup can be previewed before it runs, and can be scheduled with enable, disable, and run-now controls.',
        'The default Compose topology does not mount the backup path as durable storage.',
        'Settings are GitOps-managed through `setting/system/data-management.yaml`.',
      ],
      details: [
        'Always preview a cleanup before running it in an environment with real history. The preview reports what would be removed under the current retention rules.',
        'Because there is no product-managed upload to object storage, exporting backups off the host is a deployment responsibility.',
      ],
      limits: [
        'A complete product-managed restore workflow is not implemented. Plan recovery around your own PostgreSQL restore procedure.',
        'There is no product-managed backup upload to object storage.',
      ],
      related: ['storage-and-persistence', 'known-limits', 'gitops-and-config-repositories'],
      sources: [
        { repositoryPath: 'services/nopsai/data_management_gitops.go', purpose: 'Cleanup schedule schema and GitOps ownership.' },
      ],
    },
  ],
};
