import {
  agentProfileFields,
  governanceLevels,
  knowledgeFields,
  llmProfileFields,
  mcpProfileFields,
  mcpServerFields,
} from '../fields/ai.js';
import type { WikiSection } from '../types.js';

export const aiSection: WikiSection = {
  id: 'ai',
  title: 'AI, knowledge, and governance',
  group: 'build',
  owner: 'AI platform',
  description: 'The separate control layers that decide how the AI behaves, which model it uses, what tools it reaches, and what may block it.',
  articles: [
    {
      id: 'ai-control-layers',
      title: 'The AI control layers',
      docType: 'concept',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'Five independent layers decide AI behavior. Confusing them is the most common source of surprise.',
      keywords: ['ai', 'control', 'layers', 'separation', 'persona', 'model', 'tools'],
      keyFacts: [
        '**Agent Profile** controls persona, role, and prompt instructions. It does not control provider, model, secrets, tools, credentials, or permissions.',
        '**LLM Profile** controls provider, model, endpoint, credential reference, timeout, tokens, and temperature. It does not control persona, authorization, Knowledge Context, or MCP server definitions.',
        '**MCP Profiles** control which external servers and tools LLM goals may reach. Pipeline YAML cannot declare arbitrary server URLs.',
        '**Knowledge Context** supplies architecture, policy, guardrail, example, and runbook documents. It does not by itself grant runtime resource permission.',
        '**AAA** decides whether the original caller may use each selected resource. It does not affect model selection or prompt wording.',
      ],
      details: [
        'Resolution order for conditions and LLM-backed tasks: task `llm_profile`, then step, then pipeline, then the configured default. Final outputs resolve item, then `output.llm_profile`, then pipeline, then default. Agent Profile resolves step, then pipeline, then default.',
        'MCP profiles are the exception: they are additive. Pipeline, step, and task profiles are merged and deduplicated rather than overriding one another.',
        'Naming a profile in YAML never grants access to it. Validation checks that the profile exists, is enabled, and is allowed in the run scope; AAA then checks whether the original caller may use it.',
      ],
      examples: [
        {
          title: 'Common questions, answered by the layer model',
          language: 'text',
          code: [
            'Can a task set agent_profile?            No. Pipeline and step only.',
            'Does steps[].llm_profile grant access?  No. AAA and scope still decide.',
            'Can a script task use mcp_profiles?     No. LLM goal work only.',
            'What happens with llm_enabled: false?   Script-only. No goals, conditions,',
            '                                        final outputs, explicit MCP use, or',
            '                                        blocking knowledge on scripts.',
            'Do MCP profiles override or merge?      Merge, deduplicated across levels.',
          ].join('\n'),
        },
      ],
      related: ['agent-profiles', 'llm-profiles', 'mcp', 'knowledge-context', 'governance-and-policy'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Profile resolution and scope validation.' },
        { repositoryPath: 'doc/decision-architecture.md', purpose: 'Why these layers are kept separate.' },
      ],
    },
    {
      id: 'agent-profiles',
      title: 'Agent Profiles',
      docType: 'reference',
      audiences: ['automation-author', 'administrator'],
      summary: 'Named personas and prompt instructions selected by pipelines and steps.',
      keywords: ['agent profile', 'persona', 'role', 'instructions', 'prompt'],
      keyFacts: [
        'A profile carries an ID, display name, optional role and description, instructions, and an enabled flag.',
        'Referencing a missing or disabled profile is a validation error, not a silent fallback.',
        'Profiles can be system-wide (`setting/system/agent-profiles.yaml`) or team-owned.',
        '`agent_profile` is valid on a pipeline and a step. A task that sets it fails at parse time.',
        'Instructions shape behavior only — they grant no provider access, tools, credentials, or permissions.',
      ],
      details: [
        'The platform default profile applies when nothing more specific is selected. Setting a team default lets a team standardize its persona without editing every pipeline.',
        '`GET /v1/system/agent-profiles/{profileID}/usage` shows which pipelines and steps reference a profile, which is what you want before disabling or deleting one.',
        'The Agent Profiles workspace keeps the default-profile control on the left, uses compact list-header search and create actions, and shows team tree counts that include cached team-owned profiles.',
      ],
      fields: agentProfileFields,
      examples: [
        {
          title: 'A cautious release persona',
          language: 'yaml',
          code: [
            'id: senior-release-engineer',
            'display_name: Senior Release Engineer',
            'role: Release engineer',
            'description: Cautious operator persona for production release work.',
            'enabled: true',
            'instructions: |',
            '  Prefer reversible actions over irreversible ones.',
            '  Never skip a failing check to make a run pass.',
            '  When evidence is ambiguous, stop and explain what is missing.',
          ].join('\n'),
        },
      ],
      related: ['ai-control-layers', 'llm-profiles', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'pkg/models/agent_profile.go', purpose: 'Agent Profile struct and defaults.' },
        { repositoryPath: 'doc/agent-profiles.md', purpose: 'GitOps management, AAA, and runtime prompt behavior.' },
      ],
    },
    {
      id: 'llm-profiles',
      title: 'LLM Profiles',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'Provider, model, endpoint, credential, and generation settings — the layer that decides which model actually runs.',
      keywords: ['llm profile', 'provider', 'model', 'openai', 'anthropic', 'ollama', 'credential', 'temperature'],
      keyFacts: [
        'Supported providers: `gemini`, `lmstudio`, `openai`, `anthropic`, `groq`, `mistral`, `ollama`, `openrouter`, `azure-openai`.',
        '`reasoning` and `thinking` are generic NopsAI options for LM Studio only. Other providers reject a generic value rather than silently ignoring stale configuration.',
        '`max_tokens` is supported by every current provider.',
        '`allowed_scopes` restricts which run scopes may select the profile; an empty list permits every scope.',
        'The credential value is write-only and is never returned by the API after submission.',
        'A local provider URL must be reachable from the API runtime — inside containers use a LAN IP or `host.docker.internal`, not `localhost`.',
      ],
      details: [
        'Profiles can be system-wide or team-owned, and a team can set its own default. Assistant chat and AI Evaluation select from the same profile set that pipelines do.',
        'Use the profile test action before a pipeline depends on it. A broken credential surfaces there instead of failing every goal at run time.',
        'Prompt cache and provider state settings are recorded in telemetry as hashes, revision markers, cache and session identity, and token counts — prompt bodies are not stored.',
      ],
      fields: llmProfileFields,
      examples: [
        {
          title: 'Hosted provider with scope restriction',
          language: 'yaml',
          code: [
            'reasoning-large:',
            '  provider: anthropic',
            '  model: claude-sonnet-4-5',
            '  credential_ref: llm/anthropic-prod',
            '  max_tokens: 8192',
            '  temperature: 0.2',
            '  timeout_seconds: 120',
            '  allowed_scopes:',
            '    - platform/production',
          ].join('\n'),
        },
        {
          title: 'Local LM Studio profile with reasoning',
          language: 'yaml',
          code: [
            'local-reasoning:',
            '  provider: lmstudio',
            '  model: qwen2.5-coder-32b',
            '  base_url: http://host.docker.internal:1234/v1',
            '  reasoning: high',
          ].join('\n'),
          expectedOutput: 'Accepted. The same `reasoning` value on an OpenAI profile would be rejected.',
        },
      ],
      related: ['ai-control-layers', 'credentials', 'assistant'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'Provider constants, reasoning levels, and profile struct.' },
        { repositoryPath: 'doc/llm-model-selection.md', purpose: 'Provider and model selection notes.' },
      ],
    },
    {
      id: 'mcp',
      title: 'MCP servers and profiles',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'External tool access for LLM goals, constrained by an explicit server and tool allowlist.',
      keywords: ['mcp', 'tools', 'servers', 'allowlist', 'integration', 'model context protocol'],
      keyFacts: [
        'A server definition holds the endpoint and credential; a profile is the allowlist that pipelines may reference.',
        'Pipeline YAML can reference profiles only. It cannot declare arbitrary server URLs.',
        'The agent accepts only server/tool pairs present in the resolved profile allowlist.',
        'Profiles are additive across pipeline, step, and task, then deduplicated.',
        '`mcp_profiles` is invalid on include steps, script steps, and script tasks.',
        'External MCP currently uses streamable HTTP.',
      ],
      details: [
        'Narrowing `servers[].tools` is the primary way to limit what LLM goal work can do. A profile that lists a server without a tool list grants every tool that server exposes.',
        'In database-backed deployments, PostgreSQL and the system/global GitOps files are authoritative for external MCP. Mirroring runtime MCP edits back to bootstrap `config.yml` is best-effort after database persistence.',
        'Blocking Knowledge Context applies to MCP calls and MCP arguments as well as to goals, commands, scripts, file writes, and conditions.',
        'NopsAI also exposes its own hosted MCP endpoint at `POST /v1/mcp`, which is a separate surface — see the hosted MCP interface page.',
      ],
      fields: [...mcpServerFields, ...mcpProfileFields],
      examples: [
        {
          title: 'Read-only profile over one server',
          language: 'yaml',
          code: [
            'servers:',
            '  jira:',
            '    enabled: true',
            '    url: https://mcp.internal.example.com/jira',
            '    auth_type: bearer',
            '    credential_ref: mcp/jira-token',
            '    timeout: 30s',
            'profiles:',
            '  jira-readonly:',
            '    enabled: true',
            '    description: Read-only Jira lookups for release notes.',
            '    servers:',
            '      - server: jira',
            '        tools: [search_issues, get_issue]',
          ].join('\n'),
          expectedOutput: 'Goals referencing `jira-readonly` can call those two tools and nothing else.',
        },
      ],
      limits: [
        'Local MCP URLs must be reachable from the API runtime; `localhost` inside a container refers to the container itself.',
      ],
      related: ['ai-control-layers', 'hosted-mcp', 'credentials'],
      sources: [
        { repositoryPath: 'pkg/models/mcp.go', purpose: 'Server and profile struct definitions.' },
        { repositoryPath: 'doc/mcp-pipeline-integration.md', purpose: 'How MCP is wired into pipeline execution.' },
      ],
    },
    {
      id: 'knowledge-context',
      title: 'Knowledge Context',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'Documents injected into prompts, and the two kinds that can block execution outright.',
      keywords: ['knowledge', 'guardrail', 'policy', 'adr', 'runbook', 'context', 'documents'],
      keyFacts: [
        'Supported kinds: `architecture`, `guardrail`, `policy`, `adr`, `guideline`, `runbook`, `reference`, `example`.',
        '`guardrail` and `policy` are blocking kinds. They apply to goals, commands, direct scripts, file writes, MCP calls, MCP arguments, and conditions.',
        'Use exactly one of `ref` (a managed `team/document`) or `path` (repo-local, loaded at the run commit).',
        'A managed `ref` requires `knowledge_context.use` permission on that document.',
        '`required: true` fails the run before execution when resolution or authorization fails.',
        'Resolved content is snapshotted on the run, so later document edits never rewrite run history.',
      ],
      details: [
        'Pipeline, step, and task knowledge context are merged, not replaced. The most specific level adds to what the broader levels already supply.',
        'Blocking kinds are pinned by scope at run start and recomputed as pipeline, step, and task scopes begin. Emergency policy response cancels active runs rather than mutating already-resolved policy.',
        'A script step with blocking context has its exact command LLM-validated before execution. That is why `llm_enabled: false` rejects such a combination.',
      ],
      fields: knowledgeFields,
      examples: [
        {
          title: 'Managed guardrail plus a repo-local example',
          language: 'yaml',
          code: [
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            '  - kind: architecture',
            '    path: .nopsai/docs/backend.md',
          ].join('\n'),
          expectedOutput:
            'The guardrail must resolve and authorize or the run fails before execution. The architecture document is read from the run repository at the run commit.',
        },
      ],
      related: ['governance-and-policy', 'ai-control-layers', 'access-control'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Kind, ref, and path validation.' },
        { repositoryPath: 'doc/knowledge-context.md', purpose: 'GitOps layout, runtime snapshots, and access checks.' },
      ],
    },
    {
      id: 'governance-and-policy',
      title: 'Governance levels',
      docType: 'reference',
      audiences: ['administrator', 'security', 'automation-author'],
      summary: 'How NopsAI acts on an AI policy review decision, and why the default is the strict one.',
      keywords: ['governance', 'policy', 'strict', 'advisory', 'guarded', 'exception', 'enforcement'],
      keyFacts: [
        'An unset `governance_level` normalizes to `strict`, the most restrictive level.',
        '`strict` proceeds only on a clear allow. Violations, conflicts, uncertainty, missing reviews, and unsupported decisions all block.',
        '`guarded` blocks clear violations and conflicts but treats uncertainty as a warning.',
        '`advisory` logs and warns; execution usually proceeds.',
        '`exception_based` allows normal approvals and lets conflicts proceed only with an effective approved exception. Violations and uncertainty still block.',
        'The deprecated `policy_merge_mode` still parses: `restrictive` and `fail_on_conflict` become `strict`, `override` becomes `guarded`. Setting both is an error.',
      ],
      details: [
        'The level can be set at pipeline, step, or task, with the most specific value winning. This lets a pipeline stay strict overall while one well-understood task runs advisory.',
        'Governance interacts with Knowledge Context: the policy review is what produces the decision, and the governance level is what NopsAI does with it. Without blocking knowledge there is nothing to enforce.',
      ],
      fields: governanceLevels,
      examples: [
        {
          title: 'Strict pipeline with one advisory task',
          language: 'yaml',
          code: [
            'governance_level: strict',
            'knowledge_context:',
            '  - kind: policy',
            '    ref: platform/deploy-policy',
            '    required: true',
            'steps:',
            '  - name: analyze',
            '    tasks:',
            '      - name: draft-summary',
            '        governance_level: advisory',
            '        goal: Draft a human-readable summary of the proposed change.',
          ].join('\n'),
        },
      ],
      limits: ['Lowering the governance level weakens fail-closed enforcement; it does not disable the policy review itself.'],
      related: ['knowledge-context', 'ai-control-layers', 'access-control'],
      sources: [
        { repositoryPath: 'pkg/models/policy_merge.go', purpose: 'Level constants, normalization, and the strict default.' },
      ],
    },
  ],
};
