import { access_controlRoutes } from '../fields/api/access-control.js';
import { ai_configurationRoutes } from '../fields/api/ai-configuration.js';
import { assistant_and_ai_surfacesRoutes } from '../fields/api/assistant-and-ai-surfaces.js';
import { authenticationRoutes } from '../fields/api/authentication.js';
import { dashboardsRoutes } from '../fields/api/dashboards.js';
import { external_triggersRoutes } from '../fields/api/external-triggers.js';
import { first_install_setupRoutes } from '../fields/api/first-install-setup.js';
import { git_integrationRoutes } from '../fields/api/git-integration.js';
import { gitops_and_config_syncRoutes } from '../fields/api/gitops-and-config-sync.js';
import { identity_administrationRoutes } from '../fields/api/identity-administration.js';
import { internal_service_routesRoutes } from '../fields/api/internal-service-routes.js';
import { knowledge_contextRoutes } from '../fields/api/knowledge-context.js';
import { monitoringRoutes } from '../fields/api/monitoring.js';
import { pipelines_and_stepsRoutes } from '../fields/api/pipelines-and-steps.js';
import { runsRoutes } from '../fields/api/runs.js';
import { schedulesRoutes } from '../fields/api/schedules.js';
import { system_operationsRoutes } from '../fields/api/system-operations.js';
import { teamsRoutes } from '../fields/api/teams.js';
import { variables_and_secretsRoutes } from '../fields/api/variables-and-secrets.js';
import { platform_probesRoutes } from '../fields/api/platform-probes.js';
import type { WikiSection } from '../types.js';

export const apiSection: WikiSection = {
  id: 'api',
  title: 'API',
  owner: 'Platform engineering',
  description: 'The REST surface: what authenticates against it, how routes are organised, and the complete endpoint list.',
  articles: [
    {
      id: 'api',
      title: 'REST API',
      docType: 'reference',
      audiences: ['developer', 'automation-author', 'operator'],
      summary: 'How the API is structured, what authenticates against it, and where the complete route list lives.',
      keywords: ['api', 'rest', 'endpoint', 'http', 'v1', 'token', 'bearer'],
      keyFacts: [
        'Every route is versioned under `/v1`, except the platform probes `/healthz`, `/livez`, `/version`, `/metrics`, and `/favicon.ico`.',
        'Authenticate with a bearer token: a personal access token, a service account token, or a session token.',
        'Every request passes the same chain: request ID, CORS, body limit, logging, recovery, audit, authentication, authorization.',
        '`/v1/setup/preflight` is public by design so a stuck install can be diagnosed without a token. The rest of the setup surface needs one.',
        'Routes under `/v1/internal/` require an internal service token and are not part of the public surface.',
        'The complete route list, grouped by area with access class, is on the REST API index.',
      ],
      details: [
        'Resource routes under `/v1/resources/...` are handler-authorized: the middleware defers, then the handler resolves the concrete resource and checks owner-level manage access before reading settings, changing visibility, or adding and removing use grants.',
        'List endpoints are authorization-filtered rather than returning everything and hiding it client-side, so an empty list can legitimately mean "you have no access here".',
        'Request bodies are size-limited platform-wide, and login is separately rate-limited.',
      ],
      examples: [
        {
          title: 'Authenticate and start a run',
          language: 'bash',
          code: [
            'export NOPSAI_URL=https://nopsai.example.com',
            'export NOPSAI_TOKEN=<personal access token>',
            '',
            'curl -s "$NOPSAI_URL/v1/auth/me" -H "Authorization: Bearer $NOPSAI_TOKEN"',
            'curl -sX POST "$NOPSAI_URL/v1/run/platform%2Fdeploy-service" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN"',
          ].join('\n'),
          placeholders: ['Create the token under Profile, then Personal access tokens.'],
        },
        {
          title: 'Validate a pipeline before saving it',
          language: 'bash',
          code: [
            'curl -sX POST "$NOPSAI_URL/v1/pipelines/validate" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/yaml" \\',
            '  --data-binary @pipeline.yaml',
          ].join('\n'),
          expectedOutput: 'Validation errors name the exact step, task, or directive at fault.',
        },
      ],
      related: ['api-index', 'tokens-and-service-accounts', 'access-control', 'cli'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Every registered route and its handler.' },
        { repositoryPath: 'doc/api.md', purpose: 'Request and response shapes per area.' },
      ],
    },
    {
      id: 'api-calling',
      title: 'Calling the API',
      docType: 'tutorial',
      audiences: ['developer', 'automation-author', 'operator'],
      summary:
        'One worked path from a login to a run: get a token, call a route, read the response, and handle the failure modes.',
      keywords: ['api', 'token', 'bearer', 'curl', 'cli', 'authentication', 'getting started', 'integration'],
      keyFacts: [
        'Everything except the public routes needs `Authorization: Bearer <token>`.',
        'Three token kinds reach the same surface: a session access token, a personal access token, and a service account token.',
        'A system that calls the API should hold a service account token, not a token minted from a person\'s account.',
        'Token values are returned once, at creation. There is no route that reads one back.',
        'The `nopsai` CLI drives the same routes with the same authorization: it adds no server behaviour of its own.',
      ],
      prerequisites: [
        { label: 'A reachable API', value: 'The API address, `http://localhost:8080` on a local install', verification: 'curl -s "$NOPSAI_URL/livez"' },
        { label: 'Credentials', value: 'A local account, or an existing personal or service account token' },
        { label: 'Tools', value: '`curl` and `jq`, or any HTTP client', verification: 'curl --version && jq --version' },
      ],
      steps: [
        {
          title: 'Get a token',
          description:
            'Logging in gives a short-lived access token. For anything automated, exchange it once for a personal access token — or better, use a service account.',
          commands: [
            {
              title: 'Log in and mint a personal token',
              language: 'bash',
              code: [
                'ACCESS=$(curl -sX POST "$NOPSAI_URL/v1/auth/login" \\',
                '  -H "Content-Type: application/json" \\',
                '  -d "{\\"identifier\\":\\"admin@example.com\\",\\"password\\":\\"$PASSWORD\\"}" | jq -r .access_token)',
                '',
                'curl -sX POST "$NOPSAI_URL/v1/auth/personal-tokens" \\',
                '  -H "Authorization: Bearer $ACCESS" \\',
                '  -H "Content-Type: application/json" \\',
                '  -d \'{"name":"integration"}\' | jq',
              ].join('\n'),
              placeholders: ['`$PASSWORD` is the account password; the first login forces a rotation.'],
            },
          ],
          expectedOutput: 'A token value, returned once. Store it where you keep other credentials.',
          warning: 'The first login of the bootstrap administrator must rotate its password before other routes will answer.',
        },
        {
          title: 'Confirm who you are',
          description: 'This is the fastest way to tell an authentication problem from an authorization one.',
          commands: [
            { title: 'Read the current identity', language: 'bash', code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/auth/me" | jq' },
          ],
          expectedOutput: 'The identity, its roles, and its effective capabilities. A 401 here means the token is wrong; a 403 elsewhere means the token is right and the access is not.',
        },
        {
          title: 'Call a route',
          description: 'Every authenticated route follows the same shape, so one working call generalises.',
          commands: [
            { title: 'List runs', language: 'bash', code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/runs?limit=5" | jq \'.[] | {run_id, pipeline_name, status}\'' },
          ],
          verification: 'A JSON array comes back, filtered to what this caller is allowed to see.',
        },
        {
          title: 'Ask for JSON when a route can answer either way',
          description:
            'A few routes answer with plain text unless the request asks for JSON. Starting a run is the one most integrations hit first.',
          commands: [
            {
              title: 'Start a run and read the run ID',
              language: 'bash',
              code: [
                'curl -sX POST "$NOPSAI_URL/v1/run/first-pipeline" \\',
                '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
                '  -H "Accept: application/json" \\',
                '  -H "Content-Type: application/json" \\',
                '  -d \'{"scope":"platform/production"}\' | jq -r .run_id',
              ].join('\n'),
            },
          ],
          expectedOutput: 'Without `Accept: application/json` the same call returns `Pipeline run created successfully with ID: <uuid>` as text.',
        },
        {
          title: 'Use the CLI when you would rather not hand-roll requests',
          description: 'The CLI carries a generated route catalogue that is parity-tested against the registered routes, so it cannot drift from the API.',
          commands: [
            {
              title: 'The same calls through the CLI',
              language: 'bash',
              code: [
                'nopsai context add local --api "$NOPSAI_URL"',
                'NOPSAI_TOKEN=nopat_<secret> nopsai api request GET /v1/runs',
                'nopsai api call GET \'/v1/runs/{runID}\' --path runID=<run-id>',
                'nopsai api routes --output json',
              ].join('\n'),
              placeholders: ['Replace `nopat_<secret>` and `<run-id>` with real values.'],
            },
          ],
        },
      ],
      details: [
        'Authorization is resolved per resource, not per route. Two callers hitting the same list endpoint can legitimately receive different rows, because AAA filters the result to what each may see.',
        'A 401 is about the token: missing, expired, or malformed. A 403 is about the caller: the token is valid and the action is not permitted on that resource. Treat them as different bugs.',
        'Public routes are the exception rather than the rule: the platform probes, the setup routes, login and token refresh, the OIDC and OAuth2 callbacks, provider webhook ingress, and the runner bootstrap download.',
      ],
      related: ['api', 'authentication-and-sso', 'tokens-and-service-accounts', 'cli'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'The registered route surface and its middleware chain.' },
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Token kinds, claims, refresh, and service tokens.' },
        { repositoryPath: 'internal/cli/apicatalog/catalog.go', purpose: 'Generated route catalogue the CLI drives.' },
      ],
    },
    {
      id: 'api-authentication',
      title: 'Authentication API',
      docType: 'reference',
      audiences: ['developer', 'security', 'administrator'],
      summary: 'Logging in, refreshing, logging out, minting personal tokens, and the two browser flows that hand identity over from a provider.',
      keywords: ['login', 'token', 'refresh', 'logout', 'oidc', 'oauth2', 'personal token', 'session', 'sso'],
      keyFacts: [
        'Identity is provider ID, issuer, and subject. Email is metadata with a verification status and never decides who a caller is.',
        'Login takes `identifier` and `password` — `identifier` accepts the subject or the email.',
        'Provider discovery takes `email`, which is a different field name from login on purpose: one resolves a domain, the other authenticates a subject.',
        'A 401 on login is deliberately identical for an unknown account and a wrong password.',
        'Token values — session, personal, and service account alike — are returned once at creation and never readable afterwards.',
        'The browser flows never put provider tokens in a URL: the callback issues a one-time code that is exchanged server side.',
        '`must_change_password: true` means the forced rotation is pending and other routes will keep refusing until it is done.',
      ],
      apiRoutes: authenticationRoutes,
      details: [
        'Three token kinds reach the same surface with the same authorization: a session access token from login, a personal access token that acts as the person who created it, and a service account token that acts as a system. Choosing the wrong one is the most common integration mistake, because it works right up until the person leaves.',
        'The OIDC and OAuth2 pairs exist for different provider capabilities rather than different security models. GitHub uses the OAuth2 pair because it does not issue an ID token; everything else about the flow, including state validation and the one-time exchange code, is the same.',
        'Logout is the only way a refresh token stops working before it expires. If a refresh token leaks, revoking the session is the fix — rotating a password does not invalidate it.',
      ],
      related: ['api-calling', 'authentication-and-sso', 'tokens-and-service-accounts', 'access-control'],
      sources: [
        { repositoryPath: 'services/nopsai/auth_handlers.go', purpose: 'Login, refresh, logout, and identity handlers.' },
        { repositoryPath: 'services/nopsai/auth_models.go', purpose: 'Request and response shapes for every route on this page.' },
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Token kinds, claims, refresh storage, and service tokens.' },
      ],
    },
    {
      id: 'api-platform-probes',
      title: 'Platform probes',
      docType: 'reference',
      audiences: ['operator', 'administrator', 'developer'],
      summary: 'The five routes that answer without a token, and what an operator should assert on each.',
      keywords: ['healthz', 'livez', 'version', 'metrics', 'favicon', 'probe', 'readiness', 'liveness'],
      keyFacts: [
        'All five are public by design: they have to work when authentication does not.',
        '`/livez` reports the process; `/healthz` reports readiness and stays unready while the database is unreachable.',
        '`/version` is the compatibility contract — released CLIs read it to refuse incompatible mutating requests.',
        '`/metrics` is public unless `METRICS_REQUIRE_AUTH=true`.',
        'None of them writes anything, and `/favicon.ico` exists specifically to keep browser probes out of the audit log.',
      ],
      apiRoutes: platform_probesRoutes,
      examples: [
        {
          title: 'Check every probe in one pass',
          language: 'bash',
          code: [
            'curl -s "$NOPSAI_URL/livez"',
            'curl -s -o /dev/null -w "healthz: %{http_code}\\n" "$NOPSAI_URL/healthz"',
            'curl -s "$NOPSAI_URL/version" | jq \'{productVersion, apiVersion, runnerProtocolVersion}\'',
            'curl -s "$NOPSAI_URL/metrics" | head -5',
          ].join('\n'),
          expectedOutput:
            '`livez` answers immediately, `healthz` returns 200 once the database is reachable and 503 before that, and `version` reports the build the images were produced from.',
          placeholders: ['`$NOPSAI_URL` is the API address, `http://localhost:8080` on a local install.'],
        },
      ],
      details: [
        'Gate restarts on `/livez` and traffic on `/healthz`. Inverting the two produces a restart loop during a slow database start, because readiness is exactly the thing that is temporarily false.',
        'During setup-preflight mode `/healthz` answers 503 with the full preflight document rather than a bare status, so the blocking check is visible without a second call.',
      ],
      related: ['api-setup', 'monitoring', 'release-integrity'],
      sources: [
        { repositoryPath: 'services/nopsai/health_handler.go', purpose: 'Readiness and liveness responses.' },
        { repositoryPath: 'services/nopsai/version_handler.go', purpose: 'Public build identity payload.' },
      ],
    },
    {
      id: 'api-setup',
      title: 'First-install setup API',
      docType: 'reference',
      audiences: ['administrator', 'developer', 'operator'],
      summary: 'The unauthenticated routes that diagnose and complete a first install, and the one write that runs exactly once.',
      keywords: ['setup', 'bootstrap', 'preflight', 'templates', 'first install', 'wizard', 'seed'],
      keyFacts: [
        'Only `/v1/setup/preflight` is public. The rest of this surface stays reachable while the workspace is locked but still requires a token — the bootstrap administrator signs in first, then runs the wizard.',
        'Normal authenticated routes stay locked until `POST /v1/setup/bootstrap` succeeds once.',
        '`/v1/setup/preflight` names what is blocking, and a check may carry `suggested_env` with the variables that would resolve it.',
        'Template routes render the GitOps seed without writing anything; the archive route returns the same files as a zip.',
        'Bootstrap works exactly once, and needs a token but no AAA resource check: there is nothing configured yet to check against.',
      ],
      apiRoutes: first_install_setupRoutes,
      details: [
        'Preflight and status answer different questions, and their access classes follow. Preflight asks "can this install be set up right now?" and is public, because a cold start has no working login. Status asks "has it already been set up?" and needs a token, because by then there is one to have.',
        'Bootstrap errors are deliberately specific: an apply failure names the write or configuration reason, which is almost always a permissions problem on the mounted configuration volume rather than a bad payload.',
      ],
      related: ['api-platform-probes', 'first-install-wizard', 'complete-first-install-wizard'],
      sources: [
        { repositoryPath: 'services/nopsai/setup_preflight.go', purpose: 'Preflight checks and the preflight-only server.' },
        { repositoryPath: 'services/nopsai/setup_wizard_handlers.go', purpose: 'Status, templates, and bootstrap handlers.' },
      ],
    },
    {
      id: 'api-pipelines',
      title: 'Pipelines and steps API',
      docType: 'reference',
      audiences: ['developer', 'automation-author'],
      summary: 'Reading, validating, saving, and deleting pipeline and reusable step definitions.',
      keywords: ['pipeline', 'step', 'validate', 'definition', 'yaml', 'reusable', 'save', 'delete'],
      keyFacts: [
        'Both write routes take the YAML document as the request body. There is no JSON wrapper, and sending one produces a parse error that reads like a schema error.',
        'Validation always answers 200: a rejected document is `valid: false` with issues carrying a path, a line, and a code.',
        'Pipeline and step identifiers are catch-all path segments, so a team-prefixed name with slashes is passed through as-is.',
        'A 403 rather than a 404 tells you the definition exists and access is the problem.',
        'Editing a GitOps-managed definition creates a database override, which then shows as drift until it is pushed or discarded.',
        'Deleting a pipeline keeps its runs; deleting a reusable step breaks the pipelines that include it, and nothing stops you.',
      ],
      apiRoutes: pipelines_and_stepsRoutes,
      details: [
        'Validate before saving, always. Save rejects on the first failure with a 400, while validation returns every issue at once with the line that produced it — the difference between one round trip and five.',
        'A list route returning fewer rows than expected is usually authorization rather than absence: the result is filtered per caller. If authorization itself is unavailable, the platform answers 503 rather than returning an unfiltered list.',
        'Reusable steps and pipelines are validated against different rule sets. A document that validates as a step can be rejected as a pipeline, and the reverse, so use the matching validation route.',
      ],
      related: ['api-runs', 'pipeline-anatomy', 'complete-manifest', 'gitops-and-config-repositories'],
      sources: [
        { repositoryPath: 'services/nopsai/pipeline_handlers.go', purpose: 'Pipeline and reusable step handlers.' },
        { repositoryPath: 'services/nopsai/validation_contract.go', purpose: 'The valid/errors/warnings response shape.' },
      ],
    },
    {
      id: 'api-runs',
      title: 'Runs API',
      docType: 'reference',
      audiences: ['developer', 'operator', 'automation-author'],
      summary: 'Starting runs, reading their state and logs, deciding their approvals, and handling their deliverables.',
      keywords: ['run', 'start', 'status', 'logs', 'cancel', 'rerun', 'approval', 'output', 'download', 'poll'],
      keyFacts: [
        'Starting a run answers with JSON only when the request sends `Accept: application/json`; otherwise it returns a plain-text confirmation.',
        'Starting a run returns `run_id`, while rerunning returns `runId`. The two routes do not share a response shape.',
        'Poll `/status` for a status, and `/runs/{runID}` with `If-None-Match` when you need detail — that route issues an ETag and answers 304 while nothing changed.',
        'The run list filters on `limit`, `offset`, `teamId`, and `branch`. There is no pipeline filter, and passing `teamId` changes the response into a team-by-branch grouping.',
        'Rerunning a run that is still in progress is refused with 409, and authorization is re-evaluated for whoever triggers the rerun.',
        'Rejecting an approval requires a comment; approving does not.',
        'Deliverables can be retried and cancelled per item without re-running the pipeline.',
      ],
      apiRoutes: runsRoutes,
      details: [
        'Every write here is authorized against more than the pipeline. Starting a run checks the caller against each resource the run would touch — the model, the MCP profiles, the scope — which is why a 403 can name something the caller did not think they were using.',
        'Log masking covers what the platform knows to be secret: declared secrets, names listed in `sensitive_variables`, and outputs marked `sensitive`. A value a script prints itself cannot be masked, because nothing declared it.',
        'The two bulk deletes on this page — deleting a run and clearing a branch — have no preview and no undo. Retention at scale belongs in the data cleanup routes, which preview first.',
      ],
      related: ['api-pipelines', 'pipeline-runs', 'first-run-logs-history', 'approvals'],
      sources: [
        { repositoryPath: 'services/nopsai/run_handlers.go', purpose: 'Run start, list, detail, cancel, rerun, and delete handlers.' },
        { repositoryPath: 'services/nopsai/approval_handlers.go', purpose: 'Approval listing and decision handling.' },
        { repositoryPath: 'services/nopsai/run_internal_handlers.go', purpose: 'Status and log responses.' },
      ],
    },
    {
      id: 'api-external-triggers',
      title: 'External triggers API',
      docType: 'reference',
      audiences: ['developer', 'automation-author', 'security'],
      summary: 'Defining an entry point another system may call, invoking it safely, and diagnosing a caller that believes it is being ignored.',
      keywords: ['external trigger', 'invoke', 'idempotency', 'rate limit', 'allowed_callers', 'payload schema', 'integration'],
      keyFacts: [
        'Invoking answers 202 when it queues a run, and 200 when a replayed idempotency key returns the original run.',
        'The idempotency key is scoped by trigger and caller, so two systems using the same key do not collide.',
        'A key currently in flight answers 409 rather than starting a second run.',
        '`rate_limit.per_minute` is enforced per trigger and answers 429 when exceeded.',
        '`payload_schema` is checked before a run is created, so a malformed call costs nothing.',
        'Every call, accepted or rejected, is recorded in the invocation history with its caller and reason.',
        'The JSON body and the GitOps YAML document carry the same fields, so a trigger can move between the two unchanged.',
      ],
      apiRoutes: external_triggersRoutes,
      details: [
        'Read the status codes as a state machine: 202 means this call created work, 200 means an earlier identical call did, 409 means one is happening right now, and 429 means you are asking too often. A client that treats all four as success will double-run; one that treats them all as failure will retry forever.',
        '`allowed_callers` narrows rather than grants. AAA still authorizes the caller against the trigger resource first, which is why an empty list does not open the trigger to everyone.',
        'When a caller insists it is triggering runs and nothing appears, read the invocation history before anything else — a 403 or a schema rejection is recorded there with the reason.',
      ],
      related: ['api-runs', 'external-triggers', 'first-external-trigger', 'tokens-and-service-accounts'],
      sources: [
        { repositoryPath: 'services/nopsai/external_triggers.go', purpose: 'Invocation, idempotency, and rate-limit handling.' },
        { repositoryPath: 'services/nopsai/external_triggers_gitops.go', purpose: 'The trigger document schema shared with GitOps.' },
      ],
    },
    {
      id: 'api-variables-and-secrets',
      title: 'Variables and secrets API',
      docType: 'reference',
      audiences: ['developer', 'security', 'administrator'],
      summary: 'The three stores behind runtime configuration, and which action decides who can recover a stored secret.',
      keywords: ['variable', 'secret', 'scope', 'encrypt', 'credential', 'rotate', 'read_value', 'gitops envelope'],
      keyFacts: [
        'A scope secret is not write-only. `GET /v1/secrets/{secretName}` decrypts and returns the value to a caller holding `secret.read_value` on that secret.',
        'Listing secrets and reading a value are separate actions: `secret.list_metadata` returns names, `secret.read_value` returns the value.',
        'Reading a secret value is audited, naming the caller and the secret.',
        'The credential store is different: `/v1/system/credentials` returns metadata and version history, never a value.',
        'Names and scopes come from the path and query; the request body carries only `value`.',
        'Writing over a GitOps-managed value makes the database the owner, and the next sync reports drift rather than restoring Git.',
        'A GitOps envelope from `/v1/secrets/encrypt` is bound to this install’s master key, which is what makes committing it safe and the key a restore dependency.',
      ],
      apiRoutes: variables_and_secretsRoutes,
      details: [
        'The distinction that matters for a security review is not "can secrets be read" but "who holds `secret.read_value`". Storing a credential here protects it from everyone without that action and from nobody with it, and every read leaves an audit record naming the reader.',
        'Variables are readable by design, because they are configuration. If a value should not be listed by anyone who can list variables, it is a secret, not a variable — the two stores differ in exactly that respect.',
        'A missing scope is created rather than rejected on write. A typo in a scope name produces a value nothing resolves, with no error at the time you make the mistake.',
      ],
      related: ['api-runs', 'pipeline-secrets', 'credentials', 'first-variables-and-secrets'],
      sources: [
        { repositoryPath: 'services/nopsai/secrets_variables_handlers.go', purpose: 'Variable and secret storage, encryption, and value reads.' },
        { repositoryPath: 'services/nopsai/pkg/routeauthz/routeauthz.go', purpose: 'The actions each secret route checks.' },
        { repositoryPath: 'services/nopsai/credential_handlers.go', purpose: 'Credential store responses, which carry metadata only.' },
      ],
    },
    {
      id: 'api-schedules',
      title: 'Schedules API',
      docType: 'reference',
      audiences: ['developer', 'operator', 'automation-author'],
      summary: 'Storing an intent to run a pipeline later, and testing it without waiting for the clock.',
      keywords: ['schedule', 'cron', 'timezone', 'recurring', 'one-time', 'enable', 'disable', 'run now'],
      keyFacts: [
        '`schedule_kind` decides which timing field is read: `recurring` uses `cron_expression`, one-time uses `run_at`.',
        '`timezone` is an IANA name. Without one, a cron expression means something different twice a year.',
        'A schedule carries its own scope, team path, and variables, so a scheduled run is not the same as a manual one.',
        'Authorization is checked when the schedule is written, because it fires later without a caller present.',
        'Enabling schedules the next fire from now: missed occurrences are not replayed.',
        '`POST /{id}/run` answers 202 and does not move the next scheduled fire.',
      ],
      apiRoutes: schedulesRoutes,
      details: [
        'Disable rather than delete while investigating. Disabling stops the fires and keeps the definition and its run history, which is exactly what you need to work out why the 2am run failed.',
        'The run history attached to schedule detail separates the two failure shapes that look identical from the outside: a schedule that never fired, and one that fired and produced failing runs.',
        'Because a schedule runs unattended, everything it needs must resolve without a caller: the scope must hold its variables and secrets, and the identity that created it must have been allowed to use them.',
      ],
      related: ['api-runs', 'schedules', 'entry-points'],
      sources: [
        { repositoryPath: 'services/nopsai/schedules.go', purpose: 'Schedule document, timing, and handlers.' },
        { repositoryPath: 'services/nopsai/schedules_test.go', purpose: 'Covering tests for schedule behaviour.' },
      ],
    },
    {
      id: 'api-git-integration',
      title: 'Git integration API',
      docType: 'reference',
      audiences: ['developer', 'administrator', 'security'],
      summary: 'The two ingress routes providers call, the managed sources that verify them, and the overrides that decide what a repository runs.',
      keywords: ['webhook', 'git', 'delivery', 'signature', 'source', 'override', 'github app', 'gitlab', 'ingress'],
      keyFacts: [
        'The ingress routes are the only part of the platform that has to be reachable from the internet.',
        'Public does not mean unauthenticated: every delivery is signature-verified against the source secret before it is accepted.',
        'A delivery answers 202 when it produced work and 200 when it was accepted with nothing to run — an event no trigger matches is not an error.',
        'GitHub App deliveries reach git-bot first, which verifies and forwards a normalised event to `/v1/git/events`. Other providers use a managed source.',
        'Every delivery is recorded, accepted or rejected, with its verification result.',
        'A repository with no override answers 200 with an empty document rather than 404.',
        'An override outranks the repository’s own trigger manifest.',
      ],
      apiRoutes: git_integrationRoutes,
      details: [
        'The delivery status codes separate three states an integrator otherwise conflates: 401 means the signature did not match, 403 means the repository is not in the allowlist, and 422 means the event was understood and carried nothing runnable. Only the first two are configuration mistakes.',
        'When a push produces no run, read the delivery list before anything else. It distinguishes "the provider never called" from "the provider called and we rejected it", and those have entirely different fixes.',
        'Overrides are the reason a repository can run something its own manifest does not mention. They are easy to set and easy to forget, so list them when trigger resolution surprises you.',
        'The GitHub App registration and installation routes are a browser flow driven by the System UI. They carry index rows here; the flow itself is documented in `doc/git-apps.md`.',
      ],
      related: ['api-external-triggers', 'git-webhook-sources', 'git-triggers', 'connect-git-repository'],
      sources: [
        { repositoryPath: 'services/nopsai/git_webhook_sources_model.go', purpose: 'Source document, delivery records, and verification results.' },
        { repositoryPath: 'doc/git-webhook-sources.md', purpose: 'Provider configuration, security, and payload normalisation.' },
        { repositoryPath: 'doc/git-apps.md', purpose: 'GitHub App registration, installations, and git-bot routing.' },
      ],
    },
    {
      id: 'api-access-control',
      title: 'Access control API',
      docType: 'reference',
      audiences: ['security', 'administrator', 'developer'],
      summary: 'Granting access, revoking it, and asking the platform what a caller may actually do.',
      keywords: ['access', 'grant', 'permission', 'aaa', 'authorization', 'effective', 'inherit', 'resource use'],
      keyFacts: [
        'Effective permissions are the authoritative answer; grants and roles explain how it was reached.',
        '`inherit` decides whether a grant covers one resource or everything nested under it — the setting most often wrong when access is broader than intended.',
        'Granting requires owner-level access on the resource, not the role being granted.',
        'A resource-use check answers 200 with `allowed: false` for a denial; a 403 means the caller may not even ask.',
        'An authorization team comes from the identity provider; a NopsAI team path is ownership. Granting to one does not change the other.',
        'When authorization is unavailable these routes fail closed with 503 rather than guessing.',
      ],
      apiRoutes: access_controlRoutes,
      details: [
        'Debug access in one order: read effective permissions for the caller, and only then read the grants that produced the answer. Reconstructing the answer from roles and grants by hand is how people convince themselves the platform is wrong.',
        'The batch check exists so an editor can warn while a pipeline is being written rather than when the run fails. It asks about every resource the pipeline would touch — the model, the MCP profiles, the scope — in one request.',
        'Reading who has access is itself an access decision, which is why the list route can answer 403. That is deliberate: an access list is a map of who to compromise.',
      ],
      related: ['access-control', 'api-variables-and-secrets', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'services/nopsai/access_grants.go', purpose: 'Grant documents and handlers.' },
        { repositoryPath: 'services/nopsai/resource_authz.go', purpose: 'Resource-use checks and the resource access surface.' },
        { repositoryPath: 'doc/access-control.md', purpose: 'AAA service, product roles, and route authorization.' },
      ],
    },
    {
      id: 'api-identity-administration',
      title: 'Identity administration API',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary: 'Accounts, service accounts, tokens, roles, identity providers, and the audit log that records what they all did.',
      keywords: ['user', 'service account', 'token', 'role', 'identity provider', 'oidc', 'audit', 'admin'],
      keyFacts: [
        'Every route here is administrator-gated.',
        'Creating a user answers with the whole user list rather than the created record.',
        'A token carries its account’s permissions at request time, so rebinding a role takes effect without reissuing tokens.',
        'Disabling a service account is the fastest kill switch for an integration: one call instead of one per token.',
        'Local login can only be turned off while external auth is enabled and a provider remains enabled — the platform refuses to lock itself out.',
        'Changing a live provider’s issuer re-identifies its users, because a subject is scoped by issuer.',
        'The audit log is where a secret read appears, naming who recovered it.',
      ],
      apiRoutes: identity_administrationRoutes,
      details: [
        'Users and service accounts are the same kind of thing to the authorization layer: a subject with roles and grants. The difference is operational — a person leaves, a system does not — which is why an integration should hold a service account token rather than a personal one.',
        'Roles and grants answer different halves of one question. A role permits an action on a kind of object; a grant decides which concrete resources it reaches. Neither alone tells you whether a caller can do something, which is what effective permissions are for.',
        'Prefer disabling to deleting. A disabled account stops authenticating while its audit trail still resolves to a real subject; a deleted one leaves records naming an account nobody can look up.',
      ],
      related: ['api-access-control', 'api-authentication', 'tokens-and-service-accounts', 'authentication-and-sso'],
      sources: [
        { repositoryPath: 'services/nopsai/admin_user_handlers.go', purpose: 'User and service account handlers.' },
        { repositoryPath: 'services/nopsai/admin_role_handlers.go', purpose: 'Role definitions and bindings.' },
        { repositoryPath: 'services/nopsai/auth_oidc_handlers.go', purpose: 'Identity provider configuration.' },
      ],
    },
    {
      id: 'api-gitops',
      title: 'GitOps and config sync API',
      docType: 'reference',
      audiences: ['administrator', 'developer', 'operator'],
      summary: 'Connecting configuration repositories, syncing from them, reviewing drift, and pushing desired state back.',
      keywords: ['gitops', 'config repository', 'sync', 'drift', 'push', 'validate', 'team repository'],
      keyFacts: [
        'Two scopes, one shape: the global repository holds system settings, a team repository holds that team’s pipelines, steps, schedules, scopes, and triggers. Both expose read, sync, drift, write, and validate.',
        'A sync is asynchronous and singular. Starting one while another runs answers 409 — that is the platform refusing to run two, not a bad request.',
        'Cancelling mid-sync leaves a partial import rather than rolling back.',
        'Disconnecting a repository does not remove configuration; it removes the source of truth, and the documents become database-owned.',
        'Drift carries both `git_content` and `desired_content` per file, which is what the side-by-side review renders.',
        'The write routes are the only ones here that change something outside the platform.',
      ],
      apiRoutes: gitops_and_config_syncRoutes,
      details: [
        'Drift is not a fault. It is what happens when someone edits a GitOps-managed document through the UI or API: the database becomes the owner until the change is pushed back or discarded. The question a reviewer answers is which of the two contents should win.',
        'Validate a whole file set rather than a document at a time. That is the call a CI job should make on a configuration repository pull request, and it reports every issue with the file it came from.',
        'When several repositories are connected, the per-repository status routes are how you find which one failed. The platform-wide status tells you a sync failed, not where.',
      ],
      related: ['gitops-and-config-repositories', 'api-teams', 'api-pipelines'],
      sources: [
        { repositoryPath: 'services/nopsai/config_sync.go', purpose: 'Sync orchestration and status.' },
        { repositoryPath: 'services/nopsai/config_repository_drift.go', purpose: 'Drift comparison and push behaviour.' },
        { repositoryPath: 'services/nopsai/internal/configsync/diff.go', purpose: 'Per-file drift item shape.' },
      ],
    },
    {
      id: 'api-teams',
      title: 'Teams API',
      docType: 'reference',
      audiences: ['administrator', 'developer'],
      summary: 'The ownership tree, the applications under it, and the team-owned models, agent roles, and MCP profiles.',
      keywords: ['team', 'application', 'ownership', 'defaults', 'notifications', 'models', 'agent roles', 'mcp'],
      keyFacts: [
        'The team list is a tree with `children` populated, so one call gives the whole hierarchy.',
        'Moving a team changes its path, and the path is what scopes, grants, and notifications refer to.',
        'Moving an application is expressed by the team in the URL, not a field in the body.',
        'An application is a team whose kind is `application`: it owns a repository rather than other teams.',
        'Team defaults decide what a pipeline resolves to when it names no model or agent role; they never override one that does.',
        '`default` is a literal path segment on the models and agent-roles routes, so a profile cannot be named `default`.',
        'The collection PUT on models replaces the set — anything omitted is removed. The single-profile PUT does not.',
        'Teams choose which events they hear about; the platform decides how they are delivered.',
      ],
      apiRoutes: teamsRoutes,
      details: [
        'Everything in this area exists so a resource can answer "who owns this?". A team path is not a label — it is the key that access grants, scope resolution, notification routing, and GitOps ownership all join on. That is why moving a team is a bigger operation than renaming one.',
        'The AI resources hang off teams rather than the platform so two teams can hold different models and tool sets without one being able to use the other’s. A profile listed for a team may be inherited rather than defined there, which is why the list can show more than the team owns.',
        'The `mcp/profiles` paths are compatibility aliases for the hyphenated `mcp-profiles` routes and reach the same handlers. Prefer the hyphenated form in new integrations.',
      ],
      related: ['api-access-control', 'api-gitops', 'teams-and-ownership', 'mcp'],
      sources: [
        { repositoryPath: 'services/nopsai/team_handlers.go', purpose: 'Team, application, defaults, and notification handlers.' },
        { repositoryPath: 'services/nopsai/team_profile_handlers.go', purpose: 'Team-owned model, agent role, and MCP profile handlers.' },
        { repositoryPath: 'pkg/models/types.go', purpose: 'Team and application record shape.' },
      ],
    },
    {
      id: 'api-ai-configuration',
      title: 'AI configuration API',
      docType: 'reference',
      audiences: ['administrator', 'security', 'automation-author'],
      summary: 'The three registries a pipeline draws on: model profiles, agent roles, and MCP servers and profiles.',
      keywords: ['model', 'llm', 'agent role', 'mcp', 'profile', 'server', 'test', 'discover', 'default'],
      keyFacts: [
        'A pipeline names these resources; it cannot define them. That is the boundary that makes AI use reviewable.',
        'Model resolution runs task, step, pipeline, team, then platform default.',
        'Deleting a profile still in use answers 409 rather than breaking the pipelines that name it.',
        'The test routes make a real provider or server call — the difference between "configured" and "working".',
        'Tool discovery is what makes a profile reviewable: you grant named tools rather than whatever a server exposes.',
        'The profile is the only place tool access narrows; pipeline, step, and task profiles are additive at run time.',
        '`allowed_scopes` bounds where a profile may be used, which keeps a production tool set out of development runs.',
      ],
      apiRoutes: ai_configurationRoutes,
      details: [
        'Read the three registries as three separate questions. A model profile answers "which provider and model may this run use", an agent role answers "how should it behave", and an MCP profile answers "which tools may it call". Conflating them is the usual reason a change has no effect: raising a governance level does not add tools, and swapping an agent role does not change the model.',
        'The 409 on delete is deliberate. A model or profile that a pipeline still names cannot be removed, so the failure happens at configuration time with a clear message rather than at the next run with an authorization error.',
        'Test after every credential rotation. A rotated key that was never tested fails at the least convenient moment, and the test route is one call.',
      ],
      related: ['api-teams', 'models', 'agent-roles', 'mcp', 'ai-context-and-tools'],
      sources: [
        { repositoryPath: 'services/nopsai/llm_profiles.go', purpose: 'Model profile storage, defaults, and provider tests.' },
        { repositoryPath: 'services/nopsai/agent_profiles.go', purpose: 'Agent role storage, usage, and validation.' },
        { repositoryPath: 'services/nopsai/mcp_registry.go', purpose: 'MCP server registration, discovery, and profiles.' },
      ],
    },
    {
      id: 'api-assistant',
      title: 'Assistant and AI surfaces API',
      docType: 'reference',
      audiences: ['developer', 'security', 'operator'],
      summary: 'Conversations, pipeline evaluation, and the hosted MCP endpoint — all running as the calling subject.',
      keywords: ['assistant', 'conversation', 'mcp', 'jsonrpc', 'evaluation', 'analysis', 'tools'],
      keyFacts: [
        'These surfaces run as the caller. The assistant sees exactly what that caller could fetch through the API, which is why two people get different answers to the same question.',
        'Feature flags decide which capability families exist; AAA still decides which resources within them are reachable.',
        'Mutating MCP tools stay hidden unless assistant action execution is enabled, and confirmed mutations still pass every existing check.',
        'A conversation belonging to another subject answers 404, not 403 — the API does not confirm it exists.',
        'An empty body on `/v1/mcp` is treated as `tools/list`, which makes the endpoint checkable by hand.',
        'JSON-RPC errors come back as a 200 with an `error` member, not as an HTTP error.',
        'An evaluation is advice; enforcement lives in governance levels, guardrails, and approvals.',
      ],
      apiRoutes: assistant_and_ai_surfacesRoutes,
      details: [
        'The security property that matters here is that none of these surfaces is a privileged reader. They are wrappers over the same authenticated API, so an assistant answer cannot reveal something the person asking could not have fetched themselves.',
        'Conversations are per subject with no cross-subject read, which is why a missing conversation and someone else’s conversation are indistinguishable from the outside.',
        'Every model-backed route here records AI usage, so assistant and evaluation spend show up in the same accounting as pipeline runs.',
      ],
      related: ['api-ai-configuration', 'assistant', 'hosted-mcp', 'analysis-reviewers'],
      sources: [
        { repositoryPath: 'services/nopsai/assistant_routes.go', purpose: 'Assistant configuration, conversations, and messages.' },
        { repositoryPath: 'services/nopsai/hosted_mcp_api_bridge.go', purpose: 'Hosted MCP tool bridge and its authorization boundary.' },
        { repositoryPath: 'services/nopsai/analysis_evaluation_handlers.go', purpose: 'Analysis evaluation handler and feature gate.' },
      ],
    },
    {
      id: 'api-knowledge-context',
      title: 'Knowledge Context API',
      docType: 'reference',
      audiences: ['administrator', 'automation-author', 'security'],
      summary: 'Governed documents merged into LLM context, and the provider connections that import them.',
      keywords: ['knowledge', 'guardrail', 'policy', 'connection', 'confluence', 'import', 'resolve', 'search'],
      keyFacts: [
        'Kind is not a label: `guardrail` and `policy` documents validate direct scripts before execution, while the other kinds only inform the prompt.',
        'Storing a blocking guardrail is an enforcement change, not a documentation change.',
        'A connection imports documents; it does not give a run live access to the provider.',
        'Deleting a document a pipeline requires answers 409 rather than breaking the run.',
        'Disabling a connection stops imports while leaving already-imported documents working.',
        'Resolve a page before importing it: the preview shows exactly which document a URL becomes.',
        'The `knowledge-connections` paths are compatibility aliases for `knowledge-context-connections`.',
      ],
      apiRoutes: knowledge_contextRoutes,
      details: [
        'The two halves answer different questions. A knowledge document is content the platform governs and merges into an LLM task context. A connection is a link to somewhere that content lives, used at import time only — so revoking a connection never removes what a run already depends on.',
        'Guardrail and policy documents are the reason this area belongs in a security review. They participate in script validation, which means adding one narrows what pipelines under it may execute, and removing one widens it.',
        'Import in three steps rather than one: search for the page, resolve it to see the document it becomes, then import. Each step makes exactly one provider call and stores nothing until the last.',
      ],
      related: ['knowledge-context', 'ai-context-and-tools', 'api-ai-configuration', 'credentials'],
      sources: [
        { repositoryPath: 'services/nopsai/knowledge_context.go', purpose: 'Document storage, kinds, and lifecycle.' },
        { repositoryPath: 'services/nopsai/knowledge_connections.go', purpose: 'Provider connections, test, resolve, and search.' },
        { repositoryPath: 'doc/knowledge-context.md', purpose: 'Document kinds, merging, GitOps layout, and access checks.' },
      ],
    },
    {
      id: 'api-monitoring',
      title: 'Monitoring API',
      docType: 'reference',
      audiences: ['operator', 'administrator', 'developer'],
      summary: 'Analytics over runs, performance, AI usage and security, plus recommendations, alert rules, and saved views.',
      keywords: ['monitoring', 'analytics', 'metrics', 'performance', 'p95', 'ai usage', 'alert', 'recommendation', 'saved view'],
      keyFacts: [
        'Every analytics route shares one filter model: a `from`/`to` window defaulting to the last 30 days, plus team, pipeline, branch, and status filters.',
        '`to` must be after `from`, and an unparseable window is a 400 naming which half failed.',
        'Results are filtered per caller, so a summary is what this caller may see rather than a platform total.',
        '`compare=true` adds the preceding window of equal length, which is what turns a number into a signal.',
        'AI usage covers assistant and evaluation spend alongside pipeline runs — it is the whole AI bill.',
        'Acknowledged and resolved are different recommendation states: one says "we know", the other says "it is fixed".',
        'Evaluating an alert rule by hand does not fire notifications, which makes it safe to test a threshold.',
        'A saved view stores filters rather than results, so it always reflects current data.',
      ],
      apiRoutes: monitoringRoutes,
      details: [
        'Read p95 rather than the average when chasing a slow pipeline: a three-minute average with a twelve-minute p95 is the one people complain about, and the average hides it. The pipeline, step, and task performance routes are the same question at three depths, which is how a slow pipeline is narrowed to a single task.',
        'Efficiency separates waiting from working. Queue time and approval waits are not execution time, so "the pipeline is slow" can be answered honestly rather than by optimising steps that were never the problem.',
        'The security view aggregates; the audit log holds the individual records. Reach for the view to see a pattern and the log to see who did what — including who read which secret.',
        'Test an alert rule with the evaluate route before enabling it. A threshold that matches everything looks exactly like one that matches nothing until it runs, and the difference is discovered at 3am.',
      ],
      related: ['monitoring', 'api-runs', 'api-ai-configuration', 'release-integrity'],
      sources: [
        { repositoryPath: 'services/nopsai/monitoring_analytics_handlers.go', purpose: 'Window and filter parsing, analytics responses.' },
        { repositoryPath: 'services/nopsai/monitoring_handlers.go', purpose: 'Dispatcher status, recommendations, alert rules, and saved views.' },
      ],
    },
    {
      id: 'api-dashboards',
      title: 'Dashboards API',
      docType: 'reference',
      audiences: ['operator', 'automation-author', 'administrator'],
      summary: 'Dashboards, sections, source bindings, publication history, refreshes, and refresh schedules.',
      keywords: ['dashboard', 'section', 'source', 'publication', 'refresh', 'schedule', 'strict', 'entry key'],
      keyFacts: [
        'A refresh is not a query. It re-runs the bound source pipelines, so it is asynchronous, consumes runner capacity, and answers 409 while one is already in flight.',
        '`required_for_refresh` decides whether a strict refresh fails on a source failure or carries on.',
        'Retrying only the failed sources is much cheaper than a fresh refresh, and successful sources are not re-run.',
        '`section_key` is what a pipeline `dashboard.section` must match — a typo publishes nowhere without erroring.',
        'Deleting a section deletes the entries published into it, and pipelines publishing there then silently stop appearing.',
        'Removing a publication is a display fix, not a data fix: the next publication brings it back.',
        'A PUT on a dashboard removes any section it omits; PATCH is the safe edit.',
      ],
      apiRoutes: dashboardsRoutes,
      details: [
        'The mental model is publish-then-read, not query. A pipeline final output of `type: dashboard` publishes an entry; the dashboard stores it; the view composes what has been stored. Nothing here reaches back into run data on demand, which is why an empty section means "nothing published yet" rather than "the query failed".',
        'That is also why refresh cadence is a capacity decision. A daily refresh of a five-source dashboard is five pipeline runs a day, and a strict schedule turns one flaky source into a daily failure. Both settings exist to be tuned rather than defaulted.',
        'When a tile is missing, read the publication history first: it distinguishes never published, published into the wrong section key, and published and later removed. Those have three different fixes.',
      ],
      related: ['dashboards', 'api-runs', 'final-deliverables', 'api-schedules'],
      sources: [
        { repositoryPath: 'services/nopsai/dashboards.go', purpose: 'Dashboard, section, source, publication, and refresh handlers.' },
        { repositoryPath: 'doc/dashboards.md', purpose: 'Dashboard model, publication, refresh orchestration, and GitOps ownership.' },
      ],
    },
    {
      id: 'api-system-operations',
      title: 'System operations API',
      docType: 'reference',
      audiences: ['administrator', 'operator', 'security'],
      summary: 'Runtime configuration, the runner fleet and its install generation, platform logs, mail delivery, and the data lifecycle.',
      keywords: ['system', 'config', 'dispatcher', 'runner', 'bootstrap', 'logs', 'mail', 'backup', 'cleanup', 'retention'],
      keyFacts: [
        'Runner install generation is separately authorized because it hands out service credentials, and the one-time token expires in 10 minutes and is consumed by the first download.',
        'Ejecting a runner blocklists its id; an ordinary disconnect keeps the registration so it can reconnect.',
        'Disabling dispatch is the drain switch: new work stops, in-flight runs finish.',
        'Log sources are allow-listed, and lines are redacted before they leave the platform.',
        'Live log streaming is concurrency-capped, so a forgotten stream answers 429 for the next one.',
        'The platform takes and stores backups. It does not upload or restore them.',
        'Cleanup is permanent. Preview first — the counts are easy to misread by an order of magnitude.',
      ],
      apiRoutes: system_operationsRoutes,
      details: [
        'The runner routes come in two shapes for a reason. The one-time bootstrap command hands the host a short-lived token and nothing else, while the Compose fragment and Kubernetes manifest embed long-lived material directly — which makes them convenient for GitOps and dangerous to commit unsealed. Prefer the bootstrap command unless the output is going somewhere encrypted.',
        'Backups and cleanup pull in opposite directions and are easy to get wrong together. A backup that never leaves the platform volume does not survive losing the platform, and a cleanup schedule quietly deletes the history an incident may need. Verify a downloaded backup against its checksum, and disable the cleanup schedule before it removes evidence you are still reading.',
        'Runtime configuration is what the platform resolved rather than what a file says: environment, config file, and runtime overrides are already merged. Changing the dispatcher address affects newly generated installs, not runners that are already registered.',
      ],
      related: ['api-monitoring', 'runners-and-dispatcher', 'system-logs', 'data-management'],
      sources: [
        { repositoryPath: 'services/nopsai/system_handlers.go', purpose: 'Configuration, dispatcher, and notification handlers.' },
        { repositoryPath: 'services/nopsai/internal/runnerinstall/docker.go', purpose: 'Runner install generation and one-time token behaviour.' },
        { repositoryPath: 'services/nopsai/data_management.go', purpose: 'Backups, cleanup jobs, and cleanup schedules.' },
      ],
    },
    {
      id: 'api-internal-routes',
      title: 'Internal service routes',
      docType: 'reference',
      audiences: ['developer', 'operator', 'security'],
      summary: 'Component-to-component traffic: what calls each route, why it exists, and why none of it is a public surface.',
      keywords: ['internal', 'service token', 'agent', 'git-bot', 'runtime config', 'ingest', 'finalize', 'checkpoint'],
      keyFacts: [
        'These routes are documented at contract depth: caller, purpose, and boundary, with no call samples.',
        'Calling them by hand corrupts run state rather than integrating with the platform.',
        '`logs/ingest`, the task status route, and `finalize` sit under `/v1/runs/` rather than `/v1/internal/`, so they look public in a route list while being agent-only.',
        'The runtime-config watch is why a `PUT /v1/system/config` takes effect without restarting services.',
        'The approval pause route is what makes a checkpoint durable: the run becomes a record rather than a held process.',
        'AI usage records reported here are the source of the numbers in the monitoring AI usage view.',
      ],
      apiRoutes: internal_service_routesRoutes,
      details: [
        'Every route here has a public counterpart to reach for instead. Read logs with `GET /v1/runs/{runID}/logs`, not the ingest route. Sync configuration with `POST /v1/system/config/sync`, not the internal trigger. Inspect the fleet with `GET /v1/system/dispatcher`, not the routing table. The internal form exists for a component that already holds a service token and a specific job.',
        'The three routes under `/v1/runs/` are the ones worth knowing about, because a route list makes them look like part of the public API. They advance the run graph: ingesting logs, transitioning a task, and finalising a run. Calling any of them by hand ends up with a run whose recorded state does not match what happened.',
        'This page exists so the surface is complete rather than to invite use. If an integration seems to need one of these routes, the public equivalent is almost always the right answer.',
      ],
      related: ['api-runs', 'api-system-operations', 'control-execution-plane'],
      sources: [
        { repositoryPath: 'services/nopsai/run_internal_handlers.go', purpose: 'Agent log ingest and run status reporting.' },
        { repositoryPath: 'services/nopsai/runtime_config_api.go', purpose: 'Runtime configuration pull and watch.' },
        { repositoryPath: 'services/nopsai/aaa_helpers.go', purpose: 'Which internal paths are authenticated rather than authorized.' },
      ],
    },
    {
      id: 'api-index',
      title: 'All REST endpoints',
      docType: 'reference',
      audiences: ['developer', 'operator', 'administrator'],
      summary: 'Every documented route with method, access class, and purpose, grouped by area.',
      keywords: ['index', 'api', 'routes', 'endpoints', 'rest', 'all', 'http'],
      keyFacts: [
        '**Public** routes need no token. **Authenticated** routes need any valid token. **Authorized** routes additionally pass an AAA check on the target resource.',
        '**Administrator** routes require the platform administrator role.',
        '**Service token** routes are internal component traffic and are not part of the public surface.',
        'Filter by area or search by path fragment to find the route you need.',
      ],
      details: [
        'Access class describes the gate before resource-level checks. An "authorized" route can still return an empty list if the caller has no matching resources.',
      ],
      related: ['api', 'access-control', 'tokens-and-service-accounts'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Route registration for every area.' },
        { repositoryPath: 'doc/api.md', purpose: 'Request and response shapes.' },
      ],
    },
  ],
};
