import { pipelineFields, pipelineStructuralLimits } from '../fields/pipeline.js';
import { approvalFields, stepCommonFields, stepModeFields, taskFields } from '../fields/step-task.js';
import { dashboardOutputFields, finalOutputFields } from '../fields/output.js';
import type { WikiSection } from '../types.js';

export const automationSection: WikiSection = {
  id: 'automation',
  title: 'Authoring pipelines',
  group: 'build',
  owner: 'Automation platform',
  description: 'Every directive you can write in pipeline, step, task, approval, and output YAML, with the rules the validator enforces.',
  articles: [
    {
      id: 'pipeline-schema',
      title: 'Pipeline YAML schema',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary: 'Top-level pipeline directives, their defaults, and the structural limits validation enforces.',
      keywords: ['schema', 'yaml', 'directives', 'pipeline', 'fields', 'reference'],
      keyFacts: [
        '`name` and `steps` are the only unconditionally required top-level fields.',
        '`version` defaults to `latest`; validation writes the value back when it is omitted.',
        '`container_image` is required only if some executable step has no `image` of its own. Approval steps never need one.',
        '`governance_level` defaults to `strict` when unset — the most restrictive enforcement, not the most permissive.',
        '`working_directory` defaults to `/workspace` and cannot escape it, be the container root, or contain `:` or NUL.',
        '`llm_enabled: false` turns the pipeline script-only and makes goals, conditions, and final outputs validation errors.',
      ],
      details: [
        'Validation runs before a run is queued and reports the first problem it finds with the exact step, task, or directive at fault. It is worth calling `POST /v1/pipelines/validate` in your own tooling.',
        'Structural limits exist to keep the dependency graph tractable. They are checked after schema validation and before the graph is built.',
        'The dependency graph is cycle-checked. A cycle error prints the full path so you can see which edge closed the loop.',
      ],
      fields: [...pipelineFields, ...pipelineStructuralLimits],
      examples: [
        {
          title: 'Minimal valid pipeline',
          language: 'yaml',
          code: ['name: minimal', 'container_image: alpine:3.20', 'steps:', '  - name: run', '    script: echo ok'].join('\n'),
          expectedOutput: 'Accepted. `version` is written back as `latest`.',
          validationCommand: 'POST /v1/pipelines/validate',
        },
        {
          title: 'Script-only pipeline with an explicit governance level',
          language: 'yaml',
          code: [
            'name: nightly-backup',
            'container_image: postgres:15-alpine',
            'llm_enabled: false',
            'timeout: 1h',
            'variables:',
            '  - PGHOST',
            '  - platform/shared:BACKUP_BUCKET',
            'steps:',
            '  - name: dump',
            '    secrets: [PGPASSWORD]',
            '    script: pg_dump -h "$PGHOST" -Fc > /workspace/db.dump',
            '  - name: upload',
            '    depends_on: [dump]',
            '    script: aws s3 cp /workspace/db.dump "s3://$BACKUP_BUCKET/"',
          ].join('\n'),
          expectedOutput: 'Accepted. `governance_level` is irrelevant here because no LLM work is defined.',
        },
      ],
      limits: [
        'A pipeline with `llm_enabled: false` cannot define `output.items`, step conditions, goals, or scripts carrying blocking knowledge context.',
      ],
      related: ['step-task-directives', 'runtime-outputs', 'final-deliverables', 'directive-index'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Every validation rule documented on this page.' },
        { repositoryPath: 'pkg/models/model.go', purpose: 'Struct definitions and YAML tags for the pipeline schema.' },
        { repositoryPath: 'pkg/models/pipeline_paths.go', purpose: 'working_directory normalization and rejection rules.' },
      ],
    },
    {
      id: 'step-task-directives',
      title: 'Step and task directives',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary: 'The five step execution modes, the directives common to all of them, and what is valid on a task.',
      keywords: ['step', 'task', 'goal', 'script', 'include', 'depends_on', 'mode'],
      keyFacts: [
        'Every step defines exactly one execution mode: `include`, `tasks`, `goal`, `script`, or `approval`. Combining two is a validation error.',
        'A task defines exactly one of `goal` or `script` — neither and both are both errors.',
        '`agent_profile` is valid on a pipeline and a step but never on a task. Parsing rejects it with an explicit message.',
        '`mcp_profiles` is invalid on include steps, script steps, and script tasks.',
        'Task dependencies must be a task in the same step or a qualified `step.task`; a bare step name is not valid.',
        'Steps with `tasks` declare outputs on the tasks, never at step level.',
      ],
      details: [
        'Step-level settings cascade down to tasks unless the task overrides them. The resolution order for LLM Profile is task, then step, then pipeline, then the configured default; Agent Profile resolves step, then pipeline, then default; MCP profiles are additive across all three levels and deduplicated.',
        '`ignore_failure` on a step also applies to every task inside it. Ignored failures stay auditable as `failure (ignored)` and turn an otherwise successful run into status `warning`.',
        'Volume mounts use `volume:/mount/path`. Existing storage is reused and missing storage is created. Mounting the reserved runtime output path `/nopsai/outputs` is rejected.',
      ],
      fields: [...stepModeFields, ...stepCommonFields, ...taskFields],
      examples: [
        {
          title: 'Multi-task step with a task-level dependency',
          language: 'yaml',
          code: [
            'steps:',
            '  - name: verify',
            '    image: golang:1.24',
            '    tasks:',
            '      - name: vet',
            '        script: go vet ./...',
            '      - name: test',
            '        script: go test ./...',
            '      - name: report',
            '        depends_on: [vet, test]',
            '        goal: Summarize any vet or test failures for the pull request comment.',
          ].join('\n'),
          expectedOutput: '`vet` and `test` run concurrently; `report` waits for both.',
        },
        {
          title: 'Cross-step qualified dependency',
          language: 'yaml',
          code: [
            'steps:',
            '  - name: prepare',
            '    tasks:',
            '      - name: generate-tag',
            '        script: echo "v1.4.2" > /nopsai/outputs/IMAGE_TAG',
            '        outputs:',
            '          - name: IMAGE_TAG',
            '  - name: build',
            '    depends_on: [prepare.generate-tag]',
            '    variables:',
            '      TAG: $steps.prepare.generate-tag.outputs.IMAGE_TAG',
            '    script: docker build -t "app:$TAG" .',
          ].join('\n'),
          expectedOutput: '`build` waits for the specific producing task, not the whole `prepare` step.',
        },
      ],
      limits: [
        'Reusable `step:` include outputs are owned by the reusable step definition after expansion, not by the including pipeline.',
      ],
      related: ['pipeline-schema', 'runtime-outputs', 'reuse-and-children', 'approvals'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Mode exclusivity, dependency resolution, and profile rules.' },
        { repositoryPath: 'pkg/models/model.go', purpose: 'Step and task struct definitions, including the agent_profile rejection.' },
      ],
    },
    {
      id: 'runtime-outputs',
      title: 'Runtime outputs and dependencies',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary: 'How one task publishes a value and another consumes it, and the rules that make a reference valid.',
      keywords: ['outputs', 'runtime', 'variables', 'depends_on', 'graph', 'reference'],
      keyFacts: [
        'A producer writes files under the reserved mount `/nopsai/outputs` and declares them with `outputs`.',
        'Output names must match `^[A-Za-z_][A-Za-z0-9_]*$` and be unique within one producer.',
        'A consumer reads a value through `$steps.<step>.<task>.outputs.<name>` in a `variables` entry.',
        'The reference must be the entire variable value — it cannot be embedded in a larger string.',
        'A dependency path to the producer is required, but a direct `depends_on` edge is not: a transitive upstream path is enough.',
        'A single-task step publishes under its own name, so the reference reads `$steps.<step>.<step>.outputs.<name>`.',
      ],
      details: [
        'Validation distinguishes three failure modes with different messages: referencing a producer task that does not exist, referencing an output the producer never declared, and consuming an output without a valid dependency path. Read the message before changing the graph.',
        'Mark a value `sensitive: true` when it should be masked in run logs. Non-sensitive output JSON deliberately stays visible so release evidence such as versions, image references, and change IDs remains reviewable.',
        '`RUNTIME_OUTPUT_MAX_BYTES` caps the size of a single output value, defaulting to 65536.',
        'A step cannot consume its own outputs, and a task cannot consume its own.',
      ],
      examples: [
        {
          title: 'Sensitive output masked in logs',
          language: 'yaml',
          code: [
            '  - name: mint-token',
            '    script: ./mint.sh > /nopsai/outputs/DEPLOY_TOKEN',
            '    outputs:',
            '      - name: DEPLOY_TOKEN',
            '        sensitive: true',
          ].join('\n'),
          expectedOutput: 'The value is available to downstream steps but masked wherever logs are rendered.',
        },
        {
          title: 'Invalid: reference embedded in a larger expression',
          language: 'yaml',
          code: ['    variables:', '      URL: "https://registry/$steps.prepare.tag.outputs.TAG"'].join('\n'),
          expectedOutput:
            'Rejected: "uses a runtime output in an unsupported expression; use the full value $steps.<step>.<task>.outputs.<name>".',
        },
      ],
      limits: ['A runtime output reference is never a valid `depends_on` value.'],
      related: ['step-task-directives', 'variables-secrets-scopes', 'pipeline-runs'],
      sources: [
        { repositoryPath: 'pkg/models/runtime_outputs.go', purpose: 'Reference parsing and the reserved mount path.' },
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Output declaration and dependency-path validation.' },
      ],
    },
    {
      id: 'approvals',
      title: 'Approval checkpoints',
      docType: 'reference',
      audiences: ['automation-author', 'operator', 'security'],
      summary: 'Durable human gates that pause a run, release capacity, and record who decided what.',
      keywords: ['approval', 'gate', 'checkpoint', 'four eyes', 'segregation of duties'],
      keyFacts: [
        'A paused approval releases runner capacity instead of holding it, so a waiting run costs nothing.',
        'At least one approval team is required; team paths must be relative and cannot repeat.',
        '`allow_self_approval` defaults to false, keeping requester and approver separate.',
        'Approving may include a comment; rejecting requires one.',
        'An expired `timeout` marks the run `timed_out`.',
        'Approval failures always fail closed — `ignore_failure` does not apply.',
      ],
      details: [
        'The checkpoint is durable: it survives an API restart, a runner restart, and a dispatcher reconnect, because the pause is recorded in PostgreSQL rather than held in the agent.',
        'Approval steps cannot declare task outputs and cannot combine with any other execution mode.',
      ],
      fields: approvalFields,
      examples: [
        {
          title: 'Two-team production gate',
          language: 'yaml',
          code: [
            '  - name: production-gate',
            '    depends_on: [stage-verify]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '        - security',
            '      allow_self_approval: false',
            '      timeout: 12h',
          ].join('\n'),
          expectedOutput: 'Members of either team may decide. After 12 hours without a decision the run is marked `timed_out`.',
        },
      ],
      related: ['add-approval-checkpoint', 'access-control', 'notifications'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Approval definition validation.' },
        { repositoryPath: 'services/nopsai/approval_handlers.go', purpose: 'Decision handling and timeout behavior.' },
      ],
    },
    {
      id: 'reuse-and-children',
      title: 'Reusable steps and child pipelines',
      docType: 'concept',
      audiences: ['automation-author', 'developer'],
      summary: 'Share step definitions across pipelines and compose pipelines out of other pipelines.',
      keywords: ['include', 'reusable', 'child pipeline', 'composition', 'sync'],
      keyFacts: [
        '`include: step:<identifier>` expands a stored reusable step definition in place.',
        '`include: pipeline:<identifier>` launches a child pipeline as its own run.',
        'A `pipeline:` include must set `sync: true` to declare parent-visible `outputs`.',
        'Include steps cannot define `mcp_profiles` or combine with any other execution mode.',
        'A reusable step is validated the same way as a one-step pipeline, so its directives follow the normal step rules.',
      ],
      details: [
        'Asynchronous child pipelines start and are tracked independently; the parent does not wait and cannot import their outputs. Use `sync: true` when the parent needs a result.',
        'After expansion, a reusable `step:` include owns its own output contract. The including pipeline does not redeclare it.',
        'Child pipelines are separate runs with their own authorization, logs, and outputs, which keeps ownership and audit boundaries intact across composition.',
      ],
      examples: [
        {
          title: 'Synchronous child pipeline with imported outputs',
          language: 'yaml',
          code: [
            '  - name: deploy-service',
            '    include: pipeline:platform/deploy-service',
            '    sync: true',
            '    outputs:',
            '      - name: DEPLOYED_VERSION',
            '  - name: announce',
            '    depends_on: [deploy-service]',
            '    variables:',
            '      VERSION: $steps.deploy-service.deploy-service.outputs.DEPLOYED_VERSION',
            '    script: ./announce.sh "$VERSION"',
          ].join('\n'),
          expectedOutput: 'The parent waits for the child run and imports its declared output.',
        },
      ],
      limits: ['An include step cannot declare outputs for a `step:` include, only for a synchronous `pipeline:` include.'],
      related: ['step-task-directives', 'runtime-outputs', 'pipeline-runs'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Include mode rules and output import validation.' },
        { repositoryPath: 'doc/runtime-flows.md', purpose: 'Child pipeline execution flow.' },
      ],
    },
    {
      id: 'variables-secrets-scopes',
      title: 'Variables, secrets, and scopes',
      docType: 'concept',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'How a run resolves configuration values and credentials, and what a scope actually controls.',
      keywords: ['variables', 'secrets', 'scope', 'environment', 'configuration'],
      keyFacts: [
        'A scope is the namespace that resolves runtime variables and secrets for a run.',
        'A bare name resolves in the run scope; `scope/path:NAME` resolves an explicit scope and injects the value as `NAME`.',
        'Names must match `^[A-Za-z0-9_.-]+$`, and the same runtime name may not resolve from two different scopes in one place.',
        'Secret values are write-only: the API returns metadata but never the value after submission.',
        'Declared secrets and outputs marked `sensitive` are masked in run logs.',
        'Step `variables` apply to every task in the step; task `variables` are applied afterwards and win.',
      ],
      details: [
        'Pipeline `variables` are a declaration of what the run requires. If a declared variable cannot be resolved in the run scope, the run fails before execution rather than starting with a missing value.',
        'Scope encryption produces a GitOps-safe envelope through `POST /v1/secrets/encrypt`, so a secret can live in a configuration repository without being readable there.',
        'Scope is orthogonal to team path. Scope decides which values resolve; team path decides who owns the resource and who is notified.',
      ],
      examples: [
        {
          title: 'Cross-scope variable injection',
          language: 'yaml',
          code: [
            'variables:',
            '  - REGISTRY_HOST',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: publish',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    script: ./publish.sh',
          ].join('\n'),
          expectedOutput:
            '`REGISTRY_HOST` and `REGISTRY_TOKEN` resolve in the run scope; the two `platform/shared` values resolve from that scope and are injected under their bare names.',
        },
      ],
      limits: ['Secret values cannot be read back through the API or UI after they are stored.'],
      related: ['credentials', 'gitops-and-config-repositories', 'runtime-outputs'],
      sources: [
        { repositoryPath: 'pkg/models/runtime_refs.go', purpose: 'Scoped reference parsing and name validation.' },
        { repositoryPath: 'doc/credential-management.md', purpose: 'Encrypted registry, GitOps envelopes, rotation, and AAA.' },
      ],
    },
    {
      id: 'final-deliverables',
      title: 'Final deliverables',
      docType: 'reference',
      audiences: ['automation-author', 'operator'],
      summary: 'Generate Markdown, JSON, HTML, PDF, Excel, or dashboard artifacts from run evidence after execution.',
      keywords: ['output', 'deliverable', 'report', 'pdf', 'excel', 'dashboard', 'artifact'],
      keyFacts: [
        'Supported types: `markdown`, `pdf`, `excel`, `json`, `html`, `dashboard`.',
        '`when` accepts `always`, `success`, or `failure`; omitted or empty means `always`.',
        '`name`, `type`, and `prompt` are all required on every item, and names must be unique.',
        'Dashboard directives are only valid when `type: dashboard`; setting any of them on another type is a validation error.',
        'LLM Profile resolution runs item, then `output.llm_profile`, then pipeline, then the configured default.',
        '`output.llm_profile` without at least one item is a validation error.',
      ],
      details: [
        'Generation happens after the run finishes, so an output can describe the whole run including approvals and ignored failures.',
        'Generated content stays on authorized detail and read paths. List surfaces expose only an aggregate `final_output_status`.',
        'Provider and network errors during generation are not retried automatically. Use the retry action on the output row.',
        'PDF rendering goes through Gotenberg at `FINAL_OUTPUT_PDF_RENDERER_URL`, bounded by `FINAL_OUTPUT_PDF_TIMEOUT_SECONDS`.',
      ],
      fields: [...finalOutputFields, ...dashboardOutputFields],
      examples: [
        {
          title: 'Dashboard publication in series mode',
          language: 'yaml',
          code: [
            'output:',
            '  items:',
            '    - name: Deployment duration',
            '      type: dashboard',
            '      when: success',
            '      prompt: Report the total deployment duration in minutes.',
            '      dashboard:',
            '        ref: platform/release-health',
            '        section: deployments',
            '        entry_key: payments/prod',
            '        mode: series',
            '        preset: metrics',
            '        ttl: 7d',
          ].join('\n'),
          expectedOutput: 'Each successful run appends a point to the same series entry on the dashboard.',
        },
      ],
      limits: [
        'Final outputs are rejected when the pipeline sets `llm_enabled: false`.',
        'PDF output fails when no Gotenberg renderer is reachable.',
      ],
      related: ['dashboards', 'create-final-deliverable', 'llm-profiles'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Output and dashboard target validation.' },
        { repositoryPath: 'doc/final-output-rendering.md', purpose: 'Renderer contracts and retry/audit behavior.' },
      ],
    },
  ],
};
