import {
  externalTriggerFields,
  gitTriggerFields,
  scheduleFields,
} from '../fields/events.js';
import type { WikiSection } from '../types.js';

export const automationSection: WikiSection = {
  id: 'automation',
  title: 'Automation',
  owner: 'Automation platform',
  description: 'How runs start: manually, from a Git event, on a schedule, from an external system, or from a parent pipeline.',
  articles: [
    {
      id: 'entry-points',
      title: 'How runs start',
      docType: 'concept',
      audiences: ['automation-author', 'operator'],
      summary: 'The six entry points into a run, and what each one controls about ownership and scope.',
      keywords: ['trigger', 'entry point', 'start', 'run', 'manual'],
      keyFacts: [
        'Manual — `POST /v1/run/{pipelineName}` from the UI, CLI, or API.',
        'Schedule — a cron or one-time schedule owned by a team path.',
        'Git event — a GitHub App event or a Git Webhook Source delivery matched against a repository trigger manifest.',
        'External trigger — an authenticated invocation from another system, with payload mapping and rate limiting.',
        'Child pipeline — a `pipeline:` include started by a parent run.',
        'Rerun — a new run created from an existing run definition and inputs.',
      ],
      details: [
        'Every entry point produces a normal run with the same authorization, logging, and audit behavior. What differs is who the original caller is and which scope and team path the run inherits.',
        'Scope decides which variables and secrets resolve. Team path decides run ownership and notification lineage; `global` means no concrete team assignment.',
        'AAA authorizes the original caller for every resource the run references, including the pipeline, the scope, and each selected profile — not just the entry point.',
      ],
      examples: [
        {
          title: 'Start the same pipeline from each entry point',
          language: 'bash',
          code: [
            '# manually, in a chosen scope',
            'curl -sX POST "$NOPSAI_URL/v1/run/platform/release-service" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Accept: application/json" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"scope":"platform/production"}\'',
            '',
            '# from another system, through an external trigger',
            'curl -sX POST "$NOPSAI_URL/v1/external-triggers/$TRIGGER_ID/invoke" \\',
            '  -H "Authorization: Bearer $CALLER_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"payload":{"channel":"stable"}}\'',
            '',
            '# on a schedule, run once now without waiting for the next tick',
            'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  "$NOPSAI_URL/v1/schedules/$SCHEDULE_ID/run"',
          ].join('\n'),
          expectedOutput:
            'Three different entry points, one pipeline, and one run record shape. The entry point decides ownership and scope, not what the pipeline does.',
          placeholders: ['`$NOPSAI_URL` is the API address; `$TRIGGER_ID` and `$SCHEDULE_ID` come from their list endpoints.'],
        },
      ],
      related: ['git-triggers', 'schedules', 'external-triggers', 'run-lifecycle'],
      sources: [{ repositoryPath: 'doc/runtime-flows.md', purpose: 'Execution flow for each entry point.' }],
    },
    {
      id: 'git-triggers',
      title: 'Git trigger manifests',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary: 'The repository-side `.nopsai.yaml` that decides which events start which pipelines.',
      keywords: ['trigger', 'nopsai.yaml', 'branches', 'paths', 'push', 'pull request', 'ci'],
      keyFacts: [
        'The manifest lives in the repository, so trigger rules are reviewed like code.',
        '`on: all` matches any event from the provider.',
        'Branch matching applies `branches` first, then removes anything matching `skip_branches`.',
        'Path matching intentionally fails open: when changed-file metadata is unknown, the rule still matches so CI is not silently skipped.',
        'Non-GitHub providers must name a managed `webhook_source`.',
        '`pipelines` accepts scalar paths only; an empty path is rejected at parse time.',
      ],
      details: [
        'When `branches` is empty and either `skip_branches` is set or `on` is `all`, every branch is treated as included before exclusions are applied. This makes "everything except these" rules straightforward.',
        '`exclude_paths` is applied before `include_paths` is evaluated, so a file removed by an exclusion cannot satisfy an include.',
        'Forwarded GitHub App events reach `POST /v1/git/events`, which is an internal service call requiring a git-bot service token. It is not public webhook ingress and should not be exposed as such.',
      ],
      fields: gitTriggerFields,
      examples: [
        {
          title: 'Everything except documentation and bot branches',
          language: 'yaml',
          code: [
            'team: platform/payments',
            'triggers:',
            '  - on: all',
            '    skip_branches:',
            '      - dependabot/*',
            '    exclude_paths:',
            '      - "**/*.md"',
            '      - docs/**',
            '    pipelines:',
            '      - .nopsai/pipelines/ci.yaml',
          ].join('\n'),
          expectedOutput: 'Any event on any branch except dependabot branches starts CI, unless every changed file is documentation.',
        },
        {
          title: 'GitLab source with tag filtering',
          language: 'yaml',
          code: [
            'provider: gitlab',
            'webhook_source: gitlab-main',
            'team: platform/payments',
            'triggers:',
            '  - on: push',
            '    tags:',
            '      - "v*"',
            '    pipelines:',
            '      - .nopsai/pipelines/release.yaml',
            '    scope: platform/production',
          ].join('\n'),
        },
      ],
      related: ['git-webhook-sources', 'connect-git-repository', 'trigger-pipeline-from-git'],
      sources: [
        { repositoryPath: 'pkg/gittrigger/matcher.go', purpose: 'Exact branch, tag, and path matching behavior including fail-open.' },
        { repositoryPath: 'pkg/models/model.go', purpose: 'Manifest and trigger struct definitions.' },
      ],
    },
    {
      id: 'git-webhook-sources',
      title: 'Git webhook sources',
      docType: 'how-to',
      audiences: ['administrator', 'developer'],
      summary: 'Managed ingress for GitLab, Bitbucket, Gitea, and generic providers.',
      keywords: ['webhook', 'gitlab', 'bitbucket', 'gitea', 'generic', 'ingress', 'signature'],
      keyFacts: [
        'Each source owns its own signing secret and receives deliveries at `POST /v1/git/webhooks/{sourceID}`.',
        'Deliveries are normalized into the same event model that GitHub App events use, so trigger manifests stay provider-neutral.',
        'Recent deliveries are visible for diagnosis at `GET /v1/git-webhook-sources/{sourceID}/deliveries`.',
        'A trigger manifest for a non-GitHub provider must reference the source by ID.',
      ],
      details: [
        'The webhook endpoint is public by necessity — the provider calls it — but every delivery is signature-verified against the source secret before it is accepted.',
        'A repository allowlist limits which repositories a source may start runs for, so one shared source cannot be used to trigger unrelated pipelines.',
      ],
      prerequisites: [
        { label: 'Provider', value: 'A GitLab, Bitbucket, Gitea, or generic provider that can send webhooks' },
        { label: 'Reachable ingress', value: 'The webhook endpoint reachable from the provider; nothing else about the install needs to be exposed' },
        { label: 'Access', value: 'Permission to create Git webhook sources and the trigger that consumes them' },
      ],
      steps: [
        {
          title: 'Create the source',
          description: 'A source owns its provider kind, its signing secret, and the repository allowlist that bounds what it may start runs for.',
          commands: [
            {
              title: 'Create a source',
              language: 'bash',
              code: 'curl -sX POST "$NOPSAI_URL/v1/git-webhook-sources" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @source.json | jq -r .id',
              placeholders: ['`source.json` names the provider kind, the signing secret reference, and the allowed `owner/repository` patterns.'],
            },
          ],
          expectedOutput: 'A source ID. Deliveries for this source arrive at `POST /v1/git/webhooks/{sourceID}`.',
        },
        {
          title: 'Point the provider at it',
          description: 'Configure the webhook in the provider with that URL and the same signing secret. Every delivery is signature-verified before it is accepted.',
          verification: 'The provider reports a successful delivery, and the source lists it.',
        },
        {
          title: 'Read the deliveries',
          description: 'Delivery history is the first place to look when a push produced no run: it separates "never arrived" from "arrived and was rejected".',
          commands: [
            { title: 'List recent deliveries', language: 'bash', code: 'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/git-webhook-sources/$SOURCE_ID/deliveries" | jq' },
          ],
          verification: 'The delivery appears with its verification result and the event it normalised to.',
        },
        {
          title: 'Bind a trigger to the source',
          description: 'A trigger manifest for a non-GitHub provider must reference the source by ID. The event model is already normalised, so the manifest stays provider-neutral.',
          verification: 'A push matching the trigger rules produces a run.',
        },
      ],
      related: ['git-triggers', 'connect-git-repository', 'credentials'],
      sources: [
        { repositoryPath: 'doc/git-webhook-sources.md', purpose: 'Provider configuration, security, payload normalization, and operations.' },
        { repositoryPath: 'services/nopsai/git_webhook_sources_schema.go', purpose: 'Source schema and delivery handling.' },
      ],
    },
    {
      id: 'external-triggers',
      title: 'External API triggers',
      docType: 'reference',
      audiences: ['automation-author', 'developer', 'security'],
      summary: 'Let another system start a run, with explicit callers, payload validation, mapping, and rate limits.',
      keywords: ['external trigger', 'api trigger', 'invoke', 'webhook', 'integration', 'idempotency'],
      keyFacts: [
        '`allowed_callers` names explicit `user`, `service_account`, or `auth_team` callers.',
        '`variable_mapping` pulls run variables from `event_type`, `payload.<path>`, `variables.<name>`, a direct payload path, or `literal:<value>`.',
        '`payload_schema` guards required fields and basic property types before a run starts.',
        '`rate_limit.per_minute` caps invocations over the previous minute.',
        '`idempotency_key` on the request is scoped by trigger and caller, so a retry returns the original run.',
      ],
      details: [
        'An empty `allowed_callers` list does not widen access. AAA still authorizes the caller against the trigger resource, so the list narrows an already-authorized set rather than granting anything.',
        'Invocation history is available per trigger, which is usually the fastest way to diagnose a caller that believes it is triggering runs but is being rejected.',
      ],
      fields: externalTriggerFields,
      examples: [
        {
          title: 'Change-management trigger',
          language: 'yaml',
          code: [
            'name: deploy-from-change-request',
            'pipeline: platform/deploy-service',
            'enabled: true',
            'scope: platform/production',
            'run_team_path: platform/payments',
            'allowed_callers:',
            '  - service_account: change-management',
            'payload_schema:',
            '  type: object',
            '  required: [service, change_id]',
            '  properties:',
            '    service: { type: string }',
            '    change_id: { type: string }',
            'variable_mapping:',
            '  SERVICE: payload.service',
            '  CHANGE_ID: payload.change_id',
            '  ENVIRONMENT: literal:production',
            'rate_limit:',
            '  per_minute: 10',
          ].join('\n'),
        },
        {
          title: 'Invoking with an idempotency key',
          language: 'bash',
          code: [
            'curl -sX POST "$NOPSAI_URL/v1/external-triggers/$TRIGGER_ID/invoke" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"idempotency_key":"change-4821","payload":{"service":"payments","change_id":"4821"}}\'',
          ].join('\n'),
          expectedOutput: 'A repeated call with the same key returns the original run instead of starting a second one.',
        },
      ],
      related: ['entry-points', 'tokens-and-service-accounts', 'access-control'],
      sources: [
        { repositoryPath: 'services/nopsai/external_triggers_gitops.go', purpose: 'External trigger GitOps document schema.' },
        { repositoryPath: 'services/nopsai/external_triggers.go', purpose: 'Invocation, idempotency, and rate-limit handling.' },
      ],
    },
    {
      id: 'schedules',
      title: 'Schedules',
      docType: 'reference',
      audiences: ['automation-author', 'operator'],
      summary: 'Cron and one-time schedules, their ownership, and the variables they supply.',
      keywords: ['schedule', 'cron', 'timer', 'recurring', 'once', 'timezone'],
      keyFacts: [
        '`schedule_kind` is `cron` or `once`, defaulting to `cron`.',
        '`cron_expression` is required for cron schedules; the API also accepts `cron` as an alias.',
        '`run_at` is required for one-time schedules and must be in the future while enabled.',
        '`timezone` is an IANA name and defaults to `UTC`.',
        '`run_team_path` sets the resulting run ownership and notification lineage; `global` means no concrete team.',
        'Disabled schedules stay visible in the registry rather than disappearing.',
      ],
      details: [
        'The Schedules workspace groups by `run_team_path` when present, falling back to the schedule path for older rows. The registry table stays focused on name, pipeline, cadence, next run, and latest status, with the status linking straight to the run detail when a run exists.',
        'Selecting a schedule navigates to `/schedules/<resource path/name>`. The detail panel owns mutations, ownership, GitOps source, runtime scope, run team, and variables.',
        'A schedule can be run immediately outside its cadence with `POST /v1/schedules/{scheduleID}/run`, which is useful for verifying a new cron rule.',
      ],
      fields: scheduleFields,
      examples: [
        {
          title: 'Nightly report in a local timezone',
          language: 'yaml',
          code: [
            'name: nightly-compliance-report',
            'pipeline: platform/compliance-report',
            'schedule_kind: cron',
            'cron_expression: "0 2 * * *"',
            'timezone: Europe/Amsterdam',
            'enabled: true',
            'scope: platform/production',
            'run_team_path: platform/payments',
            'variables:',
            '  REPORT_WINDOW: 24h',
          ].join('\n'),
        },
      ],
      related: ['entry-points', 'pipeline-runs', 'notifications'],
      sources: [
        { repositoryPath: 'services/nopsai/config_repository_resource_export.go', purpose: 'Schedule GitOps document schema.' },
      ],
    },
  ],
};
