import { allEnvironmentFields, runnerEnvironmentFields } from '../fields/environment.js';
import type { WikiSection } from '../types.js';

export const installSection: WikiSection = {
  id: 'install',
  title: 'Install and deploy',
  group: 'run',
  owner: 'Platform engineering',
  description: 'Supported deployment models, the values every install needs, and how runners join a control plane.',
  articles: [
    {
      id: 'deployment-models',
      title: 'Supported deployment models',
      docType: 'concept',
      audiences: ['administrator', 'operator'],
      summary: 'Four shapes the platform is built for, and what each one implies for runtime and database.',
      keywords: ['deployment', 'compose', 'helm', 'kubernetes', 'bundle', 'hybrid', 'topology'],
      keyFacts: [
        '**Docker Compose** — development, demos, evaluation, and small single-host installs. Docker runner, bundled PostgreSQL 15.',
        '**Release bundle** — version-pinned single-host deployment. Docker runner, deployment-managed PostgreSQL.',
        '**Helm / Kubernetes** — cluster production deployment. Kubernetes runner, bundled or external PostgreSQL.',
        '**Hybrid runners** — one central control plane with remote Docker or Kubernetes runners. Control-plane PostgreSQL.',
        'The Helm chart deploys PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, and the Kubernetes runner.',
      ],
      details: [
        '`nopsai install kubernetes` generates non-secret Helm values, an `installation.md`, and a separate Secret manifest for new installations. Values and locks are GitOps-friendly; apply the Secret manifest directly for a first install, or seal and encrypt it before it enters GitOps.',
        'Managed PostgreSQL is supported by disabling the bundled StatefulSet and replacing the generated database URL.',
        '`topology.dispatcherGRPCAddress` controls the dispatcher endpoint injected into API and Kubernetes runner pods, and the same topology block carries the internal NopsAI, AAA, git-bot, and Gotenberg service URLs for custom DNS or split-service deployments.',
      ],
      limits: [
        'There are no Terraform modules and no AWS-, Azure-, or Google-specific deployment automation in this repository.',
        'Raising every replica count does not by itself produce a highly available deployment.',
      ],
      related: ['docker-compose', 'helm-kubernetes', 'environment-reference', 'runners-and-dispatcher'],
      sources: [
        { repositoryPath: 'deploy/helm/nopsai/values.yaml', purpose: 'Chart topology and component values.' },
        { repositoryPath: 'doc/release-bundles.md', purpose: 'Versioned release assets and generated install files.' },
      ],
    },
    {
      id: 'first-install-wizard',
      title: 'First-install setup',
      docType: 'reference',
      audiences: ['administrator'],
      summary: 'The one-time bootstrap that unlocks the platform, and how to diagnose it when it will not complete.',
      keywords: ['setup', 'bootstrap', 'preflight', 'first install', 'unlock'],
      keyFacts: [
        'Normal authenticated routes and APIs stay locked until setup completes once.',
        '`GET /v1/setup/preflight` and `GET /v1/setup/status` are public so a stuck install can be diagnosed without a token.',
        'During cold starts the API serves preflight while PostgreSQL is still starting: `/livez` stays process-alive and `/healthz` stays unready with the current preflight JSON.',
        'The wizard can generate secrets, seed starter profiles, create the GitOps layout, and create repository teams.',
        'Setup apply errors include the actionable write or configuration reason.',
        'Setup does not force an env-file write for dispatcher TLS when a valid effective service JWT fallback is already configured.',
      ],
      details: [
        'Bootstrap-created local admin credentials rotate on first login by default, and generated Docker Compose installs reject the built-in development `admin` password.',
        'Preflight is the right first stop for any "the UI will not let me in" report. It names the blocker rather than leaving you to infer it from logs.',
      ],
      related: ['complete-first-install-wizard', 'authentication-and-sso', 'production-hardening'],
      sources: [
        { repositoryPath: 'doc/first-install-wizard.md', purpose: 'Bootstrap flow, starter profiles, and production guardrails.' },
        { repositoryPath: 'services/nopsai/setup_preflight.go', purpose: 'Cold-start preflight behavior.' },
      ],
    },
    {
      id: 'environment-reference',
      title: 'Environment and service configuration',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary:
        'Every environment variable the platform reads, starting with the secrets and service URLs that must exist before GitOps can take over.',
      keywords: ['environment', 'env', 'secrets', 'bootstrap', 'configuration', 'variables', 'settings'],
      keyFacts: [
        'Bootstrap environment and deployment secrets are not the long-term source of truth — GitOps is. They exist so the platform can start and reach the point where GitOps loads.',
        '`JWT_SIGNING_KEY` and `SERVICE_JWT_SIGNING_KEY` must be different secrets so user tokens cannot impersonate services.',
        'Compose fails fast on a missing required value rather than starting in a broken state.',
        'Production should keep `DISPATCHER_TLS_MODE` at `mtls` or `tls`, never `disabled`.',
        'Rotating `SERVICE_JWT_SIGNING_KEY` and `DISPATCHER_TLS_SECRET` together is what prevents retired runners from rejoining a replacement control plane.',
      ],
      details: [
        'The table below covers every documented variable. Filter by scope to see what a single component actually reads, or use the environment variable index for the same rows grouped for scanning.',
        'Keep bootstrap-only values such as `DATABASE_URL`, `NOPSAI_MASTER_KEY`, `JWT_SIGNING_KEY`, `SERVICE_JWT_SIGNING_KEY`, `AAA_SHARED_INTERNAL_TOKEN`, and the bootstrap admin password in deployment secrets or the service environment — not in a configuration repository.',
        'Most product settings move to GitOps once the platform is running. Files under `setting/system/` become authoritative for runner topology, authentication, mail, data management, models, MCP, and Agent roles.',
      ],
      fields: allEnvironmentFields,
      examples: [
        {
          title: 'Helm bootstrap Secret keys',
          language: 'yaml',
          code: [
            'apiVersion: v1',
            'kind: Secret',
            'metadata:',
            '  name: nopsai-bootstrap',
            'stringData:',
            '  database-url: postgres://nopsai:***@nopsai-postgresql:5432/nopsai',
            '  master-key: <32+ byte random value>',
            '  jwt-signing-key: <high-entropy value>',
            '  service-jwt-signing-key: <different high-entropy value>',
            '  aaa-shared-internal-token: <high-entropy value>',
            '  bootstrap-admin-password: <generated value>',
            '  dispatcher-tls-secret: <high-entropy value>',
          ].join('\n'),
          placeholders: ['Replace every placeholder with a freshly generated value.'],
        },
      ],
      related: ['environment-index', 'production-hardening', 'docker-compose', 'helm-kubernetes'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'Config struct with yaml and env tags for every setting.' },
        { repositoryPath: 'config.yml', purpose: 'Which values stay bootstrap-only and which move to GitOps.' },
      ],
    },
    {
      id: 'docker-compose',
      title: 'Docker Compose deployment',
      docType: 'how-to',
      audiences: ['administrator', 'developer'],
      summary: 'The local and small single-host topology, its services, and its exposure defaults.',
      keywords: ['compose', 'docker', 'local', 'single host', 'ports'],
      keyFacts: [
        'The stack runs PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, the restricted socket proxy, and a Docker runner.',
        '`NOPSAI_BIND_ADDRESS` defaults to `127.0.0.1`, so published ports are workstation-local unless you change it.',
        'System Logs read through `tcp://docker-socket-proxy:2375`, never the raw Docker socket.',
        'The default topology does not mount `/data/backups` as durable storage.',
      ],
      details: [
        'Compose is the fastest way to see real product behavior, and everything configured there can be exported to a configuration repository afterwards.',
        'The Docker runner mounts the Docker socket because it creates agent and step containers. Treat the runner host as a trusted execution boundary and isolate workloads by scope.',
        'Docker step containers default to bridge networking so package installs, source fetches, and registry access work. Set `DOCKER_NETWORK_NAME=none` when steps must run without egress, or name a dedicated network for controlled egress.',
      ],
      examples: [
        {
          title: 'Start, inspect, and stop',
          language: 'bash',
          code: [
            'docker compose up -d --build',
            'docker compose ps',
            'docker compose logs -f nopsai aaa dispatcher docker-runner',
            'docker compose down',
          ].join('\n'),
        },
      ],
      limits: [
        'Compose defaults are development defaults. Replace every fallback secret and review exposure before using them anywhere shared.',
      ],
      related: ['install-local-docker-compose', 'networking-and-exposure', 'system-logs', 'production-hardening'],
      sources: [{ repositoryPath: 'docker-compose.yaml', purpose: 'Exact services, ports, and environment variables.' }],
    },
    {
      id: 'helm-kubernetes',
      title: 'Kubernetes and Helm deployment',
      docType: 'how-to',
      audiences: ['administrator', 'operator'],
      summary: 'Cluster deployment, generated install artifacts, and the service accounts that separate platform from workload.',
      keywords: ['kubernetes', 'helm', 'chart', 'cluster', 'rbac', 'pvc', 'namespace'],
      keyFacts: [
        'The chart deploys PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, and the Kubernetes runner.',
        '`nopsai install kubernetes` generates non-secret values, `installation.md`, and a separate Secret manifest.',
        'The runner Deployment and agent pods use an RBAC-bearing runner ServiceAccount; step pods use a separate no-RBAC workload ServiceAccount.',
        '`topology.dispatcherGRPCAddress` defaults to `dispatcher:9090` and is injected into API and runner pods.',
        'Cross-namespace runners normally need `dispatcher.<platform-namespace>.svc.cluster.local:9090`.',
        'Private registries work through explicit `imagePullSecrets`.',
        'The chart version is the only version to change: NopsAI image tags resolve from `global.releaseVersion`, and an empty value falls back to the chart `appVersion`. Per-image `tag` and `digest` values stay available as intentional overrides.',
      ],
      details: [
        'Keeping step pods on a no-RBAC service account is what stops workload code from calling the Kubernetes API. Do not merge the two accounts to simplify a chart values file.',
        'Managed PostgreSQL is supported by disabling the bundled StatefulSet and replacing the generated database URL.',
        'The Kubernetes runner gives each run an agent-owned PVC-backed workspace rather than an emptyDir, so the workspace survives step pod churn within the run.',
        'System Logs on Kubernetes use read-only `pods` and `pods/log` RBAC instead of the Docker socket proxy.',
      ],
      fields: runnerEnvironmentFields.filter(field => field.scope === 'kubernetes runner'),
      examples: [
        {
          title: 'Generate install artifacts for a pinned version',
          language: 'bash',
          code: 'nopsai install kubernetes --version 1.4.2',
          expectedOutput: 'Non-secret Helm values, installation.md, and a separate Secret manifest to apply directly or seal.',
        },
      ],
      limits: [
        'The repository documents no HPA/autoscaling implementation and no Kubernetes NetworkPolicy set.',
        'Helm does not manage PostgreSQL beyond the bundled StatefulSet.',
      ],
      related: ['deployment-models', 'runners-and-dispatcher', 'private-registry-auth', 'storage-and-persistence'],
      sources: [
        { repositoryPath: 'deploy/helm/nopsai/values.yaml', purpose: 'Chart values including topology and service accounts.' },
        { repositoryPath: 'doc/kubernetes-runner.md', purpose: 'Runner runtime, PVC workspace behavior, affinity, and manifests.' },
      ],
    },
    {
      id: 'runners-and-dispatcher',
      title: 'Runners and the dispatcher',
      docType: 'reference',
      audiences: ['administrator', 'operator'],
      summary: 'How runners register, how work is routed to them, and what happens when one disconnects or is ejected.',
      keywords: ['runner', 'dispatcher', 'routing', 'capacity', 'registration', 'ejection', 'fleet'],
      keyFacts: [
        'Runner registration is trusted by service JWT and TLS material plus the ejected-runner blocklist.',
        'Routing tables use the effective view: paused or unreachable runner IDs stay visible for diagnosis, but only reachable dispatch-enabled runners are treated as dispatchable targets.',
        'An ordinary network disconnect keeps the registration available for reconnect. A reconnected runner keeps `last_disconnected_at` and shows as recovered or degraded during the recovery window.',
        'Deliberate removal disconnects the runner, clears dispatcher status, and adds its ID to `ejected_runner_ids`.',
        'An explicit empty `runner_scopes` value means all scopes.',
        'Generated installs preserve the friendly name as `runner_name` and use a unique suffixed `RUNNER_ID` for dispatcher identity.',
      ],
      details: [
        'The System dispatcher workspace separates compact overview metrics, a runtime-filtered table-first fleet view, route editing with the effective routing table, and install command generation. Runner detail appears below the fleet table only after an operator selects a runner.',
        'The GitOps-owned configured route map and the live effective routing view are different things. The configured map is desired state; the effective view is derived from registered runner scopes and runtime status.',
        'Replacing a control plane while keeping the old `SERVICE_JWT_SIGNING_KEY` and `DISPATCHER_TLS_SECRET` lets old runner definitions authenticate again unless their IDs are carried forward in `ejected_runner_ids`. Rotate those secrets before exposing a fresh dispatcher when old runners must not join.',
      ],
      fields: runnerEnvironmentFields,
      examples: [
        {
          title: 'Generate a Docker runner install command',
          language: 'bash',
          code: 'curl -s "$NOPSAI_URL/v1/system/dispatcher/runner-bootstrap-command?scopes=platform/production" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN"',
          expectedOutput: 'A one-line install command carrying the runner identity, scopes, and dispatcher connection material.',
        },
      ],
      related: ['helm-kubernetes', 'private-registry-auth', 'system-logs', 'monitoring'],
      sources: [
        { repositoryPath: 'services/dispatcher/internal/app/app.go', purpose: 'Dispatcher listen address and registration handling.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Dispatcher management and install-generation routes.' },
      ],
    },
    {
      id: 'private-registry-auth',
      title: 'Private registry authentication',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary: 'Two separate mechanisms: infrastructure-owned pull secrets and NopsAI-owned runner credential assignments.',
      keywords: ['registry', 'private', 'imagePullSecrets', 'docker_config_json', 'RegistryAuth', 'credentials'],
      keyFacts: [
        'Infrastructure-owned platform pull secrets (`imagePullSecrets`, `KUBERNETES_IMAGE_PULL_SECRETS`) and NopsAI-owned runner credential assignments (`runner_registry_credentials`, `registry_credential_ref`) are distinct and should not be conflated.',
        'Docker runners use bootstrap-delivered `NOPSAI_REGISTRY_DOCKER_CONFIG_B64` to build local per-image `RegistryAuth`.',
        'The legacy `/v1/internal/registry-auth/docker` broker route has been removed.',
        'Kubernetes step and agent pods continue to pull through explicit `imagePullSecrets`.',
      ],
      details: [
        'Assigning a registry credential to a runner is a NopsAI-side operation recorded with audit and metrics. Attaching a pull secret to a pod is a cluster-side operation owned by whoever manages the namespace.',
        'Keep the two boundaries separate when debugging a pull failure: a Kubernetes `ImagePullBackOff` is almost always a missing or wrong `imagePullSecret`, while a Docker runner pull failure points at the delivered docker config.',
      ],
      related: ['runners-and-dispatcher', 'helm-kubernetes', 'credentials'],
      sources: [
        { repositoryPath: 'doc/runner-registry-auth.md', purpose: 'Credential assignment, image pulls, GitOps, audit, and metrics behavior.' },
        { repositoryPath: 'pkg/registryauth', purpose: 'RegistryAuth construction for Docker image pulls.' },
      ],
    },
    {
      id: 'networking-and-exposure',
      title: 'Networking and exposure',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'What has to be reachable from where, and what should never be exposed.',
      keywords: ['network', 'ports', 'exposure', 'ingress', 'egress', 'firewall'],
      keyFacts: [
        'Runners hold long-lived outbound connections to the dispatcher, so runners never need inbound access.',
        'The UI and API are the only surfaces that normally need external exposure, plus the Git webhook endpoint when non-GitHub providers are used.',
        'Docker step containers default to bridge networking; `DOCKER_NETWORK_NAME=none` removes egress entirely.',
        '`GET /metrics` is public by default for scraper compatibility and can be locked behind bearer auth with `METRICS_REQUIRE_AUTH`.',
        'The Docker socket proxy exposes only the allow-listed reads System Logs needs and must never be replaced by the raw socket.',
      ],
      details: [
        'Internal service URLs (`AAA_API_URL`, `GIT_BOT_API_URL`, `NOPSAI_API_URL`) describe a private network. Exposing AAA or the dispatcher publicly removes a boundary the design depends on.',
        'Provider endpoints for LLM and MCP must be reachable from the API runtime. Inside containers `localhost` refers to the container, so host-launched tools need a LAN IP or `host.docker.internal`.',
      ],
      limits: ['The repository documents no Kubernetes NetworkPolicy set and no automatic certificate-management integration.'],
      related: ['docker-compose', 'helm-kubernetes', 'production-hardening', 'system-logs'],
      sources: [
        { repositoryPath: 'docker-compose.yaml', purpose: 'Published ports and bind address defaults.' },
        { repositoryPath: 'services/docker-socket-proxy', purpose: 'The allow-listed Docker API surface.' },
      ],
    },
    {
      id: 'storage-and-persistence',
      title: 'Storage and persistence',
      docType: 'concept',
      audiences: ['administrator', 'operator'],
      summary: 'What is durable, what is per-run, and what the default topology does not persist.',
      keywords: ['storage', 'persistence', 'volume', 'pvc', 'workspace', 'database', 'backup'],
      keyFacts: [
        'PostgreSQL holds durable execution, audit, credential, monitoring, and setup state.',
        'Docker runners create named Docker volumes; Kubernetes runners create an agent-owned PVC-backed workspace per run.',
        'Step `volumes` reuse existing storage and create it when missing, in `volume:/mount/path` form.',
        'The reserved runtime output path `/nopsai/outputs` cannot be used as a volume mount target.',
        'Backups are gzip-compressed JSON Lines files under `DATA_BACKUP_DIR`, defaulting to `/data/backups`.',
      ],
      details: [
        'The default Compose topology does not mount the backup directory as durable storage, so production deployments must mount or export it. This is the single most common persistence surprise.',
        'Docker step containers leave image-provided temporary directories such as `/tmp` and `/var/tmp` unchanged, so images that rely on them behave normally.',
      ],
      limits: [
        'There is no S3 or generic object-storage artifact or backup backend.',
        'Backup creation, listing, checksum metadata, download, and cleanup exist; a verified product-managed restore workflow does not.',
      ],
      related: ['data-management', 'helm-kubernetes', 'known-limits'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'DATA_BACKUP_DIR and runtime output limits.' },
        { repositoryPath: 'doc/kubernetes-runner.md', purpose: 'Agent-owned PVC workspace behavior.' },
      ],
    },
  ],
};
