import type { WikiSection } from '../types.js';

export const interfacesSection: WikiSection = {
  id: 'interfaces',
  title: 'Interfaces',
  group: 'look-up',
  owner: 'Platform engineering',
  description: 'The four ways to drive NopsAI: REST, CLI, Assistant chat, and the hosted MCP endpoint.',
  articles: [
    {
      id: 'api',
      title: 'REST API',
      docType: 'reference',
      audiences: ['developer', 'automation-author', 'operator'],
      summary: 'How the API is structured, what authenticates against it, and where the complete route list lives.',
      keywords: ['api', 'rest', 'endpoint', 'http', 'v1', 'token', 'bearer'],
      keyFacts: [
        'Every route is versioned under `/v1`, except the platform probes `/healthz`, `/livez`, `/version`, `/metrics`, and `/favicon.ico`.',
        'Authenticate with a bearer token: a personal access token, a service account token, or a session token.',
        'Every request passes the same chain: request ID, CORS, body limit, logging, recovery, audit, authentication, authorization.',
        'Setup routes are public by design so a stuck install can be diagnosed without a token.',
        'Routes under `/v1/internal/` require an internal service token and are not part of the public surface.',
        'The complete route list, grouped by area with access class, is on the REST API index.',
      ],
      details: [
        'Resource routes under `/v1/resources/...` are handler-authorized: the middleware defers, then the handler resolves the concrete resource and checks owner-level manage access before reading settings, changing visibility, or adding and removing use grants.',
        'List endpoints are authorization-filtered rather than returning everything and hiding it client-side, so an empty list can legitimately mean "you have no access here".',
        'Request bodies are size-limited platform-wide, and login is separately rate-limited.',
      ],
      examples: [
        {
          title: 'Authenticate and start a run',
          language: 'bash',
          code: [
            'export NOPSAI_URL=https://nopsai.example.com',
            'export NOPSAI_TOKEN=<personal access token>',
            '',
            'curl -s "$NOPSAI_URL/v1/auth/me" -H "Authorization: Bearer $NOPSAI_TOKEN"',
            'curl -sX POST "$NOPSAI_URL/v1/run/platform%2Fdeploy-service" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN"',
          ].join('\n'),
          placeholders: ['Create the token under Profile, then Personal access tokens.'],
        },
        {
          title: 'Validate a pipeline before saving it',
          language: 'bash',
          code: [
            'curl -sX POST "$NOPSAI_URL/v1/pipelines/validate" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/yaml" \\',
            '  --data-binary @pipeline.yaml',
          ].join('\n'),
          expectedOutput: 'Validation errors name the exact step, task, or directive at fault.',
        },
      ],
      related: ['api-index', 'tokens-and-service-accounts', 'access-control', 'cli'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Every registered route and its handler.' },
        { repositoryPath: 'doc/api.md', purpose: 'Request and response shapes per area.' },
      ],
    },
    {
      id: 'cli',
      title: 'Command-line interface',
      docType: 'reference',
      audiences: ['operator', 'administrator', 'developer'],
      summary: 'Automation commands plus an interactive operator console over the same authenticated API.',
      keywords: ['cli', 'nopsai', 'terminal', 'console', 'install', 'doctor', 'update', 'completion'],
      keyFacts: [
        'The CLI drives the same authenticated REST API as the UI. It has no private path.',
        'Contexts hold the API URL and credentials so one binary can target several installations.',
        'The interactive console exposes API catalog calls, raw API requests, route listing and descriptions, context management, token login and logout, install generation, platform doctor, platform release, platform upgrade, completion generation, guide topics, help, and exit.',
        '`nopsai install docker-compose` and `nopsai install kubernetes` generate version-pinned install files.',
        '`nopsai update --version <x.y.z>` downloads the exact OCI archive and `SHA256SUMS`, verifies the checksum, then replaces the local binary.',
        '`nopsai platform upgrade docker-compose|kubernetes --version <x.y.z>` upgrades an installed platform. It keeps the secrets install generated, is forward-only, and prints the verified release changelog with the required actions before applying.',
        'Interactive actions show the equivalent `nopsai ...` command as a final preview before anything is sent or changed.',
      ],
      details: [
        'The live terminal layout uses centered screens with fixed header and footer chrome, breadcrumb text above nested menus, a fixed 20-row menu viewport, and a pinned guide and details section beneath it. Every feature menu, result viewer, wizard, and platform screen shares that layout.',
        'API request parameter lists follow the wizard step order, expand the active item inline with its required marker and value, and render an empty active value as a cursor rather than a blank placeholder. Blank optional parameters, including multiline ones, advance with Enter.',
        'UI release gates print UTC start and finish timestamps and durations for each npm stage so local-time log rendering cannot look like a loop.',
      ],
      examples: [
        {
          title: 'Point the CLI at an installation and check it',
          language: 'bash',
          code: [
            'nopsai context set prod --url https://nopsai.example.com',
            'nopsai auth login',
            'nopsai doctor',
          ].join('\n'),
          expectedOutput: 'Doctor reports platform reachability and configuration problems it can detect from the client side.',
        },
        {
          title: 'Generate a pinned Docker Compose install',
          language: 'bash',
          code: 'nopsai install docker-compose --version 1.4.2',
          expectedOutput: 'Generated Compose files and locks with exact versions rather than floating tags.',
        },
        {
          title: 'Review and apply a platform upgrade',
          language: 'bash',
          code: [
            'nopsai update --version 1.5.0',
            'nopsai platform upgrade docker-compose --version 1.5.0 --plan',
            'nopsai platform upgrade docker-compose --version 1.5.0 --run',
          ].join('\n'),
          expectedOutput: 'The plan prints the changelog and required actions; a series upgrade needs --accept-series-upgrade before it applies.',
        },
      ],
      related: ['api', 'release-integrity', 'deployment-models'],
      sources: [
        { repositoryPath: 'doc/cli.md', purpose: 'Contexts, credentials, interactive REST access, installs, and diagnostics.' },
        { repositoryPath: 'internal/cli/command', purpose: 'Command implementations, including the interactive console.' },
      ],
    },
    {
      id: 'assistant',
      title: 'Assistant chat',
      docType: 'concept',
      audiences: ['operator', 'automation-author', 'security'],
      summary: 'In-product chat with page context, and exactly what that context contains.',
      keywords: ['assistant', 'chat', 'context', 'help', 'debugging', 'conversation'],
      keyFacts: [
        'Current-page context is metadata only: route, page area, active tab, team and scope, selected resource IDs, and allow-listed filters.',
        'The composer renders a removable context chip so you can see and drop the context before sending.',
        'The Assistant does not scrape page text, logs, secrets, credentials, or arbitrary query parameters.',
        'Assistant selects from the same models pipelines use, filtered by what the caller may access.',
        'Conversations are per-user and can be deleted; memory can be compacted with a summarize action.',
        'Assistant availability and individual features are configuration-controlled.',
      ],
      details: [
        'AI Evaluation on analysis surfaces is a separate mechanism. It uses the analysis evaluation endpoint rather than creating an Assistant conversation, and it does not ask hosted MCP to inspect resources.',
        'If Assistant reports that no model is available, configure provider, model, credential reference, and scope access in Models — the same place pipeline goals get their profiles.',
      ],
      related: ['models', 'analysis-reviewers', 'hosted-mcp'],
      sources: [
        { repositoryPath: 'doc/assistant-capabilities.md', purpose: 'User-facing capabilities and example prompts per feature area.' },
        { repositoryPath: 'services/ui/src/features/assistant/pageContext.ts', purpose: 'Exactly which page metadata is collected.' },
      ],
    },
    {
      id: 'hosted-mcp',
      title: 'Hosted NopsAI MCP endpoint',
      docType: 'reference',
      audiences: ['developer', 'automation-author', 'security'],
      summary: 'Let an external MCP client drive NopsAI, filtered by the caller AAA permissions.',
      keywords: ['hosted mcp', 'mcp server', 'endpoint', 'integration', 'tools', 'agent'],
      keyFacts: [
        'NopsAI exposes a hosted MCP endpoint at `POST /v1/mcp`.',
        'The tool surface is filtered by the calling identity AAA permissions — it is not a privileged back door.',
        'This is the inverse of MCP Profiles: profiles let NopsAI call out to external servers, while the hosted endpoint lets external clients call in.',
        'Authenticate with the same bearer tokens the REST API accepts.',
      ],
      details: [
        'Because the surface is permission-filtered per caller, two clients with different tokens see different available tools. That is the intended behavior, not a discovery bug.',
        'Use a service account rather than a personal token when an external agent will call the endpoint continuously.',
      ],
      related: ['mcp', 'tokens-and-service-accounts', 'api'],
      sources: [
        { repositoryPath: 'doc/mcp-feature-coverage.md', purpose: 'Hosted MCP feature coverage and user-scoped permissions.' },
        { repositoryPath: 'services/nopsai/hosted_mcp.go', purpose: 'Endpoint implementation and permission filtering.' },
      ],
    },
  ],
};
