import type { WikiSection } from '../types.js';

export const operationsSection: WikiSection = {
  id: 'operations',
  title: 'Operate',
  group: 'run',
  owner: 'Operations',
  description: 'Watching runs, reading logs, diagnosing failures, and keeping the platform healthy.',
  articles: [
    {
      id: 'pipeline-runs',
      title: 'Pipeline runs',
      docType: 'how-to',
      audiences: ['operator', 'automation-author'],
      summary: 'Reading a run: the execution graph, step and task detail, outputs, and what each status means.',
      keywords: ['run', 'graph', 'status', 'warning', 'timed out', 'execution', 'detail'],
      keyFacts: [
        'Run detail separates Graph and Outputs tabs. Selecting a multi-task step reveals its task DAG below the step overview.',
        'A run finishes `success`, `failure`, `warning`, `timed_out`, or `canceled`.',
        '`warning` means work failed but was ignored: the failing task stays auditable as `failure (ignored)`.',
        '`timed_out` is what an expired approval timeout or run timeout produces.',
        'Run list surfaces expose only aggregate `final_output_status`; generated content stays on authorized detail paths.',
        'Pipeline detail is organized as Flow, Definition, Trigger rules, Runs, Health, and Dependencies tabs.',
      ],
      details: [
        'The expanded graph dialog supports scroll-zoom traversal of larger graphs, centers bounds when a run opens or Fit is pressed, and keeps the task reveal during zoom and pan. Unmodified wheel input still scrolls the page outside expanded graph mode.',
        'The Health tab owns the full pipeline analysis result and the AI Evaluation surface. The Analyse Pipeline header action switches there rather than opening a separate modal.',
        'Copy actions across pipeline YAML, step YAML, trigger YAML, knowledge content, credential references, run definition YAML, and run graph links all use the shared clipboard helper, so the selection-copy fallback works when the browser Clipboard API is unavailable.',
      ],
      related: ['run-lifecycle', 'pipeline-logs', 'analysis-reviewers', 'final-deliverables'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Run lifecycle, approval, and output routes.' },
        { repositoryPath: 'doc/runtime-flows.md', purpose: 'Cancellation, rerun, and child pipeline flows.' },
      ],
    },
    {
      id: 'pipeline-logs',
      title: 'Pipeline logs and redaction',
      docType: 'reference',
      audiences: ['operator', 'security'],
      summary: 'Durable run records, what is masked, and what is deliberately left visible.',
      keywords: ['logs', 'redaction', 'masking', 'secrets', 'sensitive', 'audit'],
      keyFacts: [
        'Pipeline logs are durable run records, distinct from live System Logs.',
        'Agent-side masking covers declared secrets, sensitive variable names, and outputs marked `sensitive`.',
        'Non-sensitive operational evidence — environment names, versions, image references, change IDs, declared non-sensitive output JSON — stays visible for troubleshooting and release review.',
        'Durable ingestion applies best-effort credential-pattern redaction, including escaped JSON inside agent log messages, before writing `pipeline_run_logs`.',
      ],
      details: [
        'The distinction matters when investigating a leak: agent-side masking is intentional and driven by your declarations, while ingestion-side redaction is a best-effort safety net. Declaring a value as a secret or `sensitive` output is the reliable control.',
        'If a value you expected to be masked appears in logs, check whether it was declared under `secrets` or marked `sensitive: true` on the producing output.',
      ],
      related: ['system-logs', 'variables-secrets-scopes', 'runtime-outputs'],
      sources: [
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Run log read and ingest routes.' },
      ],
    },
    {
      id: 'system-logs',
      title: 'System logs',
      docType: 'how-to',
      audiences: ['operator', 'administrator'],
      summary: 'Live allow-listed platform container and pod logs, streamed over authenticated SSE.',
      keywords: ['system logs', 'sse', 'stream', 'tail', 'docker', 'kubernetes', 'runner logs'],
      keyFacts: [
        'Docker deployments read through the restricted socket proxy; Kubernetes deployments use read-only `pods` and `pods/log` RBAC.',
        'Installed runners appear as `runner:<runner-id>` sources while the runner remains in dispatcher status.',
        'A runner source is marked unavailable until the configured provider can reach the Docker host or an owned pod in the namespace the runner advertises.',
        'Discovery follows registered `docker_container_name`, `kubernetes_namespace`, `kubernetes_label_selector`, and `nopsai_platform_id` metadata.',
        'Removed runner registrations hide old runner logs even if their containers or pods still exist.',
        'Runner source labels overlay dispatcher connection health, so a ready pod can still show `dispatcher unreachable` or `recently reconnected`.',
      ],
      details: [
        'Hybrid deployments use comma-separated providers such as `docker,kubernetes`. Reading logs from the opposite runtime still requires the API to have matching Kubernetes RBAC or a restricted Docker endpoint.',
        '`NOPSAI_PLATFORM_ID` keeps bundled runners and generated runner installs on the same ownership boundary, which is what prevents one platform from listing another platform runner logs.',
        'Buffer size, age, tail limits, line size, and stream counts are all bounded by configuration so a log viewer cannot exhaust the API.',
      ],
      related: ['pipeline-logs', 'runners-and-dispatcher', 'networking-and-exposure'],
      sources: [
        { repositoryPath: 'doc/system-logs.md', purpose: 'Providers, SSE replay, AAA, redaction, limits, and monitoring.' },
        { repositoryPath: 'config/config.go', purpose: 'System logs provider and limit settings.' },
      ],
    },
    {
      id: 'monitoring',
      title: 'Monitoring and metrics',
      docType: 'reference',
      audiences: ['operator', 'administrator'],
      summary: 'Authorization-filtered analytics across runs, triggers, runners, AI usage, reliability, efficiency, and security.',
      keywords: ['monitoring', 'metrics', 'prometheus', 'analytics', 'alerts', 'recommendations'],
      keyFacts: [
        'Monitoring is authorization-filtered: you see the runs, pipelines, and resources you are allowed to see.',
        'Coverage spans runs, pipelines, steps, tasks, triggers, external triggers, runners, LLM usage, reliability, efficiency, and security.',
        '`GET /metrics` exposes Prometheus metrics including identity-provider capability and authorization grant ownership series.',
        'Metrics are public by default for scraper compatibility and can require bearer auth with `metrics_require_auth`.',
        'Alert rules can be created, evaluated on demand, and produce alert events.',
        'Recommendations can be acknowledged or resolved so the same finding does not resurface indefinitely.',
      ],
      details: [
        'AI usage telemetry records hashes, revision markers, cache and session identity, provider-state IDs and support, cached input tokens, cache-write tokens where providers expose them, and bounded workspace retrieval sizes — without storing prompt bodies.',
        'Saved monitoring views let a team keep a filter set rather than rebuilding it each time.',
      ],
      related: ['pipeline-runs', 'runners-and-dispatcher', 'analysis-reviewers', 'api-index'],
      sources: [
        { repositoryPath: 'services/nopsai/monitoring_analytics_schema.go', purpose: 'Analytics schema and filters.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'The monitoring route surface.' },
      ],
    },
    {
      id: 'analysis-reviewers',
      title: 'Analysis reviewers and AI Evaluation',
      docType: 'how-to',
      audiences: ['operator', 'automation-author'],
      summary: 'Read-only analysis of pipelines, runs, and resources, with an optional AI-reviewed health score.',
      keywords: ['analysis', 'health score', 'ai evaluation', 'analyse', 'review', 'findings'],
      keyFacts: [
        'The health score starts at 100 and subtracts weighted visible findings: critical ×25, high ×15, medium ×8, low ×3, opportunity ×1.',
        'Category scores use the same weights filtered to that category.',
        'A structured AI Evaluation can replace the displayed number with an AI-reviewed score.',
        'Analysis is read-only. Analyse Run never reruns a failed step; it opens existing logs and resources or copies the diagnosis until a user chooses a separate confirmed action.',
        'AI Evaluation uses the authenticated `POST /v1/analysis/evaluate` endpoint with a usable LLM profile, a redacted reviewer snapshot, and bounded page-owned evidence.',
        'It does not create an Assistant conversation and does not ask hosted MCP to inspect the pipeline, team, resource, or run.',
      ],
      details: [
        'Structured AI reviews are cached in browser-local review history by subject type, subject ID, and snapshot revision. Reopening the same analysis shows the reviewed score immediately.',
        'When only an older same-subject review exists, the modal labels it as a previous-snapshot score and asks you to regenerate for current evidence.',
        'Deterministic analysis still works when Assistant debugging or LLM profile access is unavailable — you lose the AI-reviewed score, not the findings.',
        'AI Evaluation selects the configured default from the unscoped Assistant profile picker and still sends the team and resource scope path to the evaluation endpoint for policy validation.',
      ],
      examples: [
        {
          title: 'Why the score moved',
          language: 'text',
          code: [
            'Base                      100',
            '2 critical findings       -50   (2 x 25)',
            '1 high finding            -15   (1 x 15)',
            '3 medium findings         -24   (3 x 8)',
            '                          ----',
            'Displayed health score      11',
          ].join('\n'),
        },
      ],
      related: ['pipeline-runs', 'llm-profiles', 'assistant', 'monitoring'],
      sources: [
        { repositoryPath: 'services/nopsai/analysis_evaluation_handlers.go', purpose: 'Evaluation endpoint, snapshot redaction, and policy validation.' },
        { repositoryPath: 'doc/feature-reference.md', purpose: 'Analysis reviewer behavior and scoring.' },
      ],
    },
    {
      id: 'dashboards',
      title: 'Team dashboards',
      docType: 'how-to',
      audiences: ['operator', 'automation-author', 'administrator'],
      summary: 'Team-owned dashboards fed by pipeline dashboard outputs, with publication history and scheduled refresh.',
      keywords: ['dashboard', 'chart', 'series', 'publication', 'refresh', 'sections', 'sources'],
      keyFacts: [
        'A dashboard has sections; pipeline `output` items publish entries into a named section.',
        'Publication modes are `replace` (default), `append`, `snapshot`, and `series`.',
        '`entry_key` is what lets `replace` and `series` find the same entry across runs; it defaults to the output item name.',
        'Source bindings connect a dashboard to the pipelines that feed it, which is what makes refresh possible.',
        'Refreshes can be scheduled, run on demand, canceled, and retried for only the failed parts.',
        'Creating a dashboard from the UI requires selecting at least one matching dashboard-output pipeline.',
      ],
      details: [
        'GitOps applies dependency roots before dependents, so team-owned dashboards and notification routes resolve their team paths before pipeline dashboard outputs attach to dashboards created in the same sync.',
        'Final-output rows for dashboard items can link directly to the configured dashboard and section when `dashboard_target` metadata is available.',
        '`ttl` marks an entry stale after a duration, which is how a dashboard shows "this number is old" rather than quietly presenting outdated state as current.',
      ],
      related: ['final-deliverables', 'gitops-and-config-repositories', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'doc/dashboards.md', purpose: 'Dashboard model, publication, history, source bindings, and scheduled refresh.' },
        { repositoryPath: 'services/nopsai/dashboard_schema.go', purpose: 'Dashboard, section, and publication schema.' },
      ],
    },
    {
      id: 'release-integrity',
      title: 'Release integrity and updates',
      docType: 'reference',
      audiences: ['administrator', 'operator'],
      summary: 'How releases are tagged and published, and how the CLI verifies what it downloads.',
      keywords: ['release', 'version', 'update', 'ghcr', 'checksum', 'compatibility', 'upgrade'],
      keyFacts: [
        '`scripts/release-tags.sh` publishes the stable tag set: exact version, `latest`, major, and major.minor.',
        'Container images and the Helm OCI chart publish all four aliases; installers keep exact versions in generated Compose, Helm values, and locks.',
        'CLI archives and `SHA256SUMS` publish to the `nopsai-cli` GHCR OCI package, which must be public so `nopsai update --version <x.y.z>` does not need repository release access.',
        '`nopsai update` downloads the exact OCI package archive and `SHA256SUMS`, verifies the checksum, then replaces the local binary.',
        '`release/compatibility.yaml` is read into buildinfo linker flags and Docker build args so binaries advertise the current platform, runner, API, and capability contract.',
        'Enterprise mirrors can override the package, repository, or asset base URL without changing the archive naming contract.',
      ],
      details: [
        'Multi-arch container builds carry `org.opencontainers.image.source` as both Dockerfile labels and OCI index/manifest annotations so GHCR can associate packages with the source repository. Already-created unlinked packages may still need a one-time settings connection or a delete and republish.',
        'The exact GitHub Release is marked latest, and moving `v<major>` and `v<major>.<minor>` release aliases carry compatibility copies of the same CLI assets.',
        'Repository-owned platform release automation lives in `.nopsai/nopsai-platform-release.yaml`.',
      ],
      related: ['deployment-models', 'cli', 'known-limits'],
      sources: [
        { repositoryPath: 'doc/release-bundles.md', purpose: 'Shared build identity, versioned assets, and GitOps release locks.' },
        { repositoryPath: 'release/compatibility.yaml', purpose: 'Platform, runner, API, and capability contract.' },
      ],
    },
  ],
};
