import { pickWikiFields } from '../fields/select.js';
import {
  dashboardOutputFields,
  finalOutputFields,
} from '../fields/output.js';
import { pipelineFields, pipelineStructuralLimits } from '../fields/pipeline.js';
import {
  approvalFields,
  stepCommonFields,
  stepModeFields,
  taskFields,
} from '../fields/step-task.js';
import type { WikiSection } from '../types.js';

/**
 * The pipeline chapter introduces one capability per page and grows a single
 * manifest, `release-service`, from a two-line script pipeline into the complete
 * example in examples/gitops-quickstart. Every page carries the manifest as it
 * stands at that point under the title "Pipeline so far", which is what makes
 * the chapter followable and what content.test.ts checks.
 */
export const pipelinesSection: WikiSection = {
  id: 'pipelines',
  title: 'Pipelines',
  owner: 'Automation platform',
  description:
    'Every pipeline capability, introduced one page at a time on a single manifest that grows from one script step into a full release pipeline.',
  articles: [
    {
      id: 'pipeline-anatomy',
      title: 'Pipeline anatomy',
      docType: 'reference',
      audiences: ['automation-author', 'new-user', 'developer'],
      summary:
        'The shape of a pipeline document: what it must declare, what it may declare, and what every step inherits from it.',
      keywords: ['pipeline', 'anatomy', 'schema', 'name', 'container_image', 'timeout', 'working_directory', 'version'],
      keyFacts: [
        '`name` and `steps` are the only unconditionally required top-level fields.',
        '`version` defaults to `latest`, and validation writes the resolved value back when it is omitted.',
        '`container_image` is the default image for every step; a step can override it, and a step that does not inherit this one.',
        '`working_directory` defaults to `/workspace`. Relative values are joined onto it and may not escape with `..`; the container root, NUL bytes, and any value containing `:` are rejected.',
        '`timeout` is a duration; without it the pipeline falls back to the configured `default_pipeline_timeout`.',
        '`runtime_pool` and `affinity_enabled` are placement hints resolved by the runner, not scheduling guarantees.',
        'A pipeline may declare at most 512 steps.',
      ],
      details: [
        'Read the top of a pipeline as its defaults block. Almost every top-level directive here is a value that steps and tasks inherit unless they say otherwise, which is why the later pages in this chapter mostly add overrides rather than new concepts.',
        'The chapter builds one manifest called `release-service`. Each page shows it as it stands, so the code block on any page is a complete, valid pipeline rather than a fragment. The finished version is checked into `examples/gitops-quickstart/team-repo/pipelines/platform/release-service.yaml`.',
        'A step still needs a mode — `script`, `goal`, `tasks`, `include`, or `approval` — before the pipeline is runnable. The next page starts there.',
      ],
      fields: [
        ...pickWikiFields(pipelineFields, ['name', 'version', 'description', 'container_image', 'working_directory', 'timeout', 'runtime_pool', 'affinity_enabled', 'steps']),
        ...pickWikiFields(pipelineStructuralLimits, ['steps (max per pipeline)']),
      ],
      examples: [
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
          ].join('\n'),
          expectedOutput:
            'A valid pipeline: one step, running `make build` in `alpine:3.20` under `/workspace`.',
        },
        {
          title: 'Rejected: a working directory that escapes the workspace',
          language: 'yaml',
          code: [
            'working_directory: ../etc',
          ].join('\n'),
          expectedOutput:
            'Validation rejects the value: relative paths are joined onto /workspace and may not escape it.',
        },
      ],
      related: ['script-steps', 'first-script-pipeline', 'directive-index'],
      sources: [
        { repositoryPath: 'pkg/models/model.go', purpose: 'Pipeline, step, and task field definitions.' },
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
      ],
    },
    {
      id: 'script-steps',
      title: 'Script steps',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary:
        'The simplest step mode: a shell script in a container, optionally with its own image and mounted storage.',
      keywords: ['script', 'step', 'shell', 'image', 'volumes', 'container'],
      keyFacts: [
        'A step needs exactly one mode. `script` cannot be combined with `goal`, `tasks`, `include`, or `approval`.',
        '`steps[].image` overrides the pipeline `container_image` for that step only.',
        '`steps[].volumes` mounts named Docker volumes or Kubernetes PVCs as `volume:/mount/path`; existing storage is reused and missing storage is created.',
        'Mounting the reserved runtime output path `/nopsai/outputs` is rejected, and a step may declare at most 32 volumes.',
        'A script step cannot define `mcp_profiles` — tools belong to LLM-backed work.',
        'With blocking guardrail or policy knowledge context in scope, the exact command is validated by the model before it executes.',
      ],
      details: [
        'Step names are how everything else refers to a step: dependencies, output references, and the run graph all use them. Choose names you are willing to see in a failure message.',
        'Volumes are how work survives between steps that do not share a container. The workspace itself is already shared for the whole run; a volume is for caches and artefacts you want to keep across runs.',
      ],
      fields: [
        ...pickWikiFields(stepModeFields, ['steps[].script']),
        ...pickWikiFields(stepCommonFields, ['steps[].name', 'steps[].image', 'steps[].volumes']),
        ...pickWikiFields(pipelineStructuralLimits, ['steps[].volumes (max per step)']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: verify',
            '    image: golang:1.24',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
          ].join('\n'),
          expectedOutput:
            'Two independent steps. Nothing orders them yet, so both are eligible to start at once.',
        },
        {
          title: 'Rejected: two modes on one step',
          language: 'yaml',
          code: [
            '  - name: verify',
            '    script: go test ./...',
            '    goal: Check the tests pass.',
          ].join('\n'),
          expectedOutput:
            'Validation rejects the step: `script` cannot be combined with `goal`.',
        },
      ],
      related: ['pipeline-anatomy', 'dependencies-and-parallelism', 'ai-steps'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'services/agent/internal/app/pipeline.go', purpose: 'Step execution and the reserved output mount.' },
      ],
    },
    {
      id: 'dependencies-and-parallelism',
      title: 'Dependencies and parallelism',
      docType: 'reference',
      audiences: ['automation-author', 'developer', 'operator'],
      summary:
        'How the graph is ordered, how a step splits into concurrent tasks, and where the structural limits are.',
      keywords: ['depends_on', 'graph', 'parallel', 'concurrency', 'tasks', 'dag', 'runtime_pool'],
      keyFacts: [
        'Steps run in dependency order, not list order. Independent branches run concurrently up to runner capacity.',
        '`depends_on` values are a step name or a qualified `step.task`; an undefined name fails validation.',
        'The full graph is cycle-checked, and a cycle reports the exact path.',
        '`tasks` turns one step into a sub-graph. Task names must be unique within the step, and a task depends on another task as `step.task` — a bare step name is not a valid task dependency.',
        'Limits: 512 steps, 256 tasks per step, 1024 tasks per pipeline, and 256 dependencies per node with 4096 across the pipeline.',
        '`runtime_pool` on a step overrides the pipeline pool, which is how one step can be placed on different capacity than the rest.',
      ],
      details: [
        'Two different things create concurrency. Independent steps run at the same time because nothing orders them; independent tasks inside one step run at the same time inside a single execution context, sharing the step image and environment.',
        'Reach for tasks when the work belongs together and shares setup — a batch of checks against one build — and for separate steps when the work has its own image, placement, or failure meaning.',
        'A dependency is a promise about ordering, not about data. Passing a value is a separate declaration, which the next page covers.',
      ],
      fields: [
        ...pickWikiFields(stepCommonFields, ['steps[].depends_on', 'steps[].runtime_pool']),
        ...pickWikiFields(stepModeFields, ['steps[].tasks']),
        ...pickWikiFields(taskFields, ['tasks[].name', 'tasks[].script', 'tasks[].depends_on']),
        ...pickWikiFields(pipelineStructuralLimits, ['steps[].tasks (max per step)', 'tasks (total)', 'depends_on (per node)', 'depends_on (total)']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        script: |',
            '          echo "checks complete"',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        script: |',
            '          echo "checks complete"',
          ].join('\n'),
          expectedOutput:
            '`build` runs first, then `verify`, then the `checks` step, whose `licenses` and `sbom` tasks run concurrently before `report`.',
        },
        {
          title: 'Rejected: a task depending on a bare step name',
          language: 'yaml',
          code: [
            '      - name: report',
            '        depends_on: [checks]',
          ].join('\n'),
          expectedOutput:
            'Validation rejects it: a task dependency must be qualified as `step.task`.',
        },
      ],
      related: ['script-steps', 'step-outputs', 'pipeline-runs'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'pkg/models/model.go', purpose: 'Pipeline, step, and task field definitions.' },
      ],
    },
    {
      id: 'step-outputs',
      title: 'Step outputs',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary:
        'How one step publishes a value and another consumes it, and the rules that make a reference valid.',
      keywords: ['outputs', 'runtime outputs', 'variables', 'sensitive', 'nopsai/outputs', 'pass value'],
      keyFacts: [
        'A producer writes a file under the reserved mount `/nopsai/outputs` whose name is exactly the output name, then declares it under `outputs`.',
        'Output names must match `^[A-Za-z_][A-Za-z0-9_]*$` and be unique within one producer.',
        'A consumer reads the value in `variables` as `$steps.<step>.outputs.<NAME>`, or `$steps.<step>.<task>.outputs.<NAME>` for a task producer. The reference must be the entire value.',
        'A dependency path to the producer is required, but a direct `depends_on` edge is not: a transitive path is enough.',
        'A missing file fails the step with `required output file /nopsai/outputs/<NAME> was not produced`.',
        'A step with `tasks` declares outputs on the tasks instead, and an approval step cannot declare outputs at all.',
        '`sensitive: true` masks the value wherever logs are rendered while still passing it downstream.',
      ],
      details: [
        'Validation separates three failure modes with different messages: referencing a producer that does not exist, referencing an output the producer never declared, and consuming an output with no dependency path. Read the message before rewriting the graph.',
        'Non-sensitive output values stay visible on purpose. Release evidence — versions, digests, image references — is meant to be reviewable after the fact.',
        '`RUNTIME_OUTPUT_MAX_BYTES` caps a single output value and defaults to 65536 bytes. A step cannot consume its own outputs, and neither can a task.',
      ],
      fields: [
        ...pickWikiFields(stepCommonFields, ['steps[].outputs', 'steps[].outputs[].sensitive', 'steps[].variables']),
        ...pickWikiFields(taskFields, ['tasks[].outputs', 'tasks[].variables']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: package',
            '    depends_on: [checks]',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
          ].join('\n'),
          expectedOutput:
            '`build` publishes `BUILD_TAG`, the `sbom` task publishes `SBOM_DIGEST`, and both are consumed downstream through a dependency path.',
        },
        {
          title: 'Rejected: a reference inside a larger string',
          language: 'yaml',
          code: [
            '    variables:',
            '      URL: "https://registry/$steps.build.outputs.BUILD_TAG"',
          ].join('\n'),
          expectedOutput:
            'Rejected: "uses a runtime output in an unsupported expression; use the full value $steps.<step>.<task>.outputs.<name>".',
        },
      ],
      limits: [
        'A runtime output reference is never a valid `depends_on` value.',
      ],
      related: ['dependencies-and-parallelism', 'pipeline-variables', 'first-script-pipeline'],
      sources: [
        { repositoryPath: 'pkg/models/runtime_outputs.go', purpose: 'Reference parsing for the short and long forms.' },
        { repositoryPath: 'services/agent/internal/app/runtime_outputs.go', purpose: 'Output collection and the missing-file failure.' },
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
      ],
    },
    {
      id: 'pipeline-variables',
      title: 'Variables and scopes',
      docType: 'reference',
      audiences: ['automation-author', 'administrator'],
      summary:
        'What a pipeline declares it needs, where those values resolve from, and how a scope decides the answer.',
      keywords: ['variables', 'scope', 'declaration', 'cross-scope', 'environment', 'resolution'],
      keyFacts: [
        'Pipeline `variables` is a declaration of what the run requires, not an assignment. Values resolve from the run scope.',
        'A declared variable that cannot be resolved fails the run before execution rather than starting with a missing value.',
        'A bare name resolves in the run scope; `scope/path:NAME` resolves in that scope and is injected under the bare name.',
        'Names must match `^[A-Za-z0-9_.-]+$`, and the same runtime name may not resolve from two different scopes in one place.',
        'Step `variables` apply to every task in the step; task `variables` are applied afterwards and win.',
        'Scope is not team path. Scope decides which values resolve; team path decides ownership and notification.',
      ],
      details: [
        'The two `variables` directives are different things that share a name. At the top level it is a list of requirements. On a step or task it is a map of assignments, which is also where runtime outputs are consumed.',
        'Cross-scope use is always explicit. Nothing resolves from another scope unless the reference says so, which keeps a pipeline honest about what it reaches for.',
        'A run can also override variables at start time, and the values a run actually resolved are visible on the run record, which is usually faster than reasoning about scope inheritance.',
      ],
      fields: pickWikiFields(pipelineFields, ['variables']),
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
          ].join('\n'),
          expectedOutput:
            '`RELEASE_CHANNEL` resolves in the run scope and `ARTIFACT_BUCKET` in `platform/shared`; both reach the step as plain environment variables.',
        },
        {
          title: 'Rejected: the same name from two scopes',
          language: 'yaml',
          code: [
            'variables:',
            '  - platform/shared:ARTIFACT_BUCKET',
            '  - platform/staging:ARTIFACT_BUCKET',
          ].join('\n'),
          expectedOutput:
            'Rejected: one runtime name may not resolve from two different scopes in the same place.',
        },
      ],
      related: ['step-outputs', 'pipeline-secrets', 'first-variables-and-secrets'],
      sources: [
        { repositoryPath: 'pkg/models/runtime_refs.go', purpose: 'Scoped reference parsing and name validation.' },
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
      ],
    },
    {
      id: 'pipeline-secrets',
      title: 'Secrets in steps',
      docType: 'reference',
      audiences: ['automation-author', 'security'],
      summary:
        'Declaring the credentials a step needs, and what the platform does with them.',
      keywords: ['secrets', 'credentials', 'masking', 'redaction', 'scope', 'security'],
      keyFacts: [
        'Secrets are declared per step, not per pipeline, so a credential is not injected into steps that have no use for it.',
        'A declared secret is injected as an environment variable under its bare name.',
        'Cross-scope references work exactly as they do for variables: `scope/path:NAME`.',
        'Declared secret values are masked in run logs.',
        'A stored secret value can be read back through `GET /v1/secrets/{name}`, but only by a caller holding `secret.read_value` on that secret. Treat that action as the sensitive one.',
        'The same runtime name may not resolve from two different scopes in one step.',
      ],
      details: [
        'Declaring a secret is an access statement. It is visible in review, it is auditable, and it is the thing a security reviewer reads to answer "what can this step reach?".',
        'For a secret that should live in Git rather than the database, encrypt it first through `POST /v1/secrets/encrypt`; the envelope is safe to commit and resolves at run time.',
        'Masking covers declared secrets and outputs marked sensitive. A value the pipeline constructs itself — a token pasted into a log line by a script — is not something the platform can know about.',
      ],
      fields: pickWikiFields(stepCommonFields, ['steps[].secrets']),
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
          ].join('\n'),
          expectedOutput:
            '`package` can sign and publish; the two values appear masked wherever the run logs are rendered.',
        },
        {
          title: 'Rejected: a secret name with an unsupported character',
          language: 'yaml',
          code: [
            '    secrets:',
            '      - registry/token',
          ].join('\n'),
          expectedOutput:
            'Rejected: names must match ^[A-Za-z0-9_.-]+$, and a `/` is read as a scope separator.',
        },
      ],
      related: ['pipeline-variables', 'credentials', 'first-variables-and-secrets'],
      sources: [
        { repositoryPath: 'pkg/models/runtime_refs.go', purpose: 'Scoped secret reference parsing.' },
        { repositoryPath: 'doc/credential-management.md', purpose: 'Encrypted registry, GitOps envelopes, rotation, and AAA.' },
      ],
    },
    {
      id: 'conditions-and-failure-handling',
      title: 'Conditions and failure handling',
      docType: 'reference',
      audiences: ['automation-author', 'operator'],
      summary:
        'Skipping work that does not apply, and deciding which failures should stop a run.',
      keywords: ['condition', 'ignore_failure', 'skip', 'warning', 'failure', 'guardrail'],
      keyFacts: [
        '`condition` is a natural-language question evaluated by the model against run context; it is rejected when `llm_enabled: false`.',
        'A false condition normally skips the step, but under blocking guardrail or policy context it fails closed instead.',
        '`ignore_failure` lets the graph continue past a failed step, and the run finishes `warning` rather than `failure`.',
        'Step `ignore_failure` also applies to every task in the step; a task can set its own.',
        'An ignored failure stays auditable as `failure (ignored)` — it is not hidden.',
        'Approval failures and explicit policy or guardrail enforcement failures still fail closed, whatever `ignore_failure` says.',
      ],
      details: [
        'These two directives answer different questions. `condition` asks whether the work applies to this run at all; `ignore_failure` asks whether the work failing should stop everything else.',
        '`warning` exists so a run that did its job but lost a best-effort side task is not reported the same way as a run that failed to build. Treat a `warning` run as a real signal, not a green one.',
        'Because a condition is model-evaluated, write it as a question about the run, not as an expression. "Only run when the changed files include a migration" is a condition; a boolean expression over variables is not what this directive is.',
      ],
      fields: [
        ...pickWikiFields(stepCommonFields, ['steps[].condition', 'steps[].ignore_failure']),
        ...pickWikiFields(taskFields, ['tasks[].ignore_failure']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
          ].join('\n'),
          expectedOutput:
            'A failing licence check or a failing announcement now leaves the run `warning`; everything else still fails the run.',
        },
        {
          title: 'Rejected: a condition with the LLM disabled',
          language: 'yaml',
          code: [
            'llm_enabled: false',
            'steps:',
            '  - name: announce',
            '    condition: Only run on the stable channel.',
            '    script: ./scripts/announce.sh',
          ].join('\n'),
          expectedOutput:
            'Rejected: `condition` requires an LLM-enabled pipeline.',
        },
      ],
      related: ['dependencies-and-parallelism', 'ai-steps', 'pipeline-runs'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'doc/runtime-flows.md', purpose: 'Step skipping, ignored failures, and run status resolution.' },
      ],
    },
    {
      id: 'display-options',
      title: 'Display options',
      docType: 'reference',
      audiences: ['automation-author', 'operator'],
      summary:
        'Choosing how a run presents itself, in the UI and in the Git check-run summary.',
      keywords: ['display_option', 'graph', 'list', 'presentation', 'check run', 'ui'],
      keyFacts: [
        '`display_option` accepts `list` or `graph`; any other value is rejected by validation.',
        'An empty or absent value falls back to `graph`.',
        'It selects which tab opens first in run detail; the other tabs stay reachable.',
        'The same value drives the git-bot GitHub check-run summary, so it changes what a reviewer sees on a pull request.',
      ],
      details: [
        'This is the smallest directive in the chapter and a good illustration of the rule the whole reference follows: a directive with a fixed set of values documents that set, and validation rejects everything else rather than silently falling back.',
        'Choose `list` for a long, mostly linear pipeline where the sequence matters, and `graph` when concurrency is the thing a reader needs to see.',
      ],
      fields: pickWikiFields(pipelineFields, ['display_option']),
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            'display_option: list',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
          ].join('\n'),
          expectedOutput:
            'Run detail opens on the list view, and the GitHub check-run summary renders the same way.',
        },
        {
          title: 'Rejected: an unsupported value',
          language: 'yaml',
          code: [
            'display_option: timeline',
          ].join('\n'),
          expectedOutput:
            'Rejected: `display_option must be "list" or "graph", got "timeline"`.',
        },
      ],
      related: ['pipeline-runs', 'git-triggers', 'pipeline-anatomy'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'services/git-bot/internal/checkrender/render.go', purpose: 'Check-run summary rendering for the selected display option.' },
      ],
    },
    {
      id: 'approvals',
      title: 'Approvals',
      docType: 'reference',
      audiences: ['automation-author', 'operator', 'security'],
      summary:
        'A durable human checkpoint in the middle of a run, and the rules that decide who may release it.',
      keywords: ['approval', 'gate', 'checkpoint', 'production-release', 'teams', 'timeout', 'self approval'],
      keyFacts: [
        'An approval step pauses the run and releases runner capacity rather than holding it, and it survives a control-plane restart.',
        '`approval` cannot be combined with `tasks`, `goal`, `script`, or `include`, and an approval step cannot declare outputs.',
        '`teams` names the teams whose members may decide; `allow_self_approval` decides whether the person who started the run may be one of them.',
        '`timeout` bounds the wait. An expired approval produces a `timed_out` run, not a failure.',
        'Approval failures always fail closed: `ignore_failure` does not apply to them.',
      ],
      details: [
        'The checkpoint is durable because it is a record, not a paused process. That is why capacity is released while it waits, and why a restart does not lose the pending decision.',
        'Put the gate where the risk changes. In this chapter it sits between packaging an artefact and promoting it, so everything reviewable has already happened and nothing irreversible has.',
        'Who may approve is an authorization question, resolved through AAA against the named teams. The directive narrows the set; it does not grant anyone the right to decide.',
      ],
      fields: [
        ...pickWikiFields(stepModeFields, ['steps[].approval']),
        ...pickWikiFields(approvalFields, ['steps[].approval.type', 'steps[].approval.teams', 'steps[].approval.allow_self_approval', 'steps[].approval.timeout']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
          ].join('\n'),
          expectedOutput:
            'The run pauses before `publish` until a member of `platform/sre` approves, or 24 hours pass and the run ends `timed_out`.',
        },
        {
          title: 'Rejected: an approval step that also runs something',
          language: 'yaml',
          code: [
            '  - name: production-gate',
            '    approval:',
            '      type: production-release',
            '    script: ./scripts/promote.sh',
          ].join('\n'),
          expectedOutput:
            'Rejected: `approval` cannot be combined with `script`.',
        },
      ],
      related: ['conditions-and-failure-handling', 'access-control', 'pipeline-runs'],
      sources: [
        { repositoryPath: 'services/nopsai/approval_schema.go', purpose: 'Approval document schema and decision handling.' },
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
      ],
    },
    {
      id: 'ai-steps',
      title: 'AI steps',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary:
        'Replacing a script with a goal, and choosing the model that pursues it.',
      keywords: ['goal', 'llm', 'model', 'ai step', 'agent', 'llm_enabled'],
      keyFacts: [
        '`goal` is the LLM-backed step mode. It cannot be combined with `script`, `tasks`, `include`, or `approval`.',
        '`llm_enabled` defaults to `true`. Setting it to `false` bans `output.items`, every step `condition`, every `goal`, and any script carrying blocking guardrail or policy knowledge context.',
        '`model` resolves in order: task, step, pipeline, configured default.',
        'The named model must be configured and allowed in the run scope; AAA decides whether the caller may use it.',
        'A goal runs inside the per-run agent. There is no always-on LLM service, and the agent calls the provider the resolved model names.',
        'A task can carry a goal too, so one step can mix deterministic and model-driven work across its tasks.',
      ],
      details: [
        'A goal is a statement of intent with a definition of done, not a prompt fragment. "Read the commits since the last tag and write release notes to /workspace/NOTES.md" tells the agent what to read, what to produce, and where to put it.',
        'The workspace is the interface. A goal step reads and writes the same `/workspace` the script steps use, which is why an LLM step can sit in the middle of a deterministic pipeline without special plumbing.',
        'Model selection is a governance decision as much as a quality one. Naming a model in the pipeline makes it reviewable, and the scope check makes it enforceable.',
      ],
      fields: [
        ...pickWikiFields(pipelineFields, ['llm_enabled', 'model']),
        ...pickWikiFields(stepModeFields, ['steps[].goal']),
        ...pickWikiFields(stepCommonFields, ['steps[].model']),
        ...pickWikiFields(taskFields, ['tasks[].goal', 'tasks[].model']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            'llm_enabled: true',
            'model: reasoning-large',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'llm_enabled: true',
            'model: reasoning-large',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: risk-review',
            '        depends_on: [checks.sbom]',
            '        goal: Review the changed files and list the risks this release carries.',
            '        model: reasoning-large',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
          ].join('\n'),
          expectedOutput:
            'One model-driven task inside `checks` and one model-driven step after `publish`, both resolving to `reasoning-large`.',
        },
        {
          title: 'Rejected: a goal with the LLM disabled',
          language: 'yaml',
          code: [
            'llm_enabled: false',
            'steps:',
            '  - name: release-notes',
            '    goal: Write the release notes.',
          ].join('\n'),
          expectedOutput:
            'Rejected: `goal` requires an LLM-enabled pipeline.',
        },
      ],
      related: ['ai-context-and-tools', 'models', 'conditions-and-failure-handling'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'doc/llm-model-selection.md', purpose: 'Model resolution and provider selection.' },
      ],
    },
    {
      id: 'ai-context-and-tools',
      title: 'Agent roles, knowledge, and tools',
      docType: 'reference',
      audiences: ['automation-author', 'security', 'administrator'],
      summary:
        'The four separate controls over LLM behaviour: who it acts as, what it knows, what tools it may reach, and what may block it.',
      keywords: ['agent_role', 'knowledge_context', 'mcp_profiles', 'governance_level', 'guardrail', 'policy', 'llm_content'],
      keyFacts: [
        'The controls are independent. `agent_role` is persona and behaviour, `knowledge_context` is what the model is told, `mcp_profiles` is which tools it may call, and `governance_level` decides how hard a guardrail bites.',
        'Pipeline, step, and task MCP profiles are additive and deduplicated, not overriding, and pipeline YAML cannot declare arbitrary MCP server URLs.',
        '`governance_level` accepts `advisory` or `strict` and defaults to `strict`; a task falls back to the step, then the pipeline.',
        'Knowledge context is merged across pipeline, step, and task rather than replaced, and `guardrail` and `policy` entries also validate direct scripts before execution.',
        '`agent_role` cannot be set on a task: parsing fails with `task "<name>" cannot define agent_role; set agent_role on the pipeline or step`.',
        '`llm_content_preload` is a prompt-size and cost control, not a permission. Use `llm_content_include` and `llm_content_ignore` to shape what the retrieval tools can reach.',
        'Every referenced profile must exist, be enabled, and be allowed in the run scope.',
      ],
      details: [
        'Read these directives as four questions with four answers. Conflating them is the usual source of surprise: raising the governance level does not change which tools are available, and adding a knowledge document does not change who the agent is acting as.',
        'Because MCP profiles are additive, a step cannot narrow what the pipeline already granted. Narrowing is a configuration decision made where the profile is defined, not in the manifest.',
        '`llm_content_preload: false` means the model receives no unrequested file dump, but bounded workspace tools can still retrieve files on demand. Files that must stay out of reach belong in `llm_content_ignore`, because that shapes the index the retrieval tools read from.',
        'Shared and retrieved files carry path, SHA-256, size, and workspace revision metadata, so a file replaced mid-run is rejected rather than silently used.',
      ],
      fields: [
        ...pickWikiFields(pipelineFields, ['agent_role', 'mcp_profiles', 'governance_level', 'knowledge_context', 'llm_content_preload', 'llm_content_include', 'llm_content_ignore']),
        ...pickWikiFields(stepCommonFields, ['steps[].agent_role', 'steps[].mcp_profiles', 'steps[].governance_level', 'steps[].knowledge_context']),
        ...pickWikiFields(taskFields, ['tasks[].agent_role', 'tasks[].mcp_profiles', 'tasks[].governance_level', 'tasks[].knowledge_context']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            'agent_role: senior-release-engineer',
            'governance_level: strict',
            'mcp_profiles:',
            '  - jira-readonly',
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            'llm_content_preload: false',
            'llm_content_include:',
            '  - "src/**/*.go"',
            'llm_content_ignore:',
            '  - "**/testdata/**"',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'llm_enabled: true',
            'model: reasoning-large',
            'agent_role: senior-release-engineer',
            'governance_level: strict',
            'mcp_profiles:',
            '  - jira-readonly',
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            'llm_content_preload: false',
            'llm_content_include:',
            '  - "src/**/*.go"',
            'llm_content_ignore:',
            '  - "**/testdata/**"',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: build',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: risk-review',
            '        depends_on: [checks.sbom]',
            '        goal: Review the changed files and list the risks this release carries.',
            '        model: reasoning-large',
            '        governance_level: advisory',
            '        mcp_profiles:',
            '          - jira-readonly',
            '        knowledge_context:',
            '          - kind: example',
            '            path: .nopsai/docs/risk-review-example.md',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
            '    agent_role: release-writer',
            '    governance_level: advisory',
            '    mcp_profiles:',
            '      - github-readonly',
            '    knowledge_context:',
            '      - kind: policy',
            '        ref: platform/release-notes',
            '        required: true',
          ].join('\n'),
          expectedOutput:
            'Both model-driven units inherit the pipeline guardrail and tool set, and each narrows its own governance level and knowledge.',
        },
        {
          title: 'Rejected: an agent role on a task',
          language: 'yaml',
          code: [
            '      - name: risk-review',
            '        goal: Review the changed files.',
            '        agent_role: reviewer',
          ].join('\n'),
          expectedOutput:
            'Rejected during unmarshaling: `task "risk-review" cannot define agent_role; set agent_role on the pipeline or step`.',
        },
      ],
      related: ['ai-steps', 'agent-roles', 'knowledge-context', 'mcp', 'governance-and-policy'],
      sources: [
        { repositoryPath: 'pkg/models/model.go', purpose: 'Pipeline, step, and task field definitions.' },
        { repositoryPath: 'doc/knowledge-context.md', purpose: 'Knowledge document kinds, merging, and runtime snapshots.' },
        { repositoryPath: 'doc/mcp-pipeline-integration.md', purpose: 'Profile resolution and tool-call boundaries.' },
      ],
    },
    {
      id: 'reuse-and-children',
      title: 'Reusable steps and child pipelines',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary:
        'Pulling in a shared step definition, and launching another pipeline as part of this one.',
      keywords: ['include', 'reusable step', 'child pipeline', 'sync', 'composition', 'reuse'],
      keyFacts: [
        '`include: step:<identifier>` expands a reusable step definition in place; `include: pipeline:<identifier>` launches a child pipeline.',
        '`include` cannot be combined with `tasks`, `goal`, `script`, or `approval`, and an included step cannot define `mcp_profiles`.',
        'Only a `pipeline:` include may declare parent-visible `outputs`, and only with `sync: true`.',
        '`sync: true` makes the parent wait for the child; without it the child runs independently.',
        'A child pipeline is a real run with its own record, so it carries its own logs, approvals, and history.',
      ],
      details: [
        'Reusable steps are for the work every pipeline repeats — checkout, setup, a standard scan — kept in one definition so a fix lands everywhere. Child pipelines are for work that has its own lifecycle and deserves its own run record.',
        'The `sync` rule follows from that: a value can only cross the boundary if the parent actually waited for it. Declaring outputs on an async child would be a promise the graph cannot keep.',
        'Because a child is its own run, it resolves its own scope and its own access checks. Including a pipeline does not lend it the parent caller’s permissions.',
      ],
      fields: pickWikiFields(stepModeFields, ['steps[].include', 'steps[].sync']),
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            '  - name: checkout',
            '    include: step:platform/shared/checkout',
            '',
            '  - name: deploy',
            '    depends_on: [publish]',
            '    include: pipeline:platform/deploy-service',
            '    sync: true',
            '    outputs:',
            '      - name: DEPLOY_ID',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'llm_enabled: true',
            'model: reasoning-large',
            'agent_role: senior-release-engineer',
            'governance_level: strict',
            'mcp_profiles:',
            '  - jira-readonly',
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            'llm_content_preload: false',
            'llm_content_include:',
            '  - "src/**/*.go"',
            'llm_content_ignore:',
            '  - "**/testdata/**"',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: checkout',
            '    include: step:platform/shared/checkout',
            '',
            '  - name: build',
            '    depends_on: [checkout]',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: risk-review',
            '        depends_on: [checks.sbom]',
            '        goal: Review the changed files and list the risks this release carries.',
            '        model: reasoning-large',
            '        governance_level: advisory',
            '        mcp_profiles:',
            '          - jira-readonly',
            '        knowledge_context:',
            '          - kind: example',
            '            path: .nopsai/docs/risk-review-example.md',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
            '    agent_role: release-writer',
            '    governance_level: advisory',
            '    mcp_profiles:',
            '      - github-readonly',
            '    knowledge_context:',
            '      - kind: policy',
            '        ref: platform/release-notes',
            '        required: true',
            '',
            '  - name: deploy',
            '    depends_on: [publish]',
            '    include: pipeline:platform/deploy-service',
            '    sync: true',
            '    outputs:',
            '      - name: DEPLOY_ID',
          ].join('\n'),
          expectedOutput:
            'The shared checkout step runs first, and the deployment runs as its own child run whose `DEPLOY_ID` comes back to the parent.',
        },
        {
          title: 'Rejected: child outputs without sync',
          language: 'yaml',
          code: [
            '  - name: deploy',
            '    include: pipeline:platform/deploy-service',
            '    outputs:',
            '      - name: DEPLOY_ID',
          ].join('\n'),
          expectedOutput:
            'Rejected: a `pipeline:` include may only declare outputs with `sync: true`.',
        },
      ],
      related: ['step-outputs', 'dependencies-and-parallelism', 'gitops-and-config-repositories'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Rules the validator enforces on this directive set.' },
        { repositoryPath: 'doc/runtime-flows.md', purpose: 'Child pipeline launch, synchronisation, and output resolution.' },
      ],
    },
    {
      id: 'final-deliverables',
      title: 'Final deliverables',
      docType: 'reference',
      audiences: ['automation-author', 'operator'],
      summary:
        'What the run produces for people to read after the work is done, including dashboard publications.',
      keywords: ['output', 'deliverable', 'markdown', 'pdf', 'excel', 'json', 'html', 'dashboard', 'publication'],
      keyFacts: [
        'The `output` block runs after execution finishes, so it can describe what happened, including failures.',
        '`output.items[].type` accepts `markdown`, `pdf`, `excel`, `json`, `html`, or `dashboard`.',
        '`when` accepts `always`, `success`, or `failure` and defaults to `always`.',
        'The whole `output` block is rejected when `llm_enabled: false`, because deliverables are generated.',
        'A `dashboard` item needs a `dashboard` block; `mode` accepts `replace`, `append`, `snapshot`, or `series`, and defaults to `replace`.',
        'Deliverables are stored separately from raw task logs, and run list surfaces expose only an aggregate `final_output_status`.',
      ],
      details: [
        'Think of deliverables as the audience-facing half of a run. The logs are for whoever is debugging; the deliverable is for whoever needs to know what shipped, and it is the artefact that survives into a review.',
        'A failed run can still produce a deliverable. `when: failure` is how a pipeline explains itself to the person who did not watch it run.',
        'Dashboard publication turns a run into a data point rather than a document: `series` accumulates entries over time under an entry key, while `replace` keeps only the current state.',
        'Generation can be retried and cancelled per item without re-running the pipeline, which matters when a renderer, not the work, is what failed.',
      ],
      fields: [
        ...pickWikiFields(pipelineFields, ['output']),
        ...pickWikiFields(finalOutputFields, ['output.model', 'output.items[].name', 'output.items[].type', 'output.items[].when', 'output.items[].prompt', 'output.items[].model']),
        ...pickWikiFields(dashboardOutputFields, ['output.items[].dashboard.ref', 'output.items[].dashboard.section', 'output.items[].dashboard.entry_key', 'output.items[].dashboard.mode', 'output.items[].dashboard.preset', 'output.items[].dashboard.ttl']),
      ],
      examples: [
        {
          title: 'What this page adds',
          language: 'yaml',
          code: [
            'output:',
            '  model: reasoning-large',
            '  items:',
            '    - name: Release summary',
            '      type: markdown',
            '      when: always',
            '      prompt: Summarize the release, its approvals, and anything that failed.',
            '      model: reasoning-large',
            '    - name: Release health',
            '      type: dashboard',
            '      when: success',
            '      prompt: Publish the release health entry for this service.',
            '      dashboard:',
            '        ref: platform/service-health',
            '        section: releases',
            '        entry_key: payments',
            '        mode: series',
            '        preset: metrics',
            '        ttl: 30d',
          ].join('\n'),
        },
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'llm_enabled: true',
            'model: reasoning-large',
            'agent_role: senior-release-engineer',
            'governance_level: strict',
            'mcp_profiles:',
            '  - jira-readonly',
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            'llm_content_preload: false',
            'llm_content_include:',
            '  - "src/**/*.go"',
            'llm_content_ignore:',
            '  - "**/testdata/**"',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: checkout',
            '    include: step:platform/shared/checkout',
            '',
            '  - name: build',
            '    depends_on: [checkout]',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: risk-review',
            '        depends_on: [checks.sbom]',
            '        goal: Review the changed files and list the risks this release carries.',
            '        model: reasoning-large',
            '        governance_level: advisory',
            '        mcp_profiles:',
            '          - jira-readonly',
            '        knowledge_context:',
            '          - kind: example',
            '            path: .nopsai/docs/risk-review-example.md',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
            '    agent_role: release-writer',
            '    governance_level: advisory',
            '    mcp_profiles:',
            '      - github-readonly',
            '    knowledge_context:',
            '      - kind: policy',
            '        ref: platform/release-notes',
            '        required: true',
            '',
            '  - name: deploy',
            '    depends_on: [publish]',
            '    include: pipeline:platform/deploy-service',
            '    sync: true',
            '    outputs:',
            '      - name: DEPLOY_ID',
            '',
            'output:',
            '  model: reasoning-large',
            '  items:',
            '    - name: Release summary',
            '      type: markdown',
            '      when: always',
            '      prompt: Summarize the release, its approvals, and anything that failed.',
            '      model: reasoning-large',
            '    - name: Release health',
            '      type: dashboard',
            '      when: success',
            '      prompt: Publish the release health entry for this service.',
            '      dashboard:',
            '        ref: platform/service-health',
            '        section: releases',
            '        entry_key: payments',
            '        mode: series',
            '        preset: metrics',
            '        ttl: 30d',
          ].join('\n'),
          expectedOutput:
            'Every run produces a Markdown summary, and a successful run also appends a point to the service health dashboard.',
        },
        {
          title: 'Rejected: a deliverable with the LLM disabled',
          language: 'yaml',
          code: [
            'llm_enabled: false',
            'output:',
            '  items:',
            '    - name: Summary',
            '      type: markdown',
            '      prompt: Summarize the run.',
          ].join('\n'),
          expectedOutput:
            'Rejected: `output.items` requires an LLM-enabled pipeline.',
        },
      ],
      related: ['dashboards', 'ai-steps', 'complete-manifest'],
      sources: [
        { repositoryPath: 'services/nopsai/pipeline_final_output_specs.go', purpose: 'Item specification, types, and generation contract.' },
        { repositoryPath: 'doc/final-output-rendering.md', purpose: 'Renderers, retry and audit behavior.' },
      ],
    },
    {
      id: 'complete-manifest',
      title: 'The complete manifest',
      docType: 'reference',
      audiences: ['automation-author', 'developer', 'operator'],
      summary:
        'Every capability in this chapter assembled into one pipeline, with the reference tables that carry the rest.',
      keywords: ['complete', 'full example', 'assembled', 'release-service', 'reference', 'summary'],
      keyFacts: [
        'This manifest is the accumulation of every page in the chapter, and it is checked into `examples/gitops-quickstart/team-repo/pipelines/platform/release-service.yaml`.',
        'Every stage of it validates: the repository test suite runs the example through the same `ValidatePipeline` the API uses.',
        'Nothing here is new. Each directive was introduced on exactly one earlier page, which is what the directive index is built from.',
        'For the exhaustive tables — every directive, every allowed value, every constraint — use **All YAML directives** in Reference.',
      ],
      details: [
        'Read this page as a check on your own model of the product: for each block, you should be able to name which page introduced it and what rule constrains it.',
        'The pipeline is deliberately ordinary. It builds, verifies, runs checks concurrently, packages with a secret, waits for a human, publishes, delegates a deployment to a child pipeline, and explains itself afterwards. That is the shape most real pipelines converge on.',
        'To run it as-is you need the referenced resources to exist: the `platform/shared/checkout` reusable step, the `platform/deploy-service` pipeline, a `platform/service-health` dashboard, the named models and profiles, and the scope holding `RELEASE_CHANNEL`, `ARTIFACT_BUCKET`, `REGISTRY_TOKEN`, and `SIGNING_KEY`.',
      ],
      examples: [
        {
          title: 'Pipeline so far',
          language: 'yaml',
          code: [
            'name: release-service',
            'description: Build, verify, and publish the payments service.',
            'container_image: alpine:3.20',
            'working_directory: /workspace',
            'timeout: 45m',
            'display_option: list',
            'llm_enabled: true',
            'model: reasoning-large',
            'agent_role: senior-release-engineer',
            'governance_level: strict',
            'mcp_profiles:',
            '  - jira-readonly',
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            'llm_content_preload: false',
            'llm_content_include:',
            '  - "src/**/*.go"',
            'llm_content_ignore:',
            '  - "**/testdata/**"',
            'variables:',
            '  - RELEASE_CHANNEL',
            '  - platform/shared:ARTIFACT_BUCKET',
            'steps:',
            '  - name: checkout',
            '    include: step:platform/shared/checkout',
            '',
            '  - name: build',
            '    depends_on: [checkout]',
            '    script: |',
            '      make build',
            '      echo "1.0.$(date +%s)" > /nopsai/outputs/BUILD_TAG',
            '    outputs:',
            '      - name: BUILD_TAG',
            '',
            '  - name: verify',
            '    image: golang:1.24',
            '    depends_on: [build]',
            '    runtime_pool: ci',
            '    volumes:',
            '      - build-cache:/root/.cache',
            '    script: |',
            '      go vet ./...',
            '      go test ./...',
            '',
            '  - name: checks',
            '    depends_on: [verify]',
            '    tasks:',
            '      - name: licenses',
            '        ignore_failure: true',
            '        script: |',
            '          ./scripts/license-check.sh',
            '      - name: sbom',
            '        script: |',
            '          ./scripts/sbom.sh > /workspace/sbom.json',
            '          sha256sum /workspace/sbom.json | cut -d\' \' -f1 > /nopsai/outputs/SBOM_DIGEST',
            '        outputs:',
            '          - name: SBOM_DIGEST',
            '      - name: risk-review',
            '        depends_on: [checks.sbom]',
            '        goal: Review the changed files and list the risks this release carries.',
            '        model: reasoning-large',
            '        governance_level: advisory',
            '        mcp_profiles:',
            '          - jira-readonly',
            '        knowledge_context:',
            '          - kind: example',
            '            path: .nopsai/docs/risk-review-example.md',
            '      - name: report',
            '        depends_on: [checks.licenses, checks.sbom]',
            '        variables:',
            '          SBOM_DIGEST: $steps.checks.sbom.outputs.SBOM_DIGEST',
            '        script: |',
            '          echo "checks complete"',
            '          echo "sbom $SBOM_DIGEST"',
            '',
            '  - name: package',
            '    depends_on: [checks]',
            '    secrets:',
            '      - REGISTRY_TOKEN',
            '      - platform/shared:SIGNING_KEY',
            '    variables:',
            '      BUILD_TAG: $steps.build.outputs.BUILD_TAG',
            '    script: |',
            '      ./scripts/package.sh "$BUILD_TAG"',
            '      echo "channel $RELEASE_CHANNEL, bucket $ARTIFACT_BUCKET"',
            '      ./scripts/mint-token.sh > /nopsai/outputs/PUBLISH_TOKEN',
            '      ./scripts/sign.sh --key "$SIGNING_KEY" --token "$REGISTRY_TOKEN"',
            '    outputs:',
            '      - name: PUBLISH_TOKEN',
            '        sensitive: true',
            '',
            '  - name: announce',
            '    depends_on: [package]',
            '    condition: Only run when the release channel is stable.',
            '    ignore_failure: true',
            '    script: |',
            '      ./scripts/announce.sh',
            '',
            '  - name: production-gate',
            '    depends_on: [package]',
            '    approval:',
            '      type: production-release',
            '      teams:',
            '        - platform/sre',
            '      allow_self_approval: false',
            '      timeout: 24h',
            '',
            '  - name: publish',
            '    depends_on: [production-gate]',
            '    script: |',
            '      ./scripts/promote.sh',
            '',
            '  - name: release-notes',
            '    depends_on: [publish]',
            '    goal: Read the commits since the last tag and write release notes to /workspace/NOTES.md.',
            '    model: reasoning-large',
            '    agent_role: release-writer',
            '    governance_level: advisory',
            '    mcp_profiles:',
            '      - github-readonly',
            '    knowledge_context:',
            '      - kind: policy',
            '        ref: platform/release-notes',
            '        required: true',
            '',
            '  - name: deploy',
            '    depends_on: [publish]',
            '    include: pipeline:platform/deploy-service',
            '    sync: true',
            '    outputs:',
            '      - name: DEPLOY_ID',
            '',
            'output:',
            '  model: reasoning-large',
            '  items:',
            '    - name: Release summary',
            '      type: markdown',
            '      when: always',
            '      prompt: Summarize the release, its approvals, and anything that failed.',
            '      model: reasoning-large',
            '    - name: Release health',
            '      type: dashboard',
            '      when: success',
            '      prompt: Publish the release health entry for this service.',
            '      dashboard:',
            '        ref: platform/service-health',
            '        section: releases',
            '        entry_key: payments',
            '        mode: series',
            '        preset: metrics',
            '        ttl: 30d',
          ].join('\n'),
          expectedOutput:
            'The finished chapter manifest, valid against the pipeline validator.',
          validationCommand: 'curl -sX POST http://localhost:8080/v1/pipelines/validate -H "Authorization: Bearer $NOPSAI_TOKEN" -H "Content-Type: application/yaml" --data-binary @release-service.yaml',
        },
      ],
      related: ['directive-index', 'final-deliverables', 'first-script-pipeline', 'gitops-and-config-repositories'],
      sources: [
        { repositoryPath: 'examples/gitops-quickstart/team-repo/pipelines/platform/release-service.yaml', purpose: 'The assembled manifest as a runnable example.' },
        { repositoryPath: 'examples_pipeline_validation_test.go', purpose: 'Test that validates every example pipeline against the pipeline validator.' },
      ],
    },
  ],
};
