import {
  agentProfileFields,
  governanceLevels,
  knowledgeFields,
  llmProfileFields,
  mcpProfileFields,
  mcpServerFields,
} from '../fields/ai.js';
import {
  allEnvironmentFields,
  authEnvironmentFields,
  runnerEnvironmentFields,
} from '../fields/environment.js';
import type { WikiSection } from '../types.js';

export const platformSection: WikiSection = {
  id: 'platform',
  title: 'Platform',
  owner: 'Platform engineering',
  description: 'Installing, configuring, and owning the platform: deployment shapes, runners, networking, storage, GitOps authority, teams, access, and credentials.',
  articles: [
    {
      id: 'control-execution-plane',
      title: 'Control plane and execution plane',
      docType: 'concept',
      audiences: ['administrator', 'operator', 'developer'],
      summary:
        'The API, AAA, dispatcher, git-bot, UI, PostgreSQL, Gotenberg, and socket proxy form the control plane; runners and per-run agents form the execution plane.',
      keywords: ['architecture', 'components', 'services', 'topology'],
      keyFacts: [
        '`nopsai-api` owns REST APIs, validation, orchestration, setup, monitoring, credentials, notifications, GitOps, auth integration, and run records.',
        '`aaa` owns authorization decisions, policy checks, ACL expansion, filtering, and decision audit records.',
        '`dispatcher` owns runner registration, queueing, routing, capacity selection, and job assignment over gRPC.',
        '`git-bot` owns GitHub App webhooks, repository access, check runs, and GitHub-specific integration.',
        'Runners start one agent per assigned run; the agent then starts step containers or pods and reports status back.',
        'Gotenberg renders PDF final outputs. The Docker socket proxy exposes only the allow-listed reads System Logs needs.',
      ],
      details: [
        'The API submits jobs to the dispatcher. Runners hold long-lived outbound connections to the dispatcher, which keeps registration and capacity visible to the control plane without inbound access to the runner.',
        'Docker runners create containers and named Docker volumes. Kubernetes runners create an agent pod, a PVC-backed workspace, and step pods in their namespace.',
        'UI and CLI are entry points only. They call authenticated REST routes and never talk directly to AAA, the dispatcher, PostgreSQL, or runners.',
        'During cold starts, setup preflight keeps `/healthz` unready while retrying a database that is still starting. `/livez` stays process-alive, and normal API startup resumes automatically once PostgreSQL is reachable.',
      ],
      examples: [
        {
          title: 'Component topology',
          language: 'text',
          code: [
            'ENTRY POINTS',
            '  browser · CLI · API clients            git providers',
            '            │                                 │',
            '            │ authenticated REST              │ signed webhooks',
            '            │                                 ▼',
            '            │                              git-bot',
            '            └───────────────┬─────────────────┘',
            '                            ▼',
            '───────────────────────────────────────────────────────────',
            'DURABLE CONTROL PLANE',
            '                       nopsai API ◀────▶ aaa',
            '                            │',
            '           ┌────────────────┼──────────────────┐',
            '           ▼                ▼                  ▼',
            '      PostgreSQL       gotenberg      docker-socket-proxy',
            '     durable state     PDF outputs    allow-listed reads',
            '───────────────────────────────────────────────────────────',
            '                            │ SubmitJob gRPC',
            '                            ▼',
            'EPHEMERAL EXECUTION PLANE',
            '                       dispatcher',
            '                          ▲   │',
            '        runner dials out ─┘   │ assigns runs over that stream',
            '                              ▼',
            '                           runner',
            '                              │ starts one agent per run',
            '                              ▼',
            '                           agent ────▶ step containers or pods',
            '                              │',
            '                              ├───────▶ LLM providers',
            '                              └───────▶ MCP servers',
            '───────────────────────────────────────────────────────────',
          ].join('\n'),
          expectedOutput:
            'The dashed direction matters: the runner opens the stream to the dispatcher, so a runner never needs inbound network access.',
        },
      ],
      limits: [
        'Kubernetes emptyDir is not used for shared run workspaces; the agent owns a PVC instead.',
        'Docker runners ignore Kubernetes runtime pools and affinity settings.',
      ],
      related: ['run-lifecycle', 'runners-and-dispatcher', 'helm-kubernetes'],
      sources: [
        { repositoryPath: 'doc/service-reference.md', purpose: 'What each service owns and which files to read.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'The REST surface the control plane exposes.' },
      ],
    },
    {
      id: 'deployment-models',
      title: 'Supported deployment models',
      docType: 'concept',
      audiences: ['administrator', 'operator'],
      summary: 'Four shapes the platform is built for, and what each one implies for runtime and database.',
      keywords: ['deployment', 'compose', 'helm', 'kubernetes', 'bundle', 'hybrid', 'topology'],
      keyFacts: [
        '**Docker Compose** — development, demos, evaluation, and small single-host installs. Docker runner, bundled PostgreSQL 15.',
        '**Release bundle** — version-pinned single-host deployment. Docker runner, deployment-managed PostgreSQL.',
        '**Helm / Kubernetes** — cluster production deployment. Kubernetes runner, bundled or external PostgreSQL.',
        '**Hybrid runners** — one central control plane with remote Docker or Kubernetes runners. Control-plane PostgreSQL.',
        'The Helm chart deploys PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, and the Kubernetes runner.',
      ],
      details: [
        'Install the CLI from `https://github.com/nopsai/nopsai/releases/latest`, extract the binary onto `PATH`, and remove the archive before running install commands. `nopsai install kubernetes` generates non-secret Helm values, an `installation.md`, and a separate Secret manifest for new installations. Values and locks are GitOps-friendly; apply the Secret manifest directly for a first install, or seal and encrypt it before it enters GitOps.',
        'Managed PostgreSQL is supported by disabling the bundled StatefulSet and replacing the generated database URL.',
        '`topology.dispatcherGRPCAddress` controls the dispatcher endpoint injected into API and Kubernetes runner pods, and the same topology block carries the internal NopsAI, AAA, git-bot, and Gotenberg service URLs for custom DNS or split-service deployments.',
      ],
      limits: [
        'There are no Terraform modules and no AWS-, Azure-, or Google-specific deployment automation in this repository.',
        'Raising every replica count does not by itself produce a highly available deployment.',
      ],
      examples: [
        {
          title: 'Identify what an install actually is',
          language: 'bash',
          code: [
            'curl -s "$NOPSAI_URL/version" | jq \'{product_version, api_version, runner_protocol_version}\'',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/dispatcher" | jq \'.runners | length\'',
          ].join('\n'),
          expectedOutput:
            'Build identity plus the number of registered runners: enough to tell a single-host evaluation from a deployment with a separate execution plane.',
        },
      ],
      related: ['docker-compose', 'helm-kubernetes', 'environment-reference', 'runners-and-dispatcher'],
      sources: [
        { repositoryPath: 'deploy/helm/nopsai/values.yaml', purpose: 'Chart topology and component values.' },
        { repositoryPath: 'doc/release-bundles.md', purpose: 'Versioned release assets and generated install files.' },
      ],
    },
    {
      id: 'first-install-wizard',
      title: 'First-install setup',
      docType: 'reference',
      audiences: ['administrator'],
      summary: 'The one-time bootstrap that unlocks the platform, and how to diagnose it when it will not complete.',
      keywords: ['setup', 'bootstrap', 'preflight', 'first install', 'unlock'],
      keyFacts: [
        'Normal authenticated routes and APIs stay locked until setup completes once.',
        '`GET /v1/setup/preflight` and `GET /v1/setup/status` are public so a stuck install can be diagnosed without a token.',
        'During cold starts the API serves preflight while PostgreSQL is still starting: `/livez` stays process-alive and `/healthz` stays unready with the current preflight JSON.',
        'The wizard can generate secrets, seed starter profiles, create the GitOps layout, and create repository teams.',
        'Setup apply errors include the actionable write or configuration reason.',
        'Setup does not force an env-file write for dispatcher TLS when a valid effective service JWT fallback is already configured.',
        'Once the one-time wizard has run, **System > Setup** is a status page: health checks and resource counts. The setup steps are not shown again.',
      ],
      details: [
        'Bootstrap-created local admin credentials rotate on first login by default, and generated Docker Compose installs reject the built-in development `admin` password.',
        'Preflight is the right first stop for any "the UI will not let me in" report. It names the blocker rather than leaving you to infer it from logs.',
      ],
      examples: [
        {
          title: 'Check setup state before and after the wizard',
          language: 'bash',
          code: [
            '# both routes answer before authentication so a stuck install can be diagnosed',
            'curl -s "$NOPSAI_URL/v1/setup/preflight" | jq',
            'curl -s "$NOPSAI_URL/v1/setup/status" | jq',
          ].join('\n'),
          expectedOutput:
            'Preflight lists what still blocks setup, including a database that is still starting. Status reports whether the one-time bootstrap has already run.',
        },
      ],
      related: ['complete-first-install-wizard', 'authentication-and-sso', 'production-hardening'],
      sources: [
        { repositoryPath: 'doc/first-install-wizard.md', purpose: 'Bootstrap flow, starter profiles, and production guardrails.' },
        { repositoryPath: 'services/nopsai/setup_preflight.go', purpose: 'Cold-start preflight behavior.' },
      ],
    },
    {
      id: 'environment-reference',
      title: 'Environment and service configuration',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary:
        'Every environment variable the platform reads, starting with the secrets and service URLs that must exist before GitOps can take over.',
      keywords: ['environment', 'env', 'secrets', 'bootstrap', 'configuration', 'variables', 'settings'],
      keyFacts: [
        'Bootstrap environment and deployment secrets are not the long-term source of truth — GitOps is. They exist so the platform can start and reach the point where GitOps loads.',
        '`JWT_SIGNING_KEY` and `SERVICE_JWT_SIGNING_KEY` must be different secrets so user tokens cannot impersonate services.',
        'Compose fails fast on a missing required value rather than starting in a broken state.',
        'Production should keep `DISPATCHER_TLS_MODE` at `mtls` or `tls`, never `disabled`.',
        'Rotating `SERVICE_JWT_SIGNING_KEY` and `DISPATCHER_TLS_SECRET` together is what prevents retired runners from rejoining a replacement control plane.',
      ],
      details: [
        'The table below covers every documented variable. Filter by scope to see what a single component actually reads, or use the environment variable index for the same rows grouped for scanning.',
        'Keep bootstrap-only values such as `DATABASE_URL`, `NOPSAI_MASTER_KEY`, `JWT_SIGNING_KEY`, `SERVICE_JWT_SIGNING_KEY`, `AAA_SHARED_INTERNAL_TOKEN`, and the bootstrap admin password in deployment secrets or the service environment — not in a configuration repository.',
        'Most product settings move to GitOps once the platform is running. Files under `setting/system/` become authoritative for runner topology, authentication, mail, data management, models, MCP, and Agent roles.',
      ],
      fields: allEnvironmentFields,
      examples: [
        {
          title: 'Helm bootstrap Secret keys',
          language: 'yaml',
          code: [
            'apiVersion: v1',
            'kind: Secret',
            'metadata:',
            '  name: nopsai-bootstrap',
            'stringData:',
            '  database-url: postgres://nopsai:***@nopsai-postgresql:5432/nopsai',
            '  master-key: <32+ byte random value>',
            '  jwt-signing-key: <high-entropy value>',
            '  service-jwt-signing-key: <different high-entropy value>',
            '  aaa-shared-internal-token: <high-entropy value>',
            '  bootstrap-admin-password: <generated value>',
            '  dispatcher-tls-secret: <high-entropy value>',
          ].join('\n'),
          placeholders: ['Replace every placeholder with a freshly generated value.'],
        },
      ],
      related: ['environment-index', 'production-hardening', 'docker-compose', 'helm-kubernetes'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'Config struct with yaml and env tags for every setting.' },
        { repositoryPath: 'config.yml', purpose: 'Which values stay bootstrap-only and which move to GitOps.' },
      ],
    },
    {
      id: 'docker-compose',
      title: 'Docker Compose deployment',
      docType: 'how-to',
      audiences: ['administrator', 'developer'],
      summary: 'The local and small single-host topology, its services, and its exposure defaults.',
      keywords: ['compose', 'docker', 'local', 'single host', 'ports'],
      keyFacts: [
        'The stack runs PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, the restricted socket proxy, and a Docker runner.',
        '`NOPSAI_BIND_ADDRESS` defaults to `127.0.0.1`, so published ports are workstation-local unless you change it.',
        'System Logs read through `tcp://docker-socket-proxy:2375`, never the raw Docker socket.',
        'The default topology does not mount `/data/backups` as durable storage.',
      ],
      details: [
        'Compose is the fastest way to see real product behavior, and everything configured there can be exported to a configuration repository afterwards.',
        'The Docker runner mounts the Docker socket because it creates agent and step containers. Treat the runner host as a trusted execution boundary and isolate workloads by scope.',
        'Docker step containers default to bridge networking so package installs, source fetches, and registry access work. Set `DOCKER_NETWORK_NAME=none` when steps must run without egress, or name a dedicated network for controlled egress.',
      ],
      examples: [
        {
          title: 'Start, inspect, and stop',
          language: 'bash',
          code: [
            'docker compose up -d --build',
            'docker compose ps',
            'docker compose logs -f nopsai aaa dispatcher docker-runner',
            'docker compose down',
          ].join('\n'),
        },
      ],
      limits: [
        'Compose defaults are development defaults. Replace every fallback secret and review exposure before using them anywhere shared.',
      ],
      prerequisites: [
        { label: 'Runtime', value: 'Docker Engine with the Compose v2 plugin', verification: 'docker compose version' },
        { label: 'Bootstrap values', value: 'The seven required values present in `.env`', verification: 'grep -c "^\\(POSTGRES_PASSWORD\\|DATABASE_URL\\|NOPSAI_MASTER_KEY\\|JWT_SIGNING_KEY\\|SERVICE_JWT_SIGNING_KEY\\|AAA_SHARED_INTERNAL_TOKEN\\|NOPSAI_BOOTSTRAP_ADMIN_PASSWORD\\)=" .env' },
        { label: 'Images', value: 'A checkout to build from, or access to the configured image registry' },
      ],
      steps: [
        {
          title: 'Start the topology',
          description: 'Compose brings up PostgreSQL, the API, AAA, the dispatcher, git-bot, the UI, Gotenberg, and the socket proxy on the `nopsai-net` network.',
          commands: [
            { title: 'Build and start', language: 'bash', code: 'docker compose up -d --build\ndocker compose ps' },
          ],
          expectedOutput: 'Every service reaches a running state; the database becomes healthy before the API finishes starting.',
        },
        {
          title: 'Confirm the control plane answers',
          description: '`/livez` reports the process is up; `/healthz` waits for a reachable database, which is what a cold start is usually blocked on.',
          commands: [
            { title: 'Probe the API', language: 'bash', code: 'curl -s localhost:8080/livez\ncurl -s localhost:8080/healthz\ncurl -s localhost:8080/version | jq' },
          ],
          verification: '`/healthz` reports ready and `/version` returns the build identity of the images you started.',
        },
        {
          title: 'Add a runner',
          description: 'The `docker-runner` service in this file only builds the image; its entrypoint is `true`. Install a working runner from the dispatcher workspace instead.',
          verification: 'The runner registers and appears dispatchable in System, then the dispatcher workspace.',
        },
        {
          title: 'Upgrade or tear down',
          description: 'Upgrading is a pull and recreate. Tearing down keeps the database volume unless you ask for it to go.',
          commands: [
            { title: 'Upgrade, stop, or drop state', language: 'bash', code: 'NOPSAI_VERSION=0.22 docker compose pull && docker compose up -d\ndocker compose down\ndocker compose down -v' },
            ],
          warning: '`down -v` deletes the database volume, and with it every run record, credential, and setting.',
        },
      ],
      related: ['install-local-docker-compose', 'networking-and-exposure', 'system-logs', 'production-hardening'],
      sources: [{ repositoryPath: 'docker-compose.yaml', purpose: 'Exact services, ports, and environment variables.' }],
    },
    {
      id: 'helm-kubernetes',
      title: 'Kubernetes and Helm deployment',
      docType: 'how-to',
      audiences: ['administrator', 'operator'],
      summary: 'Cluster deployment, generated install artifacts, and the service accounts that separate platform from workload.',
      keywords: ['kubernetes', 'helm', 'chart', 'cluster', 'rbac', 'pvc', 'namespace'],
      keyFacts: [
        'The chart deploys PostgreSQL, API, AAA, dispatcher, git-bot, UI, Gotenberg, and the Kubernetes runner.',
        'Install the CLI from the latest GitHub Release assets before running `nopsai install kubernetes`; remove the downloaded archive after extraction.',
        '`nopsai install kubernetes` generates non-secret values, `installation.md`, and a separate Secret manifest.',
        'The runner Deployment and agent pods use an RBAC-bearing runner ServiceAccount; step pods use a separate no-RBAC workload ServiceAccount.',
        '`topology.dispatcherGRPCAddress` defaults to `dispatcher:9090` and is injected into API and runner pods.',
        'Cross-namespace runners normally need `dispatcher.<platform-namespace>.svc.cluster.local:9090`.',
        'Private registries work through explicit `imagePullSecrets`.',
        'The chart version is the only version to change: NopsAI image tags resolve from `global.releaseVersion`, and an empty value falls back to the chart `appVersion`. Per-image `tag` and `digest` values stay available as intentional overrides.',
      ],
      details: [
        'Keeping step pods on a no-RBAC service account is what stops workload code from calling the Kubernetes API. Do not merge the two accounts to simplify a chart values file.',
        'Managed PostgreSQL is supported by disabling the bundled StatefulSet and replacing the generated database URL.',
        'The Kubernetes runner gives each run an agent-owned PVC-backed workspace rather than an emptyDir, so the workspace survives step pod churn within the run.',
        'System Logs on Kubernetes use read-only `pods` and `pods/log` RBAC instead of the Docker socket proxy.',
      ],
      fields: runnerEnvironmentFields.filter(field => field.scope === 'kubernetes runner'),
      examples: [
        {
          title: 'Generate install artifacts for a pinned version',
          language: 'bash',
          code: 'nopsai install kubernetes --version 1.4.2',
          expectedOutput: 'Non-secret Helm values, installation.md, and a separate Secret manifest to apply directly or seal.',
        },
      ],
      limits: [
        'The repository documents no HPA/autoscaling implementation and no Kubernetes NetworkPolicy set.',
        'Helm does not manage PostgreSQL beyond the bundled StatefulSet.',
      ],
      prerequisites: [
        { label: 'Cluster access', value: 'A namespace you can install into', verification: 'kubectl auth can-i create deployment -n nopsai' },
        { label: 'Helm', value: 'Helm 3', verification: 'helm version --short' },
        { label: 'Secrets', value: 'The platform secrets available as Kubernetes secrets rather than a local `.env`' },
        { label: 'Registry access', value: 'Pull access to the platform images from the cluster, with `imagePullSecrets` where the registry is private' },
      ],
      steps: [
        {
          title: 'Render before you apply',
          description: 'Plan mode renders the manifests without touching the cluster, which is the cheapest way to catch a bad value file.',
          commands: [
            {
              title: 'Render the chart',
              language: 'bash',
              code: 'helm template nopsai deploy/helm/nopsai --values my-values.yaml',
              placeholders: ['`my-values.yaml` carries the topology, image, and secret references for the target cluster.'],
            },
          ],
          expectedOutput: 'Rendered manifests for the API, AAA, dispatcher, git-bot, UI, and supporting services.',
        },
        {
          title: 'Install or upgrade',
          description: 'The same command does both, which keeps the first install and every later one on one path.',
          commands: [
            { title: 'Install the release', language: 'bash', code: 'helm upgrade --install nopsai deploy/helm/nopsai \\\n  --namespace nopsai --create-namespace \\\n  --values my-values.yaml --wait' },
            ],
          verification: 'kubectl get pods -n nopsai',
        },
        {
          title: 'Confirm the dispatcher is reachable by runners',
          description: 'Runners dial out, so the dispatcher address in the values must be resolvable from wherever the runners live — cross-namespace runners need the fully qualified service name.',
          commands: [
            { title: 'Check the service', language: 'bash', code: 'kubectl get svc dispatcher -n nopsai' },
          ],
          expectedOutput: 'The dispatcher answers on port 9090, which is the port `DISPATCHER_GRPC_ADDRESS` must point at.',
        },
        {
          title: 'Install a Kubernetes runner',
          description: 'Generate the runner install from the dispatcher workspace rather than hand-writing a manifest, so identity, scopes, and TLS material come from the control plane.',
          verification: 'The runner registers and appears in the fleet view with its scopes.',
        },
      ],
      related: ['deployment-models', 'runners-and-dispatcher', 'private-registry-auth', 'storage-and-persistence'],
      sources: [
        { repositoryPath: 'deploy/helm/nopsai/values.yaml', purpose: 'Chart values including topology and service accounts.' },
        { repositoryPath: 'doc/kubernetes-runner.md', purpose: 'Runner runtime, PVC workspace behavior, affinity, and manifests.' },
      ],
    },
    {
      id: 'runners-and-dispatcher',
      title: 'Runners and the dispatcher',
      docType: 'reference',
      audiences: ['administrator', 'operator'],
      summary: 'How runners register, how work is routed to them, and what happens when one disconnects or is ejected.',
      keywords: ['runner', 'dispatcher', 'routing', 'capacity', 'registration', 'ejection', 'fleet'],
      keyFacts: [
        'Runner registration is trusted by service JWT and TLS material plus the ejected-runner blocklist.',
        'Routing tables use the effective view: paused or unreachable runner IDs stay visible for diagnosis, but only reachable dispatch-enabled runners are treated as dispatchable targets.',
        'An ordinary network disconnect keeps the registration available for reconnect. A reconnected runner keeps `last_disconnected_at` and shows as recovered or degraded during the recovery window.',
        'Deliberate removal disconnects the runner, clears dispatcher status, and adds its ID to `ejected_runner_ids`.',
        'An explicit empty `runner_scopes` value means all scopes.',
        'Generated installs preserve the friendly name as `runner_name` and use a unique suffixed `RUNNER_ID` for dispatcher identity.',
      ],
      details: [
        'The System dispatcher workspace separates compact overview metrics, a runtime-filtered table-first fleet view, route editing with the effective routing table, and install command generation. Runner detail appears below the fleet table only after an operator selects a runner.',
        'The GitOps-owned configured route map and the live effective routing view are different things. The configured map is desired state; the effective view is derived from registered runner scopes and runtime status.',
        'Replacing a control plane while keeping the old `SERVICE_JWT_SIGNING_KEY` and `DISPATCHER_TLS_SECRET` lets old runner definitions authenticate again unless their IDs are carried forward in `ejected_runner_ids`. Rotate those secrets before exposing a fresh dispatcher when old runners must not join.',
      ],
      fields: runnerEnvironmentFields,
      examples: [
        {
          title: 'Generate a Docker runner install command',
          language: 'bash',
          code: 'curl -s "$NOPSAI_URL/v1/system/dispatcher/runner-bootstrap-command?scopes=platform/production" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN"',
          expectedOutput: 'A one-line install command carrying the runner identity, scopes, and dispatcher connection material.',
        },
      ],
      related: ['helm-kubernetes', 'private-registry-auth', 'system-logs', 'monitoring'],
      sources: [
        { repositoryPath: 'services/dispatcher/internal/app/app.go', purpose: 'Dispatcher listen address and registration handling.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Dispatcher management and install-generation routes.' },
      ],
    },
    {
      id: 'private-registry-auth',
      title: 'Private registry authentication',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary: 'Two separate mechanisms: infrastructure-owned pull secrets and NopsAI-owned runner credential assignments.',
      keywords: ['registry', 'private', 'imagePullSecrets', 'docker_config_json', 'RegistryAuth', 'credentials'],
      keyFacts: [
        'Infrastructure-owned platform pull secrets (`imagePullSecrets`, `KUBERNETES_IMAGE_PULL_SECRETS`) and NopsAI-owned runner credential assignments (`runner_registry_credentials`, `registry_credential_ref`) are distinct and should not be conflated.',
        'Docker runners use bootstrap-delivered `NOPSAI_REGISTRY_DOCKER_CONFIG_B64` to build local per-image `RegistryAuth`.',
        'The legacy `/v1/internal/registry-auth/docker` broker route has been removed.',
        'Kubernetes step and agent pods continue to pull through explicit `imagePullSecrets`.',
      ],
      details: [
        'Assigning a registry credential to a runner is a NopsAI-side operation recorded with audit and metrics. Attaching a pull secret to a pod is a cluster-side operation owned by whoever manages the namespace.',
        'Keep the two boundaries separate when debugging a pull failure: a Kubernetes `ImagePullBackOff` is almost always a missing or wrong `imagePullSecret`, while a Docker runner pull failure points at the delivered docker config.',
      ],
      examples: [
        {
          title: 'Generate a runner install that carries registry credentials',
          language: 'bash',
          code: [
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  "$NOPSAI_URL/v1/system/dispatcher/runner-bootstrap-command?runner_id=runner-prod-1&registry_credential_ref=platform/registry" \\',
            '  | jq \'{runner_image, registry_credentials, registry_hosts}\'',
          ].join('\n'),
          expectedOutput:
            'The response names the credentials the install will deliver. The runner receives them as NOPSAI_REGISTRY_DOCKER_CONFIG_B64 and builds per-image RegistryAuth locally.',
          placeholders: ['`registry_credential_ref` names a credential that already exists in the credential store.'],
        },
      ],
      related: ['runners-and-dispatcher', 'helm-kubernetes', 'credentials'],
      sources: [
        { repositoryPath: 'doc/runner-registry-auth.md', purpose: 'Credential assignment, image pulls, GitOps, audit, and metrics behavior.' },
        { repositoryPath: 'pkg/registryauth', purpose: 'RegistryAuth construction for Docker image pulls.' },
      ],
    },
    {
      id: 'networking-and-exposure',
      title: 'Networking and exposure',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'What has to be reachable from where, and what should never be exposed.',
      keywords: ['network', 'ports', 'exposure', 'ingress', 'egress', 'firewall'],
      keyFacts: [
        'Runners hold long-lived outbound connections to the dispatcher, so runners never need inbound access.',
        'The UI and API are the only surfaces that normally need external exposure, plus the Git webhook endpoint when non-GitHub providers are used.',
        'Docker step containers default to bridge networking; `DOCKER_NETWORK_NAME=none` removes egress entirely.',
        '`GET /metrics` is public by default for scraper compatibility and can be locked behind bearer auth with `METRICS_REQUIRE_AUTH`.',
        'The Docker socket proxy exposes only the allow-listed reads System Logs needs and must never be replaced by the raw socket.',
      ],
      details: [
        'Internal service URLs (`AAA_API_URL`, `GIT_BOT_API_URL`, `NOPSAI_API_URL`) describe a private network. Exposing AAA or the dispatcher publicly removes a boundary the design depends on.',
        'Provider endpoints for LLM and MCP must be reachable from the API runtime. Inside containers `localhost` refers to the container, so host-launched tools need a LAN IP or `host.docker.internal`.',
      ],
      limits: ['The repository documents no Kubernetes NetworkPolicy set and no automatic certificate-management integration.'],
      examples: [
        {
          title: 'Confirm what is actually exposed',
          language: 'bash',
          code: [
            '# from the host: the published surfaces',
            'curl -s localhost:8080/livez',
            'curl -sI localhost/ | head -1',
            '',
            '# from anywhere else: these should not answer',
            'nc -z -w2 $HOST 9091 && echo "dispatcher reachable" || echo "dispatcher closed"',
            'nc -z -w2 $HOST 5432 && echo "database reachable" || echo "database closed"',
          ].join('\n'),
          expectedOutput:
            'On a correctly bound install the dispatcher and database report closed from anywhere but the host itself.',
          placeholders: ['`$HOST` is the address another machine would use to reach the install.'],
        },
      ],
      related: ['docker-compose', 'helm-kubernetes', 'production-hardening', 'system-logs', 'github-app'],
      sources: [
        { repositoryPath: 'docker-compose.yaml', purpose: 'Published ports and bind address defaults.' },
        { repositoryPath: 'services/docker-socket-proxy', purpose: 'The allow-listed Docker API surface.' },
      ],
    },
    {
      id: 'storage-and-persistence',
      title: 'Storage and persistence',
      docType: 'concept',
      audiences: ['administrator', 'operator'],
      summary: 'What is durable, what is per-run, and what the default topology does not persist.',
      keywords: ['storage', 'persistence', 'volume', 'pvc', 'workspace', 'database', 'backup'],
      keyFacts: [
        'PostgreSQL holds durable execution, audit, credential, monitoring, and setup state.',
        'Docker runners create named Docker volumes; Kubernetes runners create an agent-owned PVC-backed workspace per run.',
        'Step `volumes` reuse existing storage and create it when missing, in `volume:/mount/path` form.',
        'The reserved runtime output path `/nopsai/outputs` cannot be used as a volume mount target.',
        'Backups are gzip-compressed JSON Lines files under `DATA_BACKUP_DIR`, defaulting to `/data/backups`.',
      ],
      details: [
        'The default Compose topology does not mount the backup directory as durable storage, so production deployments must mount or export it. This is the single most common persistence surprise.',
        'Docker step containers leave image-provided temporary directories such as `/tmp` and `/var/tmp` unchanged, so images that rely on them behave normally.',
      ],
      limits: [
        'There is no S3 or generic object-storage artifact or backup backend.',
        'Backup creation, listing, checksum metadata, download, and cleanup exist; a verified product-managed restore workflow does not.',
      ],
      examples: [
        {
          title: 'See what holds state on a Compose install',
          language: 'bash',
          code: [
            '# the only durable volume the control plane needs',
            'docker volume ls --filter name=db',
            '',
            '# volumes created by pipeline steps, which are caches rather than state',
            'docker volume ls --filter label=nopsai.io/runner-id',
          ].join('\n'),
          expectedOutput:
            'The database volume is the one that must be backed up. Step volumes can be recreated by re-running the work.',
        },
      ],
      related: ['data-management', 'helm-kubernetes', 'known-limits'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'DATA_BACKUP_DIR and runtime output limits.' },
        { repositoryPath: 'doc/kubernetes-runner.md', purpose: 'Agent-owned PVC workspace behavior.' },
      ],
    },
    {
      id: 'gitops-and-config-repositories',
      title: 'GitOps and configuration repositories',
      docType: 'reference',
      audiences: ['administrator', 'automation-author'],
      summary: 'Which resources Git can own, how sync applies them, and what happens when the UI edits a managed resource.',
      keywords: ['gitops', 'config repository', 'sync', 'drift', 'desired state', 'override'],
      keyFacts: [
        'GitOps can manage `pipelines/`, `steps/`, `schedules/`, `triggers/`, `external-triggers/`, `git-webhook-sources/`, `dashboards/`, `scopes/`, `knowledge/`, `access/`, `config-repositories/`, `setting/git-apps/`, and `setting/system/`.',
        'Canonical system files: `credentials.yaml`, `runner.yaml`, `assistant.yaml`, `auth.yaml`, `mail.yaml`, `data-management.yaml`, plus `setting/git-apps/github.yaml`.',
        'Models, agent roles, and MCP servers and profiles are one file per resource under `models/`, `agent-roles/`, `mcp/servers/`, and `mcp/profiles/`, where the file path is the resource name. Team scoping uses the path just like pipelines, so `models/<team>/<name>.yaml` is a team-scoped model, and one file per registry may set `default: true`.',
        '`setting/system/assistant.yaml` owns the assistant block. Sync fails with a migration error when `assistant:` is still in `setting/system/runner.yaml`.',
        'UI or API edits to GitOps-managed resources create database overrides. The next sync can replace or recreate them unless the change is pushed back.',
        'Sync applies dependency roots first: team hierarchy from `config-repositories/`, then team-owned dashboards and notification routes, then pipeline dashboard outputs.',
        'Long-running syncs can be canceled. If no worker is registered but the row is still `running`, cancellation marks it `canceled` so operators can retry without editing the database.',
        '`setting/git-apps/github.yaml` is app-scoped; the legacy `setting/system/github.yaml` is read for migration compatibility for one release.',
      ],
      details: [
        'Drift review presents Git and NopsAI panes side by side with line numbers, synchronized scrolling, and highlighted removed Git lines and added desired lines before a push.',
        'Both a global configuration repository and per-team repositories are supported. Team repositories are bound through `PUT /v1/teams/{teamID}/config-repository`.',
        'Internal service URLs stay in system configuration rather than in the app-scoped Git App file.',
      ],
      examples: [
        {
          title: 'Configuration repository layout',
          language: 'text',
          code: [
            'pipelines/            steps/               schedules/',
            'models/               agent-roles/         mcp/',
            'triggers/             external-triggers/   git-webhook-sources/',
            'dashboards/           scopes/              knowledge/',
            'access/               config-repositories/',
            'setting/git-apps/github.yaml',
            'setting/system/credentials.yaml',
            'setting/system/runner.yaml',
            'setting/system/assistant.yaml',
            'setting/system/auth.yaml',
            'setting/system/mail.yaml',
            'setting/system/data-management.yaml',
            'models/<name>.yaml            models/<team>/<name>.yaml',
            'agent-roles/<name>.yaml       mcp/servers/<name>.yaml',
            'mcp/profiles/<name>.yaml',
          ].join('\n'),
        },
      ],
      related: ['teams-and-ownership', 'credentials', 'schedules', 'dashboards'],
      sources: [
        { repositoryPath: 'examples/gitops-quickstart/README.md', purpose: 'GitOps sample repository layout.' },
        { repositoryPath: 'services/nopsai/config_sync_apply.go', purpose: 'Apply order and upsert behavior.' },
      ],
    },
    {
      id: 'teams-and-ownership',
      title: 'Teams and resource ownership',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'Team paths are the ownership boundary for access, notifications, and GitOps authority.',
      keywords: ['team', 'ownership', 'team path', 'global', 'hierarchy', 'application'],
      keyFacts: [
        'Product team paths are canonical. Team sync and OIDC `team_mapping` mirror those paths into AAA auth-team subjects.',
        'Pipelines, reusable steps, schedules, scopes, and Knowledge Context expose a selectable `global` bucket for resources without a concrete team path.',
        '`root` and `general` are not accepted aliases for `global`.',
        '`All teams` is an aggregate filter only and must never be persisted as the resource owner.',
        'Mapped SSO teams get viewer access to the matching product team path when it exists, unless a stronger `basic_role_mapping` is configured.',
        'Team-scoped create authorization works before any resource row exists.',
      ],
      details: [
        'Create preflight that depends on manifest ownership can pass `team_path` or `run_team_path` to `GET /v1/access/effective-permissions`. That is how an inherited team owner creates the first schedule, trigger, external trigger, webhook source, or scope under their team without a seed resource.',
        'Teams can own applications, configuration repository bindings, notification routes, defaults, and their own LLM, Agent, and MCP profiles.',
        'Run ownership comes from `run_team_path` on the entry point, which is what drives notification lineage and Pipeline Runs grouping.',
      ],
      examples: [
        {
          title: 'Read the ownership tree',
          language: 'bash',
          code: [
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams" | jq \'.[] | {id, path}\'',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/teams/$TEAM_ID/applications" | jq',
          ].join('\n'),
          expectedOutput:
            'Team paths are the ownership boundary every other resource refers to, so this tree is what access, notification, and GitOps authority hang off.',
        },
      ],
      related: ['access-control', 'gitops-and-config-repositories', 'notifications'],
      sources: [
        { repositoryPath: 'doc/team-resource-ownership-design.md', purpose: 'Separation of Teams from Pipeline Runs and team-scoped profiles.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Team, application, defaults, and profile routes.' },
      ],
    },
    {
      id: 'access-control',
      title: 'Access control and AAA',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'How authorization decisions are made, where grants come from, and what is audited.',
      keywords: ['aaa', 'authorization', 'permissions', 'grants', 'roles', 'acl', 'audit'],
      keyFacts: [
        'AAA owns authorization decisions, policy checks, ACL expansion, filtering, and decision audit records.',
        'Every interface — UI, CLI, REST, hosted MCP, runners — passes through the same authorization boundary.',
        'AAA authorizes the original caller for every referenced resource, not only the entry point.',
        '`/v1/resources/...` routes are handler-authorized: middleware defers, then the handler resolves the concrete resource and checks owner-level manage access.',
        '`GET /v1/access/effective-permissions` answers "what may I do here", including for a team path with no resource row yet.',
        'IdP sync owns only `source: idp` grants for its provider; local UI, API, and GitOps grants stay editable.',
      ],
      details: [
        'Resource access has two questions: may the caller manage this resource, and may the caller use it inside a run. `POST /v1/authz/resource-use/check` and its batch form answer the second, which is what pipeline validation relies on when a run names a profile or knowledge document.',
        'System Access is presented as a compact settings workspace with Basic and Advanced modes over the existing AAA, GitOps, identity-provider, and service-account token APIs. The page introduces no separate policy mutation path.',
        'Authorization outcomes are auditable through `GET /v1/audit` and surface in monitoring under the security view.',
      ],
      examples: [
        {
          title: 'Ask what a caller may actually do',
          language: 'bash',
          code: [
            '# the effective answer, after roles and grants are resolved',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/access/effective-permissions" | jq',
            '',
            '# the grants that produced it',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/access/grants" | jq',
          ].join('\n'),
          expectedOutput:
            'Effective permissions are the authoritative answer; the grant list explains how it was reached. Debug with both, never with the role name alone.',
        },
      ],
      related: ['teams-and-ownership', 'authentication-and-sso', 'tokens-and-service-accounts', 'api'],
      sources: [
        { repositoryPath: 'doc/access-control.md', purpose: 'AAA service, product roles, access grants, route authorization, and audit behavior.' },
        { repositoryPath: 'services/nopsai/resource_authz.go', purpose: 'Handler-level resource authorization.' },
      ],
    },
    {
      id: 'authentication-and-sso',
      title: 'Authentication and SSO',
      docType: 'reference',
      audiences: ['administrator', 'security'],
      summary: 'Local login, OIDC and OAuth2 providers, and what actually constitutes identity.',
      keywords: ['auth', 'login', 'sso', 'oidc', 'oauth2', 'keycloak', 'identity', 'email'],
      keyFacts: [
        'Authentication identity is provider ID, issuer, and the ID-token subject. Email is nullable metadata and may be duplicated.',
        'Email carries a status: verified, unverified, unknown, or not-provided. Only an explicitly verified email may be used by opt-in email-linking policy.',
        'Malformed `email_verified` claims continue login as unknown email assurance and produce auth audit metadata.',
        'Local login and the protected break-glass administrator are always available.',
        'Only one external provider can be active per installation.',
        'Local username and password login can be disabled only while external authentication is enabled with at least one enabled provider.',
      ],
      details: [
        'Production authority lives in `setting/system/auth.yaml`, credential references, AAA ownership, and runtime IdP-managed identity state. The runnable fixtures under `examples/sso/keycloak` and `examples/sso/idp-test-pack` are test fixtures for local scenario testing, not production configuration.',
        'The identity-provider tab lists providers directly, while provider create and edit flows own provider details, OIDC connection, login defaults, mapping, and review panels.',
        'Login is rate limited and lockout protected through `RATE_LIMIT_LOGIN_PER_MINUTE`, `LOGIN_LOCKOUT_THRESHOLD`, and `LOGIN_LOCKOUT_WINDOW_MINUTES`.',
      ],
      fields: authEnvironmentFields,
      examples: [
        {
          title: 'See which login methods an install offers',
          language: 'bash',
          code: [
            '# public: this is what the login screen renders from',
            'curl -s "$NOPSAI_URL/v1/auth/providers" | jq',
            '',
            '# resolve which provider should handle an identifier',
            'curl -sX POST "$NOPSAI_URL/v1/auth/discover" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"email":"person@example.com"}\' | jq',
          ].join('\n'),
          expectedOutput:
            'Provider ID, issuer, and subject are the identity. Email is metadata, and only an explicitly verified email may be used by email-linking policy.',
        },
      ],
      related: ['access-control', 'tokens-and-service-accounts', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Local auth, SSO/OIDC, user and service tokens, refresh behavior.' },
        { repositoryPath: 'doc/local-keycloak-sso.md', purpose: 'The local Keycloak fixture with seeded users and teams.' },
        { repositoryPath: 'examples/sso/README.md', purpose: 'Runnable SSO example fixtures. Test material only.' },
      ],
    },
    {
      id: 'tokens-and-service-accounts',
      title: 'Tokens and service accounts',
      docType: 'reference',
      audiences: ['administrator', 'developer', 'security'],
      summary: 'Personal access tokens, service accounts, and the internal service tokens components use.',
      keywords: ['token', 'pat', 'service account', 'jwt', 'api key', 'automation'],
      keyFacts: [
        '`JWT_SIGNING_KEY` signs user, personal-access, service-account, browser, CLI, automation, and hosted MCP tokens.',
        '`SERVICE_JWT_SIGNING_KEY` signs internal REST and dispatcher service tokens and must be a different secret.',
        'Personal access tokens are created and revoked by the owning user under `/v1/auth/personal-tokens`.',
        'Service account tokens are administrator-managed under `/v1/admin/service-accounts/{id}/tokens`.',
        'Token values are returned once at creation and cannot be read back.',
        'A service account is a first-class caller for AAA, so it can be named in external trigger `allowed_callers`.',
      ],
      details: [
        'Use a service account for machine-to-machine automation rather than a human personal access token. It survives staff changes and carries its own roles and grants.',
        'Internal service tokens are not part of the public surface. Routes under `/v1/internal/` and the git-bot event ingress require them and should never be exposed as public endpoints.',
      ],
      examples: [
        {
          title: 'Create the two kinds of token',
          language: 'bash',
          code: [
            '# a personal token, for a human automating their own access',
            'curl -sX POST "$NOPSAI_URL/v1/auth/personal-tokens" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"name":"laptop-cli"}\' | jq',
            '',
            '# a service account token, for a system',
            'curl -sX POST "$NOPSAI_URL/v1/admin/service-accounts/$SERVICE_ACCOUNT_ID/tokens" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"name":"release-bot"}\' | jq',
          ].join('\n'),
          expectedOutput:
            'Both values are returned once and never again. A system that needs access should hold a service account token rather than a personal one.',
        },
      ],
      related: ['authentication-and-sso', 'access-control', 'external-triggers', 'api'],
      sources: [
        { repositoryPath: 'doc/jwt-authentication.md', purpose: 'Token types, signing keys, and refresh behavior.' },
        { repositoryPath: 'services/nopsai/routes.go', purpose: 'Personal token and service account token routes.' },
      ],
    },
    {
      id: 'credentials',
      title: 'Credentials and secrets store',
      docType: 'concept',
      audiences: ['administrator', 'security'],
      summary: 'One encrypted registry behind every credential reference, with versions, rotation, and GitOps envelopes.',
      keywords: ['credential', 'secret', 'rotation', 'encryption', 'registry', 'envelope', 'master key'],
      keyFacts: [
        'There is a single credential interface. Models, MCP servers, Git Apps, webhook sources, and registry auth all reference it rather than storing values themselves.',
        '`NOPSAI_MASTER_KEY` is the root encryption material for the registry.',
        'Credential values are write-only: the API returns metadata but never the value after submission.',
        'Credentials are versioned. A rotation creates a new version, and a specific version can be activated or deleted.',
        'A credential can be disabled without being deleted.',
        '`POST /v1/secrets/encrypt` produces a GitOps-safe envelope so a secret can live in a configuration repository without being readable there.',
      ],
      details: [
        'Legacy inline forms — `api_key_secret` on an model, `auth_secret` on an MCP server, `GITHUB_PRIVATE_KEY` and `GITHUB_WEBHOOK_SECRET` — remain only for migration. New configuration should use credential references.',
        'Losing the master key makes stored credentials unrecoverable. Rotating it requires re-encrypting the registry, so treat it as the most sensitive value in the deployment.',
      ],
      examples: [
        {
          title: 'Store and rotate a credential without ever reading it back',
          language: 'bash',
          code: [
            'curl -sX POST "$NOPSAI_URL/v1/system/credentials" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  --data @credential.json | jq -r .id',
            '',
            '# rotation adds a version; activation decides which one is in use',
            'curl -sX PUT "$NOPSAI_URL/v1/system/credentials/$CREDENTIAL_ID/value" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  --data @new-value.json | jq',
          ].join('\n'),
          expectedOutput:
            'The registry returns metadata and version history, never a stored value. Rotation is additive, so a bad rotation is recoverable by activating the previous version.',
          placeholders: ['`credential.json` names the credential and its kind; `new-value.json` carries only the new secret material.'],
        },
      ],
      related: ['pipeline-variables', 'models', 'private-registry-auth', 'production-hardening'],
      sources: [
        { repositoryPath: 'doc/credential-management.md', purpose: 'Encrypted registry, GitOps envelopes, AAA, rotation, and migration.' },
        { repositoryPath: 'services/nopsai/credential_schema.go', purpose: 'Credential schema and version handling.' },
      ],
    },
    {
      id: 'data-management',
      title: 'Backups and data cleanup',
      docType: 'how-to',
      audiences: ['administrator', 'operator'],
      summary: 'Creating backups, scheduling cleanup, and the restore boundary you need to plan around.',
      keywords: ['backup', 'cleanup', 'retention', 'restore', 'data management', 'archive'],
      keyFacts: [
        'Backups are gzip-compressed JSON Lines files written under `DATA_BACKUP_DIR`, defaulting to `/data/backups`.',
        'The product supports backup creation, listing, checksum metadata, download, and cleanup.',
        'Cleanup can be previewed before it runs, and can be scheduled with enable, disable, and run-now controls.',
        'The default Compose topology does not mount the backup path as durable storage.',
        'Settings are GitOps-managed through `setting/system/data-management.yaml`.',
      ],
      details: [
        'Always preview a cleanup before running it in an environment with real history. The preview reports what would be removed under the current retention rules.',
        'Because there is no product-managed upload to object storage, exporting backups off the host is a deployment responsibility.',
      ],
      limits: [
        'A complete product-managed restore workflow is not implemented. Plan recovery around your own PostgreSQL restore procedure.',
        'There is no product-managed backup upload to object storage.',
      ],
      prerequisites: [
        { label: 'Access', value: 'Administrator access to system data settings' },
        { label: 'Backups', value: 'A current database backup, since cleanup deletes records permanently' },
      ],
      steps: [
        {
          title: 'Preview before deleting anything',
          description: 'Preview reports what a cleanup would remove under the current retention settings without removing it.',
          commands: [
            {
              title: 'Preview a cleanup',
              language: 'bash',
              code: 'curl -sX POST "$NOPSAI_URL/v1/system/data/cleanup/preview" \\\n  -H "Authorization: Bearer $NOPSAI_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  --data @cleanup.json | jq',
              placeholders: ['`cleanup.json` carries the retention window and the record types to consider.'],
            },
          ],
          expectedOutput: 'Counts per record type. Nothing is deleted by a preview.',
        },
        {
          title: 'Run it once, deliberately',
          description: 'A manual run is the right first step: it produces a job record you can inspect before you automate anything.',
          commands: [
            { title: 'Run and inspect jobs', language: 'bash', code: 'curl -sX POST "$NOPSAI_URL/v1/system/data/cleanup/run" -H "Authorization: Bearer $NOPSAI_TOKEN" --data @cleanup.json | jq\ncurl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/data/cleanup/jobs" | jq' },
          ],
          verification: 'The job appears with what it removed.',
        },
        {
          title: 'Schedule it',
          description: 'A cleanup schedule can be enabled, disabled, and run on demand, so retention becomes a setting rather than a chore.',
          commands: [
            { title: 'Create and trigger a schedule', language: 'bash', code: 'curl -sX POST "$NOPSAI_URL/v1/system/data/cleanup/schedules" -H "Authorization: Bearer $NOPSAI_TOKEN" --data @schedule.json | jq -r .id\ncurl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/system/data/cleanup/schedules/$SCHEDULE_ID/run" | jq' },
          ],
          verification: 'The schedule is listed as enabled and its manual run produces a job.',
        },
        {
          title: 'Back up what cleanup will not restore',
          description: 'Retention is not a backup strategy. The database holds every run record, credential, and setting; a cleanup that ran on the wrong window is only recoverable from a backup.',
        },
      ],
      related: ['storage-and-persistence', 'known-limits', 'gitops-and-config-repositories'],
      sources: [
        { repositoryPath: 'services/nopsai/data_management_gitops.go', purpose: 'Cleanup schedule schema and GitOps ownership.' },
      ],
    },
    {
      id: 'agent-roles',
      title: 'Agent roles',
      docType: 'reference',
      audiences: ['automation-author', 'administrator'],
      summary: 'Named personas and prompt instructions selected by pipelines and steps.',
      keywords: ['agent role', 'persona', 'role', 'instructions', 'prompt'],
      keyFacts: [
        'A profile carries an ID, display name, optional role and description, instructions, and an enabled flag.',
        'Referencing a missing or disabled profile is a validation error, not a silent fallback.',
        'Agent roles are one file per role at `agent-roles/<name>.yaml`, where the file path is the role name; a team-scoped role lives at `agent-roles/<team>/<name>.yaml`, exactly like a team-scoped pipeline.',
        '`agent_role` is valid on a pipeline and a step. A task that sets it fails at parse time.',
        'Instructions shape behavior only — they grant no provider access, tools, credentials, or permissions.',
      ],
      details: [
        'The platform default profile applies when nothing more specific is selected. Setting a team default lets a team standardize its persona without editing every pipeline.',
        '`GET /v1/system/agent-roles/{profileID}/usage` shows which pipelines and steps reference a profile, which is what you want before disabling or deleting one.',
        'The Agent roles workspace keeps the default-profile control on the left, uses compact list-header search and create actions, and shows team tree counts that include cached team-owned profiles.',
      ],
      fields: agentProfileFields,
      examples: [
        {
          title: 'A cautious release persona',
          language: 'yaml',
          code: [
            'id: senior-release-engineer',
            'display_name: Senior Release Engineer',
            'role: Release engineer',
            'description: Cautious operator persona for production release work.',
            'enabled: true',
            'instructions: |',
            '  Prefer reversible actions over irreversible ones.',
            '  Never skip a failing check to make a run pass.',
            '  When evidence is ambiguous, stop and explain what is missing.',
          ].join('\n'),
        },
      ],
      related: ['ai-context-and-tools', 'models', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'pkg/models/agent_profile.go', purpose: 'Agent role struct and defaults.' },
        { repositoryPath: 'doc/agent-profiles.md', purpose: 'GitOps management, AAA, and runtime prompt behavior.' },
      ],
    },
    {
      id: 'models',
      title: 'Models',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'Provider, model, endpoint, credential, and generation settings — the layer that decides which model actually runs.',
      keywords: ['llm profile', 'provider', 'model', 'openai', 'anthropic', 'ollama', 'credential', 'temperature'],
      keyFacts: [
        'Supported providers: `gemini`, `lmstudio`, `openai`, `anthropic`, `groq`, `mistral`, `ollama`, `openrouter`, `azure-openai`.',
        '`reasoning` and `thinking` are generic NopsAI options for LM Studio only. Other providers reject a generic value rather than silently ignoring stale configuration.',
        '`max_tokens` is supported by every current provider.',
        '`allowed_scopes` restricts which run scopes may select the profile; an empty list permits every scope.',
        'The credential value is write-only and is never returned by the API after submission.',
        'A local provider URL must be reachable from the API runtime — inside containers use a LAN IP or `host.docker.internal`, not `localhost`.',
      ],
      details: [
        'Profiles can be system-wide or team-owned, and a team can set its own default. Assistant chat and AI Evaluation select from the same profile set that pipelines do.',
        'Use the profile test action before a pipeline depends on it. A broken credential surfaces there instead of failing every goal at run time.',
        'Prompt cache and provider state settings are recorded in telemetry as hashes, revision markers, cache and session identity, and token counts — prompt bodies are not stored.',
      ],
      fields: llmProfileFields,
      examples: [
        {
          title: 'Hosted provider with scope restriction',
          language: 'yaml',
          code: [
            'reasoning-large:',
            '  provider: anthropic',
            '  model: claude-sonnet-4-5',
            '  credential_ref: llm/anthropic-prod',
            '  max_tokens: 8192',
            '  temperature: 0.2',
            '  timeout_seconds: 120',
            '  allowed_scopes:',
            '    - platform/production',
          ].join('\n'),
        },
        {
          title: 'Local LM Studio profile with reasoning',
          language: 'yaml',
          code: [
            'local-reasoning:',
            '  provider: lmstudio',
            '  model: qwen2.5-coder-32b',
            '  base_url: http://host.docker.internal:1234/v1',
            '  reasoning: high',
          ].join('\n'),
          expectedOutput: 'Accepted. The same `reasoning` value on an OpenAI profile would be rejected.',
        },
      ],
      related: ['ai-context-and-tools', 'credentials', 'assistant'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'Provider constants, reasoning levels, and profile struct.' },
        { repositoryPath: 'doc/llm-model-selection.md', purpose: 'Provider and model selection notes.' },
      ],
    },
    {
      id: 'mcp',
      title: 'MCP servers and profiles',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'External tool access for LLM goals, constrained by an explicit server and tool allowlist.',
      keywords: ['mcp', 'tools', 'servers', 'allowlist', 'integration', 'model context protocol'],
      keyFacts: [
        'A server definition holds the endpoint and credential; a profile is the allowlist that pipelines may reference.',
        'Pipeline YAML can reference profiles only. It cannot declare arbitrary server URLs.',
        'The agent accepts only server/tool pairs present in the resolved profile allowlist.',
        'Profiles are additive across pipeline, step, and task, then deduplicated.',
        '`mcp_profiles` is invalid on include steps, script steps, and script tasks.',
        'External MCP currently uses streamable HTTP.',
      ],
      details: [
        'Narrowing `servers[].tools` is the primary way to limit what LLM goal work can do. A profile that lists a server without a tool list grants every tool that server exposes.',
        'In database-backed deployments, PostgreSQL and the system/global GitOps files are authoritative for external MCP. Mirroring runtime MCP edits back to bootstrap `config.yml` is best-effort after database persistence.',
        'Blocking Knowledge Context applies to MCP calls and MCP arguments as well as to goals, commands, scripts, file writes, and conditions.',
        'NopsAI also exposes its own hosted MCP endpoint at `POST /v1/mcp`, which is a separate surface — see the hosted MCP interface page.',
      ],
      fields: [...mcpServerFields, ...mcpProfileFields],
      examples: [
        {
          title: 'Read-only profile over one server',
          language: 'yaml',
          code: [
            'servers:',
            '  jira:',
            '    enabled: true',
            '    url: https://mcp.internal.example.com/jira',
            '    auth_type: bearer',
            '    credential_ref: mcp/jira-token',
            '    timeout: 30s',
            'profiles:',
            '  jira-readonly:',
            '    enabled: true',
            '    description: Read-only Jira lookups for release notes.',
            '    servers:',
            '      - server: jira',
            '        tools: [search_issues, get_issue]',
          ].join('\n'),
          expectedOutput: 'Goals referencing `jira-readonly` can call those two tools and nothing else.',
        },
      ],
      limits: [
        'Local MCP URLs must be reachable from the API runtime; `localhost` inside a container refers to the container itself.',
      ],
      related: ['ai-context-and-tools', 'hosted-mcp', 'credentials'],
      sources: [
        { repositoryPath: 'pkg/models/mcp.go', purpose: 'Server and profile struct definitions.' },
        { repositoryPath: 'doc/mcp-pipeline-integration.md', purpose: 'How MCP is wired into pipeline execution.' },
      ],
    },
    {
      id: 'knowledge-context',
      title: 'Knowledge Context',
      docType: 'reference',
      audiences: ['automation-author', 'administrator', 'security'],
      summary: 'Documents injected into prompts, and the two kinds that can block execution outright.',
      keywords: ['knowledge', 'guardrail', 'policy', 'adr', 'runbook', 'context', 'documents'],
      keyFacts: [
        'Supported kinds: `architecture`, `guardrail`, `policy`, `adr`, `guideline`, `runbook`, `reference`, `example`.',
        '`guardrail` and `policy` are blocking kinds. They apply to goals, commands, direct scripts, file writes, MCP calls, MCP arguments, and conditions.',
        'Use exactly one of `ref` (a managed `team/document`) or `path` (repo-local, loaded at the run commit).',
        'A managed `ref` requires `knowledge_context.use` permission on that document.',
        '`required: true` fails the run before execution when resolution or authorization fails.',
        'Resolved content is snapshotted on the run, so later document edits never rewrite run history.',
        'Documents, and the Notion/Confluence/wiki connections they attach to, are Git-owned: `knowledge/connections/<team>/<connection>.yaml` defines a connection, and a mirrored document declares `source.type: external_page` with the page reference and sync settings.',
        'The mirrored page body, sync status, and cached content stay runtime state, so an upstream page edit is never reported as configuration drift.',
      ],
      details: [
        'Pipeline, step, and task knowledge context are merged, not replaced. The most specific level adds to what the broader levels already supply.',
        'Blocking kinds are pinned by scope at run start and recomputed as pipeline, step, and task scopes begin. Emergency policy response cancels active runs rather than mutating already-resolved policy.',
        'A script step with blocking context has its exact command LLM-validated before execution. That is why `llm_enabled: false` rejects such a combination.',
      ],
      fields: knowledgeFields,
      examples: [
        {
          title: 'Managed guardrail plus a repo-local example',
          language: 'yaml',
          code: [
            'knowledge_context:',
            '  - kind: guardrail',
            '    ref: security/repo-check',
            '    required: true',
            '  - kind: architecture',
            '    path: .nopsai/docs/backend.md',
          ].join('\n'),
          expectedOutput:
            'The guardrail must resolve and authorize or the run fails before execution. The architecture document is read from the run repository at the run commit.',
        },
      ],
      related: ['governance-and-policy', 'ai-context-and-tools', 'access-control'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Kind, ref, and path validation.' },
        { repositoryPath: 'doc/knowledge-context.md', purpose: 'GitOps layout, runtime snapshots, and access checks.' },
      ],
    },
    {
      id: 'governance-and-policy',
      title: 'Governance levels',
      docType: 'reference',
      audiences: ['administrator', 'security', 'automation-author'],
      summary: 'How NopsAI acts on an AI policy review decision, and why the default is the strict one.',
      keywords: ['governance', 'policy', 'strict', 'advisory', 'enforcement'],
      keyFacts: [
        'There are two levels: `advisory` and `strict`. An unset `governance_level` normalizes to `strict`.',
        '`strict` proceeds only on a clear allow. Violations, conflicts, uncertainty, and unsupported decisions all block.',
        '`advisory` logs and warns; execution proceeds despite an evaluated policy concern.',
        'Advisory never skips the evaluation. If no judgment can be obtained at all, because no model is available or the review call fails, the task fails closed at every level.',
        'Any value other than `advisory` or `strict` is a validation error.',
      ],
      details: [
        'The level can be set at pipeline, step, or task, with the most specific value winning. This lets a pipeline stay strict overall while one well-understood task runs advisory.',
        'Governance interacts with Knowledge Context: the policy review is what produces the decision, and the governance level is what NopsAI does with it. Without blocking knowledge there is nothing to enforce.',
      ],
      fields: governanceLevels,
      examples: [
        {
          title: 'Strict pipeline with one advisory task',
          language: 'yaml',
          code: [
            'governance_level: strict',
            'knowledge_context:',
            '  - kind: policy',
            '    ref: platform/deploy-policy',
            '    required: true',
            'steps:',
            '  - name: analyze',
            '    tasks:',
            '      - name: draft-summary',
            '        governance_level: advisory',
            '        goal: Draft a human-readable summary of the proposed change.',
          ].join('\n'),
        },
      ],
      limits: ['Lowering the governance level weakens fail-closed enforcement; it does not disable the policy review itself.'],
      related: ['knowledge-context', 'ai-context-and-tools', 'access-control'],
      sources: [
        { repositoryPath: 'pkg/models/policy_merge.go', purpose: 'Level constants, normalization, and the strict default.' },
      ],
    },
  ],
};
