import type { WikiSection } from '../types.js';

export const referenceSection: WikiSection = {
  id: 'reference',
  title: 'Reference',
  owner: 'Product',
  description: 'Complete indexes, interface contracts, vocabulary, and confirmed limits, for looking something up once you know the concept.',
  articles: [
    {
      id: 'directive-index',
      title: 'All YAML directives',
      docType: 'reference',
      audiences: ['automation-author', 'developer'],
      summary: 'Every documented directive across pipeline, step, task, approval, output, trigger, schedule, and profile YAML, in one searchable table.',
      keywords: ['index', 'directives', 'all', 'yaml', 'search', 'fields', 'schema'],
      keyFacts: [
        'This index is generated from the same field data the individual reference pages render, so it can never drift from them.',
        'Filter by scope to narrow to pipeline, step, task, approval, output, trigger, schedule, or profile directives.',
        'Every row links to the article that explains the directive in context.',
      ],
      details: [
        'If a directive is missing here, it is missing from the wiki. That is a documentation gap worth reporting rather than a directive that does not exist.',
      ],
      related: ['pipeline-anatomy', 'script-steps', 'final-deliverables', 'environment-index'],
      sources: [
        { repositoryPath: 'services/nopsai/pkg/validation/pipeline.go', purpose: 'Authoritative validation for pipeline, step, task, approval, and output directives.' },
        { repositoryPath: 'pkg/models/model.go', purpose: 'Struct definitions and YAML tags.' },
      ],
    },
    {
      id: 'environment-index',
      title: 'All environment variables',
      docType: 'reference',
      audiences: ['administrator', 'operator', 'security'],
      summary: 'Every documented environment variable with its owning service, default, and security note.',
      keywords: ['index', 'environment', 'env', 'variables', 'settings', 'configuration', 'all'],
      keyFacts: [
        'Grouped by owning service so you can see what one component actually needs.',
        'Required values are the ones a deployment cannot start without.',
        'Security notes call out the values that must be rotated together or must never be reused across environments.',
      ],
      details: [
        'Bootstrap values are deliberately not the long-term source of truth. Once GitOps is loaded, most product settings move to configuration files under `setting/system/`.',
      ],
      related: ['environment-reference', 'production-hardening', 'docker-compose', 'helm-kubernetes'],
      sources: [
        { repositoryPath: 'config/config.go', purpose: 'Config struct with yaml and env tags.' },
        { repositoryPath: 'docker-compose.yaml', purpose: 'Local defaults and required-value enforcement.' },
      ],
    },
    {
      id: 'cli',
      title: 'Command-line interface',
      docType: 'reference',
      audiences: ['operator', 'administrator', 'developer'],
      summary: 'Automation commands plus an interactive operator console over the same authenticated API.',
      keywords: ['cli', 'nopsai', 'terminal', 'console', 'install', 'doctor', 'update', 'completion'],
      keyFacts: [
        'The CLI drives the same authenticated REST API as the UI. It has no private path.',
        'First-time installs download the latest GitHub Release archive from `https://github.com/nopsai/nopsai/releases/latest`, extract `nopsai` or `nopsai.exe` onto `PATH`, and remove the archive.',
        'Contexts hold the API URL and credentials so one binary can target several installations.',
        'The interactive console exposes API catalog calls, raw API requests, route listing and descriptions, context management, token login and logout, install generation, platform doctor, platform release, platform upgrade, completion generation, guide topics, help, and exit.',
        '`nopsai install docker-compose` and `nopsai install kubernetes` generate version-pinned install files.',
        'After the first install, `nopsai update --version <x.y.z>` downloads the exact OCI archive and `SHA256SUMS`, verifies the checksum, then replaces the local binary.',
        '`nopsai platform upgrade docker-compose|kubernetes --version <x.y.z>` upgrades an installed platform. It keeps the secrets install generated, is forward-only, and prints the verified release changelog with the required actions before applying.',
        'Interactive actions show the equivalent `nopsai ...` command as a final preview before anything is sent or changed.',
      ],
      details: [
        'The live terminal layout uses centered screens with fixed header and footer chrome, breadcrumb text above nested menus, a fixed 20-row menu viewport, and a pinned guide and details section beneath it. Every feature menu, result viewer, wizard, and platform screen shares that layout.',
        'API request parameter lists follow the wizard step order, expand the active item inline with its required marker and value, and render an empty active value as a cursor rather than a blank placeholder. Blank optional parameters, including multiline ones, advance with Enter.',
        'UI release gates print UTC start and finish timestamps and durations for each npm stage so local-time log rendering cannot look like a loop.',
      ],
      examples: [
        {
          title: 'Install the latest CLI',
          language: 'bash',
          code: [
            "version=\"$(curl -fsSL https://api.github.com/repos/nopsai/nopsai/releases/latest | sed -nE 's/.*\"tag_name\": *\"v?([^\"]+)\".*/\\1/p' | head -1)\"",
            '[ -n "$version" ] || { echo "Could not resolve latest NopsAI release" >&2; exit 1; }',
            "os=\"$(uname -s | tr '[:upper:]' '[:lower:]')\"",
            'arch="$(uname -m)"',
            'case "$os" in linux|darwin) ;; *) echo "Unsupported OS: $os" >&2; exit 1 ;; esac',
            'case "$arch" in x86_64|amd64) arch=amd64 ;; arm64|aarch64) arch=arm64 ;; *) echo "Unsupported architecture: $arch" >&2; exit 1 ;; esac',
            'archive="nopsai-cli_${version}_${os}_${arch}.tar.gz"',
            'base_url="https://github.com/nopsai/nopsai/releases/download/v${version}"',
            '',
            'curl -fL "$base_url/$archive" -o "$archive"',
            'curl -fL "$base_url/SHA256SUMS" -o SHA256SUMS',
            'checksum_line="$(awk -v asset="$archive" \'{ name=$2; sub(/^\\*/, "", name); sub(/^\\.\\//, "", name); if (name == asset) print $0 }\' SHA256SUMS)"',
            '[ -n "$checksum_line" ] || { echo "Missing checksum for $archive" >&2; exit 1; }',
            'if command -v sha256sum >/dev/null 2>&1; then',
            "  printf '%s\\n' \"$checksum_line\" | sha256sum -c -",
            'else',
            "  printf '%s\\n' \"$checksum_line\" | shasum -a 256 -c -",
            'fi',
            'tar -xzf "$archive" nopsai',
            'sudo install -m 0755 nopsai /usr/local/bin/nopsai',
            'rm -f "$archive" SHA256SUMS nopsai',
            'nopsai --version',
          ].join('\n'),
          expectedOutput: 'The `nopsai` binary is installed on PATH and the downloaded archive has been removed.',
        },
        {
          title: 'Point the CLI at an installation and check it',
          language: 'bash',
          code: [
            'nopsai context add prod --api https://nopsai.example.com',
            'nopsai context use prod',
            'NOPSAI_TOKEN=nopat_<secret> nopsai login --token',
            'nopsai platform doctor',
          ].join('\n'),
          expectedOutput: 'Doctor reports platform reachability and configuration problems it can detect from the client side.',
        },
        {
          title: 'Generate a pinned Docker Compose install',
          language: 'bash',
          code: 'nopsai install docker-compose --version 1.4.2',
          expectedOutput: 'Generated Compose files and locks with exact versions rather than floating tags.',
        },
        {
          title: 'Review and apply a platform upgrade',
          language: 'bash',
          code: [
            'nopsai update --version 1.5.0',
            'nopsai platform upgrade docker-compose --version 1.5.0 --plan',
            'nopsai platform upgrade docker-compose --version 1.5.0 --run',
          ].join('\n'),
          expectedOutput: 'The plan prints the changelog and required actions; a series upgrade needs --accept-series-upgrade before it applies.',
        },
      ],
      related: ['api', 'release-integrity', 'deployment-models'],
      sources: [
        { repositoryPath: 'doc/cli.md', purpose: 'Contexts, credentials, interactive REST access, installs, and diagnostics.' },
        { repositoryPath: 'internal/cli/command', purpose: 'Command implementations, including the interactive console.' },
      ],
    },
    {
      id: 'assistant',
      title: 'Assistant chat',
      docType: 'concept',
      audiences: ['operator', 'automation-author', 'security'],
      summary: 'In-product chat with page context, and exactly what that context contains.',
      keywords: ['assistant', 'chat', 'context', 'help', 'debugging', 'conversation'],
      keyFacts: [
        'Current-page context is metadata only: route, page area, active tab, team and scope, selected resource IDs, and allow-listed filters.',
        'The composer renders a removable context chip so you can see and drop the context before sending.',
        'The Assistant does not scrape page text, logs, secrets, credentials, or arbitrary query parameters.',
        'Assistant selects from the same models pipelines use, filtered by what the caller may access.',
        'Conversations are per-user and can be deleted; memory can be compacted with a summarize action.',
        'Assistant availability and individual features are configuration-controlled.',
      ],
      details: [
        'AI Evaluation on analysis surfaces is a separate mechanism. It uses the analysis evaluation endpoint rather than creating an Assistant conversation, and it does not ask hosted MCP to inspect resources.',
        'If Assistant reports that no model is available, configure provider, model, credential reference, and scope access in Models — the same place pipeline goals get their profiles.',
      ],
      examples: [
        {
          title: 'See what the assistant is allowed to do for this caller',
          language: 'bash',
          code: [
            '# feature families enabled for the install',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/config" | jq',
            '',
            '# models the caller may drive the assistant with',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/models" | jq',
            '',
            '# conversations belong to the caller',
            'curl -s -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/assistant/conversations" | jq',
          ].join('\n'),
          expectedOutput:
            'Configuration decides which capability families exist; AAA still decides the specific resources and actions the caller may reach through them.',
        },
      ],
      related: ['models', 'analysis-reviewers', 'hosted-mcp'],
      sources: [
        { repositoryPath: 'doc/assistant-capabilities.md', purpose: 'User-facing capabilities and example prompts per feature area.' },
        { repositoryPath: 'services/ui/src/features/assistant/pageContext.ts', purpose: 'Exactly which page metadata is collected.' },
      ],
    },
    {
      id: 'hosted-mcp',
      title: 'Hosted NopsAI MCP endpoint',
      docType: 'reference',
      audiences: ['developer', 'automation-author', 'security'],
      summary: 'Let an external MCP client drive NopsAI, filtered by the caller AAA permissions.',
      keywords: ['hosted mcp', 'mcp server', 'endpoint', 'integration', 'tools', 'agent'],
      keyFacts: [
        'NopsAI exposes a hosted MCP endpoint at `POST /v1/mcp`.',
        'The tool surface is filtered by the calling identity AAA permissions — it is not a privileged back door.',
        'This is the inverse of MCP Profiles: profiles let NopsAI call out to external servers, while the hosted endpoint lets external clients call in.',
        'Authenticate with the same bearer tokens the REST API accepts.',
      ],
      details: [
        'Because the surface is permission-filtered per caller, two clients with different tokens see different available tools. That is the intended behavior, not a discovery bug.',
        'Use a service account rather than a personal token when an external agent will call the endpoint continuously.',
      ],
      examples: [
        {
          title: 'Talk to the hosted MCP endpoint',
          language: 'bash',
          code: [
            '# an empty body defaults to tools/list rather than a parse error',
            'curl -sX POST -H "Authorization: Bearer $NOPSAI_TOKEN" "$NOPSAI_URL/v1/mcp" | jq',
            '',
            '# explicit JSON-RPC initialize',
            'curl -sX POST "$NOPSAI_URL/v1/mcp" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"curl","version":"dev"}}}\' | jq',
            '',
            '# the tools this subject may actually call',
            'curl -sX POST "$NOPSAI_URL/v1/mcp" \\',
            '  -H "Authorization: Bearer $NOPSAI_TOKEN" \\',
            '  -H "Content-Type: application/json" \\',
            '  -d \'{"jsonrpc":"2.0","id":2,"method":"tools/list"}\' | jq',
          ].join('\n'),
          expectedOutput:
            'The tool list is scoped to the authenticated subject: feature flags decide which families exist at all, and AAA decides which resources within them the caller may reach.',
        },
      ],
      related: ['mcp', 'tokens-and-service-accounts', 'api'],
      sources: [
        { repositoryPath: 'doc/mcp-feature-coverage.md', purpose: 'Hosted MCP feature coverage and user-scoped permissions.' },
        { repositoryPath: 'services/nopsai/hosted_mcp.go', purpose: 'Endpoint implementation and permission filtering.' },
      ],
    },
    {
      id: 'concepts-glossary',
      title: 'Concepts and glossary',
      docType: 'reference',
      audiences: ['new-user', 'automation-author', 'operator'],
      summary: 'The terms NopsAI uses, and what each one does and does not control.',
      keywords: ['terminology', 'vocabulary', 'definitions', 'glossary'],
      keyFacts: [
        '**Pipeline** — a named YAML workflow made of steps. The unit you run, schedule, and trigger.',
        '**Step** — one node in the pipeline graph. Exactly one execution mode: `include`, `tasks`, `goal`, `script`, or `approval`.',
        '**Task** — a unit inside a multi-task step. Defines exactly one of `goal` or `script`.',
        '**Run** — one execution of a pipeline, with its own logs, outputs, approvals, and audit trail.',
        '**Scope** — the namespace that resolves runtime variables and secrets for a run.',
        '**Team path** — the ownership boundary (`platform/payments`) used for access, notifications, and GitOps authority.',
        '**Runner** — a Docker or Kubernetes worker that accepts assigned runs from the dispatcher.',
        '**Agent** — the per-run process a runner starts; it drives step containers or pods and reports status back.',
        '**Agent role** — persona and prompt instructions. Controls how the AI behaves, not what it may access.',
        '**Model** — provider, model, endpoint, credential reference, and generation settings.',
        '**MCP Profile** — the allowlist of external MCP servers and tools available to LLM goal work.',
        '**Knowledge Context** — documents injected into prompts. `guardrail` and `policy` kinds also block execution.',
        '**AAA** — the authorization service that decides whether the original caller may use each selected resource.',
        '**GitOps** — configuration repositories that own resource definitions; UI and API edits create database overrides.',
      ],
      details: [
        'The AI control layers are deliberately separate. An Agent role cannot grant provider access, an Model cannot change the persona, an MCP Profile cannot widen AAA permissions, and Knowledge Context cannot by itself authorize a runtime resource.',
        'Scope and team path are different axes. Scope answers "which variables and secrets resolve for this run"; team path answers "who owns this resource and who gets notified".',
      ],
      related: ['ai-context-and-tools', 'pipeline-variables', 'teams-and-ownership'],
      sources: [
        { repositoryPath: 'doc/decision-architecture.md', purpose: 'Why the separation between control layers exists.' },
      ],
    },
    {
      id: 'known-limits',
      title: 'Confirmed gaps and limits',
      docType: 'reference',
      audiences: ['administrator', 'security', 'new-user'],
      summary: 'Capabilities this repository does not implement. Valid roadmap items, but not current behavior.',
      keywords: ['limits', 'gaps', 'not supported', 'roadmap', 'unsupported', 'boundaries'],
      keyFacts: [
        'No Terraform modules.',
        'No AWS-, Azure-, or Google-specific deployment automation.',
        'No built-in Redis dependency.',
        'No S3 or generic object-storage artifact or backup backend.',
        'No Helm-managed PostgreSQL beyond the bundled StatefulSet.',
        'No documented HPA or autoscaling implementation.',
        'No documented Kubernetes NetworkPolicy set.',
        'No complete air-gap installation workflow.',
        'No product-managed backup upload to object storage.',
        'No verified product-managed restore workflow.',
        'No published production sizing or throughput benchmark.',
        'No automatic certificate-management integration.',
        'No multi-region database or control-plane architecture.',
        'Raising every replica count does not by itself produce high availability.',
      ],
      details: [
        'This page exists so a sales claim, a design document, or an architecture review can be checked against implementation evidence. Anything listed here should not appear elsewhere in the wiki as implemented behavior.',
        'These are legitimate roadmap items. The distinction the wiki maintains is between what the current repository does and what is planned.',
      ],
      related: ['data-management', 'storage-and-persistence', 'deployment-models'],
      sources: [
        { repositoryPath: 'doc/enterprise-refactor-roadmap.md', purpose: 'Where future-state capability is tracked.' },
        { repositoryPath: 'doc/README.md', purpose: 'The code-grounded documentation set this wiki summarizes.' },
      ],
    },
  ],
};
