syntax = "proto3";

package proto;

option go_package = "nopsai/pkg/proto";

// Service for the LLM Agent, called by the Agent
service LLMService {
    rpc GetAction(GetActionRequest) returns (Action);
    rpc EvaluateCondition(ConditionRequest) returns (ConditionResponse);
}

// Request for evaluating a condition
message ConditionRequest {
    string goal = 1;
    string history = 2;
    map<string, string> environment = 3;
}

// Response for a condition evaluation
message ConditionResponse {
    bool result = 1;
}

// The entire context needed by the LLM to decide on the next action.
message GetActionRequest {
    string goal = 1;
    string history = 2;
    map<string, string> directory_listing = 3;
    map<string, string> environment = 4;
}

// Action defines the operation for the agent to perform.
message Action {
  string type = 1;
  oneof payload {
    CommandAction command_action = 2;
    FileAction file_action = 3;
    AnswerAction answer_action = 4;
  }
}

message CommandAction {
  string command = 1;
}

message FileAction {
  string path = 1;
  string content = 2;
}

message AnswerAction {
  string answer = 1;
}