// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for evaluating a condition
type ConditionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	History       string                 `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionRequest) Reset() {
	*x = ConditionRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionRequest) ProtoMessage() {}

func (x *ConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionRequest.ProtoReflect.Descriptor instead.
func (*ConditionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConditionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ConditionRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

func (x *ConditionRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// Response for a condition evaluation
type ConditionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionResponse) Reset() {
	*x = ConditionResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionResponse) ProtoMessage() {}

func (x *ConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionResponse.ProtoReflect.Descriptor instead.
func (*ConditionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConditionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// The entire context needed by the LLM to decide on the next action.
type GetActionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Goal             string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	History          string                 `protobuf:"bytes,2,opt,name=history,proto3" json:"history,omitempty"`
	DirectoryListing map[string]string      `protobuf:"bytes,3,rep,name=directory_listing,json=directoryListing,proto3" json:"directory_listing,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Variables        map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetActionRequest) Reset() {
	*x = GetActionRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequest) ProtoMessage() {}

func (x *GetActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetActionRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *GetActionRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

func (x *GetActionRequest) GetDirectoryListing() map[string]string {
	if x != nil {
		return x.DirectoryListing
	}
	return nil
}

func (x *GetActionRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// Action defines the operation for the agent to perform.
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Action_CommandAction
	//	*Action_FileAction
	//	*Action_AnswerAction
	Payload       isAction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetPayload() isAction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Action) GetCommandAction() *CommandAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_CommandAction); ok {
			return x.CommandAction
		}
	}
	return nil
}

func (x *Action) GetFileAction() *FileAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_FileAction); ok {
			return x.FileAction
		}
	}
	return nil
}

func (x *Action) GetAnswerAction() *AnswerAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_AnswerAction); ok {
			return x.AnswerAction
		}
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_CommandAction struct {
	CommandAction *CommandAction `protobuf:"bytes,2,opt,name=command_action,json=commandAction,proto3,oneof"`
}

type Action_FileAction struct {
	FileAction *FileAction `protobuf:"bytes,3,opt,name=file_action,json=fileAction,proto3,oneof"`
}

type Action_AnswerAction struct {
	AnswerAction *AnswerAction `protobuf:"bytes,4,opt,name=answer_action,json=answerAction,proto3,oneof"`
}

func (*Action_CommandAction) isAction_Payload() {}

func (*Action_FileAction) isAction_Payload() {}

func (*Action_AnswerAction) isAction_Payload() {}

type CommandAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAction) Reset() {
	*x = CommandAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAction) ProtoMessage() {}

func (x *CommandAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAction.ProtoReflect.Descriptor instead.
func (*CommandAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CommandAction) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type FileAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAction) Reset() {
	*x = FileAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAction) ProtoMessage() {}

func (x *FileAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAction.ProtoReflect.Descriptor instead.
func (*FileAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FileAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileAction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnswerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerAction) Reset() {
	*x = AnswerAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerAction) ProtoMessage() {}

func (x *AnswerAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerAction.ProtoReflect.Descriptor instead.
func (*AnswerAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerAction) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x05proto\"\xc4\x01\n" +
	"\x10ConditionRequest\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x18\n" +
	"\ahistory\x18\x02 \x01(\tR\ahistory\x12D\n" +
	"\tvariables\x18\x03 \x03(\v2&.proto.ConditionRequest.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x11ConditionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\xe5\x02\n" +
	"\x10GetActionRequest\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x18\n" +
	"\ahistory\x18\x02 \x01(\tR\ahistory\x12Z\n" +
	"\x11directory_listing\x18\x03 \x03(\v2-.proto.GetActionRequest.DirectoryListingEntryR\x10directoryListing\x12D\n" +
	"\tvariables\x18\x04 \x03(\v2&.proto.GetActionRequest.VariablesEntryR\tvariables\x1aC\n" +
	"\x15DirectoryListingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12=\n" +
	"\x0ecommand_action\x18\x02 \x01(\v2\x14.proto.CommandActionH\x00R\rcommandAction\x124\n" +
	"\vfile_action\x18\x03 \x01(\v2\x11.proto.FileActionH\x00R\n" +
	"fileAction\x12:\n" +
	"\ranswer_action\x18\x04 \x01(\v2\x13.proto.AnswerActionH\x00R\fanswerActionB\t\n" +
	"\apayload\")\n" +
	"\rCommandAction\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\":\n" +
	"\n" +
	"FileAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"&\n" +
	"\fAnswerAction\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2\x89\x01\n" +
	"\n" +
	"LLMService\x123\n" +
	"\tGetAction\x12\x17.proto.GetActionRequest\x1a\r.proto.Action\x12F\n" +
	"\x11EvaluateCondition\x12\x17.proto.ConditionRequest\x1a\x18.proto.ConditionResponseB\x12Z\x10nopsai/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_agent_proto_goTypes = []any{
	(*ConditionRequest)(nil),  // 0: proto.ConditionRequest
	(*ConditionResponse)(nil), // 1: proto.ConditionResponse
	(*GetActionRequest)(nil),  // 2: proto.GetActionRequest
	(*Action)(nil),            // 3: proto.Action
	(*CommandAction)(nil),     // 4: proto.CommandAction
	(*FileAction)(nil),        // 5: proto.FileAction
	(*AnswerAction)(nil),      // 6: proto.AnswerAction
	nil,                       // 7: proto.ConditionRequest.VariablesEntry
	nil,                       // 8: proto.GetActionRequest.DirectoryListingEntry
	nil,                       // 9: proto.GetActionRequest.VariablesEntry
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	7, // 0: proto.ConditionRequest.variables:type_name -> proto.ConditionRequest.VariablesEntry
	8, // 1: proto.GetActionRequest.directory_listing:type_name -> proto.GetActionRequest.DirectoryListingEntry
	9, // 2: proto.GetActionRequest.variables:type_name -> proto.GetActionRequest.VariablesEntry
	4, // 3: proto.Action.command_action:type_name -> proto.CommandAction
	5, // 4: proto.Action.file_action:type_name -> proto.FileAction
	6, // 5: proto.Action.answer_action:type_name -> proto.AnswerAction
	2, // 6: proto.LLMService.GetAction:input_type -> proto.GetActionRequest
	0, // 7: proto.LLMService.EvaluateCondition:input_type -> proto.ConditionRequest
	3, // 8: proto.LLMService.GetAction:output_type -> proto.Action
	1, // 9: proto.LLMService.EvaluateCondition:output_type -> proto.ConditionResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	file_pkg_proto_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*Action_CommandAction)(nil),
		(*Action_FileAction)(nil),
		(*Action_AnswerAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
