// -----------------------------------------------------------------------------
// File: pkg/proto/agent.proto
// -----------------------------------------------------------------------------
// Purpose: Defines the gRPC service contract for communication between the
// Agent and the LLM Agent. This is the API definition.
//
// HOW TO COMPILE:
// 1. Install protoc and the Go gRPC plugins:
//    - `go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28`
//    - `go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2`
// 2. Run from the project root directory:
//    - `protoc --go_out=. --go-grpc_out=. pkg/proto/agent.proto`
// This will generate `agent.pb.go` and `agent_grpc.pb.go` in the proto directory.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ExecutionStream_FullMethodName = "/proto.AgentService/ExecutionStream"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The core service that the LLM Agent provides and the Agent consumes.
type AgentServiceClient interface {
	// The main communication loop is a bidirectional stream.
	// This allows for continuous, stateful conversation between the agent and the llm-agent.
	ExecutionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionRequest, Action], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ExecutionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionRequest, Action], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ExecutionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, Action]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecutionStreamClient = grpc.BidiStreamingClient[ExecutionRequest, Action]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// The core service that the LLM Agent provides and the Agent consumes.
type AgentServiceServer interface {
	// The main communication loop is a bidirectional stream.
	// This allows for continuous, stateful conversation between the agent and the llm-agent.
	ExecutionStream(grpc.BidiStreamingServer[ExecutionRequest, Action]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ExecutionStream(grpc.BidiStreamingServer[ExecutionRequest, Action]) error {
	return status.Errorf(codes.Unimplemented, "method ExecutionStream not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ExecutionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ExecutionStream(&grpc.GenericServerStream[ExecutionRequest, Action]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecutionStreamServer = grpc.BidiStreamingServer[ExecutionRequest, Action]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutionStream",
			Handler:       _AgentService_ExecutionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/agent.proto",
}
