// -----------------------------------------------------------------------------
// File: pkg/proto/agent.proto
// -----------------------------------------------------------------------------
// Purpose: Defines the gRPC service contract for communication between the
// Agent and the LLM Agent. This is the API definition.
//
// HOW TO COMPILE:
// 1. Install protoc and the Go gRPC plugins:
//    - `go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28`
//    - `go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2`
// 2. Run from the project root directory:
//    - `protoc --go_out=. --go-grpc_out=. pkg/proto/agent.proto`
// This will generate `agent.pb.go` and `agent_grpc.pb.go` in the proto directory.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent -> LLM Agent: The agent sends requests for actions or reports results.
type ExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecutionRequest_GetNextAction
	//	*ExecutionRequest_ReportActionResult
	Event         isExecutionRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionRequest) GetEvent() isExecutionRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecutionRequest) GetGetNextAction() *GetNextActionRequest {
	if x != nil {
		if x, ok := x.Event.(*ExecutionRequest_GetNextAction); ok {
			return x.GetNextAction
		}
	}
	return nil
}

func (x *ExecutionRequest) GetReportActionResult() *ReportActionResult {
	if x != nil {
		if x, ok := x.Event.(*ExecutionRequest_ReportActionResult); ok {
			return x.ReportActionResult
		}
	}
	return nil
}

type isExecutionRequest_Event interface {
	isExecutionRequest_Event()
}

type ExecutionRequest_GetNextAction struct {
	GetNextAction *GetNextActionRequest `protobuf:"bytes,2,opt,name=get_next_action,json=getNextAction,proto3,oneof"`
}

type ExecutionRequest_ReportActionResult struct {
	ReportActionResult *ReportActionResult `protobuf:"bytes,3,opt,name=report_action_result,json=reportActionResult,proto3,oneof"`
}

func (*ExecutionRequest_GetNextAction) isExecutionRequest_Event() {}

func (*ExecutionRequest_ReportActionResult) isExecutionRequest_Event() {}

// A request from the agent to get the next action for a step.
type GetNextActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextActionRequest) Reset() {
	*x = GetNextActionRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextActionRequest) ProtoMessage() {}

func (x *GetNextActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextActionRequest.ProtoReflect.Descriptor instead.
func (*GetNextActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

// A report from the agent containing the result of a completed action.
type ReportActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // We can add file changes here later if needed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportActionResult) Reset() {
	*x = ReportActionResult{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActionResult) ProtoMessage() {}

func (x *ReportActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActionResult.ProtoReflect.Descriptor instead.
func (*ReportActionResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ReportActionResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ReportActionResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ReportActionResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// LLM Agent -> Agent: The llm-agent sends actions to be executed.
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g., "EXECUTE_COMMAND", "REPLACE_FILE"
	// Types that are valid to be assigned to Payload:
	//
	//	*Action_CommandAction
	//	*Action_FileAction
	//	*Action_AnswerAction
	Payload       isAction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetPayload() isAction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Action) GetCommandAction() *CommandAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_CommandAction); ok {
			return x.CommandAction
		}
	}
	return nil
}

func (x *Action) GetFileAction() *FileAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_FileAction); ok {
			return x.FileAction
		}
	}
	return nil
}

func (x *Action) GetAnswerAction() *AnswerAction {
	if x != nil {
		if x, ok := x.Payload.(*Action_AnswerAction); ok {
			return x.AnswerAction
		}
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_CommandAction struct {
	CommandAction *CommandAction `protobuf:"bytes,2,opt,name=command_action,json=commandAction,proto3,oneof"`
}

type Action_FileAction struct {
	FileAction *FileAction `protobuf:"bytes,3,opt,name=file_action,json=fileAction,proto3,oneof"`
}

type Action_AnswerAction struct {
	AnswerAction *AnswerAction `protobuf:"bytes,4,opt,name=answer_action,json=answerAction,proto3,oneof"`
}

func (*Action_CommandAction) isAction_Payload() {}

func (*Action_FileAction) isAction_Payload() {}

func (*Action_AnswerAction) isAction_Payload() {}

type CommandAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAction) Reset() {
	*x = CommandAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAction) ProtoMessage() {}

func (x *CommandAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAction.ProtoReflect.Descriptor instead.
func (*CommandAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CommandAction) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type FileAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAction) Reset() {
	*x = FileAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAction) ProtoMessage() {}

func (x *FileAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAction.ProtoReflect.Descriptor instead.
func (*FileAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FileAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileAction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnswerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerAction) Reset() {
	*x = AnswerAction{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerAction) ProtoMessage() {}

func (x *AnswerAction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerAction.ProtoReflect.Descriptor instead.
func (*AnswerAction) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerAction) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x05proto\"\xc8\x01\n" +
	"\x10ExecutionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12E\n" +
	"\x0fget_next_action\x18\x02 \x01(\v2\x1b.proto.GetNextActionRequestH\x00R\rgetNextAction\x12M\n" +
	"\x14report_action_result\x18\x03 \x01(\v2\x19.proto.ReportActionResultH\x00R\x12reportActionResultB\a\n" +
	"\x05event\"\x16\n" +
	"\x14GetNextActionRequest\"a\n" +
	"\x12ReportActionResult\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\xd8\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12=\n" +
	"\x0ecommand_action\x18\x02 \x01(\v2\x14.proto.CommandActionH\x00R\rcommandAction\x124\n" +
	"\vfile_action\x18\x03 \x01(\v2\x11.proto.FileActionH\x00R\n" +
	"fileAction\x12:\n" +
	"\ranswer_action\x18\x04 \x01(\v2\x13.proto.AnswerActionH\x00R\fanswerActionB\t\n" +
	"\apayload\")\n" +
	"\rCommandAction\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\":\n" +
	"\n" +
	"FileAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"&\n" +
	"\fAnswerAction\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2M\n" +
	"\fAgentService\x12=\n" +
	"\x0fExecutionStream\x12\x17.proto.ExecutionRequest\x1a\r.proto.Action(\x010\x01B\x12Z\x10nopsai/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_agent_proto_goTypes = []any{
	(*ExecutionRequest)(nil),     // 0: proto.ExecutionRequest
	(*GetNextActionRequest)(nil), // 1: proto.GetNextActionRequest
	(*ReportActionResult)(nil),   // 2: proto.ReportActionResult
	(*Action)(nil),               // 3: proto.Action
	(*CommandAction)(nil),        // 4: proto.CommandAction
	(*FileAction)(nil),           // 5: proto.FileAction
	(*AnswerAction)(nil),         // 6: proto.AnswerAction
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	1, // 0: proto.ExecutionRequest.get_next_action:type_name -> proto.GetNextActionRequest
	2, // 1: proto.ExecutionRequest.report_action_result:type_name -> proto.ReportActionResult
	4, // 2: proto.Action.command_action:type_name -> proto.CommandAction
	5, // 3: proto.Action.file_action:type_name -> proto.FileAction
	6, // 4: proto.Action.answer_action:type_name -> proto.AnswerAction
	0, // 5: proto.AgentService.ExecutionStream:input_type -> proto.ExecutionRequest
	3, // 6: proto.AgentService.ExecutionStream:output_type -> proto.Action
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	file_pkg_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecutionRequest_GetNextAction)(nil),
		(*ExecutionRequest_ReportActionResult)(nil),
	}
	file_pkg_proto_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*Action_CommandAction)(nil),
		(*Action_FileAction)(nil),
		(*Action_AnswerAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
